### ISSUE TITLE
Access exclusion groups in custom handler

### ISSUE THREAD

**Issue by Narcotic** [schmittjoh/serializer#1003]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hi,

I working with a custom Handler. Is there a way to have access to the exclusion groups (the ones set in the SerializationContext, given in parameter to the serialize() method)?

Tanks for your help.

**Comment by goetas** [comment]
Not really.... 

(each time I found similar needs, some time after I've realized that I was doing something wrong... 
Handlers should not be aware of groups. If you need to exclude some props in your custom handler, you can use something as:

```php
public function myHandler($visitor, $data, $type, $context)
{
  $obj = new MyWrappedObject($data);

  return $context->accept($obj);
}
```

`MyWrappedObject` can perform the custom manipluations of `$data` and the be itself a ordinary object (suing standard groups)

**Comment by goetas** [comment]
Can you share more in detail your use case?

**Comment by Narcotic** [comment]
Thank you for the answer! I'll try this solution, and then provide an exemple of the use cas, and maybe refactor the all thing to avoid the issue. (Sorry for the delay)
