### ISSUE TITLE
Using the serializer in reverse in e2e test

### ISSUE THREAD

**Issue by jandom** [schmittjoh/serializer#1007]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Setup 

We use JMSSerializer with SerializationContext and simple groups to expose selected entity fields in a Symfony REST api. 

## Problem 

In functional tests, it'd be awesome to check if the entity was serialized in the "desired" way. The backend sends me some JSON and I use the JMS serializer annotations and context to assert if it matches the JSON schema. 

## Caveats

Not sure if the JMS bundle is the right tool for it – after all it's a serializer, rather than JSON document schema validator. But it comes pretty close! I'm hope you guys might be able to point to the right way – thanks for providing this awesome library!

**Comment by goetas** [comment]
This is an interesting approach... however, as you said, using the serializer to "validate" response is a pretty uncommon approach.

I had a similar problem to solve (testing that the returned fields are what is expected) and almost always the best solution was to effectively assert the presence/absence of specific fields, without trying to _magically_ infer it from the serialization group passed in the context.
Is a bit verbose but in my cases was always worth.

Of course this is my approach used for my usecases, you are free to decide the best approach for your specific problem.

I will close the ticket as it is more of a "question" and the eventual discussion can continue on a closed ticket.

**Comment by goetas** [comment]
> Checking for the same shape, say twice, in different tests can be a pain. How do you deal with that? Do you just factor out reused code to some parent class?

To be honest, im not afraid of doing copy&paste of very simple code that has no logic. 
in my case i have just a list of assertions (no conditionals or loops at all).

When the business logic changes, is just about using find/replace that most ide offer.
Another thing I do is avoiding to test the same condition on multiple tests.

The reason for a test failure should be only one (or really few) (some people tend to be strict about it, see http://programmaticallyspeaking.com/one-assertion-per-test-please.html) :smiley:

**Comment by jandom** [comment]
Thanks!
