### ISSUE TITLE
BC Break on deserialize with non existing properties in JSON payload?

### ISSUE THREAD

**Issue by narcoticfresh** [schmittjoh/serializer#1011]
| Q                | A
| ---------------- | -----
| Bug report?      | unsure
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

## Steps required to reproduce the problem

1. Create the following entity with one property to show the problem

```php
<?php

namespace App;

class Field
{

    /**
     * @var Constraint[]
     */
    private $constraints = [];

    /**
     * @return Constraint[]
     */
    public function getConstraints()
    {
        return $this->constraints;
    }

    /**
     * @param Constraint[] $constraints Field constraints
     * @return $this
     */
    public function setConstraints(array $constraints)
    {
        $this->constraints = $constraints;
        return $this;
    }
}

```

Let's create a mapping:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<serializer>
    <class name="App\Field">
        <property name="constraints"
                  type="array&lt;App\Constraint&gt;"
                  serialized-name="constraints"
                  accessor-getter="getConstraints"
                  accessor-setter="setConstraints"
        />
    </class>
</serializer>
```
Now, when i try to deserialize an example content, that does NOT contain the existing property, this happens:

```php
var_dump($serializer->deserialize('{}', 'App\Field'));
```
```
Type error: Argument 1 passed to App\Field::setConstraints() must be of the type array, null given, called in /app/vendor/jms/serializer/src/Accessor/DefaultAccessorStrategy.php on line 122
```
### Trying the same with our previous serializer version (1.13.0)

```php
var_dump($serializer->deserialize('{}', 'App\Field'));

object(App\Field)#724 (17) {
  ["constraints":"App\Field":private]=>
  array(0) {
  }
}
```

## Expected Result

I expect Serializer 2.* to not BC break in such a dramatic fashion - that doesn't seem to be documented as well. At least I couldn't find that in UPGRADING.

Is this intended behavior of the new release or a bug?

I'm not sure how we could adapt to that behavior. The fact that default member values in classes are *changed* even if not present in the JSON payload is hard to circumvent - one would need to rewrite every setter method?! 

I checked if there is any new annotation to deal with that behavior, but I could not find anything.

Any input and information is appreciated! 
Thanks for the great library!

## Actual Result

* Serializer seems to iterate all properties of class metadata and sets all the setters even if the property is not present in the JSON payload. The default class member types as specified in the class is not respected anymore.

**Comment by goetas** [comment]
Hmm. Interesting. 
Setters should not be called if the property is not in the json. Sounds more like a bug.
