### ISSUE TITLE
AbstractDoctrineTypeDriver::normalizeFieldType() must be of the type string, null given

### ISSUE THREAD

**Issue by dekamaru** [schmittjoh/serializer#1015]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I want serialize Entity with Embeddables and get this error.

Error throwed by type-hint value mismatch `$doctrineMetadata->getTypeOfField()` returns DoctrineType|string|**null**, but JMS `normalizeFieldType` (AbastractDoctrineTypeDriver.php) have `protected function normalizeFieldType(string $type): ?string` signature and error happens.

It was happened after upgrade from symfony 3 to symfony 4, and all bundles updates.
In SerializerBundle 2.3 version all working good, because there is doc-block usage instead type-hint

I think you need set nullable type-hint in `normalizeFieldType` function.

## Steps required to reproduce the problem

1. Serialize any Entity with Embedded property

## Expected Result

* Serialized entity

## Actual Result

* `Argument 1 passed to JMS\Serializer\Metadata\Driver\AbstractDoctrineTypeDriver::normalizeFieldType() must be of the type string, null given`

**Comment by dekamaru** [comment]
#1016

**Comment by goetas** [comment]
fixed by https://github.com/schmittjoh/serializer/pull/1020
