### ISSUE TITLE
Exclude field for depth

### ISSUE THREAD

**Issue by 1271** [schmittjoh/serializer#1022]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hey.
How can I exclude a field with a depth greater than 1?

For example:

Entity/Article:

```
[
'article' => [
   'id' => 1,
       'title' => 'L',
       'text' => 'text - here',
   ],
   ...
]
```

But for user relation we need:
```
[
   'user' => [
      ...
      'articles' => [
      [
        'id' => 1,
      ],
      [
        'id' => 2,
      ],
    ],
]
```

Is there such a possibility?

Thank you!

**Comment by goetas** [comment]
http://jmsyst.com/libs/serializer/master/reference/annotations#maxdepth
