### ISSUE TITLE
Serialize Generator

### ISSUE THREAD

**Issue by simPod** [schmittjoh/serializer#1023]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. 
```php
function getData() {
   yield 1;
   yield 2;
}
...
$classToSerialize = new ClassToSerialize($this->getData()); // Save getData()'s result to inner iterable-typed property
// annotated with * @Serializer\Type("array<int>")


```
2. `$data = $serializer->serialize($classToSerialize, ...);`

## Expected Result

* `$data` contains array `[1, 2]`, Generator was converted to array

## Actual Result

* `$data` contains empty array, Generator was not converted to array

What do you think of auto converting generators to arrays when serializing?

**Comment by scyzoryck** [comment]
I can see two ways to add this feature. 

1. In `SerializationGraphNavigator` we can add 
```
if ($data instanceof \Iterator) {
    return $this->visitor->visitArray(iterator_to_array($data), $type);
}
return $this->visitor->visitArray((array) $data, $type);
```

2. Breaking change in `SerializationVisitorInterface` 
```
public function visitArray(iterable $data, array $type);
```

@goetas 
What do you think about it? 🤔

**Comment by goetas** [comment]
Why not adding a custom handler for `Generator` and to exactly the same thing as for `ArrayCollection` ?

See https://github.com/schmittjoh/serializer/blob/master/src/Handler/ArrayCollectionHandler.php

**Comment by goetas** [comment]
Solved in https://github.com/schmittjoh/serializer/pull/1034
