### ISSUE TITLE
Provide an option to the SerializeBuilder to set AccessType to a specified value globally

### ISSUE THREAD

**Issue by rrajkomar** [schmittjoh/serializer#1025]
Say for example that I have a project with 50-like serializable classes.
Each class has its own serialization annotations to be converted to xml and/or json

If I want to make all classes use the "public-method" AccessType, I currently have to go on each of the 50 classes to add the annotation.

Could it be possible to add a setting to the SerializerBuilder so that in one call I can set the default accessor Type Strategy to public-method (for any call that uses that serializer)

**Comment by goetas** [comment]
Third party libraries could rely on a default that is not true anymore
