### ISSUE TITLE
[Question] JSON:API support

### ISSUE THREAD

**Issue by torinaki** [schmittjoh/serializer#1026]
Is there plans to implement JSON:API specification or at least provide a possibility to extend JMS Serializer to implement JSON:API as an extension.
Currently, we are supporting our [fork](https://github.com/ecentria/JsonApiBundle) of [koemeet/JsonApiBundle](https://github.com/koemeet/JsonApiBundle). Our experience shows that it is not supposed that the 1.x version of JMS Serializer can be extended with a new serialization format and there no easy way to implement an alternative version of JSON serialization.

**Comment by goetas** [comment]
Implementing  JSON:API specification is out of the scope for this library.

This library is a generic serializer, of course JSON:API specifications can be implemented on top of it in similar was how http://stateless.co/hal_specification.html was implemented by https://github.com/willdurand/Hateoas
