### ISSUE TITLE
Instructions for upgrading from addData in 1.x don't work

### ISSUE THREAD

**Issue by GKFX** [schmittjoh/serializer#1030]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The provided instructions for upgrading from `addData` in 1.x don't work. This is code from a project using the Symfony bundle. Instructions were ([UPGRADING.md](https://github.com/schmittjoh/serializer/blob/master/UPGRADING.md))
>Removed deprecated method JsonSerializationVisitor::addData, use :visitProperty(new StaticPropertyMetadata('', 'name', 'value'), null) instead

## Steps required to reproduce the problem

1. My old code (extract from https://github.com/camdram/camdram/blob/38216b3fe4c3b87d0f2f74d73a2521a315c0d920/src/Acts/CamdramApiBundle/Serializer/JsonEventSubscriber.php)
```php
public function onPostSerialize(ObjectEvent $event)
{
    // ...
    $visitor->addData('_links', $linkJson); // $linkJson is an array
    $visitor->addData('_type', strtolower($class->getShortName()));
}
```

2. My new code, now with library version v2.0.2, following instructions provided in UPDATING.md:
```php
$visitor->visitProperty(new StaticPropertyMetadata('', '_links', $linkJson), null);
```

3. My new code, having ignored the documentation and read the source instead ;)
```php
$visitor->visitProperty(new StaticPropertyMetadata('', '_links', null), $linkJson);
```

## Expected Result

```json
    "_links": {
        "self": "\/shows\/2020-the-phantom-of-the-opera",
        "venue": "\/venues\/demo-venue",
        "society": "\/societies\/society-10"
    },
    "_type": "show"
```
formed part of the output with with 1.x and was expected with method 2. 

## Actual Result

The expected JSON did not appear with method 2. It did appear with method 3.

Is this a bug in the code or a bug in the documentation? I.e. should I continue using method 3 or wait until a fix is released that makes method 2 work?

**Comment by Sander-Toonen** [comment]
I have the same experience. 
Are you sure the documentation is right?

**Comment by CHTJonas** [comment]
Bump!

**Comment by goetas** [comment]
Option 3 was the right way and https://github.com/schmittjoh/serializer/pull/1066 updated the documentation

**Comment by CHTJonas** [comment]
That's grand - thanks!

**Comment by faysh** [comment]
What's the forth parameter ($groups) on StaticPropertyMetadata for? I added groups, but it don't exclude property at all. What I'm doing wrong?

**Comment by afkernohan** [comment]
It fails silently if your StaticPropertyMetadata is set up incorrectly:

        try {
            $v = $this->navigator->accept($v, $metadata->type);
        } catch (NotAcceptableException $e) {
            return;
        }
