### ISSUE TITLE
DateTime and DateTimeImmutable from PHP 7.1 serialization and deserialization with microseconds

### ISSUE THREAD

**Issue by pdec86** [schmittjoh/serializer#1033]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

According to PHP documentation, DateTime::setTime
Version | Description
7.1.0 | The microseconds parameter was added.

## Steps required to reproduce the problem

Code like follows fails:
$date = new \DateTimeImmutable(null);
$serializer = SerializerBuilder::create()->build();
$json = $serializer->serialize($date, 'json');
$dateBack = $serializer->deserialize($json, \DateTimeImmutable::class, 'json');
$this->assertEquals($date, $dateBack);

## Expected Result
Tests pass OK.

## Actual Result
Failed asserting that two DateTime objects are equal.
--- Expected
+++ Actual
@@ @@
-2019-01-16T18:45:54.578422+0100
+2019-01-16T18:45:54.000000+0100

**Comment by goetas** [comment]
Not sure if your test makes sense. this two dates will be always different unless you serialize also the microsecods

**Comment by pdec86** [comment]
Yes, I thought that full DateTime object will be serialized, also with microseconds if they are part of the DateTime object. But maybe they should not be serialized because of some reasons in JMS serializer. 

In one of my projects, I store DateTimeImmutable of an object, of an event which has occurred in the system.

If new PHP version supports microseconds it would be beneficial to me if serialized time would contain those microseconds, so it is less possible, that two events occur on the same time - with same hour, minute, second and microseconds.

If it's not a bug, please close that issue. I will refactor my tests so microseconds won't be considered if two DateTimeImmutable are equal.
