### ISSUE TITLE
What should I use instead of the dropped GenericDeserializationVisitor class?

### ISSUE THREAD

**Issue by Deuchnord** [schmittjoh/serializer#1035]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Question | yes

I'm working on a project that uses the version 1.x of this library, with a class which extends the [`JMS\Serializer\GenericDeserializationVisitor`](https://github.com/schmittjoh/serializer/blob/dbddbc4d54118be60026dec4dfe20a5f99fba58f/src/JMS/Serializer/GenericDeserializationVisitor.php) abstract class.
But it appears it has been deprecated in #877 for the v1.13.0, and dropped in v2.0.
Problem is, nothing in the docs says what we should do to fix the deprecation and to be able to upgrade to v2.0.
How should we proceed to get rid of the usage of this class?

Thanks

**Comment by goetas** [comment]
It is not a good idea to extend the visitors. Most probably in your custom implementation you did some handing of some special case, that most probably should/can be handled using a custom type handler or event listener.
