### ISSUE TITLE
@SerializedName not being ignored since 2.x is bug or feature?

### ISSUE THREAD

**Issue by ThreeDots3** [schmittjoh/serializer#1036]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe?

In issue [#334](https://github.com/schmittjoh/serializer/issues/334) it was stated, that `@SerializedName` being ignored, when `IdenticalPropertyNamingStrategy` is set, is not a bug...

But since version 2.x the behavior is, that `@SerializedName` is always taken into account no matter naming strategy - is that now a bug or a feature? I liked the behavior of 1.x more.

**Comment by goetas** [comment]
Hi,
What is the point of specifying the serialized name, and then expecting it
to be ignored?

**Comment by ThreeDots3** [comment]
Well it kind of made sense, that `IdenticalPropertyNamingStrategy`  will map properties identically no matter what and that I have a choice to make the annotation work if needed. I've actually found use case for that behavior because I am using 2 instances with different settings - to map data from database to entity and then to send entity to frontend - and some column names slighty differed from that in entity (so the annotation helped to get data loaded from database, but then identical naming strategy used to send it to frontend as is). But fixing that was not a problem, I just made sure that the entity attributes fit the database ones.

I don't have a problem with how it is now, because I altered the code to it, I just wanted to make sure this is what you intended and it is not a bug (since the behavior is different from previous version)

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/issues/334 was a bug and some people were expecting it to work as it is now.

When `@serializedname` is specified, it is honored. So the current way it the expected way.
I'm closing the issue since it seems that your question has been answered.
