### ISSUE TITLE
How serialize Exception class?

### ISSUE THREAD

**Issue by spolischook** [schmittjoh/serializer#1038]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

When I have very simple class for serialization it works as expected.
Class
```php
class BadRequestHttpException
{
    /**
     * @JMS\Type("int")
     */
    public $code = 400;

    /**
     * @JMS\Type("array<string, array<string>>")
     */
    public $messages = [];
```
## Expected Result
json:
```json
{
  "code": 400,
  "messages": {
    "securityId": [
      "Missed security_id OAuth token for authentication"
    ]
  }
}
```
## Actual Result
But as soon I extend my class from any exception, include `\Exception` the result is weird - only \Exception `message` field (instead of messages and code) will be serialized:
```json
{
  "message": "securityId: Missed security_id OAuth token for authentication"
}
```

**Comment by goetas** [comment]
are you using FOSREST? they have a custom exception handler as I know

**Comment by spolischook** [comment]
I have try use it without rest - just put arguments to the `$serializer->serialize($exception, 'json');` and return as Http Response.
But I'll try without FosRest to be sure.

**Comment by spolischook** [comment]
It looks like issue with FosRest. @goetas  Where I should look at first?

**Comment by goetas** [comment]
My question is: Do you have `friendsofsymfony/rest-bundle` installed?

**Comment by spolischook** [comment]
Yes it is installed, and I've try to reproduce without FosRest and it looks like this issue is present only when FosRest is installed and configured.

**Comment by goetas** [comment]
FOS REST bundle has its own exception handler always registered, make sure that your handler has a higher priority than the FOS Rest
