### ISSUE TITLE
Add use of annotation registry to docs

### ISSUE THREAD

**Issue by andig** [schmittjoh/serializer#1044]
As new user of plain JMS without Symfony I've struggled with various annotation exceptions. 

It would be great if the docs could reference the need for setting the annotation registry up (https://stackoverflow.com/questions/14629137/jmsserializer-stand-alone-annotation-does-not-exist-or-cannot-be-auto-loaded):

    AnnotationRegistry::registerLoader('class_exists');

**Comment by goetas** [comment]
Will be happy to accept a pull request about it

**Comment by goetas** [comment]
done in https://github.com/schmittjoh/serializer/pull/1047
