### ISSUE TITLE
[Semantical Error] The annotation \"@generated\" in class JMS\\Serializer\\Type\\InnerParser was never imported

### ISSUE THREAD

**Issue by andig** [schmittjoh/serializer#1046]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             |no

## Steps required to reproduce the problem

I'm running something like this inside a larger non-Symfony application:

	AnnotationRegistry::registerLoader('class_exists');

	$serializer = SerializerBuilder::create()->build();
	$json = $serializer->serialize($request, 'json');

I'm using

    "jms/serializer": "^2.1",

## Expected Result

No exception inside JMS code. I do not expect to load any Annotations for library-internal usage unless they apply to my model.

## Actual Result

    AnnotationException
    [Semantical Error] The annotation \"@generated\" in class JMS\\Serializer\\Type\\InnerParser was never imported. Did you maybe forget to add a \"use\" statement for this annotation?

The code in question in `InnerParser` is:

	/**
	 * @internal
	 *
	 * @generated Use regenerate-parser.php to refresh this class.
	 */

**Comment by FabianTe** [comment]
@andig Why did you close this? How was this issue resolved? Having similar problems here ...

**Comment by FabianTe** [comment]
Looks like this is an issue not being adressed: https://github.com/schmittjoh/serializer/issues/1185

**Comment by goetas** [comment]
2.x is abandoned, in 3.x the `InnerParser` has been dropped, this this problem is gone

**Comment by FabianTe** [comment]
Oh, thank you for the note!
