### ISSUE TITLE
Using @Until and @Since on class level

### ISSUE THREAD

**Issue by tjveldhuizen** [schmittjoh/serializer#1048]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes/no

The `@VirtualProperty` annotation can be used on classes and methods. The `@Until` and `@Since` annotations can be used on methods and properties. As such, it is not possible to use the \@Since annotation in the options argument of the `@VirtualProperty`, on class level.

In most cases I prefer not to create a method in the class, just to be used in the API. However, such virtual property is limited to specific versions. Therefore, my questions are: Am I right about not being abled to use those annotations in this way? If yes, would it be possible to make `@Until` and `@Since` available on class level, within the options-parameter of `@VirtualProperty`? I guess it might be relatively easy, since `@Groups` is available and seems to be working in the same way.

Example:
```
/**
 * Class Team
 *
 * @package Nevobo\BeachBundle\Entity
 *
 * @ORM\Entity(repositoryClass="Nevobo\BeachBundle\Entity\Repository\TeamRepository")
 * @Serializer\ExclusionPolicy("all")
 * @Serializer\VirtualProperty(
 *      name="players",
 *      exp="object.getTeam().getPlayers()",
 *      options={
 *          @Serializer\Until(0),
 *          @Serializer\Groups({
 *              "beach_team_results",
 *          })
 *      }
 * )
 * @ORM\Table(name="beach_participant")
 */
class Participant {
...
}
```

**Comment by goetas** [comment]
Hmm, it should work out of the box. Can it be that you have a field named players in your class that overrides the virtual property?

**Comment by tjveldhuizen** [comment]
No, there is no players property, nor a players() method (or even getPlayers()). The error message is as following.

> AnnotationException in AnnotationException.php line 54: [Semantical Error] Annotation @Serializer\Until is not allowed to be declared on class Nevobo\BeachBundle\Entity\Participant. You may only use this annotation on these code elements: PROPERTY, METHOD.

(I've made a small correction in the class naming of my simplified example, by the way, maing clear the VirtualProperty doesn't refer to the 'current' class)

**Comment by goetas** [comment]
Well, then if is so, a PR is welcome.

**Comment by goetas** [comment]
Fixed via https://github.com/schmittjoh/serializer/pull/1049
