### ISSUE TITLE
xmlRootPrefix missing from unserialized metadata

### ISSUE THREAD

**Issue by kasparsklavins** [schmittjoh/serializer#1050]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Is there a particular reason why `xmlRootPrefix` is not being serialised when caching metadata? https://github.com/schmittjoh/serializer/blob/master/src/Metadata/ClassMetadata.php#L280

**Comment by goetas** [comment]
I think is a bug (this feature was added not long time ago as i remember...) PR with a fix is welcome!
