### ISSUE TITLE
GROUP BY 

### ISSUE THREAD

**Issue by victorgp89** [schmittjoh/serializer#1051]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

## Steps required to reproduce the problem

1. Create handler 

## Expected Result
![image](https://user-images.githubusercontent.com/9083812/53429352-c57ed700-39ec-11e9-8bbe-6756ef7c2054.png)

A object group by InvTypeCode and RatePlanCode and all node like LengtOfStay | RestictionStatus etc inside it

**Comment by goetas** [comment]
Did not get it what is about this ticket. Can you clarify?

**Comment by victorgp89** [comment]
Yes,
If for example I receive an xml with many AvailStatusMessage nodes, I would like to group them by doing a group by  InvTypeCode and RatePlanCode.

And that the result was something like this:
With RestrictionStatus and LengthsOfStay ordered

![image](https://user-images.githubusercontent.com/9083812/53475083-54343800-3a6f-11e9-9bfd-d4ce779750d1.png)

**Comment by goetas** [comment]
I'm sorry but this looks not a issue of this library but just something more specific of your application.

Im closing this now. If you need some support on implementing OTA implementations, you can write me over email and we can discuss possible solutions.
