### ISSUE TITLE
Make JsonDeserializationVisitor extendable

### ISSUE THREAD

**Issue by sneakyvv** [schmittjoh/serializer#1055]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? | yes
| BC Break report? |no
| RFC?             | yes

In for example JMS\Serializer\Handler\DateHandler an exception is thrown when a value can not be properly deserialized into an DateTimeImmutable. But it is currently not possible to retrieve information about the exact field that causes the error.

I tried to solve this issue in a Symfony project by decorating the JsonDeserializationVisitor(Factory) and catching the RuntimeException in my own TraceableJsonDeserializationVisitor in the visitProperty function and then wrapping the error in a new exception together with the property info.

```   
    public function visitProperty(PropertyMetadata $metadata, $data)
    {
        try {
            return $this->jsonDeserializationVisitor->visitProperty($metadata, $data);
        } catch (RuntimeException $e) {
            throw new DeserializationException($metadata->serializedName, $e->getMessage(), $e->getCode(), $e);
        }
    }
```

However the DateHandler's deserializeDateTimeFromJson expects a JsonDeserializationVisitor. This class is final so I can not extend it. That's why I propose this change.

I can see two other solutions:

1. Change more of the JMS code so it does throw errors with property information itself, instead of decorating.
2. Change DataHandler's deserializeDateTimeFromJson to accept a DeserializationVisitorInterface.

**Comment by goetas** [comment]
closing for the same reasons as https://github.com/schmittjoh/serializer/issues/999#issuecomment-427835621

**Comment by goetas** [comment]
If you need to handle errors in date conversion, you can implement your own date handler

**Comment by sneakyvv** [comment]
FYI: I have implemented it like this with decorated services 
https://gist.github.com/sneakyvv/743b089c58c6d172d347899f85035190

**Comment by goetas** [comment]
> FYI: I have implemented it like this with decorated services
https://gist.github.com/sneakyvv/743b089c58c6d172d347899f85035190

looks very good to me!
