### ISSUE TITLE
Stop following exclusion strategy executing  after a specific one

### ISSUE THREAD

**Issue by videni** [schmittjoh/serializer#1059]
I know exclusion strategies who registered first will be executed before the later. I  have a custom strategy, when the shouldSkipProperty of this strategy  returns, I want  to stop the following strategies  from executing. anyway to do this ?

**Comment by goetas** [comment]
It looks that you have to use your custom https://github.com/schmittjoh/serializer/blob/master/src/Exclusion/DisjunctExclusionStrategy.php and to not use the exclusion strategies by the serializer.

Using DisjunctExclusionStrategy should allow you to implement your exclusion strategies.
