### ISSUE TITLE
disabling cdata by default

### ISSUE THREAD

**Issue by lsmith77** [schmittjoh/serializer#1065]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

From my understanding there is no global out of the box way to disable the use of cdata. So one has to explicitly specify this on a per descriminator/xmlelement basis. Would it make sense to add some global configuration options for cdata (and maybe other xml settings)?

**Comment by goetas** [comment]
related to https://github.com/schmittjoh/serializer/issues/752

**Comment by goetas** [comment]
It is not the first time I see this request.

CDATA semantically is the same as not having it (except that does not require you to escape manually the xml)


To not forget that `createElement($name, $value)` is not safe https://3v4l.org/jrDlu

**Comment by lsmith77** [comment]
ok closing in favor of https://github.com/schmittjoh/serializer/issues/752 .. will look into a PR
