### ISSUE TITLE
Override existing property with another

### ISSUE THREAD

**Issue by mikolajzieba** [schmittjoh/serializer#1067]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes/no
| RFC?             | no

I try to override one property with another on serialization, but I wasn't able to do so without removing target property from the serialized object.

I want to replace property "id" with property "fooBar". 
When property "id" doesn't exists in the serialized object, it replaces it as desired, but when it exists - it doesn't.

It's caused by overriding virtualProperty config when source property exists: https://github.com/schmittjoh/serializer/blob/2.2.0/src/Metadata/Driver/YamlDriver.php#L86

## Steps required to reproduce the problem

Serializer config:
```    virtual_properties:
      getFooBar:
        name: id
        serialized_name: id
        type: int
```
Serialized class:
```
class SomeClass {
 public $id;
 public $fooBar;
 public function getFooBar() {
    return $this->fooBar;
 }
}

$toSerialize = new SomeClass();
$toSerialize->id = 1;
$toSerialize->fooBar = 999;
```
## Expected Result

```
{"id":"999"}
```
## Actual Result
```
{"id":"1"}
```

**Comment by goetas** [comment]
This can already be achieved by using a virtual property as "id" filed. and inside there 
```
function getId(){
   return $this->id ?: $this->fooBar;
}```
