### ISSUE TITLE
@ExclusionPolicy(policy="ALL") causes PHP notice message

### ISSUE THREAD

**Issue by NotDvaMain** [schmittjoh/serializer#1073]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Add `@ExclusionPolicy(policy="ALL")` to class.

## Expected Result

Object is serialized with properties that have `@Expose` annotation.

## Actual Result

```
Notice: Undefined index: value
```

Using just `@ExclusionPolicy("ALL")` solves the problem but it would be nice to use `@ExclusionPolicy(policy="ALL")` as well.

**Comment by goetas** [comment]
fixed via https://github.com/schmittjoh/serializer/pull/1106
