### ISSUE TITLE
Format constants (JSON, XML)

### ISSUE THREAD

**Issue by webdevium** [schmittjoh/serializer#1079]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Would be nice to have constants with format, like `JSON` or `XML`.
And example of call:
`$serializer->serialize($object, SerializerBuilder::JSON);`

> Location of constants is unimportant

**Comment by goetas** [comment]
as per https://github.com/schmittjoh/serializer/pull/1105#issuecomment-522296126 closing this
