### ISSUE TITLE
Allow using @XmlValue together with @Accessor/@AccessType

### ISSUE THREAD

**Issue by localheinz** [schmittjoh/serializer#1083]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Use [`jms/serializer:1.5.0`](https://github.com/schmittjoh/serializer/tree/1.5.0).

2. Have XML which cannot be controlled

```xml
<foo bar="40" baz="20">
                    
    https://placekitten.com/200/300
</foo>
```
3.  Have class 

```php
<?php

use JMS\Serializer\Annotation as JMS;

class Foo
{
    /**
     * @JMS\Accessor(
     *     getter="getUrl",
     *     setter="setUrl"
     * )
     * @JMS\Type("string")
     * @JMS\XmlValue
     *
     * @var string|null
     */
    private $url;

    public function setUrl(string $url): void
    {
        $this->url = trim($url);
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }
}
```

4. Deserialize XML into object

```php
$foo = $serializer->deserialize(
    $xml,
    Foo::class,
    'xml'
);

var_dump($foo->getUrl());
```

## Expected Result

```
string(31) "https://placekitten.com/200/300"
```

## Actual Result

```
string(58) "

    https://placekitten.com/200/300
"
```

:bulb: It's of course possible to solve this using something like

```diff
diff --git a/Foo.php b/Foo.php
index f4afea402..7329e3bf2 100644
--- a/backend/Foo.php
+++ b/backend/Foo.php
@@ -25,4 +25,16 @@ class Foo
     {
         return $this->url;
     }
+
+    /**
+     * @JMS\PostDeserialize
+     */
+    public function trimUrl(): void
+    {
+        if (!\is_string($this->url)) {
+            return;
+        }
+
+        $this->url = \trim($this->url);
+    }
 }
```

but I think it would be nice _not_ having to add another method for this.

What do you think?

**Comment by goetas** [comment]
Well, in XML all those spaces have a meaning, so trimming them would be a HUGE bc break, and also not compliant to XML specs

**Comment by goetas** [comment]
adding an option `@XmlValue(trim=true)` could be an acceptable solution

**Comment by localheinz** [comment]
@goetas 

I'm not asking to trim the values, I'm wondering whether it would be possible to use the `@JMS\XmlValue` annotation together with `@JMS\Accessor` or `@JMS\AccessType` - then modifications can be made in userland code.

**Comment by goetas** [comment]
So you are saying that `@JMS\XmlValue` can not be used with `@JMS\Accessor`? If is to, to me sounds more like a bug than a feature request.... Can you submit a failing test case?

**Comment by localheinz** [comment]
Looks like this is already covered by tests:

* https://github.com/schmittjoh/serializer/blob/cb3e1678cf572dade284bad3e55316e2c579c65f/tests/Serializer/XmlSerializationTest.php#L73-L92
* https://github.com/schmittjoh/serializer/blob/cb3e1678cf572dade284bad3e55316e2c579c65f/tests/Fixtures/AccessorSetter.php#L73-L80

I'll take another look, closing for now!

**Comment by localheinz** [comment]
Works like a charm, not sure what I was doing wrong!

**Comment by goetas** [comment]
:+1:
