### ISSUE TITLE
Empty namespace

### ISSUE THREAD

**Issue by antonioturdo** [schmittjoh/serializer#1087]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

I really am not sure whether this is a bug or not. I have a third party xml that looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<A xmlns="http://namespace.org/ns">
   <B xmlns="">text</B>
</A>
```

An empty namespace should means no default namespace has to be considered for B.

Current implementation:

```
$namespaces = $data->getDocNamespaces();

if (isset($namespaces[''])) {
    $prefix = uniqid('ns-');
    $data->registerXPathNamespace($prefix, $namespaces['']);
    $nodes = $data->xpath('./' . $prefix . ':' . $name);
} else {
    $nodes = $data->xpath('./' . $name);
}
```
The document has default namespace, but since "B" element is not in the default namespace, I think xpath correctly doesn't found it.

## Steps required to reproduce the problem

1. Deserialize the xml shown above

## Expected Result

* An object "A" with the "B" property set.

## Actual Result

* An object "A" with null "B" property.

**Comment by goetas** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>
<A xmlns="http://namespace.org/ns">
   <B xmlns="">text</B>
</A>
```

OR 

```xml
<?xml version="1.0" encoding="utf-8"?>
<x:A xmlns="http://namespace.org/ns" y:xmlns="">
   <y:B>text</B>
</x:A>
```

OR
```xml
<?xml version="1.0" encoding="utf-8"?>
<x:A x:xmlns="http://namespace.org/ns">
   <B>text</B>
</x:A>
```

Are all equivalent.

The result depends on your XML mapping info in the entity. Can you share those info please?

**Comment by antonioturdo** [comment]
```
use JMS\Serializer\Annotation as JMS;

/**
 * @JMS\XmlNamespace(uri="http://namespace.org/ns")
 * @JMS\XmlNamespace(uri="", prefix="y")
 * @JMS\XmlRoot(name="A")
 */
class A {
    
	/**
	 * @JMS\Type("MyNamespace\Entity\B")
	 * @JMS\SerializedName("B")
         * @JMS\XmlElement(namespace="")
	 */	
	protected $B;
}
```

In class B I haven't annotations.
The empty namespace annotation in B property does not have effects, because

```
if ($metadata->xmlNamespace) {
    $node = $data->children($metadata->xmlNamespace)->$name;
    if (!$node->count()) {
        return;
    }
}
```

this condition evaluates to false and hovewer, also changing that to $metadata->xmlNamespace !== null, children method does not return nodes.

I also noticed that getDocNamespaces method of SimpleXMLElement does not return the namespace with empty url.

**Comment by goetas** [comment]
Have you just tried omitting `JMS\XmlElement()` on the $B variable?

**Comment by antonioturdo** [comment]
Yes, I did and it does not work.

**Comment by discordier** [comment]
Running into the exact same problem atm while trying to consume and create XML for German Tax authorities.

Currently trying to throw a PR together.

**Comment by goetas** [comment]
Would be great, thanks

**Comment by discordier** [comment]
See #1095.

**Comment by antonioturdo** [comment]
I think it should be handled for collections too.

**Comment by discordier** [comment]
If you could come up with a proper test case, I am willing to add it to my implementation.

However, I'd love to hear input vrom @goetas first if I am on the right track.

PS: @antonioturdo is your issue fixed with my implementation? Did you check?

**Comment by antonioturdo** [comment]
I am sorry I have no time to provide a test case about collections.

**Comment by goetas** [comment]
implemented in https://github.com/schmittjoh/serializer/pull/1095
