### ISSUE TITLE
JsonSerializationVisitor getResult 

### ISSUE THREAD

**Issue by FrKevin** [schmittjoh/serializer#1093]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Question?             | yes

I use a custom handler to serailize an entity. I use this code, to automaticly visit all altributs:

```php
/** @var PropertyMetadata[] $propertyMetadata */
$propertyMetadata = $context->getMetadataFactory()>getMetadataForClass(Media::class)->propertyMetadata;

foreach ($propertyMetadata as $key => $property) {
           // check group 
            // key : is attribut
            $method = 'get' . ucfirst($key);
            $visitor->visitProperty($property, $media->{$method}());
        }

// check device version, to remove or add attributs
``` 
Its impossible to me to get result, the property data in the class JsonSerializationVisitor is private.

In the VisitorInterface we have:
```php
    /**
     * Get the result of the serialization/deserialization process.
     *
     * @param mixed $data
     *
     * @return mixed
     */
    public function getResult($data);
```

But in the class JsonSerializationVisitor return the data parameter not data attribut.
```php
    /**
     * {@inheritdoc}
     */
    public function getResult($data)
    {
        $result = @json_encode($data, $this->options);

        switch (json_last_error()) {
            case JSON_ERROR_NONE:
                return $result;

            case JSON_ERROR_UTF8:
                throw new RuntimeException('Your data could not be encoded because it contains invalid UTF8 characters.');

            default:
                throw new RuntimeException(sprintf('An error occurred while encoding your data (error code %d).', json_last_error()));
        }
    }
```

How can get data attributs in JsonSerializationVisitor ?
Thanks for the help

**Comment by goetas** [comment]
Hi, can you please explain what is the "data attribute"? Did not get that part...
If you want to add remove properties, you should use exclusion strategies to skip attributes and post serialize events to add them.

The recommended approach is to declare all the props in the Metadata, and exclude them via exclusion strategies

**Comment by FrKevin** [comment]
For "data" in the class "JsonSerializationVisitor", there is a "data" attribute, it contains the results of the serialization.
I will try your approach.

**Comment by goetas** [comment]
considering this as answered
