### ISSUE TITLE
Support for iterable

### ISSUE THREAD

**Issue by simPod** [schmittjoh/serializer#1094]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Here https://github.com/schmittjoh/serializer/issues/1023 the generators and iterators support was implemented. I wonder would it be possible to support `iterable`?

Currently, I have to type against concrete type, eg.  
`* @Serializer\Type("array<T>")`  
`* @Serializer\Type("Generator<T>")`

I'd like to type as `* @Serializer\Type("iterable<T>")`. I suppose it could be deserialized eg. as an array when deserializing.

Would it make sense?

**Comment by goetas** [comment]
I think here my answer is the same as for the `Iterator` interface, see in https://github.com/schmittjoh/serializer/pull/1034#discussion_r251248190

**Comment by simPod** [comment]
I was thinking that since we're working with interface the implementation shouldn't matter (if end user respect the type ofc).

The issue is that currently it's not possible to have:

```php
/**
 * @Serializer\Type("Generator<T>")
 * @var iterable<T>
 */
private $collection;
```

`@var` says that it expects interface so implementation doesn't matter. But serializer requires concrete type. This breaks LSP.

**Comment by goetas** [comment]
how to deserialize `@Serializer\Type("iterable<T>")`? 

Do you want to say that using `iterable<T>`, the consumer should not care if it has an array, an iterator or other, the important is that is unserialized into something "iterable" ?

**Comment by simPod** [comment]
Yes exactly. I don't see any better way when working with interfaces. But consumer should not care about implementation when expecting interface. 🤔

**Comment by goetas** [comment]
You convinced me. 

With this in mind, then `Iterator` can also be implemented, amending my comment in https://github.com/schmittjoh/serializer/pull/1034#discussion_r251248190

**Comment by simPod** [comment]
Will look into it, thanks!
