### ISSUE TITLE
Cache warmup

### ISSUE THREAD

**Issue by j** [schmittjoh/serializer#11]
I noticed metadata caches on the fly.  Is there any clever way of caching all via command / function call?

This probably belongs in the metadata library, but since serializer is used more commonly, I'd like to flag this here.  We are going to start using the serializer in a high traffic application, and don't want to run across any caching issues.  I'd rather like to run a command before symlinking a directory in production ensuring all metadatas are cached.

If this doesn't belong here, then what's the best way to achieve this without running serialize() or getMetadataForClass () on every model before going live.

This also pertains to https://github.com/schmittjoh/metadata/issues/19

**Comment by goetas** [comment]
solved in https://github.com/schmittjoh/JMSSerializerBundle/pull/615
