### ISSUE TITLE
How to use fromArray correctly?

### ISSUE THREAD

**Issue by igor-tvardyi** [schmittjoh/serializer#1100]
I try to reproduce logic of symfony/serializer to create object from array.
`$dto = $this->symfonySerializer->denormalize($data, CreateMessageDTO::class);`

So I do:
`$dto = $this->jmsSerializer->fromArray($data, CreateMessageDTO::class);`

$data is an array from request.

But JMS requires specifying types for each property and here I have a problem.
**When I apply @Serializer\Type("string") for property and put in request an array it cannot be converted to string.**
JMS tries to do casting here:

`public function visitString($data, array $type): string`
`    {`
    `        return (string) $data;`
`    }`

So, when I put data from request with wrong type I get an exception: php notice.

**Comment by goetas** [comment]
What should be the expected behavior in your opinion here?

**Comment by igor-tvardyi** [comment]
I expected to to find type "any"

**Comment by goetas** [comment]
PHP does not have a type "any" and JMS when deserializing needs to know in which type deserialize the incoming data.

If your input data are not following the model, you should validate them first.

If you want a property to be able to have multiple types (string|array|SomeClass as example), you can use custom handlers as explained in https://jmsyst.com/libs/serializer/master/handlers
