### ISSUE TITLE
Could not deserialize object if all properties have not type

### ISSUE THREAD

**Issue by surikman** [schmittjoh/serializer#1102]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes #1080 
| RFC?             | no
| Affected version            | 1.3.0

## Steps required to reproduce the problem

1. Create e.g. `AbstractClass` with some private property (e.g.: `metadata`)
2. Create `User` which extends `AbstractClass` and add some property to this `User` (e.g.: `username`)
3. add `@Type("string")` as deserialization type
3. Deserialize json `{"username": "JohnDoe"}` to `User` 

## Expected Result

* class `User` will have filled property `username` with string "JohnDoe" and `AbstractClass` will have still null private property `metadata` 

## Actual Result

* Exception: You must define a type for AbstractClass::$metadata.

## Problem:
src/GraphNavigator/DeserializationGraphNavigator.php
This BC Break comes from #1080

**Comment by goetas** [comment]
Can you provide a failing test case that works before #1080 and does not after?

I stil can not figure it out...

**Comment by surikman** [comment]
Thanks!
