### ISSUE TITLE
PHP7.4: Deprecated warning - serializationContext.php on line 152

### ISSUE THREAD

**Issue by rbairwell** [schmittjoh/serializer#1111]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Setup a PHP7.4 environment with deprecated warnings turned on.
2. Serialize something (I will expand on this once I've identified the exact cause)
3. Receive:
`<b>Deprecated</b>:  Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in <b>/data/vendor/jms/serializer/src/SerializationContext.php</b> on line <b>152</b>`

## Expected Result

No deprecated warning

## Actual Result

`<b>Deprecated</b>:  Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in <b>/data/vendor/jms/serializer/src/SerializationContext.php</b> on line <b>152</b>`

**Comment by goetas** [comment]
Hi, thanks for reporting this. 
I started to work on PHP 7.4 compatibility in https://github.com/schmittjoh/serializer/pull/1113

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/pull/1113
