### ISSUE TITLE
Upgraded 2.4 -> 3.4 / Symfony 4.3.3

### ISSUE THREAD

**Issue by tlorens** [schmittjoh/serializer#1112]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | Maybe?
| RFC?             | no
| Platform | MacOS Majave
| PHP | 7.2.15
| JSON | 1.6.0

# Source JSON to deserialize
```
{
    "id": 1,
    "shortName": "Short Description",
    "description": "Default description of imported template.  Please edit me.",
    "templateType": {
        "id": 1,
        "shortName": "Template v3.2"
    },
    "reusable": true,
    "auditTemplateProcesses": [{
        "id": 1,
        "sequence": 1,
        "processObjective": {
....
```
# Output

```
  #id: 1
    -shortName: null
    -description: "Default description of imported template.  Please edit me."
    -templateType: null
    -ancestor: null
    -reusable: true
    -version: null
    -srcFile: null
    #auditTemplateProcesses: null
```

Getting an entire project up to date.  Upgraded JMS serializer and now nested objects don't seem to be deserialized and are null/empty.  The top level properties appear to be set just fine.  I feel like I may be doing something wrong?  I've tried adding @Expose and setting @Type just to see if that mattered.  I've reset the JMS yaml config file to defaults.  

So I have an Object with an array of nested Objects.  This array is empty.  JSON source hasn't changed.   I've tried changing from lazy loading to eager loading.

**Comment by goetas** [comment]
Hi,
I think you should add more details to the bug report.
Current code, current json, current output and expected output. 

Did you follow the instructions in the upgrading document https://github.com/schmittjoh/serializer/blob/master/UPGRADING.md? 

It is difficult to guess the issue...

**Comment by tlorens** [comment]
> Hi,
> I think you should add more details to the bug report.
> Current code, current json, current output and expected output.
> 
> Did you follow the instructions in the upgrading document https://github.com/schmittjoh/serializer/blob/master/UPGRADING.md?
> 
> It is difficult to guess the issue...

I read the upgrading instructions and I don't use those features.  Just basic Object->JSON->Object type stuff.  Nothing fancy.

**Comment by goetas** [comment]
are you sure the naming strategy works correct? I see only the "description" field being deserialized...

**Comment by tlorens** [comment]
> are you sure the naming strategy works correct? I see only the "description" field being deserialized...

Boom! Fixed!! Fixed up the the YAML files and had to nuke the cache manually.   

Thanks for pointing me in the right direction!
