### ISSUE TITLE
deserialize

### ISSUE THREAD

**Issue by elvispdosreis** [schmittjoh/serializer#1114]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

In a **state** table, I have the **id** and **code** as the **unique key**.

Jms tries to deserealize by id, it is possible to put a notation for it to try to find the entity by **id** or **code**

json
```
{
    "id": 1,
    "email": "elvis@gmail.com",
    "address": {
        "zip_code": "15040190",
        "street": "Rua Santa Paula 3941",
        "number": 1,
        "neighborhood": null,
        "city": "São José do Rio Preto",
        "state": {
            "name": "São Paulo",
            "code": "SP"
        },
        "country": {
            "name": "Brasil",
            "code": "BRA"
        },
        "complement": "Bloco K Apt 11",
        "reference": null
    },
}
```
usage
```
<?php
$customer = $this->serializer->deserialize(json_encode($customer), \App\Domain\Customer::class, 'json');
if ($this->em->getUnitOfWork()->getEntityState($customer) === UnitOfWork::STATE_NEW) {
            $this->em->persist($customer);
}
$this->em->flush();
```

**Comment by goetas** [comment]
jms/serializer will try to find the entity based on the primary key of the table (not some unique keys..), thus if you need such behavior you need a custom  construction class, see [here](https://github.com/schmittjoh/serializer/tree/master/src/Construction) for more info.
