### ISSUE TITLE
Add support for PSR-7 URIInterface objects

### ISSUE THREAD

**Issue by deviantintegral** [schmittjoh/serializer#1115]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

I've had a second project come up where I've needed to serialize and deserialize URI objects. I split the code out into [deviantintegral/jms-serializer-uri-handler](https://packagist.org/packages/deviantintegral/jms-serializer-uri-handler), and it's usable as is. You need a concrete implementation to deserialize, and I wasn't sure if adding a dependency on guzzle/psr7 (or Zend Dictaros) would be considered for the core serializer.

Thoughts? Happy to file a PR to bring this in if it makes sense.

**Comment by goetas** [comment]
Hi, thanks for your proposal. Unfortunately I can not accept this feature request.

Custom handler for some specific data-types are included only of they are part of PHP and they offer a benefit to a big segment of users.
There are some exceptions for popular projects as libraries as doctrine or symfony, supporting some datatypes for that projects surely brings benefits for a big portion of users.

I think that having a separate repository with that handler is a good idea.
