### ISSUE TITLE
StaticPropertyMetadata first constructor argument not nullable

### ISSUE THREAD

**Issue by KDederichs** [schmittjoh/serializer#1116]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Create a post serialisation listener
2. Try to add a property according to https://github.com/schmittjoh/serializer/blob/1792fe207b8addce6c65f9acd75822eacff3408e/src/JsonSerializationVisitor.php#L169

## Expected Result

* It serialises the property correctly

## Actual Result

* ```TypeError: Argument 1 passed to JMS\Serializer\Metadata\StaticPropertyMetadata::__construct() must be of the type string, null given```

Looks like the first argument is typed as not nullable string, if that value can indeed have the value null the typing in the constructor of ```StaticPropertyMetadata``` should be changed.

**Comment by goetas** [comment]
This has been updated in https://github.com/schmittjoh/serializer/blob/master/UPGRADING.md

> Removed deprecated method JsonSerializationVisitor::addData, use `::visitProperty(new StaticPropertyMetadata('', 'name', 'value'), null)` instead

That file has been updated, most probably we forgot to update the comment in the file.

**Comment by KDederichs** [comment]
Ok thanks for pointing that out, I do have a follow up question regarding that though:

when I do ```$visitor->visitProperty(new StaticPropertyMetadata('', 'field', 'value') , null);```
It turns out to serialise as ```null``` though instead of ```value```

When I do ```$visitor->visitProperty(new StaticPropertyMetadata('', 'field', 'value' ), 'value2');```

It put's ```value2``` in the serialised data.
That behaviour is completely different from both Documentations and I'm wondering if I'm missing something here.

**Comment by goetas** [comment]
If you want to update the documentation/comment with the current behavior (that most probably is the one I had in mind when implementing the feature), a PR is welcome

**Comment by goetas** [comment]
see https://github.com/schmittjoh/serializer/pull/1118
