### ISSUE TITLE
Throw exceptions on invalid input

### ISSUE THREAD

**Issue by evillemez** [schmittjoh/serializer#112]
Is there a way to have the serializer throw exceptions on bad input?  Was this considered and not done for any particular reason?

Imagine you are accepting input in a REST api.  You use the serializer to deserialize the input from the client, and then you use a validator to validate the model before persisting it.

In this scenario (which I think is fairly common), you lose bad input - for example the client setting a field that does not exist, or a read only field.  The operation works fine, the client can't corrupt the data, but since the serializer swallows the bad input, you also cannot really warn the client that they are misusing the API.

Am I just doing it wrong? :) Is there a better workflow for handling this scenario?

**EDIT:** If this is possible to implement in the serializer, what's the best way to go about it?  A custom ExclusionPolicy?

**Comment by goetas** [comment]
closing for the same reason of https://github.com/schmittjoh/serializer/pull/591#issuecomment-296217640
