### ISSUE TITLE
Travis builds on 1.x are failing

### ISSUE THREAD

**Issue by sanmai** [schmittjoh/serializer#1120]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Builds on Travis CI are failing for the 1.x branch because of PHP 5.5 not being included in the default distribution any more. [An example of the failure.](https://travis-ci.org/schmittjoh/serializer/jobs/580979564)

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/pull/1119 is merged
