### ISSUE TITLE
Overriding groups of deeper branches of the graph

### ISSUE THREAD

**Issue by inwaar** [schmittjoh/serializer#1121]
![image](https://user-images.githubusercontent.com/3331076/64546449-6272e300-d333-11e9-8661-8a89b9b5b409.png)

The documentation is not clear.
What do mean `manager` and `friends` array keys passed to `setGroups` in array?
Are those names of the properties on the object to be serialized?

Is this feature is working at all?
https://github.com/schmittjoh/serializer/issues/1058

This seemed to remove part or all of it?

**Comment by goetas** [comment]
Hi, the feature is part of jms/serializer v3.x as described. The PR is https://github.com/schmittjoh/serializer/pull/1071

`manager` and `friends` are the names of properties of the `User` class available few lines before.

The main aim of the feature is to be able to set a generic group for the whole class, and a specific group for a particular property.

As example:

```php
use JMS\Serializer\Annotation\Groups;

class User
{
    /** @Groups({"generic"}) */
    private $name;

    /** @Groups({"specific"}) */
    private $email;

    /** 
    * @var User 
    * @Groups({"generic"})
    * */
    private $manager;
}
```
```php
$context = SerializationContext::create()->setGroups(array(
    'generic',
    'manager' => array(
        'specific', 
    ),
));
```

will produce something as 
```json
{
  "name": "John",
  "manager": {
     "email": "info@example.com"
  }
}
```


If you had only 
```php
$context = SerializationContext::create()->setGroups(array(
    'generic'
));
```

Result would have been:

```json
{
  "name": "John",
  "manager": {
     "name": "Tom"
  }
}
```

**Comment by graanday** [comment]
Hi,
is it possible to set a specific group to each friend?
specific1 for 'John friend 1'
specific2 for 'John friend 2'

**Comment by scyzoryck** [comment]
@graanday do you mean different groups depending on the object value?

**Comment by graanday** [comment]
> @graanday do you mean different groups depending on the object value?

yes

**Comment by scyzoryck** [comment]
I guess you'd like to use it for the exclusion, right? 
Then you can use  [ExpressionLanguageExclusionStrategy](https://github.com/schmittjoh/serializer/blob/bf1105358123d7c02ee6cad08ea33ab535a09d5e/doc/cookbook/exclusion_strategies.rst#L318) or implement your own Strategy ;-)
