### ISSUE TITLE
Make possible to set ArrayCollectionHandler classes from outside

### ISSUE THREAD

**Issue by alexander-schranz** [schmittjoh/serializer#1131]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes/no?

The ArrayCollectionHandler classes are currently hardcoded. It would be good if the ArrayCollectionHandler get its classes from outside and so in the jms serializer bundle I could use PrependExtension in my bundle config to add a class to the ArrayCollectionHandler.

## Expected Result

* Allow to add ArrayCollection classes to Handler

## Actual Result

* Classes are hardcoded and no other classes can be added from outside.

**Comment by goetas** [comment]
What do you mean by "hardcoded" ?

If you want to add extra extensions you can do this:

```php
$serializerBuilder = SerializerBuilder::create();
$serializerBuilder->addMetadataDir('metadata dir', 'TestNs');
$serializerBuilder->configureHandlers(function (HandlerRegistryInterface $handler) use ($serializerBuilder) {
     // default handlers
    $serializerBuilder->addDefaultHandlers();
   // your handlers
   $handler->registerSubscribingHandler(new YourhandlerHere());
});
```

**Comment by alexander-schranz** [comment]
@goetas sorry I mean this classes are hardcoded: 

https://github.com/schmittjoh/serializer/blob/4c1e4296734385af7718ca71ec0febb4815b4a87/src/Handler/ArrayCollectionHandler.php#L34-L40

And would think about something like this in the JMS SerializerBundle to add your custom ArrayCollectionClasses:

```
jms_serializer:
     handlers:
          array_collection:
                classes:
                      - CustomClass
```

**Comment by goetas** [comment]
you can easily register more handlers 

```xml
<service id="app.my_handler" class="JMS\Serializer\Handler\ArrayCollectionHandler">
    <tag name="jms_serializer.handler" type="CustomClass" 
                direction="serialization" format="json"
                method="serializeCollection" />

    <tag name="jms_serializer.handler" type="CustomClass"
                direction="serialization" format="json"
                method="serializeCollection" />
</service>
```

This will register ArrayCollectionHandler for the CustomClass type

**Comment by alexander-schranz** [comment]
Oh didn't thought about that solution. Great! Thank you!
