### ISSUE TITLE
Embed JSON string without extra escape

### ISSUE THREAD

**Issue by bobvandevijver** [schmittjoh/serializer#1142]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I have an object which contains a couple of file reference, one of which is a JSON file. I want to serialize this object into JSON, but the not serialize the JSON string again.

I'm already using a custom serialization handler to convert the files into their string representation.

```php
$visitor->visitProperty(
        new StaticPropertyMetadata('', 'field', NULL),
        $object->file->getContents());
```

This results in:
```json
{
  "field": "[{\"id\": 1, \"prop\": 1}]"
}
```

Instead of the wanted:
```json
{
  "field": [{"id": 1, "prop":1}]
}
```

I have now fixed this with a smallworkaround (using `json_decode` to deserialize the JSON string first), but is there a way to do this without the extra deserialize/serialize roundtrip?

```php
$visitor->visitProperty(
        new StaticPropertyMetadata('', 'field', NULL),
        json_decode($object->file->getContents(), true));
```

**Comment by goetas** [comment]
The way you did is the right one. The internal data structure requires an array, that will be converted later in json.
