### ISSUE TITLE
[Improvement] Abilities to unset data in post serialization.

### ISSUE THREAD

**Issue by Yivan** [schmittjoh/serializer#1143]
Hello,

First thanks a lot for bringing to us this library. It is a great work ! : )

I woul like to propose an improvement because it doens't seems possible to handle this use case actually (or if yes, do need to be improved to explain it so).

# Use case:
Here is the use case:
- i have got many php classes being autogenerated and i cannot use direct annotation in those php classes
- the classes autogenerated use all the same Trait (which i cannot modify, to add directly annotation for instance)

What i try to achieve:
- exclude for all those classes some properties of the Trait.

Actual possibility, but not very friendly:
If i use YML (https://jmsyst.com/libs/serializer/master/reference/yml_reference), I need to make as many yml file than autogenerated classes, as the Trait property can only be exclude by ading exclusion in the php class calling the Trait. This is really not a good way to solve this i think.

# Proposition:
**Having possibility to exclude directly some properties in the post serialize event.**

Actually we have `$visitor->setData($key, $value)` (i got hard time to find it... not documented on https://jmsyst.com/libs/serializer... it should i think it is an important feature).
It would be nice to be able te remove the key, with a method like: `$visitor->unsetData($key)`.

(i should add a side bug i found, if i use `$visitor->setData($key, $value)` on already existing key, value is not changed !? Shoud another issue being opened ?)

Thanks a lot for reading me.

**Comment by goetas** [comment]
Hi. Wouldn't be easier (and more performant) to implement a custom exclusion strategy and pass it to the context? See https://github.com/schmittjoh/serializer/blob/87c992ddaa5f228efecc22e8db3db0fcf7f1db97/src/Exclusion/ExclusionStrategyInterface.php#L26

**Comment by Yivan** [comment]
Thanks for your very fast return on this !
Yes sure, it is better to handle it before serialize for performance.

I wasn't aware of those two ways to manage exclusion. They are not documented it seems (see please: https://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies).

Is your proposition already working ? Is there some exemple to implement them ?
If not i will try to dig in the code so.

Thanks.

**Comment by goetas** [comment]
One way is documented in https://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#dynamic-exclusion-strategy (this does not require you to implement a custom exclusion strategy, but you can use the symfony expression language to exclude props at runtime).

Another way, using custom exclusion strategies is explained in https://stackoverflow.com/questions/21916450/how-do-i-create-a-custom-exclusion-strategy-for-jms-serializer-that-allows-me-to

**Comment by Yivan** [comment]
Yes, i saw for the expression language, but exemple only given for annotation... and not plain html code.
Maybe plain php code exemple should be added.
Your stackoverflow links will be helpfull.

Thanks again for having taking time to discuss this. I confirm task could be left close so. Just some docs imporvement would be welcome because it is hard sometimes to find php code (docs focus a lot on annotation).
Best regards!
