### ISSUE TITLE
[Improvement] Ability to define a global exclusion_policy: ALL for all classes.

### ISSUE THREAD

**Issue by Yivan** [schmittjoh/serializer#1144]
Hello,

Actually we can only set exclusion_policy: ALL at the class level. When having many classes whith complexe inheritence (vendor package where we can not use annotation), the only way seems actually to create an class yml file for each classes and parent classes to set exclusion_policy: ALL.

This improvement is about adding a global parameters to the builder or context, which will set by exclusion_policy: ALL for all classes.

For instance something like:
`$context->setExcludePolicyAll(true);`
(like we have actually a global way to serialze null value: `$context->setSerializeNull(true);`)

Thanks

**Comment by goetas** [comment]
Global settings have been discussed and dismissed in https://github.com/schmittjoh/serializer/issues/1025 https://github.com/schmittjoh/JMSSerializerBundle/pull/427 https://github.com/schmittjoh/JMSSerializerBundle/issues/530

**Comment by Yivan** [comment]
Thanks, I have read the discussion.

What i mean is not a global static one, maybe the title is wrong and should be changed.
But more a settings for the context in the actual run for serialization. So it want change other serailization call made by other bundles.
As we can set `$context->setSerializeNull(true);`, cannot we set something like `$context->setExcludePolicyAll(true);` ? I missed something ?

**Comment by goetas** [comment]
the main reason for that is explained in https://github.com/schmittjoh/JMSSerializerBundle/pull/427#issuecomment-179178005 (other projects can not generate metadata about serialized classes, and this library itself started to explore some ideas in https://github.com/schmittjoh/serializer/pull/903, and context dependent configurations are a stil a problem)

`setSerializeNull` was implemented at the very beginning of the creation of this library... NULL handling is always tricky... so I do not know if it was a good idea or not...

**Comment by Yivan** [comment]
Thanks, i understand better! This task can remain close so.
Best regards.
