### ISSUE TITLE
Calling `Serializer::serialize` for more than one time leads to `LogicException`

### ISSUE THREAD

**Issue by boesing** [schmittjoh/serializer#1146]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Create serialization object
2. Call Serializer with `Serializer::serialize($object, 'json');`
3. Create another serialization object
3. Call Serializer again with `Serializer::serialize($anotherObject, 'json');`

## Expected Result

* Objects used for `Serializer::serialize` are both converted to string

## Actual Result

* LogicException `This context was already initialized, and cannot be re-used.`

**Comment by goetas** [comment]
Hi! Are you sure that you are not passing a third argument with the `$context`? If yes, each `serialize` call must have a new context.

**Comment by boesing** [comment]
I am calling the method just with the two parameters. 
The context factory returns a mutable context for both calls and therefore the context used for the second call is already initialized and throws that exception.

**Comment by goetas** [comment]
> The context factory returns a mutable context for both calls and therefore the context used for the second call is already initialized and throws that exception.

Are you using a custom context factory?

**Comment by boesing** [comment]
Damn, you're right... The package I am using is returning a mutable context which is not freshly instantiated... 
Sorry for wasting your time.
