### ISSUE TITLE
Properties with @Groups annotations included in output when no SerializationContext given.

### ISSUE THREAD

**Issue by pdugas** [schmittjoh/serializer#1149]
| Q                | A
| ---------------- | -----
| Bug report?      | Yes
| Feature request? | No
| BC Break report? | No
| RFC?             | No

## Steps required to reproduce the problem

1. Define a class with one or more properties with no annotations and one or more with `@Groups`.
```
use JMS\Serializer\Annotation\Groups;

class Eg
{   
    private $id = 1;

    /** @Groups({"WithFoo"}) */
    private $foo = 'foo';
}
```
2. Serialize an instance of the class without specifying a SerializationContext.
```
$this->assertSame(['id'=>1], json_decode($serializer->serialize(new Eg(), 'json')));
``` 
3. Check the output.
```
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
 Array &0 (
     'id' => 1
+    'foo' => 'foo'
 )

```

## Expected Result

* The `foo` property should not have been included in the result.

## Actual Result

* See above. `foo` property is incorrectly included.
* I can make the test pass by explicitly adding the `Default` group.
```
$this->assertSame(
    ['id'=>1], 
    json_decode($serializer->serialize(
        new Eg(), 'json',
        SerializationContext::create()->setGroups(['Default'])
    ))
);
```

The way I read the documentation, only the `Default` group should be serialized by default. Am I wrong?

**Comment by goetas** [comment]
If you don't pass to the context some groups, the serialization groups exclusion strategy is not used at all, thus all props are serialized

**Comment by pdugas** [comment]
Got it @goetas. I've adjusted my usage so I always specify the Default group when serializing the returned data from my API and optionally add groups like "withfoo" and "withbar" based on a query parameter from the client. Works great.  Thanks.
