### ISSUE TITLE
DateTime parsed invalid date

### ISSUE THREAD

**Issue by michaljusiega** [schmittjoh/serializer#1152]
| Q                | A
| ---------------- | -----
| Bug report?      | probably yes
| Feature request? | no
| BC Break report? | probably yes
| RFC?             | yes if accepted this issue

## Steps required to reproduce the problem

1. @Serializer\Type("DateTime<'Y-m-d', 'Europe/Warsaw', '|Y-m-d'>")
2. Pass to value a 2020-13-03
3. Get a 2021-01-03 object DateTime

## Expected Result

* I think should throws RuntimeException

## Actual Result

* Valid object

## Solution

In DataHandler after: 
```
        if (false === $datetime) {
            throw new RuntimeException(sprintf('Invalid datetime "%s", expected format %s.', $data, $format));
        }
```

should be next check about last errors:

```
        if (false === $datetime) {
            throw new RuntimeException(sprintf('Invalid datetime "%s", expected format %s.', $data, $format));
        }

        if ((\DateTime::getLastErrors()['warning_count'] ?? 0) > 0) {
            throw new RuntimeException(sprintf('The parsed date "%s" was invalid', $data));
        }
```

**Comment by michaljusiega** [comment]
Bump. ;)

**Comment by goetas** [comment]
This is not a bug but the normal PHP'd DateTime behavior. See https://3v4l.org/pHq23

if you need to validate your incoming data, you should use the preDeserialize event.

**Comment by goetas** [comment]
```phph
 if ((\DateTime::getLastErrors()['warning_count'] ?? 0) > 0) {
            throw new RuntimeException(sprintf('The parsed date "%s" was invalid', $data));
}
```

This sounds a good thing but would result in a BC break. I can accept this new behavior only if the PR allows to opt-in for this stricter validation. (maybe passing some parameter in the constructor?

**Comment by michaljusiega** [comment]
Hi @goetas.
Thanks for answer on my issue. I know that is a expected behavior in PHP but not in the package. If I deserialize something like Date in my opinion should be one to one same like input data.

btw, PR should be on 4.0 version, right ?

**Comment by goetas** [comment]
If we make the `DateHandler` constructor as:

```php
__construct(
  string $defaultFormat = \DateTime::ATOM, 
  string $defaultTimezone = 'UTC', 
  bool $xmlCData = true
  string $dateTimeParsing = 'lax', // or 'strict'
)
```

and then we use `$dateTimeParsing` to trigger the strict parsing, I think can be included in the next feature release (3.x)

**Comment by michaljusiega** [comment]
Hi. Sorry for unactivity. I saw a 3.6 release but I can't found a changes in code.

**Comment by goetas** [comment]
> Hi. Sorry for unactivity. I saw a 3.6 release but I can't found a changes in code.

which changes?

**Comment by goetas** [comment]
it seems that the tool i use to generate the changelog messed up, this ticket was closed by you, so no changes have been implemented on my end.

**Comment by goetas** [comment]
As said in https://github.com/schmittjoh/serializer/issues/1152#issuecomment-573519857, i'm happy to accept a PR implementing something as suggested there.

**Comment by michaljusiega** [comment]
I understand. I closed this issue because I thought I couldn't add this option on PR cause is related to bundle too.
