### ISSUE TITLE
hoa/protocol package conflicts with laravel helper

### ISSUE THREAD

**Issue by sleenen** [schmittjoh/serializer#1154]
Hi!

We've upgraded to version 3 within our Laravel application. Laravel uses a helper function 'resolve()', this function however is also being defined by the hoa/protocol package. 

That package does not seem to be maintained however. Can I ask why you are using it? 
And is it possible to replace it ?

Thank in advance. 

ps if you want a better explanation let me know

**Comment by goetas** [comment]
it is used to parse the `@Type(".....")` anttotations, thus can not be replaced

**Comment by sleenen** [comment]
for parsing the specific type set in the annotation you mean?

**Comment by goetas** [comment]
yes, see https://github.com/schmittjoh/serializer/tree/master/src/Type

**Comment by sleenen** [comment]
I see, I was just looking at that.
Is it just used to validate the type given?

**Comment by sleenen** [comment]
I checked it out a bit, I think I understand what is going on (partly at least)
This hoa stuff is not being maintained however. Anyone using Laravel in combination with your package (and maybe Symfony users too) will run into problems because of this issue, which is a shame.

**Comment by goetas** [comment]
can you please share the error message you are having?

**Comment by sleenen** [comment]
Well the error won't actually help you much. The problem is that this file:

https://github.com/hoaproject/Protocol/blob/5c2cf972151c45f373230da170ea015deecf19e2/Wrapper.php

has this piece of code at the end
```
namespace
{
/**
 * Alias of `Hoa\Protocol::resolve` method.
 *
 * @param   string  $path      Path to resolve.
 * @param   bool    $exists    If `true`, try to find the first that exists,
 *                             else return the first solution.
 * @param   bool    $unfold    Return all solutions instead of one.
 * @return  mixed
 */
if (!function_exists('resolve')) {
    function resolve($path, $exists = true, $unfold = false)
    {
        return Hoa\Protocol::getInstance()->resolve($path, $exists, $unfold);
    }
}
}
```

Laravel has something similar, which it uses internally with the IoC. The Hoa one is defined first, so Laravel won't define the function again. Running into a whole lot of issues when trying to instantiate classes. 

The master branch has a Protocol file which does not have this issue, but it has not been tagged in a release it seems and the package it not active it seems.

**Comment by goetas** [comment]
I'm not sure if is compatible, but you can try including `master` of `hoa/protocol`, by requiring

```
"hoa/protocol":"dev-master as 1.17.01.99"
```

**Comment by sanmai** [comment]
Try using [`sanmai/hoa-protocol`](https://packagist.org/packages/sanmai/hoa-protocol), it should be backward-compatible with the original project except for missing `resolve`, and also PHP 7.4 compatible.

**Comment by zeevin** [comment]
anyone who affected by this issue could use the old 1.0 version ,it still work
