### ISSUE TITLE
Accessing static property as non static

### ISSUE THREAD

**Issue by AlexeyKosov** [schmittjoh/serializer#1156]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I use the serializer v3.4.0 with Symfony 5 and just ran into the issue:

**Notice: Accessing static property Symfony\Component\Cache\Adapter\PhpArrayAdapter::$valuesCache as non static**

ErrorException in /vendor/jms/serializer/src/Accessor/DefaultAccessorStrategy.php (line 86) 
```
                    $this->readAccessors[$metadata->class] = \Closure::bind(static function ($o, $name) {
-->                     return $o->$name;
                    }, null, $metadata->class);
```

Stack trace:

1.
/vendor/jms/serializer/src/Accessor/DefaultAccessorStrategy.php :: JMS\Serializer\Accessor\{closure} (line 91) 

```
return $this->readAccessors[$metadata->class]($object, $metadata->name);
```

2.
/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php -> getValue (line 234) 
```
$v = $this->accessor->getValue($data, $propertyMetadata, $this->context);
```

3.
/vendor/jms/serializer/src/JsonSerializationVisitor.php -> accept (line 136) 
```
$v = $this->navigator->accept($v, $metadata->type);
```

4.
 /vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php -> visitProperty (line 241) 
```
$this->visitor->visitProperty($propertyMetadata, $v);
```

5.
/vendor/jms/serializer/src/JsonSerializationVisitor.php -> accept (line 136) 
```
$v = $this->navigator->accept($v, $metadata->type);
```

6.
/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php -> visitProperty (line 241) 
```
 $this->visitor->visitProperty($propertyMetadata, $v);
```

7.
/vendor/jms/serializer/src/JsonSerializationVisitor.php -> accept (line 136) 
```
$v = $this->navigator->accept($v, $metadata->type);
```

8.
/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php -> visitProperty (line 241) 
```
$this->visitor->visitProperty($propertyMetadata, $v);
```

9.
/vendor/jms/serializer/src/JsonSerializationVisitor.php -> accept (line 93) 
```
$v = $this->navigator->accept($v, $elType);
```

10.
/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php -> visitArray (line 159) 
```
return $this->visitor->visitArray((array) $data, $type);
```

...

**Comment by AlexeyKosov** [comment]
Looks like the serializer stumbled upon some huge backtrace of an exception and could not cope with it, so probably it's not an issue.

**Comment by xepozz** [comment]
I have the same error in Symfony 4.4.10
![image](https://user-images.githubusercontent.com/6815714/86478811-a1a37200-bd53-11ea-8893-52cdcba528a5.png)

**Comment by goetas** [comment]
solved  in https://github.com/schmittjoh/serializer/pull/1237

**Comment by xepozz** [comment]
@goetas can you please release this functionality and update `jms/serializer-bundle`?
I really need this bugfix...

**Comment by xepozz** [comment]
@goetas ?
