### ISSUE TITLE
SerializationGraphNavigator  unaware of serializeNull change of context when altered in PreSerializeEvent

### ISSUE THREAD

**Issue by gabrielspiteri-highlight** [schmittjoh/serializer#1157]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

SerializationGraphNavigator doesn't take into account a possible change in the serializeNull property of the context when altered in a PreSerializeEvent. 

## Steps required to reproduce the problem

1. Configure JMS to serialize_null: false
2. Start serializing an object that has a null value property
3. Add a pre serialize event subscriber
4. In the event call $event->getContext()->setSerializeNull(true)

## Expected Result

* The object's properties with a null value should be included in the resulting JSON

## Actual Result

* The object's properties with a null value are not included.

**Comment by goetas** [comment]
`::setSerializeNull(true)`  should not be called inside event listeners... actually should trigger an exception if done so. So most likely it is a bug.

When the serialization is started, the context should be in read-only mode.
See https://github.com/schmittjoh/serializer/blob/5286388bb55b3fdf68a56abddb6ca2e851e75594/src/Context.php#L133, `assertMutable` should be called inside `setSerializeNull`

**Comment by goetas** [comment]
See https://github.com/schmittjoh/serializer/pull/1159

**Comment by gabrielspiteri-highlight** [comment]
Alright is there a better way to configure specific entities only to serialize nulls ?

**Comment by goetas** [comment]
hmm, not really... serialize null is defined in the context, there is no easy way to do it per-entity

**Comment by gabrielspiteri-highlight** [comment]
Well changing it in the PreSerializeEvent was pretty easy :) ... However I think we could handle it if the Navigators shouldSerializeNull property had a setter function ? ... Currently we worked around the limitation by calling the initialize function with an altered context object than in PostSerialize we set it back to its original value
