### ISSUE TITLE
Serialize to xml properties with attributes using jms/serializer and yaml procuced by goetas-webservices / xsd2php

### ISSUE THREAD

**Issue by joaomfrebelo** [schmittjoh/serializer#1160]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The problem is explained in https://stackoverflow.com/questions/59917635/serialize-to-xml-properties-with-attributes-using-jms-serializer-and-yaml-procuc

## Steps required to reproduce the problem

1. https://github.com/joaomfrebelo/reports_core/blob/master/src/main/resources/schema_1_1.xsd
2. Rebelo\Reports\Pojo\Rreport\JasperfileAType:
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: string
        copies:
            expose: true
            access_type: public_method
            serialized_name: copies
            accessor:
                getter: getCopies
                setter: setCopies
            xml_attribute: true
            type: int
3. 

## Expected Result
```
 <jasperfile copies=”1”>text</jasperfile>
```
## Actual Result
```
 <jasperfile>
    <_value>text</_value>
    <copies>1</copies>
</jasperfile>
```

**Comment by goetas** [comment]
i think that metadata yaml files are simply non loaded. please check you paths and metadata configurations
