### ISSUE TITLE
JMS + Symfony + security voter

### ISSUE THREAD

**Issue by radand** [schmittjoh/serializer#1165]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

I'm using Symfony 4.4 with jms/serializer-bundle 3.5.
I have two entities: User and Post (one to many).
During entity User serialization I get all posts.
I have to use logic from security voter that filter posts.
How do I do that? The documentation has no such chapter.

I wrote this code:
```php
<?php

declare(strict_types=1);

namespace Application\EventSubscriber;

use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use JMS\Serializer\EventDispatcher\EventSubscriberInterface;
use JMS\Serializer\EventDispatcher\ObjectEvent;
use JMS\Serializer\JsonSerializationVisitor;
use Application\Entity\Post;

class ForumSubscriber implements EventSubscriberInterface
{
    protected $authorizationChecker;

    public function __construct(AuthorizationCheckerInterface $authorizationChecker)
    {
        $this->authorizationChecker = $authorizationChecker;
    }

    public static function getSubscribedEvents(): array
    {
        return [
            ['event' => 'serializer.pre_serialize', 'method' => 'onPreSerialize', 'class' => Post::class],
        ];
    }

    public function onPreSerialize(ObjectEvent $event): void
    {
        $post = $event->getObject();

        if (!$this->authorizationChecker->isGranted('show', $post)) {
            /* @var $visitor JsonSerializationVisitor */
            $visitor = $event->getVisitor();
        }
    }
}
```

I don't know how next. How to skip some posts.
I don't know my idea is correct.

**Comment by goetas** [comment]
You need https://github.com/schmittjoh/serializer/tree/master/src/Exclusion

**Comment by radand** [comment]
@goetas exclusion you mantioned only allows to exclude whole collection of entities. In my case I have collection of entities and I want to serialize only some of them depending on security voter decision.

**Comment by arneee** [comment]
Is this the same like https://github.com/schmittjoh/serializer/issues/1098? That issue describes excluding items by defining the exclude criteria on the class.

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/pull/1099 is a work in progress to address this issue

**Comment by arneee** [comment]
Possible now with https://github.com/schmittjoh/serializer/pull/1099

**Comment by arneee** [comment]
This should work on the master version of this package:

```php
/**
 * Post
 *
 * @ORM\Table(...)
 * @Exclude(if="!is_granted('view',object)")
 */
class Post {
```

Implement a Voter to check on each Post if the user is allowed to see it.

**Comment by goetas** [comment]
Thanks @arneee

**Comment by radand** [comment]
I made two commands:
composer remove jms/serializer-bundle
composer req jms/serializer-bundle:dev-master

Next I implemented your code.
I still see all objects but each is empty.

This:
`@JMS\Exclude(if="!is_granted('show', object)")`

and this:
`@JMS\Exclude(if="is_granted('show', object)")`

get same effect.
Security voter for sure is OK.

**Comment by arneee** [comment]
You have added the serializer-bundle, the change is in the serializer package.

add "jms/serializer": "dev-master" to get the master of this package.

**Comment by radand** [comment]
I have in composer.json:
`"jms/serializer": "dev-master",
"jms/serializer-bundle": "^3.5",`

It does't work:
`[2020-04-20 10:39:29] request.CRITICAL: Uncaught PHP Exception ErrorException: "Notice: Undefined offset: 15" at C:\xampp\htdocs\project\vendor\jms\serializer\src\Metadata\ClassMetadata.php line 324 {"exception":"[object] (ErrorException(code: 0): Notice: Undefined offset: 15 at C:\\xampp\\htdocs\\project\\vendor\\jms\\serializer\\src\\Metadata\\ClassMetadata.php:324)"} []
[2020-04-20 10:39:29] php.WARNING: Uncaught Notice: Undefined offset: 15 {"exception":"[object] (ErrorException(code: 0): Notice: Undefined offset: 15 at C:\\xampp\\htdocs\\project\\vendor\\jms\\serializer\\src\\Metadata\\ClassMetadata.php:324)"} []
[2020-04-20 10:39:29] request.CRITICAL: Uncaught PHP Exception ErrorException: "Notice: Undefined offset: 15" at C:\xampp\htdocs\project\vendor\jms\serializer\src\Metadata\ClassMetadata.php line 324 {"exception":"[object] (ErrorException(code: 0): Notice: Undefined offset: 15 at C:\\xampp\\htdocs\\project\\vendor\\jms\\serializer\\src\\Metadata\\ClassMetadata.php:324)"} []`

**Comment by arneee** [comment]
Can you try to clear your Symfony cache?

**Comment by radand** [comment]
It works!
Could you please release a new version with this change?

**Comment by arneee** [comment]
Hi, I'm a contributor, I can not create a new release. I'm sure there will be release sooner or later, you can you the master branch until then :)
