### ISSUE TITLE
setup options for *Visitor classes

### ISSUE THREAD

**Issue by fajnalowiec** [schmittjoh/serializer#1176]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

There should be possibility to set up user extra options for *Visitor classes; eg for JsonSerializationVisitor I cannot set up anything like JSON_HEX_APOS to be used in json_encode. Currently only JSON_PRESERVE_ZERO_FRACTION is hardcoded there.

**Comment by goetas** [comment]
you can setup your own visitor factories, by using `SerializerBuilder::setSerializationVisitor()`. In the factory you can specify custom visitor options.
If you are using the bundle, that can be also configured in the visitor options config.
