### ISSUE TITLE
Serializer doesn't keep types but convert them if not it can

### ISSUE THREAD

**Issue by krabouilleur** [schmittjoh/serializer#1181]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem
0. Symfony + fostrestbundle + jmserializer + SensioFrameworkExtraBundle : [the doc](https://symfony.com/doc/master/bundles/FOSRestBundle/request_body_converter_listener.html)
1. with postman : Post a body { "name": **true** }
2. Body must be mapped with MyClass
```
use JMS\Serializer\Annotation as JMS;
class MyClass {
    /**
     * @JMS\Type("string") 
     */
    private $name;
}
```
2. My controller : 
```
/*
 * @ParamConverter("myClass", converter="fos_rest.request_body")
 */
public function postMyClass(Myclass $myClass)
    {
        dump($myClass);die();
}
```
3. dump() result
```
MyClass:
{
  name: "1"
}
```

## Expected Result
```
MyClass:
{
  name: true
}
```

'true' should not be converted to string
the serializer have not to convert the boolean in type string 

* 

## Actual Result
'true' is converted to string "1". (same case for numbers where 123 is converted to "123"
Is there a way to keep type ? (so "name" would set to true then in my controller I get error validation)

*

**Comment by goetas** [comment]
This is not a bug but the expected behaviour. If you define `@Type("string")` jms will enforce it to be a string.

You can use `@Type("stringOrBoolean")` and define for `stringOrBoolean` a custom type handler that allows both string and boolean values.

**Comment by krabouilleur** [comment]
ok I understand, so, in API, if we post 
```
{
"IwantToSellMySoulToTheDevil" : "false"
}
```

will be returned to:
```
{
"IwantToSellMySoulToTheDevil" : true
}
```

**Comment by goetas** [comment]
Exactly. "false" passed as string will be evaluated as true by most programming languages

**Comment by krabouilleur** [comment]
Is there a way to override the type "string" for doing thing like this ?
```
@Type("string")

if ( !is_string($value) { 
 // exception
}
```

instead of creating a custom type ?
