### ISSUE TITLE
[RFC] Removing abandoned hoa from serializer

### ISSUE THREAD

**Issue by vsychov** [schmittjoh/serializer#1182]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

Hi guys,

jms serialize use hoa/compiler for parse some data, but looks like hoa project was abandoned since 2018, for now it have problem with php 7.4 opache.preload (https://github.com/hoaproject/Consistency/pull/36, https://github.com/hoaproject/Consistency/issues/35), and nobody react for this. JMS serializer is popular library, that used by lot of peoples in lot of project, but abandoned dependency blocking that projects from migrate to php 7.4, from my side situation looks not very good. 

So depends on above, I propose make decision to remove HOA project from dependency, and use something different, or fork HOA project to another repository, merge exists pull request, and forget about problems with php 7.4.

Best regards.

**Comment by goetas** [comment]
That sounds something that makes sense.

Is there anybody interested to implement the type definition parsing using doctrine lexer or via regex or with some other library?

**Comment by Jean85** [comment]
I rapidly scanned the code... I would like to have it too, but wouldn't this change be a BC requiring a new major? `Hoa\Visitor\Visit` is implemented by `\JMS\Serializer\Type\TypeVisitor`: https://github.com/schmittjoh/serializer/blob/7d81f6ae961801416aa3a8a3120316b978a8f133

Maybe stopping the usage of this class (but not removing it) is enough to fix the preloading issue?

**Comment by Jean85** [comment]
#1184 seems another possible solution, but it has some BC downstream...

**Comment by goetas** [comment]
I think that stopping to use the current `TypeVisitor`, mark it as deprecated, and start using a new implementation (implemented with "whatever") should be enough

**Comment by Jean85** [comment]
I pushed a draft of my approach with #1186. I'm not sure when I'll have time to work further on it.
