### ISSUE TITLE
Does someone know how to use phpdoc with serializer?

### ISSUE THREAD

**Issue by diegosm** [schmittjoh/serializer#1185]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. composer require phpdocumentor/phpdocumentor 
2. ./vendor/bin/phpdoc -d ./src -t ./docs/api

## Actual Result
* Fatal error: Uncaught Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@JMS\Serializer\Annotation\Type" in property phpDocumentor\Configuration::$title was never imported. Did you maybe forget to add a "use" statement for this annotation? in /Volumes/Data/Code/diegosm/keycloak-admin/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:54
Stack trace:
#0 /Volumes/Data/Code/diegosm/keycloak-admin/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(733): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...')
#1 /Volumes/Data/Code/diegosm/keycloak-admin/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(661): Doctrine\Common\Annotations\DocParser->Annotation()
#2 /Volumes/Data/Code/diegosm/keycloak-admin/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(354): Doctrine\Common\Annotations\DocParser->Annotations()
#3 /Volumes/Data/Code/diegosm/keycloak-admin/vendor in /Volumes/Data/Code/diegosm/keycloak-admin/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php on line 54

**Comment by goetas** [comment]
This issue is about phpdoc, I suggest you to open the ticket in their repo
