### ISSUE TITLE
Specify Type as nullable?

### ISSUE THREAD

**Issue by lukepass** [schmittjoh/serializer#1191]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | maybe
| BC Break report? | no
| RFC?             | no

Hello, how can i specify that a type (DateTime, in this case) is nullable?

Not working:

    /**
     * @var null|\DateTime
     *
     * @JMS\Type("?DateTime")
     */
    public $zipDate;

Not working:

    /**
     * @var null|\DateTime
     *
     * @JMS\Type("null|\DateTime")
     */
    public $zipDate;

Not working:

    /**
     * @var null|\DateTime
     *
     * @JMS\Type("DateTime?")
     */
    public $zipDate;

Thanks.

**Comment by goetas** [comment]
I have already examined this feature and currently there is no use case for such feature in the serializer context.

When serializing, the object is already instantiated by other software(and hopefully valid), when de-serializing, it is not serializer responsibility to perform validation.

I'm closing this ticket. If you have a specific use case, I can re-open this.

**Comment by lukepass** [comment]
Hello @goetas,
I actually have a use case for this: I have an API which is consumed by a third-party mobile app.
One of my models has a DateTime property which can be null when there are no data. Unfortunately there is no way to express this right now and the app developer can't know that this field can be null.

It would be really useful to add a support for `?` or add a `nullable` attribute to the `@Type` annotation.

Thanks.

**Comment by goetas** [comment]
I understand the situation and I had similar issues but this behavior is just about documentation, I guess that there is no chage in behavior needed for that case for the serializer library.

Maybe this issue should be raised in the tool you use to generate the API  documentation?

**Comment by lukepass** [comment]
I am using NelmioApiDocBundle which reads the deserialization information from JMS (since I am using it in my project).

Thanks anyway!
