### ISSUE TITLE
Using event listeners for an array on elements

### ISSUE THREAD

**Issue by Aliance** [schmittjoh/serializer#1199]
Is there any way to perform a single operation before serializing a list of elements?

For example, we have an entity called `Item`, and my code looks like:
```php
<?php

class Item
{
    private $id;
    public function __construct ($id) {
        $this->$id = $id;
    }
}

...

$list = [
    new Item(1),
    new Item(2),
    new Item(3),
];

$this->serializer->serialize($responseData, 'json', SerializationContext::create()->setGroups([GroupsExclusionStrategy::DEFAULT_GROUP]));
```

And I have event subscriber with the following code:
```php
<?php

declare(strict_types=1);

namespace App\Listener;

use JMS\Serializer\EventDispatcher\Events;
use JMS\Serializer\EventDispatcher\EventSubscriberInterface;
use JMS\Serializer\EventDispatcher\ObjectEvent;
use JMS\Serializer\Exclusion\GroupsExclusionStrategy;
use JMS\Serializer\JsonSerializationVisitor;
use JMS\Serializer\SerializationContext;
use JMS\Serializer\SerializerInterface;

class ItemSerializationSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            [
                'event' => Events::POST_SERIALIZE,
                'method' => 'onPostSerialize',
                'class' => Item::class,
            ],
        ];
    }

    public function onPostSerialize(ObjectEvent $event): void
    {
        $visitor = $event->getVisitor();

        if (!$visitor instanceof JsonSerializationVisitor) {
            return;
        }

        $object = $event->getObject();

        if (!$object instanceof Item) {
            return;
        }

        $context = $event->getContext();
        $groups = $context->hasAttribute('groups') ? $context->getAttribute('groups') : [];

        //
    }
}
```

I could easily add some extra fields inside it, but **how can I manage to make a single operation for array** of `Item`s, for example, to reduce DB queries?

**Comment by mpoiriert** [comment]
There is 2 way of doing it but they are a bit complexe.

First one would be to pass a custom $serializationVisitors parameter on the Serializer contructor with your own SerializationVisitorInterface and then change the visitArray function.

Other solution would be to create a custom graph navigator and add some logic into it.

It's been a couple of days that I am thinking about build a graph navigator for doctrine that will pass the complete graph and do optimise loading from the database using partial query. Then passing the graph again to do the actual serialization. The goal is to have one query per relation (not one per relation per entity). This is more complex but really generic.

I am just wondering if it's worth the effort since there is so many cache layer that could be put (database, orm, http, etc.) to reduce the load on the system.

**Comment by Aliance** [comment]
> I am just wondering if it's worth the effort since there is so many cache layer that could be put (database, orm, http, etc.) to reduce the load on the system.

Let's assume I'm serializing 100 complex objects, and I need to add extra data from another DB query. If I will get that data by ID, I will have N extra queries. But If I will get extra data by ID **list**, there will be only 1 extra request.

**Comment by Aliance** [comment]
> First one would be to pass a custom $serializationVisitors parameter on the Serializer contructor with your own SerializationVisitorInterface and then change the visitArray function.

> Other solution would be to create a custom graph navigator and add some logic into it.

Thanx a lot, I'll investigate both of the solutions and write here back.

**Comment by Aliance** [comment]
I've spent the whole day of thinking about your suggestions and didn't sure I've completely understood you. Now I'm using build-in [JsonSerializationVisitor](https://github.com/schmittjoh/serializer/blob/1.14.0/src/JMS/Serializer/JsonSerializationVisitor.php), and finally the code flow goes to [GraphNavigator](https://github.com/schmittjoh/serializer/blob/1.14.0/src/JMS/Serializer/GraphNavigator.php), why should I create my own custom GraphNavigator, if I can easily add custom handler to my use-case?

What I'm having right now:

1) I've created my own wrapper for the `Item`s collection:
```php
<?php

declare(strict_types=1);

namespace AppBundle\Serializer;

class ItemList
{
    private array $items;

    public function __construct(array $items)
    {
        $this->items = $items;
    }

    public function getItems(): array
    {
        return $this->items;
    }
}

```

2) Wrapped my response in it:
```php
<?php

$list = new ItemList([
    new Item(1),
    new Item(2),
    new Item(3),
]);

$this->serializer->serialize($responseData, 'json', SerializationContext::create()->setGroups([GroupsExclusionStrategy::DEFAULT_GROUP]));
```

3) And finally add custom handler for `ItemList`:

```php
<?php

declare(strict_types=1);

namespace App\Serializer;

use JMS\Serializer\GraphNavigator;
use JMS\Serializer\Handler\SubscribingHandlerInterface;

class ItemListSubscribingHandler implements SubscribingHandlerInterface
{
    public static function getSubscribingMethods(): array
    {
        return [
            [
                'direction' => GraphNavigator::DIRECTION_SERIALIZATION,
                'format' => 'json',
                'type' => ItemList::class,
                'method' => 'serializeItemList',
            ],
        ];
    }

    public function serializeItemList($visitor, $data, $type, $context)
    {
        return $data;
    }
}

```

But what should I write inside `serializeItemList` method? I can get all the IDs, and query some data, but what's next? I should add them somewhere?

**Comment by mpoiriert** [comment]
Sorry I was thinking about something a lot more generic. Let me explain what I mean first:

Imagine this


```PHP
$list1 = new ItemList([
    new Item(1),
    new Item(2),
    new Item(3),
]);

$list2 = new ItemList([
    new Item(4),
    new Item(5),
    new Item(6),
]);

$list3 = new ItemList([
    new Item(7),
    new Item(8),
    new Item(9),
]);

$responseData = [$list1, $list2, $list3];

$this->serializer->serialize($responseData, 'json', SerializationContext::create()->setGroups([GroupsExclusionStrategy::DEFAULT_GROUP]));
```

In that case you will do one query per Item list because you custom handler will be call 3 times. With a custom graph navigator you could manage to do 1 query for the 3 lists. But to be honest it gets tricky.

To go back to your specific use case (if you don't mind the all node optimisation but just one node at the time) it all depend of what kind of control you have on your object. If you have a full control you can set a property on the Item itself that is just a placeholder for the data. You do listen a pre serialize event for the ItemList you do your query and assign the result (id or object or what ever) to the Items them self, the rest of the flow will be handle by the serializer it self.

If you cannot add a property to the Item class itself you can still use the same technic to fetch the data but you will listen to a post serialize event on the Item itself. You can do a listener class that listen to both and keep the fetch data from the IDs and then assign the proper result in the post serialize.

I am clear enough ?

I could do a gist if you really need to. Just let me know.

Like I mention before if you can use a caching system in your setup optimisation might not be needed as much since the second time the data is fetch you could get it from the cache (if at all possible). But this is more a architecture question not related to JMS.

**Comment by Aliance** [comment]
In my scenario, the real object is `Item`. It's a Doctrine entity I want to expose. But I'm exposing a list of them (for example 100), and I want to add some extra data from another storage to each `Item`. So I can easily make an event listener and fetching ID-specific extra data one by one for each `Item`, but then it causes the 100 extra query which is bad. So, I've added dummy class called `ItemList`, just for wrapping my list of `Items` in it and make my job inside event/handler (btw, what suits me better?).

You write about the problem with exposing list of `ItemList`, but this is no way for that! That class is written just for wrapping, no one will wrap it twice =) So there is no need for custom graph navigator.

About the cache, I don't want to cache here anything because that will lead to another problem: cache invalidation.

> If you have a full control you can set a property on the Item itself that is just a placeholder for the data.

Yes, I have full control. I have a few questions:

1. Should I use pre/post event OR custom handler for my use case? That's difference? Or what's the purpose of both of them? Before that task I've successfully used events, but now I've been stuck.
2. It seems for me, that I should use **post**-event on `ItemList` dummy class because do not sure will the setting extra data on pre-event will cause it's removing while serializing if that field (I mean newly added extra field) won't be configured?

**Comment by mpoiriert** [comment]
If you do a custom handler it you need to handle the full object, with a event you can hook yourself to prepare data.

Here is what I would do with only one event

```PHP
class Item
{
    /**
     * @JMS\Exclude()
     */
    public $externalDbId;

    /**
     * @JMS\Type("TypeOfYourObject")
     * @JMS\Annotation\ReadOnly()
     */
    public $placeHolderProperty;
}

class ItemList
{
    public $items;
}

class MyEventSubscriber implements JMS\Serializer\EventDispatcher\EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return array(
            array(
                'event' => 'serializer.pre_serialize',
                'method' => 'onPreSerialize',
                'class' => ItemList::class, // if no class, subscribe to every serialization
                'format' => 'json', // optional format
                'priority' => 0, // optional priority
            ),
        );
    }

    public function onPreSerialize(\JMS\Serializer\EventDispatcher\PreSerializeEvent $event)
    {
        $ids = [];
        foreach($event->getObject()->items as $item) {
            $ids[$item->externalDbId][] = $item;
        }

        foreach($this->fetchData(array_keys($ids)) as $externalObject) {
            foreach($ids[$externalObject->id] as $item) {
                $item->placeHolderProperty = $item;
            }
        }
    }

    private function fetchData(array $ids)
    {
        //
    }
}
```

If you really don't want to put place holder property here what you can do with 2 events:

```
class MyEventSubscriber implements EventSubscriberInterface
{
    private $externalIds = [];
    public static function getSubscribedEvents()
    {
        return array(
            array(
                'event' => 'serializer.pre_serialize',
                'method' => 'onItemListPreSerialize',
                'class' => ItemList::class, // if no class, subscribe to every serialization
                'format' => 'json', // optional format
                'priority' => 0, // optional priority
            ),
            array(
                'event' => 'serializer.post_serialize',
                'method' => 'onItemPostSerialize',
                'class' => Item::class, // if no class, subscribe to every serialization
                'format' => 'json', // optional format
                'priority' => 0, // optional priority
            ),
        );
    }

    public function onItemListPreSerialize(PreSerializeEvent $event)
    {
        $idsToFetch = [];
        foreach($event->getObject()->items as $item) {
            if(!isset($this->externalIds[$item->externalDbId])) {
                $idsToFetch[] = $item->externalDbId;
            }
        }

        foreach($this->fetchData($idsToFetch) as $externalObject) {
            $this->externalIds[$externalObject->id] = $externalObject;
        }
    }

    public function onItemPostSerialize(ObjectEvent $event)
    {
        $object = $event->getObject();

        $visitor = $event->getVisitor();
        /* @var $visitor JsonSerializationVisitor */

        $value = $this->externalIds[$object->externalDbId];
        $visitor->visitProperty(new StaticPropertyMetadata("", 'externalProperty', $value), $value);
    }

    private function fetchData(array $ids)
    {
        // Put you code here
    }
}
```

You will need to add extra check in case the external object doesn't exist and things like that bu ti's pretty much the flow.

**Comment by Aliance** [comment]
Thanx a lot! A chose 2 events with extra class, but I can't handle the following situation:

```php
<?php

$itemList = new ItemList([
    new Item(1),
    new Item(2),
    new Item(3),
]);

$this->serializer->serialize($itemList, 'json', SerializationContext::create()->setGroups([GroupsExclusionStrategy::DEFAULT_GROUP]));
```

Will serialized into this:
```json
{
    "items": [
        // item 1 serialization,
        // item 2 serialization,
        // ...,
        // item N serialization,
    ],
}
```

But I want only this:
```json
[
    // item 1 serialization,
    // item 2 serialization,
    // ...,
    // item N serialization,
]
```

Is it possible? I can pass `$itemList->getItems()` to serializer, but I'm not sure what ItemList event will be fired in that case?

**Comment by mpoiriert** [comment]
If you pass the $itemList->getItems() to the serializer it's pretty much like you pass the list of item without the serializer.

From your message it doesn't seem that you are this a generic way so why not just make service that receive your Item, load the external information end then just return the array and listent to the post serialize event.

Here would be the code (this is code symfony like since I work with symfony):

```php
<?php

<?php
class MyItemLoader implements EventSubscriberInterface
{
    private $externalIds = [];
    public static function getSubscribedEvents()
    {
        return array(
            array(
                'event' => 'serializer.post_serialize',
                'method' => 'onItemPostSerialize',
                'class' => Item::class, // if no class, subscribe to every serialization
                'format' => 'json', // optional format
                'priority' => 0, // optional priority
            ),
        );
    }

    public function prepareItems(array $items)
    {
        $idsToFetch = [];
        foreach($items as $item) {
            if(!isset($this->externalIds[$item->externalDbId])) {
                $idsToFetch[] = $item->externalDbId;
            }
        }

        foreach($this->fetchData($idsToFetch) as $externalObject) {
            $this->externalIds[$externalObject->id] = $externalObject;
        }
    }

    public function onItemPostSerialize(ObjectEvent $event)
    {
        $object = $event->getObject();

        $visitor = $event->getVisitor();
        /* @var $visitor JsonSerializationVisitor */

        $value = $this->externalIds[$object->externalDbId];
        $visitor->visitProperty(new StaticPropertyMetadata("", 'externalProperty', $value), $value);
    }

    private function fetchData(array $ids)
    {
        // Put you code here
    }
}

class ItemController
{
    public function getList(MyItemLoader $itemLoader)
    { 
        $items = $this->fetchItems();
        $itemLoader->prepareItems($items);
        $this->serializer->serialize(items, 'json', SerializationContext::create()->setGroups([GroupsExclusionStrategy::DEFAULT_GROUP]));
    }
}

```
There is no items list anymore, just one event. The MyItemLoader is call manually and is in charge of what was in the event that have been removed.

Other wise you could do a custom handler for the ItemList and you will have control over the returned structure. You will need to manipulate the Context and Visitor to iterate over the $items but after you just return the $itemList->getItems();

You could look at the JMS\Serializer\Handler\ArrayCollectionHandler If you want a decent code example.

**Comment by Aliance** [comment]
I don't sure that injecting `ItemEventSubscriber` class and saving the state is the best way.
Thanks for your replies, I'll look onto the custom handler.

**Comment by mpoiriert** [comment]
Can you close the issue now that you have enough information to do what you need.

Thanks !

**Comment by Aliance** [comment]
Finally, I've managed to deal with my problem. There is so few information about my needs, that it takes a long for me to solve it.

I've understood that I need to write my custom handler for `ItemList` class for serializing only the array result of `->getItems()` method call. So I wrote `ItemListSubscribingHandler` like this:
```php
<?php

declare(strict_types=1);

namespace AppBundle\Listener;

use AppBundle\DTO\ItemListDTO;
use JMS\Serializer\Context;
use JMS\Serializer\GraphNavigator;
use JMS\Serializer\Handler\SubscribingHandlerInterface;
use JMS\Serializer\JsonSerializationVisitor;

class ItemListSubscribingHandler implements SubscribingHandlerInterface
{
    public static function getSubscribingMethods(): array
    {
        return [
            [
                'direction' => GraphNavigator::DIRECTION_SERIALIZATION,
                'format' => 'json',
                'type' => ItemListDTO::class,
                /** @see ItemListSubscribingHandler::serializeItemListToJson() */
                'method' => 'serializeItemListToJson',
            ],
        ];
    }

    public function serializeItemListToJson(
        JsonSerializationVisitor $visitor,
        ItemListDTO $itemList,
        array $type,
        Context $context
    ) {
        return $itemList->getItems();
    }
}
```

But that won't work for me, because If my handler returns an array, the `Item`s itself won't be serialized via JMS. As I was advised above:
>  You will need to manipulate the Context and Visitor to iterate over the $items but after you just return the $itemList->getItems();
So I tried to Google what should I do with the visitor. I searched @goetas' [article](https://www.goetas.com/blog/whats-new-in-jmsserializer-v20/) about new things in JMS serializer V2 (but I have V1), and it's said that old V1 version should have the code like this:
```php
        if ($visitor->getRoot() === null) {
            $visitor->setRoot($data);
        }
```
I've tried it too but failed. After some debugging, I finally got the correct code, share it with all who needs it in future: `$visitor->visitArray($ItemList->getItems(), $type, $context);`

**Comment by Aliance** [comment]
Let's consider of adding some information into the documentation?
