### ISSUE TITLE
Exclude if at class level are not merge

### ISSUE THREAD

**Issue by mpoiriert** [schmittjoh/serializer#1203]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Create a class hierarchy of at leas 2 class (class B extends A)
2. Configure class B @Exclude(if=true)

## Expected Result

* Class B exclusion expression should be evaluate

## Actual Result

* Class B exclusion expression is not evaluated

Look trough the flow I found out that the merge in the class hierarchy doesn't merge the value of the exclusion. Any exclusion of the top class in the hierarchy will have precedence.

Unless it's the expected behaviour it bake it really hard to have more define rules of class exclusion of child object.

**Comment by goetas** [comment]
I hope to have understood correctly the issue, but which class are you trying to serialize? A or B.
- If A, then the expected behavior is that the exclusion rule is ignored
- if B, then the rule should be considered

**Comment by goetas** [comment]
see https://github.com/schmittjoh/serializer/pull/1204

**Comment by mpoiriert** [comment]
Yes this is exactly what I meant. Thanks for the quick fix / release.

**Comment by mpoiriert** [comment]
Just installed it and now the problem is that class B always override even if no exclude if have been configured...

I presume it should be:
```
if($object->excludeIf) {
    $this->excludeIf = $object->excludeIf;
}

```

**Comment by goetas** [comment]
Can you please check https://github.com/schmittjoh/serializer/pull/1206 ?
