### ISSUE TITLE
Enable resolving collection type from the var doblock

### ISSUE THREAD

**Issue by dgafka** [schmittjoh/serializer#1208]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

Currently JMS Serializer can resolve type declaration from properties (PHP 7.4), yet can not resolve the type, when type is collection (array of specific classes).

The type however is available for us in most of the time in form of the docblock `@var`. 

## Steps required to reproduce the problem

Right now, in order to describe the collection we need to do it like this:

```php
	/**
	 * @JMS\Type("array<Application\Message>")
	 * @var Message[]
	 */
	private array $messages;
``` 
Unfortunately this solution has disadvantages. 
1) We duplicate the type in the form of the `@var `and as well `@JMS\Type`
2) IDE refactoring tools are not able to find and replace, when the class name is changed
3) We can resolve types from property declaration without any additional configuration, however not when it's collection. 

In PHP we are having convention to describe collections as `@var` docblock and mark it with suffix `[]`. 
This is respected by IDE, works with refactoring tools and is widely used in the community in order to describe the collection. 
What I would propose is to fallback to the docblock, when declared type is array. 

Previous code would looks like this:

```php
	/**
	 * @var Message[]
	 */
	private array $messages;
```

## Expected Result

Transforming Message[] into the form respected by JMS array<Application\Message>

## Actual Result

Require annotation in order to work

----

I have built such feature on top of JMS Serializer in integration with [my framework](https://docs.ecotone.tech/modules/jms-converter#example-usage). 
However I think such feature could be really nice addition build into JMS Serializer directly. 

I am willing to prepare implementation for that, if you will find it useful. :)

**Comment by goetas** [comment]
That sound a good idea. I'm curious on how is implemented. Is it something similar to what i did to detect php 7.4 types in https://github.com/schmittjoh/serializer/pull/1192 ?

**Comment by goetas** [comment]
Just saw https://github.com/ecotoneframework/jms-converter/blob/master/src/JMSConverter/ClassDefinitionDriver.php , nice job! :+1:
