### ISSUE TITLE
SerializerInterface::deserialize has incorrect psalm annotation

### ISSUE THREAD

**Issue by ostrolucky** [schmittjoh/serializer#1211]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

https://github.com/schmittjoh/serializer/blob/5b682e96def251472a0806455275c65521319e22/src/SerializerInterface.php#L26-L28 is incomplete, if nothing else. We use following code:
```php
public function deserializeSnapshot(string $json): array
    {
        return $this->serializer->deserialize($json, 'array', 'json');
    }
```

Annotation used on your interface causes following errors:
```
ERROR: InvalidReturnType - src/AppBundle/Snapshot/Common/Snapshotter.php:50:16 - The declared return type 'array<array-key, mixed>' for AppBundle\Snapshot\Common\Snapshotter::deserializeSnapshot is incorrect, got 'object' (see https://psalm.dev/011)
     * @return mixed[]


ERROR: InvalidReturnStatement - src/AppBundle/Snapshot/Common/Snapshotter.php:54:16 - The inferred type 'object' does not match the declared return type 'array<array-key, mixed>' for AppBundle\Snapshot\Common\Snapshotter::deserializeSnapshot (see https://psalm.dev/128)
        return $this->serializer->deserialize($json, 'array', 'json');


ERROR: ArgumentTypeCoercion - src/AppBundle/Snapshot/Common/Snapshotter.php:54:54 - Argument 2 of JMS\Serializer\Serializer::deserialize expects class-string, parent type string(array) provided (see https://psalm.dev/193)
        return $this->serializer->deserialize($json, 'array', 'json');


ERROR: UndefinedClass - src/AppBundle/Snapshot/Common/Snapshotter.php:54:54 - Class or interface array does not exist (see https://psalm.dev/019)
        return $this->serializer->deserialize($json, 'array', 'json');

```

**Comment by goetas** [comment]
Hi, thanks for the report. Do you know which annotation is the correct one?

**Comment by ostrolucky** [comment]
I don't, unfortunately

**Comment by ostrolucky** [comment]
So, something like this https://psalm.dev/r/84eb3d264b (You should know better what other types can go there and should be able to extend this further)

**Comment by EvgeniiR** [comment]
Just to clarify, with code example above, there'll still be problem with `array<class-string>`, e.g. `array<App\Foo>`

**Comment by goetas** [comment]
https://github.com/goetas/jms-serializer-phpstan-extension should fix it once for all

I plan to release the 1.x in the next few days
