### ISSUE TITLE
Deserialization failed when condition in Expose/Exclude

### ISSUE THREAD

**Issue by michalbundyra** [schmittjoh/serializer#1217]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

## Steps required to reproduce the problem

I have created simple skeleton application to demonstrate the issue:
https://github.com/michalbundyra/symfony-jms-deserializer

Basically I am getting error:
`Unable to call method of a non-object. (500 Internal Server Error)`

on POST when I have set some condition in Expose/Exclude annotations.

## Expected Result

* deserialization works without errors

## Actual Result

* getting error: `Unable to call method of a non-object. (500 Internal Server Error)`

Maybe I am missing something and it is just configuration issue... Thanks!

**Comment by goetas** [comment]
This is not a bug. When deserializing the `object` is not available (as the object still has to be built).

There have been proposals in  the past on how to make it available, but no results so far.

**Comment by michalbundyra** [comment]
@goetas thanks for your answer and explanation. Is it anywhere described in the documentation? I couldn't find it. If so, would you be able to provide a link for future reference? Thanks!

**Comment by goetas** [comment]
> Is it anywhere described in the documentation?

no, it would be great if you can send a pull request mentioning that.

>If so, would you be able to provide a link for future reference? Thanks!
In  question https://github.com/schmittjoh/serializer/pull/1099#issuecomment-611535822 and in this answer https://github.com/schmittjoh/serializer/pull/1099#issuecomment-612663048 I have mentioned t'm currently using
