### ISSUE TITLE
Serialize XML without xml version, encoding part

### ISSUE THREAD

**Issue by zek** [schmittjoh/serializer#1220]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

Is it possible to remove `<?xml version="1.0" encoding="UTF-8"?>` when serializing XML?

## Expected Result

```xml
  <variables>
    <variable name="key1" value="value1" />
    <variable name="key2" value="value2" />
  </variables>
```

## Actual Result

```xml
<?xml version="1.0" encoding="UTF-8"?>
  <variables>
    <variable name="key1" value="value1" />
    <variable name="key2" value="value2" />
  </variables>
```

I was able to do it via overriding `XmlSerializationVisitor` as following. I think it's good to have this feature as an option.

```php
    public function getResult()
    {
        return $this->document->saveXML($this->document->documentElement);
    }
```

**Comment by goetas** [comment]
Maybe adding some option to https://github.com/schmittjoh/serializer/blob/master/src/Visitor/Factory/XmlSerializationVisitorFactory.php ?
