### ISSUE TITLE
xml:id or xml:lang attributes handling

### ISSUE THREAD

**Issue by amaccis** [schmittjoh/serializer#1221]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | IDK
| BC Break report? | no
| RFC?             | no

Hi.
I don't know if JMS already has the feature I'm looking for, and stackoverflow too (e.g. https://stackoverflow.com/questions/24389574/jms-serializer-to-read-xmllang-attribute) does not answer.
I mean, is there a way to handle xml:id or xml:lang attributes? I can't use XmlNamespace with attributes so I can't find the proper way to solve my problem.
Thanks!
A.

**Comment by goetas** [comment]
I think that here should be used `\JMS\Serializer\Annotation\XmlMap`, but the ability to define a custom namespace is not yet defined. 

It would be a nice feature to have... are you interested in working on it?

**Comment by amaccis** [comment]
Hi @goetas. I'll take a look.

**Comment by amaccis** [comment]
Hi @goetas, I was taking a look to the code, in order to add the feature I need, and I realized that actually JMS already handles namespaces for attributes too. So I've probably put it badly when I asked for.
I solved it easily.

I had a tag like that
`<tag xml:lang="lang">data</tag>`

and I only needed to
```
/**
 * @XmlNamespace(uri="http://www.w3.org/XML/1998/namespace", prefix="xml")
 */
class Tag
{
    /**
     * @var string
     * @Type("string")
     * @XmlAttribute(namespace="http://www.w3.org/XML/1998/namespace")
     * @SerializedName("lang")
     */
    private string $lang;
```
