### ISSUE TITLE
How to pass MetadataFactory::create() into SerializationVisitorInterface::startVisitingObject()?

### ISSUE THREAD

**Issue by simPod** [schmittjoh/serializer#1226]
I'm creating metadata for class through `$classMetadata = $context->getMetadataFactory()->getMetadataForClass(My::class);`

```php
interface MetadataFactoryInterface
{
    /**
     * @return ClassHierarchyMetadata|MergeableClassMetadata|null
     */
    public function getMetadataForClass(string $className);
```

So the return type is `ClassHierarchyMetadata|MergeableClassMetadata|null`

Though `SerializationVisitorInterface::startVisitingObject()` expects `ClassMetadata` which is not contravariant to what `MetadataFactoryInterface::getMetadataForClass()` returns.

```php
interface SerializationVisitorInterface extends VisitorInterface
{
    public function startVisitingObject(ClassMetadata $metadata, object $data, array $type): void;
```

How to properly create those metadata and pass them then?

**Comment by goetas** [comment]
hmmm... did not get it. :-(

can you explain your goal rather than the technical consequence of it?

**Comment by simPod** [comment]
I'm trying to create class metadata so I can pass them to the visitor.

For that I'm using metadata factory. But it does not return compatible type to be passed into `SerializationVisitorInterface:: startVisitingObject()` (even though it technically works, the typing is not correct).

I need to pass `JMS\Serializer\Metadata\ClassMetadata` there but from factory I'm getting `ClassHierarchyMetadata|MergeableClassMetadata`

Currently what I'm doing is that I have to assert the type to be safe, because I'm not guaranteed by the MetadataFactory I'll receive ` JMS\Serializer\Metadata\ClassMetadata` instance

```php
$classMetadata = $context->getMetadataFactory()->getMetadataForClass(My::class);
Assert::isInstanceOf($classMetadata, \JMS\Serializer\Metadata\ClassMetadata::class);

$visitor->startVisitingObject($classMetadata, $entity, ['name' => get_class($entity)], $context);
```

So I'm looking for a proper way to get something like

```php
interface MetadataFactoryInterface
{
    public function getMetadataForClass(string $className) : ?\JMS\Serializer\Metadata\ClassMetadata;
```

That said to receive ClassMetadata instance that I can safely pass into a visitor. Passing `ClassHierarchyMetadata|MergeableClassMetadata` does not seem to be type safe.

**Comment by goetas** [comment]
`$classMetadata = $context->getMetadataFactory()->getMetadataForClass(My::class);` should "almost always"  return some metadata (despite its signature), so if you get NULL, something is wrong with your configs... 
did you disable the annotation metadata reader?

**Comment by simPod** [comment]
The null is not issue. The issue is that it returns `ClassHierarchyMetadata|MergeableClassMetadata` metadata types while visitor requires `\JMS\Serializer\Metadata\ClassMetadata` which is not contra variant.

**Comment by goetas** [comment]
did you customize `MetadataFactor`  ? by providing your own implementation?

**Comment by simPod** [comment]
Yes, it gives correct type actually. When executed, it returns `\JMS\Serializer\Metadata\ClassMetadata`. There's no issue with running the code. This is about API.

I'd like to rely on the interfaces and these two are incompatible:

```php
interface MetadataFactoryInterface::getMetadataForClass(...) : ClassHierarchyMetadata|MergeableClassMetadata|null;
SerializationVisitorInterface:: startVisitingObject(\JMS\Serializer\Metadata\ClassMetadata, ...);
```

so it works but it's not correct in terms of interface type compatibility. I cannot pass return type `ClassHierarchyMetadata|MergeableClassMetadata` where `\JMS\Serializer\Metadata\ClassMetadata` is expected. It's not covariant.

**Comment by goetas** [comment]
well, I'm aware that this library is not fully type safe. Adding phpstan/psalm is a lot of work (and making it type-safe would require BC breaks for sure).

Is one day someone will be interested to work on adding static analysis, that would be nice!

**Comment by simPod** [comment]
Ah ok, I was wondering whether I'm doing something wrong or not. Thanks!
