### ISSUE TITLE
Problem with deserialize related entity

### ISSUE THREAD

**Issue by ricfrank** [schmittjoh/serializer#123]
Hi.

I'm developing an api for entity creation. This entity called "Customer" is related with other entity called "Cdc". The relationship is ManyToOne   Customer (N) -> Cdc (1).

Client send me a json to create Customer, like: 

{"name": "Mario", "surname": "MariaMario", ….. , "cdc": "2"}

where cdc is the id of cdc entity.

When i deserialize this json, serializer covert cdc in a empty Cdc istance and not in right Cdc istance.

How can i obtain the right entity ?? I try to build an handler, but seems ignore when i deserialize.

Maybe, the righe question is: Can i  obtain the right entity ??

Thanks

**Comment by goetas** [comment]
> Maybe i solve.
