### ISSUE TITLE
Configure whether serializing empty array.

### ISSUE THREAD

**Issue by Tobion** [schmittjoh/serializer#124]
The serializer currently allows to configure whether to [serialize null values](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Context.php#L184). 
I think one more option is necessary: to configure whether to serialize empty arrays/strings. Otherwise it's a little incosistent that null values are not serialized but empty arrays are which is currently the case. But both basically mean the same: there is no information available.

So I'd suggest to add a method `setSerializeEmpty` which when passed false, will not serialize empty arrays (`array()`) and empty strings (`''`). So it does not have to do with the php `empty()` function because we want to serialize `0` and `false`.

**Comment by goetas** [comment]
Currently works for the XML visitor https://github.com/schmittjoh/serializer/blob/bb51b6396ae4512f09a36f1ca27155fef21b3aca/src/JMS/Serializer/Annotation/XmlCollection.php#L41

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/issues/757
