### ISSUE TITLE
@SkipWhenEmpty and @Exclude combination leads to unexpected behavior

### ISSUE THREAD

**Issue by narcoticfresh** [schmittjoh/serializer#1240]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

## Steps required to reproduce the problem

1. Create `ClassA` that has 1 property `array<ClassASub>` and has `@SkipWhenEmpty` annotation
2. Create `ClassASub` that has 1 property that has `@Exclude` annotation
3. Create a `Serializer` with `serializeNull(false)`

I created a demonstration of this bug in the branch here -> https://github.com/narcoticfresh/serializer2-problem-testcase/tree/feature/empty-array-object

You can `composer install && php test.php` to execute the demonstration.

The entity classes are in the `Entity` directory - classes are `ClassA` (main class) and `ClassASub` (class for array subproperty)

## Simple view

You basically end up with the structure
``` 
object(TestCase\Entities\ClassA)#36 (1) {
  ["members":"TestCase\Entities\ClassA":private]=>
  array(2) {
    [0]=>
    object(TestCase\Entities\ClassASub)#3 (1) {
      ["name":"TestCase\Entities\ClassASub":private]=>
      string(7) "member1"
    }
    [1]=>
    object(TestCase\Entities\ClassASub)#16 (1) {
      ["name":"TestCase\Entities\ClassASub":private]=>
      string(7) "member2"
    }
  }
}
```

Where `ClassASub` only has attribute `name` (which is excluded via `@Exclude`) - and `ClassA` only has `members` property which has `@SkipWhenEmpty`

## A note

So I realize this is a sort of "edge scenario" that should not actually happen - and it looks "impossible/doesn't make sense" to even happen like I did it in the demonstration repo.

But this is a distilled down version of what happens in our scenario over at https://github.com/libgraviton/graviton/ - where we serialize an "empty" MongoDB embedded object that only has an "_id" property - but which should not be serialized in embedded case.

## Expected Result
* With this constellation, the final serialized string IMHO should just be `null` (as `null` type) if it happens somewhere in the object graph - if this happens at the root of the object graph, the final output should be `{}` in order to return valid JSON.

## Actual Result

* The above constellation will serialize to `{"members":[{},{}]}` - which contradicts `@SkipWhenEmpty` on `members`.

## BC Break?
I said yes to BC break because this will serialize differently in Serializer 1.*; where it will serialize as `{"members":[]}`

**Comment by goetas** [comment]
> Create ClassA that has 1 property array<ClassASub> and has @SkipWhenEmpty annotation

`SkipWhenEmpty` checks only if the array is empty, it does not check the content of it. if you want to exclude `ClassASub` instances with some particular data, you should use the exclusion strategies.

SkipWhenEmpty is meant to avoid this situation:


`private $members = array();` if you serialize this with a normal config, it will be `[]`, but with `SkipWhenEmpty` the property will not be present at all in the json.
 


>I said yes to BC break because this will serialize differently in Serializer 1.*; where it will serialize as {"members":[]}

currently jms/serializer is at version 3.x, so it is normal to have bc breaks from 1.x to 3.x
