### ISSUE TITLE
Nullable properties are not initialized on deserialization

### ISSUE THREAD

**Issue by simPod** [schmittjoh/serializer#1252]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             |no

## Steps required to reproduce the problem

1. Serialize this

```php
<?php

declare(strict_types=1);

final class A
{
    public string $a;

    public ?string $b;

    public function __construct(string $a, ?string $b)
    {
        $this->a = $a;
        $this->b = $b;
    }
}

serialize(new A("1",null));
```

2. The json is `{"a": "1"}`
3. Deserialize it
4. Access `$a->b`

## Expected Result

No error, `$a->b` gives null

## Actual Result

> Typed property A::$b must not be accessed before initialization

**Comment by goetas** [comment]
Hi. I think that you should use the `$context->serializeNulls()` feature in that case. Did you try it?

**Comment by simPod** [comment]
Hm, should work, will try.

BTW shouldn't it be default on PHP 7.4+?

**Comment by goetas** [comment]
I was thinking to solve it with https://github.com/schmittjoh/serializer/pull/1081 but never had time to continue the work on it.

**Comment by simPod** [comment]
Let's continue there
