### ISSUE TITLE
DocBlockDriver unable to parse single-line DocBlocks

### ISSUE THREAD

**Issue by Namoshek** [schmittjoh/serializer#1259]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Use the new `$builder->setDocBlockTypeResolver(true)` feature from #1214.

2. Define single-line DocBlocks to save some space:
    ```php
    class Foo
    {
        /** @var Bar[] */
        public array $x;

        /** @var \Some\Namespace\Bar[] */
        public array $y;
     }
    ```

## Expected Result

Parses successfully.

## Actual Result

Throws exception(s):

**Case `Bar[]`:**
> InvalidArgumentException: Can't use incorrect type Bar[] */ for collection in Some\Namespace\Foo:x

**Case `\Some\Namespace\Bar[]`:**
> JMS\Serializer\Type\Exception\SyntaxError: Syntax error, unexpected "*/" (T_UNKNOWN), expected was T_COMMA

## Additional Information

The same code with multi-line DocBlocks parses and de-/serializes successfully:
```php
class Foo
{
    /**
     * @var Bar[]
     */
    public array $x;

    /**
     * @var \Some\Namespace\Bar[]
     */
    public array $y;
}
```

Interestingly enough, using the `array<Class>` syntax also works with single-line DocBlocks:
```php
class Foo
{
    /** @var array<Bar> */
    public array $x;

    /** @var array<\Some\Namespace\Bar> */
    public array $y;
}
```

**Comment by Namoshek** [comment]
Thank you for this cool addition by the way! Combining this with attributes and named parameters from PHP 8 will be my absolute favorite way to go in future. My vision would be something like this (some random modifier ideas thrown into the mix as well 😄):
```php
class Foo
{
    /** @var Bar[] */
    #[Serializer\Property(
        name: 'theBars',
        nullIfEmpty: true,              // for deserialization of strings and arrays
        nullIfWhitespace: true,         // for deserialization of strings
        ignoreIfNull: true,             // for serialization
        ignoreIfEmpty: true,            // for serialization of strings and arrays
        ignoreIfWhitespace: true,       // for serialization of strings
        ignoreIfNullOrWhitespace: true, // for serialization of strings
    )]
    public ?array $bars;
}
```
_Note: not all added parameters make sense with an array of objects... it's just to illustrate._

**Comment by Namoshek** [comment]
I had a look at [the regex](https://github.com/schmittjoh/serializer/blob/0ed0b6aa79cc029772286f2dc262f6933674b0ec/src/Metadata/Driver/DocBlockTypeResolver.php#L10) which is used to retrieve the type from the DocBlock. The regex is currently `#@var[\s]*([^\n\$]*)#`. I think by changing it to `#@var[\s]*([^\n\$\*\/]*)#` (`\*\/` added to the exclude clause), the problem should be resolved. As far as I know, neither `/` nor `*` may appear after `@var`, so this should be fine. If anyone can confirm this, I'm happy to provide a PR for it.

**Comment by goetas** [comment]
IMO the best thing to do here is to use https://github.com/phpstan/phpdoc-parser to parse the docblock. Is anyone willing ro provide a PR for it?

**Comment by Namoshek** [comment]
Sure, I can give it a shot. Some questions in advance though:

1. Is it ok to add a constructor to the `DocBlockTypeResolver` (to instantiate the `PhpDocParser`)? Currently, it has none, which makes it theoretically a breaking change if someone extended the resolver and added their own constructor...

2. Which syntaxes are supposed to be allowed for this feature anyway?
    In my opinion, the following _SHOULD_ be supported (using single-line for brevity, of course multi-line should work as well):
    ```php
    /** @var string[] */
    public array $strings;

    /** @var string[]|null */
    public ?array $strings;

    /** @var Product[] */
    public array $products;

    /** @var array<Product> */
    public array $products;

    /** @var Product[]|null */
    public ?array $products;

    /** @var array<Product>|null */
    public ?array $products;

    /** @var array<int,Product>|null */
    public ?array $products;

    /** @var array<string,Product>|null */
    public ?array $products;
    ```

    These variants _CANNOT_ be supported (at least I have no idea how it would be possible):
    ```php
    /**
     * @var array<Foo,Bar>
     */
    public array $bars;

    /**
     * @var array<Foo,Bar>|null
     */
    public ?array $bars;
    ```
    Although they might be handled correctly by the resolver, just not by the de-/serializer itself.

**Comment by Namoshek** [comment]
Cleaning up my issues and realized this never has been closed even though it has been fixed. 👍
