### ISSUE TITLE
DateHandler stops working when registering custom subscribing handler

### ISSUE THREAD

**Issue by Holicz** [schmittjoh/serializer#1262]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Working scenario

1. Create Serializer instance like this
```php
\JMS\Serializer\SerializerBuilder::create()->build();
```
2. Deserialize some object which has DateTime field
3. It's working

## Steps required to reproduce the problem (not working scenario)

1. Create Serializer instance like this (with custom subscribing handler)
```php
\JMS\Serializer\SerializerBuilder::create()
    ->configureHandlers(static function(HandlerRegistry $registry) {
        $registry->registerSubscribingHandler(new EnumHandler());
    })
    ->build()
;
```
2. Deserialize some object which has DateTime field

## Expected Result
DateTime fields are correctly deserialized.

## Actual Result
DateTime fields are **not** deserialized. DateHandler has to be configured manually. This works:

```php
\JMS\Serializer\SerializerBuilder::create()
    ->configureHandlers(static function(HandlerRegistry $registry) {
        $registry->registerSubscribingHandler(new EnumHandler());
        $registry->registerSubscribingHandler(new \JMS\Serializer\Handler\DateHandler(\DateTime::ATOM, 'UTC'));
    })
    ->build()
;
```

I would expect the default handlers configuration is not overrided by some other custom handlers. Or at least a warning in [the docs here](https://jmsyst.com/libs/serializer/master/handlers#subscribing-handlers).

**Comment by goetas** [comment]
You should call 

```php

$builder = \JMS\Serializer\SerializerBuilder::create();

$builder->configureHandlers(static function(HandlerRegistry $registry) use($builder){
        $registry->registerSubscribingHandler(new EnumHandler());
        $builder->addDefaultHandlers();
})
->build()
```
