### ISSUE TITLE
Make jms/serializer installable on PHP 8

### ISSUE THREAD

**Issue by sgehrig** [schmittjoh/serializer#1270]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes (sort of)
| BC Break report? | no
| RFC?             | no

As PHP 8 has just been released, it'd be nice to update the PHP version constraint of `jms/serializer` to allow for installation on PHP 8 (such as `>=7.2` e.g.). Or are there any known problems with running `jms/serializer` on PHP 8?

## Steps required to reproduce the problem

Try to require `jms/serializer ^3.10` with PHP 8.

## Expected Result

* `jms/serializer` is installed

## Actual Result

```
Problem 1
    - Installation request for jms/serializer ^3.10 -> satisfiable by jms/serializer[3.10.0].
    - jms/serializer 3.10.0 requires php ^7.2 -> your PHP version (8.0.0RC5) does not satisfy that requirement.
```

**Comment by goetas** [comment]
There is some WIP in https://github.com/schmittjoh/serializer/pull/1267

**Comment by sanmai** [comment]
I belive #1267 is ready to go.

**Comment by sanmai** [comment]
For the record, here's how can one can get things working on PHP 8, for time being:
```bash
sed -i 's/count.*nodes/count($nodes??[]/' vendor/jms/serializer/src/XmlDeserializationVisitor.php
sed -i s/libxml_disable_entity_loader/@libxml_disable_entity_loader/g vendor/jms/serializer/src/XmlDeserializationVisitor.php
```
The same commands [inside a workflow](https://github.com/sanmai/cdek-sdk/blob/25d5e4c66507150b199efc0b27fad7aa91377673/.github/workflows/ci.yaml#L59-L60).
