### ISSUE TITLE
Filtering an array collection during the deserialization

### ISSUE THREAD

**Issue by VincentLanglet** [schmittjoh/serializer#1271]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no

When serializing the following xml:
```
<xml>
   <client>
      <contract date="01/01/2020"/>
      <contract date="01/01/2019"/>
      <contract date="01/01/2018"/>
      <contract date="01/01/2017"/>
      <contract date="01/01/2016"/>
      <contract date="01/01/2015"/>
      <contract date="01/01/2014"/>
   </client>
</xml>
```
I use an entity Client, with a field contract witch is an ArrayCollection of another entity Contract.
Is there an annotation to exclude, during the serialization, all the contracts older than, for instance, 2 years ?

It would avoid to do the filtering latter. This would save me lot of ressource, since it's a small example but in my real example I have a lot of contract with a lot of others data.

I saw some documentation about some Exclude strategy,
```
@Exclude(if="someMethod(object, context, property_metadata)")
```
but I didn't understand if something was usable in this case.

Should a `@Filter` be added to this library and I would use it on the contract field of the Entity Client ; or should I add something to the Contract entity ?

**Comment by VincentLanglet** [comment]
Friendly ping @goetas

Does this exists or a PR has to be made ?

**Comment by goetas** [comment]
sorry for the delay, this feature does not exists and personally do not plan to implement it as it should be quite trivial to implement in userland code

**Comment by VincentLanglet** [comment]
Yes indeed, I solved it myself. :)
