### ISSUE TITLE
ReflectionUnionType is not supported

### ISSUE THREAD

**Issue by yyaremenko** [schmittjoh/serializer#1282]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes (?)
| BC Break report? | no (?)
| RFC?             | no

## Steps required to reproduce the problem

1. Create a class with PHP v8 union type, e.g. 

```
class A {
    public function __construct(
        private object|array $someVal;
    ) {}
}
```

2. Create an instance of such class.
3. Try to serialize the instance (e.g. to json).

## Expected Result

The object is serialized

## Actual Result

```
App\Tests\Functional\Api\App\User\UserCreateTest::testSuccess
Error: Call to undefined method ReflectionUnionType::getName()

/var/www/vendor/jms/serializer/src/Metadata/Driver/TypedPropertiesDriver.php:111
```

the code at line 111 looks as follows:

```
        if (in_array($propertyReflection->getType()->getName(), $this->whiteList, true)) {
            return true;
        }
```

since 
```
$propertyReflection->getType()
```

returns 
[ReflectionUnionType](https://www.php.net/manual/en/class.reflectionuniontype.php)

which does not have **getType()** method, but has **getTypes()** method (as this is a union type, so it has more than 1 type),

the code fails with the above error.

**Comment by alshenetsky** [comment]
I am leaving this comment just to gain more attention to this bug which I also experiencing.

**Comment by deoomen** [comment]
Bump. Still occurring.

**Comment by Ravetracer** [comment]
Will this be considered somehow? Half of our testing suite is failing because of this bug. The mentioned patch of @dgafka is working nicely.

**Comment by goetas** [comment]
done in https://github.com/schmittjoh/serializer/pull/1330
