### ISSUE TITLE
DoctrineObjectConstructor fails loading entity when deserializing XML

### ISSUE THREAD

**Issue by jviersel-ipronto** [schmittjoh/serializer#1286]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When you deserialize XML, the DoctrineObjectConstructor does not retrieve the values in the correct way, causing all values to be NULL, so loading the Doctrine entity fails.

In version 3.11.0 on line 110 of DoctrineObjectConstructor is says:
`$identifierList[$name] = $data[$propertyMetadata->serializedName];`

But when deserializing XML, $data is not an array; its a SimpleXMLElement. In this case, the value should be retrieved like
`$identifierList[$name] = (string)$data->{$propertyMetadata->serializedName}`

## Suggested fix
```
if ($data instanceof \SimpleXMLElement) {
    $identifierList[$name] = (string)$data->{$propertyMetadata->serializedName};
} else {
    $identifierList[$name] = $data[$propertyMetadata->serializedName];
}
```

## Steps required to reproduce the problem

1. Configure your project to use the DoctrineObjectConstructor
2. Deserialize some XML containing the id into a Doctrine entity
3. you get an exception because the identifier is missing

## Expected Result

* Loaded Doctrine entity by specified id

## Actual Result

* An exception, because the identifier is missing

**Comment by goetas** [comment]
Hmm, that makes sense. Can you create a pull request with a suggested fix (and a test possibly..)?

**Comment by jviersel-ipronto** [comment]
Yes, I can submit a merge request. But now I re-think this solution: is this the right way to solve the problem? Shouldn't $data always be an array (maybe even forced to be an array in the function definition)? Isn't the actual bug in the parser that should return an array instead of an SimpleXmlElement?

**Comment by goetas** [comment]
fixed by https://github.com/schmittjoh/serializer/pull/1289
