### ISSUE TITLE
Allow Post Serialize Event to overwrite existing data

### ISSUE THREAD

**Issue by Richtermeister** [schmittjoh/serializer#129]
The GenericSerializationVisitor throws an exception when trying to add a data field that already exists. This makes it impossible to change existing data for serialization purposes.

My use-case is that my entities store relative file URLs, and during serialization I would like to prepend them with the current host name.

My current workaround is to use the PreSerialize event to temporarily update the field on the entity, but that seems hackish and has limits.

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/pull/273 merged

**Comment by Richtermeister** [comment]
Yaaay! Thanks. @goetas , you rock, it's great that you're running with this project!
