### ISSUE TITLE
3.12.0 BC break on json column

### ISSUE THREAD

**Issue by TakTaki** [schmittjoh/serializer#1298]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | yes
| RFC?             |no

Since 3.12.0, the serialization of json changed, introducing what I think is a BC break.
I have a Doctrine column define as follow
`@ORM\Column(name="value", type="json", options={"jsonb"=true}, nullable=true)`
Before 3.12.0, when the value stored was equals to `true`, the serialized value was `true`.
In 3.12.0 it now returns `{true}`.

I think this is link to recent changes [here](https://github.com/schmittjoh/serializer/pull/1281/files#diff-62ee052086cb317b744555b39766e1abc844816a9f14aff3f82524e9cf41dbf5R59). I commented this line and got what I expected, ie `true`

## Steps required to reproduce the problem

1. `@ORM\Column(name="value", type="json", options={"jsonb"=true}, nullable=true)`

## Expected Result

* `true`

## Actual Result

* `{true}`

**Comment by TakTaki** [comment]
Just saw that I'm not alone and a PR is already pending https://github.com/schmittjoh/serializer/pull/1295

**Comment by goetas** [comment]
Done in https://github.com/schmittjoh/serializer/pull/1295
