### ISSUE TITLE
Excluding an item in an array results in a Json object instead of an array

### ISSUE THREAD

**Issue by arneee** [schmittjoh/serializer#1300]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no

Assume the following code:

```php
class MyItem {
    public string $color;

    public function __construct($color) {
        $this->color = $color;
    }
}

$items = [new MyItem("red"), new MyItem("green"), new MyItem("blue")];

$string = $serializer->serialize($items,'json');

echo $string;

```
The result is a javascript object with the three items:
```javascript
[ { "color": "red" }, { "color": "green" }, { "color": "blue" } ]
```

Now add an ExcludeIf to the MyItem class:
```php
/**
 * @JMS\Exclude(if="object.color == 'green'")
 */
class MyItem {
    public string $color;

    public function __construct($color) {
        $this->color = $color;
    }
}
```
The result is now a javascript object:
```javascript
{ "0": { "color": "red" }, "2": { "color": "blue" } }
```

This is an issue if you use the result in javascript, since there is for example no forEach() anymore on an object type.

The issue seems to be, that in visitArray of JsonSerializationVisitor the result array is constructed including the keys. While this is important for associate arrays, in our case it leads to a "missing" key in the array, which leads to json_encode returning an object.

A workaround is to explicitly provide the $type to serialize(), but it would be nice to have that behaviour automatically. 
```
$string = $this->serializer->serialize($items,'json',null,'array<MyItem>');
```
Unfortunately it seems like there is no easy way to know if the provided array is a "regular" array or an associate array, [since all arrays in PHP are associative arrays.](https://stackoverflow.com/questions/173400/how-to-check-if-php-array-is-associative-or-sequential) .

What do you think?

**Comment by goetas** [comment]
adding `array<MyItem>` is what needs to be done. any other way will lead to issues. what f i want to have it an object and not an array?

The current serializer behavior is consistent:

- `$this->serializer->serialize($items,'json',null,'array<MyItem>');` is always serialized as `[...]`
- `$this->serializer->serialize($items,'json',null,'array<string,MyItem>');` is always serialized as `{...}`
- `$this->serializer->serialize($items,'json');` is always serialized in an inconsistent way and can be `[...]` or `{...}` depending on the internal structure of `$items`
