### ISSUE TITLE
DocBlockTypeResolver throws InvalidArgumentException with mixed and union type annotation

### ISSUE THREAD

**Issue by gam6itko** [schmittjoh/serializer#1302]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

As I said in #1295, I have `json` type field `$value`. It marked as `mixed` type in annotation. 

```php
class MegaClass 
{
    /**
     * @var mixed
     */
    private $value;
}
```

With 3.12.1 executing of `cache:warmup` throws `Can't use incorrect type mixed for collection in MegaClass:value`

If I change the annotation to union type it will throws another exception `Can't use union type array|int|bool|null for collection in MegaClass:value`

```php
class MegaClass 
{
    /**
     * @var array|int|bool|null
     */
    private $value;
}
```

I believe @dgafka can fix it

**Comment by goetas** [comment]
done in https://github.com/schmittjoh/serializer/pull/1330

**Comment by fvozar** [comment]
Hi @goetas, is there any date planned for the bug fix release?
