### ISSUE TITLE
PHP Unit test show "Unsilenced deprecation notices"

### ISSUE THREAD

**Issue by Axent96** [schmittjoh/serializer#1309]
https://github.com/schmittjoh/serializer/blob/ea54838a0acd960839b7401bfd83fcd6ebe34aed/src/SerializationContext.php#L158

PHP Unit test:
1x: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`

**Comment by goetas** [comment]
You are reporting a bug in an unsupported branch. 3.x is the only supported branch (and there the bug has been solved).
