### ISSUE TITLE
@XmlRoot annotation no longer working

### ISSUE THREAD

**Issue by chadl** [schmittjoh/serializer#131]
@schmittjoh ::: I have a similar problem to the one reported over here(https://github.com/schmittjoh/JMSSerializerBundle/issues/262), but _this problem only arose once I upgraded my symfony_ from 2.0.9 (I know, we were lagging behind) to a slightly newer 2.0.23.

I had some simple serializer tests, like this:

``` php
use JMS\Serializer\Annotation\XmlRoot;

/**
 * @XmlRoot("root")
 */
class Foo {
   protected $name ="Chad";
}

$serializer = SerializerBuilder::create()->build();
$xml = $serializer->serialize(new Foo(), 'xml');
```

The resulting XML looks like this:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<result>
  <name><![CDATA[Chad]]></name>
</result>
```

Prior to the 2.0.23 upgrade, this code would produce:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <name><![CDATA[Chad]]></name>
</root>
```

Interested to hear your thoughts on this one, and perhaps you've seen this behaviour before and can point me to what may be wrong here?

Thanks!

**Comment by emottet** [comment]
Hi, 
  I have a similar problem with symfony 2.6, where I implement web services using FOSRESTBundle and JMSSerializerBundle.
  I don't know if i'm doing things the right way but here is what i've done.

  I have a config\serializer\Entity.Request.yml file with the following information :

Tvjp\RequestBundle\Entity\Request:
  exclusion_policy: ALL
  xml_root_name: request
  properties:
    id:
      expose: true
      type: integer
    label:
      expose: true
      type: string
    issuer:
      expose: true
      type: string

    When i try to access to a single request, this is what i got:
      - in json : {"id":23,"label":"test label ws post","issuer":"test issuer ws post"}
      - in XML :
<result>
  <id>23</id>
  <label>
     <![CDATA[ test label ws post ]]>
  </label>
  <issuer>
     <![CDATA[ test issuer ws post ]]>
  </issuer>
</result>

I can't manage to have a root element name to "request" eventhough i put   "xml_root_name: request" in the configuration file.
Am I doing something wrond here ?
