### ISSUE TITLE
PHP 8 compatibility for 1.x branch

### ISSUE THREAD

**Issue by gnutix** [schmittjoh/serializer#1319]
Hello there,

I just noticed that the latest tag on the 1.x branch fixes deprecations on PHP 7.4 a year ago (not that old) and am therefore wondering if there is a plan to keep maintaining the compatibility with recent PHP versions for this branch ? Or if it is really EOL and unmaintained ?

I'm currently upgrading a project heavily using the 1.x branch to PHP 8 and am not sure I will be able to migrate to 3.x that easily...
Thanks for your insights.

**Comment by gnutix** [comment]
For anyone interested, I started working on a fork : https://github.com/gnutix/jms-serializer-1.x

**Comment by goetas** [comment]
Thanks for sharing your project.

The 1.x and 2.x branches are not maintained anymore. I suggest you to upgrade your application to befit of the recent updates (symfony profiler and php 8 attributes support)
