### ISSUE TITLE
Change \JMS\Serializer\Handler\SubscribingHandlerInterface::getSubscribingMethods definition to instance method

### ISSUE THREAD

**Issue by grobacz** [schmittjoh/serializer#1322]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Hi, I'd like to request change to `\JMS\Serializer\Handler\SubscribingHandlerInterface`.
I don't see why the method `getSubscribingMethods` is static as the method is used on object instance.
Could it be changed to an instance method? This way service configuration could configure the behavior of a handler implementing this interface.
Of course it would be a BC to change the declaration directly, so it cannot be done in current major version

**Comment by goetas** [comment]
The `getSubscribingMethods` method is static because is called at compile time, this can not provide handlers that depend on runtime object values. Most of symfony subscribers use static methods.

**Comment by proggeler** [comment]
@goetas Can you show me the compile time usages? As I can see Handlers are always initiated before the `getSubscribingMethods` is called. (`getSubscribingMethods` is only called within the `HandlerRegistry::registerSubscribingHandler`)

If this is changed, I will make it possible to create handlers that can be reused for custom (de)serilialization formats (other than xml or json) without relying on extend or copy-paste the code. 

```
// example
final class StdClassHandler implements \JMS\Serializer\Handler\SubscribingHandlerInterface
{
    public function __construct(
        private $formats = ['json', 'xml', 'yml']
    ) {}

    public function getSubscribingMethods()
    {
        $methods = [];
        foreach ($this->formats as $format) {
             // .....
        }
    }
}
```

Same thing is true for the `getSubscribedEvents` in `EventDispatcher::addSubscriber`. 

I think both methods could be instance methods, which improves the usability of the code.
