### ISSUE TITLE
Doctrine cache deprecations / retiring Cache implementations

### ISSUE THREAD

**Issue by andrei-dascalu** [schmittjoh/serializer#1324]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

## Steps required to reproduce the problem

1.  Setup JMS serializer as per documentation
2.  Update dependencies via composer 

## Expected Result

* use serializer

## Actual Result

* `Class 'Doctrine\Common\Cache\FilesystemCache' not found`

This is due to the fact that even though JMS Serializer builder manually instantiates Doctrine Cache adapter Filesystem

```php
    public function build(): Serializer
    {
        $annotationReader = $this->annotationReader;
        if (null === $annotationReader) {
            $annotationReader = new AnnotationReader();

            if (null !== $this->cacheDir) {
                $this->createDir($this->cacheDir . '/annotations');

                var_dump($this->cacheDir);
                $annotationsCache = new FilesystemCache($this->cacheDir . '/annotations');
                $annotationReader = new CachedReader($annotationReader, $annotationsCache, $this->debug);
            }
        }
...
}
```

it doesn't specifically setup a dependency in the composer json to tie it to a doctrine/cache version

As per latest doctrine/cache 2.0, not only it's been announced that the project will retire but they've also removed all implementations of cache (including FilesystemCache) in favour of an Adapter that's supposed to provide a bridge to PSR-6 implementations. 

I'm not sure what would be the best way forward here, though perhaps suggesting the creation of a `Doctrine\Common\Annotations\PsrCachedReader` or either locking doctrine/cache to a compatible version might help.

**Comment by goetas** [comment]
fixed by https://github.com/schmittjoh/serializer/pull/1328
