### ISSUE TITLE
FR: SerDe of iterables with object-like keys is not supported

### ISSUE THREAD

**Issue by simPod** [schmittjoh/serializer#1326]
Iterables are currently converted into an `array<K of array-key, V>` for serialization so only `array-key` type is supported.

I propose to convert iterables into a `list<array{key: K, value: V}>` in order to allow serde.

I'm willing to implement the change. Though it will cause a BC break for current serialized structures and I don't know how to handle that.

WDYT?

**Comment by goetas** [comment]
I think that such change can be implemented with a custom handler for the cases (rare) in which there are duplicate keys.

we could have a type `SpecialIterable` or some other (better) name...

**Comment by simPod** [comment]
I kind of don't fancy making and exception for `the cases (rare) in which there are duplicate keys`. I don't really dare to estimate whether it is rare or not (e.g. in my cases it's kind of common).

Also I understand the BC break caused by my proposal would be enormous.

So I guess it's not really viable to pursue this.
