### ISSUE TITLE
`@ReadOnly` annotation incompatible with PHP 8.1

### ISSUE THREAD

**Issue by mbabker** [schmittjoh/serializer#1331]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The [readonly properties RFC](https://wiki.php.net/rfc/readonly_properties_v2) makes `readonly` a keyword in PHP 8.1.  This results in `ParseError: syntax error, unexpected token "readonly"` errors when parsing annotations thanks to the `JMS\Serializer\Annotation\ReadOnly` class.

**Comment by goetas** [comment]
:(

the only suggestion I have is to rename it into "ReadOnlyProperty"...
