### ISSUE TITLE
Serializing vs Deserializing DateTimeInterface with custom format

### ISSUE THREAD

**Issue by andrei-dascalu** [schmittjoh/serializer#1343]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

## Steps required to reproduce the problem

1. Sserialize and deserialize a PHP object with a DateTimeInterface member annotated with
```
* @JMS\Type("DateTimeInterface<'c'>")
```

## Expected Result

* On serialization: output an ISO-formatted date time + timezone
* On deserialization: load an  ISO-formatted date time + timezone (or without)

## Actual Result

* On serialization: output an ISO-formatted date time + timezone (OK)
* On deserialization: Exception 
```
Invalid datetime "2016-01-01T00:00:00+02:00", expected one of the format "c".
```

I am not sure about what's practical to do. The current behaviour is inconsistent in that it accepts "c" for serialization but there's an error on deserialization. I definitely believe that ideally "c" should be a sort of equivalent of `DateTimeInterface<'Y-m-d\TH:i:sP'>` otherwise maybe "c" should specifically be disallowed.

**Comment by goetas** [comment]
please see https://www.php.net/manual/en/datetime.createfromformat.php#120343

this is a missing feature in php. `C` can not be used to parse back a date

**Comment by andrei-dascalu** [comment]
@goetas that's fine, I'm just saying that it might be a nice touch to have a clear about its use on deserialization rather than allow it in a context where it can't possibly work.
