### ISSUE TITLE
JMS Serializer and Doctrine conflict

### ISSUE THREAD

**Issue by alnacas** [schmittjoh/serializer#1348]
I have a composer project with Doctrine and JMS Serializer. I try to use some JMS Annotations in Doctrine Entities but when I try to get info from database throught Doctrine, it gives an error 500. I attach the log.

Entity Usuario:
![Captura de pantalla 2021-09-29 a las 10 59 17](https://user-images.githubusercontent.com/15012111/135237226-d0dc1bc5-f424-4dce-8af8-198a77eb85d9.png)

Error when work with Entity:
`[29-Sep-2021 08:04:35 UTC] PHP Fatal error:  Uncaught Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@JMS\Serializer\Annotation\ExclusionPolicy" in class "Usuario" was never imported. Did you maybe forget to add a "use" statement for this annotation? in /var/www/html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:39`
`Stack trace:
#0 /var/www/html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(803): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...')`
`#1 /var/www/html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(719): Doctrine\Common\Annotations\DocParser->Annotation()`
`#2 /var/www/html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(376): Doctrine\Common\Annotations\DocParser->Annotations()`
`#3 /var/www/html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(146): Doctrine\Common\Annotations\DocParser->parse('/**\n * @ORM\\Ent. in /var/www/html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php on line 39`

It seems that Doctrine interprets the JMS Annotations as Doctrine's own and not as independent

**Comment by Tischi86** [comment]
Solved this by adding to my bootstrap (https://github.com/symfony/symfony/issues/25555#issuecomment-352911035):
```
AnnotationRegistry::registerLoader('class_exists');
```
