### ISSUE TITLE
Is type array supported as Attributes?

### ISSUE THREAD

**Issue by reypm** [schmittjoh/serializer#1350]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

## Steps required to reproduce the problem

1. Have a DTO having a property defined as an array (see example below) and try to move it to use Attributes instead of Annotations.
```php   
    /**
     * @var array<B>
     * @Serializer\Type("array<B>")
     */
    public array $prop = [];

    /**
     * @var array<B>
     * #[Serializer\Type('array<B>')]
     */
    public array $prop = [];
```
2. Try to deserialize some JSON into the class having `$prop` defined

## Expected Result

* Things works as when using Annotations

## Actual Result

* `You must define a type for App\DTO\A::$prop.`

**Comment by goetas** [comment]
(if you are not using the bundle, can yo please share the code you use to run build the serializer instance)

**Comment by goetas** [comment]
I see that you are using the 3.8.0 version of the bundle, but the support for attributes has been added only in 3.14.0

**Comment by reypm** [comment]
@goetas and how do I install such version if it is not available yet as a composer package? https://packagist.org/packages/jms/serializer-bundle

**Comment by goetas** [comment]
my bad, that was the library version. 

what you need is this:

```json
    "require": {
        "jms/serializer": "^3.14",
        "jms/serializer-bundle": "^3.10",
    },
```

**Comment by reypm** [comment]
@goetas gonna give this a try and if it works as I expect it to do I'll close this. Thanks in advance sir

**Comment by reypm** [comment]
By doing what you've said I was able to get it working, again thanks @goetas
