### ISSUE TITLE
Virtual property expressions overriding

### ISSUE THREAD

**Issue by micperr** [schmittjoh/serializer#1358]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

It seems there is a bug related to serializing with expressions. When I have more than one "virtual-property" with expression defined then only the latter one defined in the XML config is actually serialized

```
<virtual-property
        serialized-name="exp1"
        expression="object.exp1()"
        groups="listVenue"/>

<virtual-property
        serialized-name="exp2"
        expression="object.exp2()"
        groups="listVenue"/>
```

## Expected Result
```
{
    "exp1": "exp1 result",
    "exp2": "exp2 result"
}
```

## Actual Result
```
{
    "exp2": "exp2 result"
}
```

And if I added another one "expr3" after those two then "expr2" would disappear from serialized JSON and "exp3 result" appear instead so it seems there is some kind of overriding going on there.
```
<virtual-property
        serialized-name="exp3"
        expression="object.exp3()"
        groups="listVenue"/>
```

**Comment by W0rma** [comment]
Which version of jms-serializer do you use?

Would you mind providing a reproducer and/or a failing test case?

**Comment by goetas** [comment]
@micperr pay also attention that that the `name="..."` is mandatory, and from your examples it seems that you've omitted it

**Comment by micperr** [comment]
@goetas I confirm it was about that. Sorry for the fuss. Thanks guys.
