### ISSUE TITLE
Handle classes that implement collections (e.g. ArrayObject) and properties

### ISSUE THREAD

**Issue by tobyS** [schmittjoh/serializer#137]
I have a use case where a class realizes a collection and holds properties with meta data in addition. Without any additional config, JMS Serializer only takes care for the properties. I could get it working to serialize the collection part, too, by defining `getArrayCopy()` as an accessor for a virtual property. However, since virtual properties do not support deserialization, the collection would be lost.

Find a Gist to illustrate what I desire to do here: https://gist.github.com/tobyS/6397023

**Comment by goetas** [comment]
This has to be solved with a custom handler (since the usecase explained here is a custom extension of the array object class)
