### ISSUE TITLE
Phpdoc in PropertyMetadata is wrong because properties may be nullable

### ISSUE THREAD

**Issue by VincentLanglet** [schmittjoh/serializer#1371]
Ref: https://github.com/sonata-project/form-extensions/pull/272#discussion_r759522985

In propertyMetadata there is a property group
https://github.com/schmittjoh/serializer/blob/master/src/Metadata/PropertyMetadata.php#L25

The property is typed as `string[]` but according to the user, it can be null.
When using static analysis, it's kinda misleading because the `!== null` check is reported as useless (but if I remove it, it produce a bug).

I assume the same issue would exist with some of/all the others properties.

What is the best solution to you @goetas ? Updating the phpdoc to add `|null` or adding a default value ?

**Comment by goetas** [comment]
adding `string[]|null` seems the easiest thing to do, could you send a PR?

**Comment by VincentLanglet** [comment]
Sure, if I follow the same strategy for every properties without a default value it gives https://github.com/schmittjoh/serializer/pull/1372
