### ISSUE TITLE
8.1 backed enum functionally not correctly (de)serialize

### ISSUE THREAD

**Issue by thepercival** [schmittjoh/serializer#1373]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

## Steps required to reproduce the problem

1. create a backed enum in php 8.1
 enum AgainstRuleSet: int
{
    case DiffFirst = 1;
    case AmongFirst = 2;
}
2. add the enum as a property to a yaml file
MyDomain\MyClass:
  properties:
    pointsCalculation:
      type: MyDomain\AgainstRuleSet
3. serialize 

## Expected Result
The integer or string should be returned. In this case: 1 

## Actual Result
Instead {name: "DiffFirst", value: 1} is returned. Before enums the property-type would be int or string. With enums this is now an enum-type. For a backed enum this should automatically be casted to string or int with the designated functions(which are in the interface). in core.php
For deserialization the opposite should happen.

**Comment by scyzoryck** [comment]
Hello @thepercival ! 

I think that your proposition makes sense and should be an expected once. Current behaviour might be hard to use with real applications :D 
Would you like to create an PR with its implementation? :)

**Comment by thepercival** [comment]
I could give it a try. My proposal would be to specify the enum as a type.
Than check at (de)serialization if the type inherits from interface BackedEnum. 
If so, a string or int should be returned(internal interfaces IntBackedEnum and StringBackedEnum).
This would be myEnum->value
Would this by a correct way to implement?

**Comment by scyzoryck** [comment]
I believe that there are more then one correct way to implement it :) 
I would try to avoid adding new type like `enum< MyDomain\AgainstRuleSet>` - if possible I would try to autodetect it on the Metadata level to improve developer experience. It might introduce a small backward incompatibility, but as PHP8.1 is pretty fresh I should not be a big issue. @goetas WDYT?  
Some crazy idea - in theory it would be possible to handle enums by modifying metadata for classes that implements BackedEnum - by using  `inline`, `getter`, `setter` options. It would require only changes in metadata parsing without a need to modify Serialiser class. But it might be a kind of magic :D

**Comment by thepercival** [comment]
should we wait for @goetas to give his opinion?

**Comment by scyzoryck** [comment]
I would go with PR :)

**Comment by thepercival** [comment]
ok, next week, maybe friday i will make a start.I am not a tech-expert, but have enough php-experience. A did a few pull request before.

**Comment by Einenlum** [comment]
I'm digging now into the code and I think it's quite complicated because of how the `getSubscribingMethods` method of the `SubscribingHandlerInterface` expects to return FQCN classes to match to a specific type.

With the enum implementation of PHP 8.1, enum are specific classes without a base class that could identify them. The only way to do this (from what I understand) is to run `enum_exists` on the FQCN. So we can't just create an EnumHandler that would return `enum::class` for example. We need to get the type on runtime to know if it is an enum class or not.

Any news on this @thepercival ? Would be happy to help.

**Comment by thepercival** [comment]
I have not taken a look yet. But please continue.

**Comment by taranovegor** [comment]
> If so, a string or int should be returned(internal interfaces IntBackedEnum and StringBackedEnum).

Could you provide a link to the documentation of these interfaces? I didn't found it... and it doesn't work either 🤔 
<img width="505" alt="Screenshot 2021-12-28 at 23 49 09" src="https://user-images.githubusercontent.com/16158349/147609570-242a8d26-d1be-47e3-b516-b9f0eadfc0d2.png">

**Comment by thepercival** [comment]
I tried that too. It does not work, because the interfaces are only for internal use, but it should probably not matter. Both are native types and enums are made available for type safety. The next link has elaborate information: [https://php.watch/versions/8.1/enums]()

Interface BackedEnum can be used

**Comment by Einenlum** [comment]
Oh, I didn't see the existence of the BackedEnum interface. Thanks!

I'm trying to implement this, but still struggling to understand why the serialization does not take into account my BackedEnum serializer. Trying to understand how it works to deal with interface types.

https://github.com/Einenlum/serializer/commit/ba5d66c55d9f4c123a38232dcb56ef6dcf939ec2

**Comment by Einenlum** [comment]
Finished my work here https://github.com/schmittjoh/serializer/compare/master...Einenlum:feature/support-enums?expand=1
But another [PR](https://github.com/schmittjoh/serializer/pull/1384) is already open and I don't want open a duplicate PR.

**Comment by goetas** [comment]
Apologies for not providing my feedback on this for so long time.

I'm not sure that the backed enums have to return always the "value" when serializing. I have a quite large applications where we return the keys (not using php8 enums, but the idea is the same).

We have something as this:

```php
enum AgainstRuleSet: int
{
   case Digital = 1;
   case Analog = 2;
}
```

In the database, the enum is saved as `1` and `2`, but in order to have a nice "API" we expose it to the user as `analog` and `digital` (strtolower of the key). 

Said so, I'm fine with having the value serialized as default, but there should be a possibility to change it, or even better to override it as any other type (with type handlers)

**Comment by goetas** [comment]
@Einenlum because of this:

```php
if (is_a($typeName, \BackedEnum::class, true)) {
    return $this->handlers[$direction][\BackedEnum::class][$format];
}```

your implementation does not allow you to have custom handlers on backed enums

**Comment by Einenlum** [comment]
Hi @goetas, thanks for the feedback.

About serializing the name instead of the value, it's an interesting case, never thought about it. I mainly work with string backed enums so to me it was obvious I want to serialize the value and not the name, but good point. Should it be a global configuration or a specific metadata option for a specific enum?

Regarding the handlers, good point too. It's just the only way I found to be able to use a common handler for `BackedEnum`s. If you can think of an alternative, I'm really interested. My thought was maybe we can refactor the way handlers are retrieved by doing a foreach and use `is_a` but it adds other problems (including maybe performance issues).

I thought maybe we can use a foreach as a fallback if the specific type is not in the array keys. Something like:

```php
        if (isset($this->handlers[$direction][$typeName][$format])) {
            return $this->handlers[$direction][$typeName][$format];
        }

        foreach ($this->handlers[$direction] as $handlerType => $handlers) {
            if (is_a($typename, $handlerType, true) {
                // ... return the handler
            }
        }

        throw new \Exception('...');
```

But I guess I'm on the wrong path. Anyway, any advice or proposition is very welcomed :)

**Comment by joaojacome** [comment]
I've been using this handler to handle backed enums in a project:
```php
<?php

declare(strict_types=1);

use JMS\Serializer\Context;
use JMS\Serializer\GraphNavigator;
use JMS\Serializer\Handler\SubscribingHandlerInterface;
use JMS\Serializer\JsonDeserializationVisitor;
use JMS\Serializer\JsonSerializationVisitor;

class EnumHandler implements SubscribingHandlerInterface
{
    public static function getSubscribingMethods(): array
    {
        return [
            [
                'direction' => GraphNavigator::DIRECTION_SERIALIZATION,
                'format' => 'json',
                'type' => 'enum',
                'method' => 'serializeEnumToJson',
            ],
            [
                'direction' => GraphNavigator::DIRECTION_DESERIALIZATION,
                'format' => 'json',
                'type' => 'enum',
                'method' => 'deserializeEnumFromJson',
            ],
        ];
    }

    public function serializeEnumToJson(JsonSerializationVisitor $visitor, \BackedEnum $data, array $type, Context $context): string|int
    {
        return $data->value;
    }

    /**
     * @template T
     *
     * @param array{params: array<array-key, array{name: class-string<T>}>} $type
     *
     * @return \BackedEnum|T
     */
    public function deserializeEnumFromJson(JsonDeserializationVisitor $visitor, mixed $data, array $type, Context $context)
    {
        /** @var ?class-string<T> $type */
        $type = $type['params'][0]['name'] ?? null;
        if (null === $type || !is_a($type, \BackedEnum::class, true)) {
            throw new \LogicException();
        }

        return $type::from($data);
    }
}
```

**Comment by simPod** [comment]
@joaojacome how did you achieve serializer to match type `'enum;`? Do you explicitly annotate properties in serialized classes?

**Comment by joaojacome** [comment]
> @joaojacome how did you achieve serializer to match type `'enum'`? Do you explicitly annotate properties in serialized classes?

Yes.
```php
<?php

namespace App;

use JMS\Serializer\Annotation as JMS;

class MyClass
{
    #[JMS\Type(name: 'enum<App\MyEnum>')]
    public MyEnum $storeCode;
}
```

**Comment by simPod** [comment]
Makes sense. I do not expect enums to land in master anytime soon so I used your example. I prefer not to annotate if not necessary so I had to register handler for all enums in my app. Might be handy for others as well. Thanks btw.

```php
<?php

declare(strict_types=1);

namespace My\App\JMS;

use BackedEnum;
use Cdn77\EntityFqnExtractor\EnumExtractor;
use Cdn77\EntityFqnExtractor\Exception\EnumDefinitionInFileIsInvalid;
use My\App\Kernel;
use Generator;
use JMS\Serializer\Context;
use JMS\Serializer\GraphNavigatorInterface;
use JMS\Serializer\Handler\SubscribingHandlerInterface;
use JMS\Serializer\JsonDeserializationVisitor;
use JMS\Serializer\JsonSerializationVisitor;
use Symfony\Component\Finder\Finder;

final class EnumHandler implements SubscribingHandlerInterface
{
    /** @return Generator<array<string, int|string>> */
    public static function getSubscribingMethods(): Generator
    {
        $files = (new Finder())
            ->files()
            ->in(Kernel::getSrcDir())
            ->name('*.php');

        $formats = ['json', 'xml', 'yml'];

        foreach ($files as $file) {
            try {
                $enum = EnumExtractor::get($file->getPathname());
            } catch (EnumDefinitionInFileIsInvalid) {
                continue;
            }

            foreach ($formats as $format) {
                yield [
                    'direction' => GraphNavigatorInterface::DIRECTION_SERIALIZATION,
                    'format' => $format,
                    'type' => $enum,
                    'method' => 'serialize',
                ];

                yield [
                    'direction' => GraphNavigatorInterface::DIRECTION_DESERIALIZATION,
                    'format' => $format,
                    'type' => $enum,
                    'method' => 'deserialize',
                ];
            }
        }
    }

    /** @param array<mixed> $type */
    public function serialize(
        JsonSerializationVisitor $visitor,
        BackedEnum $data,
        array $type,
        Context $context,
    ): string|int {
        return $data->value;
    }

    /**
     * @param array{name: class-string<T>} $typeInfo
     *
     * @return T
     *
     * @template T of BackedEnum
     */
    public function deserialize(
        JsonDeserializationVisitor $visitor,
        int|string $data,
        array $typeInfo,
        Context $context,
    ): BackedEnum {
        $type = $typeInfo['name'];

        return $type::from($data);
    }
}
```

**Comment by sebastianstucke87** [comment]
Example on how to register the aforementioned [EnumHandler](https://github.com/schmittjoh/serializer/issues/1373#issuecomment-1192816436):

```php
$serializer = SerializerBuilder::create()
    ->addDefaultHandlers() // !!! (*)
    ->configureHandlers(function(HandlerRegistry $registry){
        $registry->registerSubscribingHandler(new EnumHandler());
    })
    ->build();
```

(*) When configureHandlers is called, then the default handlers (e.g. for `\DateTime`) will **NOT** be used (see https://jmsyst.com/libs/serializer/master/handlers for details).

**Comment by goetas** [comment]
I have prepared https://github.com/schmittjoh/serializer/pull/1448, feedback is welcome

**Comment by goetas** [comment]
Done in https://github.com/schmittjoh/serializer/pull/1448
