### ISSUE TITLE
Version 3.11+ is not compatible with PHP 8.1

### ISSUE THREAD

**Issue by dkreuer** [schmittjoh/serializer#1381]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Use PHP 8.1
2. Create project with composer
3. Require jms/serializer
4. Run composer-require-checker

## Expected Result

* No exception

## Actual Result

```
In LocateASTFromFiles.php line 46:
                                                                                                                                                                          
  Parsing the file [/var/www/vendor/jms/serializer/src/Annotation/ReadOnly.php] resulted in an error: Syntax error, unexpected T_READONLY, expecting T_STRING on line 14  
                                                                                                                                                                          

In ParserAbstract.php line 318:
                                                                      
  Syntax error, unexpected T_READONLY, expecting T_STRING on line 14  
                                                                      
```

## Underlying issue:

"readonly" is a reserved keyword since PHP 8.1. Albeit the Annotation class `JMS\Serializer\Annotation\ReadOnly` is deprecated since version 3.14.0 code analysis running under PHP 8.1 fails if it hits the file. Code might actually break if the annotation is used in an PHP 8.1 project/compatible library.

## Conclusion:

The library is not fully compatible with PHP 8.1 and this is a problem which cannot be fixed easily due to the open version range constraint (`"php": "^7.2 || ^8.0"`). I suggest to release bugfix versions for all maintained version branches which limits the constraint to `"php": "7.2.* || 7.3.* || 7.4.* || 8.0.*"` and a new major version removing the `ReadOnly` annotation and with constraint `"php": "7.2.* || 7.3.* || 7.4.* || 8.0.* || 8.1.*"`. This should help to at least reduce the problem surface.

**Comment by mbabker** [comment]
I'm mildly confused here.  Because the package still provides the deprecated "ReadOnly" class and didn't rush to release a major version to drop that single class (which would be more disruptive than leaving it in place and telling folks to not use it), that must mean the package cannot be used on PHP 8.1 at all?

IMO, this is a case better suited for SA tools being configured to ignore the problem class in incompatible environments instead of trying to say the entire package is unusable because of one optional code path that can lead to a fatal error thanks to a PHP B/C break.

**Comment by dkreuer** [comment]
> thanks to a PHP B/C break

It‘s a B/C break which is totally fine given the fact that PHP does not follow semantic versioning and always has made breaking changes in minor versions.

The issue is that the version constraints in the library do not account for that fact. If the constraint would have said „compatible only with PHP 7.* or 8.0.*“ it would have been totally fine and would only require a new major release dropping the deprecated class - which is already stated in the UPGRADE.md btw.

For me personally I‘d like to see that major version (and compatibility with it in jms/serializer-bundle - but that’s a different story). I‘m just thinking how to help others having potentially the same issue. Unfortunately there is only a chance of damage control.

Regarding the idea to ignore issues in SA tools in „incompatible“ environments: How to detect that reliably? For the SA tools the platform requirements are set in stone because these are the fundamentals they are testing with.

**Comment by mbabker** [comment]
I don't know how you'd deal with it in the context of `composer-require-checker`, but in https://github.com/schmittjoh/serializer/pull/1370 it ignored that class when running PHPStan.

Sure, the ReadOnly class still being present in the package might be giving developers a loaded gun to shoot themselves in the foot with in a very specific configuration and environment (must be using annotations or attributes, while using the deprecated class, and must be running PHP 8.1; folks who have updated their code in response to the deprecation, or are running PHP 8.0 and earlier, or are using non-PHP based mappings are not affected), but IMO that single class still existing in the API doesn't mean the entire package should be marked as incompatible with PHP 8.1 or that the maintainers here should rush out a new major version (which, given this package's consumers, would have a moderate impact on the ecosystem) just to drop this one class from the API.  If it were an issue in something closer to the "core" API of this package (like the interfaces themselves or the default Serializer class or something like that), you could make a stronger argument that one of these actions are needed, but we're talking about an optional feature with this particular class and one that has mitigation strategies already in place.

**Comment by ruudk** [comment]
This is how I run it in GitHub actions:
```
# JMS Serializer provides a deprecated ReadOnly class
# PHP 8.1 introduced a new `readonly` symbol that now breaks this.
# To solve that, we simply drop this file before we run the analysis.
rm vendor/jms/serializer/src/Annotation/ReadOnly.php
composer-require-checker check --config-file=.composer-require-checker.json
```

This will fail at some point in the future, when the `ReadOnly.php` file has been removed, and then we clean up the hack.

**Comment by goetas** [comment]
`composer-require-checker` is not something I intend to support. This library works pretty well with php 8.1 you just need to not use the `ReadOnly` class. 

Removing that class would be a useless BC break, that would force many other libs to bump for no reason their dependencies

**Comment by Jean85** [comment]
Unfortunately https://github.com/symfony/symfony/pull/45703 is not possible here, I've just tried: since the error is in the parsing stage, the `if` is not even run, it crashes hard beforehand.

I'll proceed with the same hack as in https://github.com/schmittjoh/serializer/issues/1381#issuecomment-1000150120, but IMHO the best solution would be to avoid loading the class altogether on the tool's side.

**Comment by goetas** [comment]
fixed by https://github.com/schmittjoh/serializer/pull/1410

**Comment by mbvb1223** [comment]
Released at https://github.com/schmittjoh/serializer/releases/tag/3.18.0
