### ISSUE TITLE
Support of enum members

### ISSUE THREAD

**Issue by the-toster** [schmittjoh/serializer#1392]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

As I understand, enum members aren't supported now. I can try to add support of deserialization, if it's relevant.

## Steps required to reproduce the problem
I added test that demonstrates current state - https://github.com/the-toster/serializer/commit/b0b07bf273c45f26b4a2c2617e78e7136140b149

## Expected Result
Serialize / deserialize objects with enum members.

## Actual Result
`Cannot instantiate enum`

**Comment by the-toster** [comment]
Seems it [doctrine/instantiator](https://github.com/doctrine/instantiator/blob/1.4.x/src/Doctrine/Instantiator/Instantiator.php) problem?

**Comment by scyzoryck** [comment]
Hi! @the-toster 
The topic seems to be related to backend enums that are discussed here: https://github.com/schmittjoh/serializer/issues/1373

Have you thought about the format for serialised Enum value? 
Current serialised value to array is:
```
[
    'enum' =>
        [
            'name' => 'a',
        ],
]
```

Best, scyzoryck.

**Comment by the-toster** [comment]
@scyzoryck yes, I see this thread. For me, current serialized format is fine, and it allows to deserialize it properly.

**Comment by the-toster** [comment]
I checked how `ObjectConstructorInterface` implementation selected, and as I understand, correct way is not add new one, but tweak `UnserializeObjectConstructor::construct()` method:

https://github.com/schmittjoh/serializer/blob/3f8750a21a4f3dc12cf8ac2edd9e39f611667a16/src/Construction/UnserializeObjectConstructor.php#L20-L23

I think about adding `ClassMetadata::isEnum()` method, and then use it here choose way instantiate value.

**Comment by the-toster** [comment]
I can add deserialization by value, but currently both pure and backed serialized by key, which is right in my opinion, I reason this way:
1) purpose of serialization - subsequent deserialization
2) complete deserialization possible only in same environment as serialization (same classes should be declared, etc)
3) so, enum key is enough and preferable (because it obey PHP identifier syntax, while value can be much complex and large string)

Ofcourse I can understand use cases when serialized object used in other environment, sending to JS frontend for example, this case can be handled with custom handlers.

**Comment by goetas** [comment]
Done in https://github.com/schmittjoh/serializer/pull/1448
