### ISSUE TITLE
Allow interfaces in event subscriber event config array

### ISSUE THREAD

**Issue by proggeler** [schmittjoh/serializer#1403]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Event subscribers method getSubscribedEvents can define return a class entry within the events config. It would be nice if this entry also works for interfaces (or parent classes)

## Steps required to reproduce the problem

```
class FooEventSubscriber implements \JMS\Serializer\EventDispatcher\EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return [
            [
                'class' => FooInterface::class
                'event' => 'serializer.pre_serialize',
                'format' => 'xml',
                'method' => 'bar',
            ],
        ];
    }

    public function bar(PreSerializeEvent $event) {}
}

interface FooInterface {}
class Foo implements FooInterface {}
class Baz implements FooInterface {}
```

1. initiate the serializer with `FooEventSubscriber`
2. Serialize an instance of `Foo` or `Baz`

## Expected Result

* The method `FooEventSubscriber::bar` is called on serialization

## Actual Result

* The method is not called.

**Comment by mvhirsch** [comment]
Use `'instance'` instead of `'class'`. It's implemented, but lacks documentation. See https://github.com/schmittjoh/serializer/pull/924

```php
public static function getSubscribedEvents()
{
    return [
        [
            'instance' => FooInterface::class, // use "instance" here, instead of "class"
            'event' => 'serializer.pre_serialize',
            'format' => 'xml',
            'method' => 'bar',
        ],
    ];
}
```

**Comment by proggeler** [comment]
@mvhirsch I will try. Thank for the update.
