### ISSUE TITLE
Annotations don't work when opcache.enable=1 and opcache.save_comments=0

### ISSUE THREAD

**Issue by karlerss** [schmittjoh/serializer#1407]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I just spent an hour figuring out why my PHPUnit tests pass, but HTTP behavior is different.

It turns out that opcache.enable=1, opcache.enable_cli=0 and opcache.save_comments=0 is a bad combination.

This is obvious in hindsight but was a pain to discover.

I propose adding a note about this to the documentation: when using opcache, set opcache.save_comments=1.

Thank you for the awesome library!

**Comment by scyzoryck** [comment]
Hello @karlerss ! 
Thank for comment. I can see that Annotation Reader from Doctrine should throw meaningful exception about it - see more here: https://github.com/doctrine/annotations/blob/1.13.x/lib/Doctrine/Common/Annotations/AnnotationReader.php#L118 . Feel free to prepare simple Pull Request with documentation update if needed! 

Best, Marcin
