### ISSUE TITLE
When is the next release

### ISSUE THREAD

**Issue by GinoPane** [schmittjoh/serializer#1420]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

It has been pretty long already since the last release. When is the next release going to happen? We have to use the dev version of the package at the moment and want to switch to the stable version once it's released.

**Comment by scyzoryck** [comment]
Hi! 

I believe that next release will be released in the second part of the month. 

Best, scyzoryck.

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/releases/tag/3.18.0
