### ISSUE TITLE
Impossible to tell to serializer to not return empty array

### ISSUE THREAD

**Issue by MatDepInfo** [schmittjoh/serializer#1423]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes

Hello, I know it is possible to not return null value, but is it possible to not return empty array ?

**Comment by goetas** [comment]
what about `@SkipWhenEmpty` ?

**Comment by MatDepInfo** [comment]
I thought to a context method like "setSerializeNull" but this annotation works well. Thanks.
