### ISSUE TITLE
Metadata/PropertyMetadata

### ISSUE THREAD

**Issue by kiropowered** [schmittjoh/serializer#1426]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | yes/no

After upgrading from 3.17.1 to 3.18 we started get lot of errors : 

Undefined array key {offset}
Metadata/PropertyMetadata.php:257

We had to go back to 3.17.1

**Comment by goetas** [comment]
did you clear the cache?

**Comment by kiropowered** [comment]
Yes I did

**Comment by kiropowered** [comment]
Sry I am closing this I properly cleared the cache and it worked
