### ISSUE TITLE
What happened to yml support?

### ISSUE THREAD

**Issue by maiermic** [schmittjoh/serializer#1441]
I used this library in the past (version 1.X) to serialize YML. However, running

```php
$context = new SerializationContext();
$context->setSerializeNull(true);
$serializer = SerializerBuilder::create()->build();
return $serializer->serialize($data, 'yml', $context);
```

with the latest version 3.18.2 results in

```
Uncaught JMS\Serializer\Exception\UnsupportedFormatException: The format "yml" is not supported for serialization.
```

According to [packagist](https://packagist.org/packages/jms/serializer) the format is still supported:

> Library for (de-)serializing data of any complexity; supports XML, JSON, and **YAML**.

However, the Github README.md does not mention YAML support

> Currently, it supports XML and JSON.

Is the description on packagist out of date? Is YAML not supported anymore? I haven't seen a note about a removal in the [changelog](https://github.com/schmittjoh/serializer/blob/master/CHANGELOG.md). It seems to be configurable, but I haven't found any example in the documentation on how to configure it.

---

Thanks for maintaining this library ❤️

**Comment by scyzoryck** [comment]
Hi @maiermic!

YML support has been removed in 2.0 with all related code. It looks like packagist description is outdated. 

Best, scyzoryck.

**Comment by maiermic** [comment]
Thanks, may I ask, why it has been removed?

**Comment by scyzoryck** [comment]
Hard to say - it was long time ago. :D May @goetas will add something it the topic, I can guess that the reasons could be: 
- no support for deserialisation implemented
- dependency in symfony/yaml library
- not popular format for exchanging data
- super complicated specification for YAML - [63 ways of defining multiline strings](https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines)
