### ISSUE TITLE
Missing changelogs since 3.16.0 👎 

### ISSUE THREAD

**Issue by nietzscheanic** [schmittjoh/serializer#1465]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

**Comment by scyzoryck** [comment]
Hi. The change log can be found here: https://github.com/schmittjoh/serializer/releases

**Comment by nietzscheanic** [comment]
What's about the CHANGELOG.md?

**Comment by goetas** [comment]
That file is not maintained anymore. The github generated change log saves me a lot of time each time I want to make a release

**Comment by nietzscheanic** [comment]
Can you please remove the CHANGELOG.md from the repository?

**Comment by goetas** [comment]
feel free to create a PR
