### ISSUE TITLE
Deserializing with missing promoted properties results in uninitialized state

### ISSUE THREAD

**Issue by mpragliola** [schmittjoh/serializer#1472]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

PHP version: 8.1.15
JMS Serializer version: 3.22.0

When I try to deserialize some payload into a class with promoted properties and a default value, I get an error when I try to use missing properties, despite having default values set in the constructor.

## Steps required to reproduce the problem

1. Define a class with **promoted properties** and **default values**

```php
class Foo
{
    public function __construct(
        public string $bar,
        public ?string $baz = null,
    ) {
    }
}
```
2. **Deserialize** into that class a payload where the property with the default is **missing**:

```php
$data = '{"bar":"hello"}';
$fooInstance = $this->serializer->deserialize($data, Foo::class, 'json');
```

3. Use the missing property

```php
print_r($fooInstance->baz);
```

## Expected Result

```
null
```

## Actual Result

```
Error: Typed property Foo::baz must not be accessed before initialization
```

## Possible root cause

As far as I've seen, the target class is instantiated via reflection but without using the constructor itself (`Instantiator.php`):

```php
        if ($this->isInstantiableViaReflection($reflectionClass)) {
            return [$reflectionClass, 'newInstanceWithoutConstructor'];
        }
```

This would leave those properties in an **uninitialized state**.

## Workaround

I have to explicitly initialize and demote the properties:

```php
class Foo
{
    public ?string $baz = null;

    public function __construct(public string $bar, ?string $baz) 
    {
        $this->baz = $baz;
    }
}
```

**Comment by scyzoryck** [comment]
Hi @mpragliola ! Is it the same issue as in https://github.com/schmittjoh/serializer/issues/1367 ?

**Comment by mpragliola** [comment]
@scyzoryck no, I don't think so. In #1367 the property that causes the error has **no default value**, while in my case there is clearly a `null` assigned as default.
And, if i _demote_ the property and assign the default outside the constructor, the error disappears.

**Comment by iKsSs** [comment]
Hi all!

I created a wrapper for JMS Serializer (a temporary solution till JMS supports promoted props) which
- **sets promoted properties**,
- **validates deserialized data**, (there is an option to call `deserializeWithoutValidation()`/`fromArrayWithoutValidation()`)
- **checks uninitialized properties** (on PROD logs warning, other envs logs error + throws `DeserializationException`)

Serializer implements `JMS\Serializer\ArrayTransformerInterface` and `JMS\Serializer\SerializerInterface` interfaces.
The code is compliant with [PHPStan](https://github.com/phpstan/phpstan) level 8.
It was written in [Symfony](https://github.com/symfony/symfony) 6.4 and it should work in Symfony 7.x however, it should be easily adaptable to other frameworks.

Check out the implementation:
https://gist.github.com/iKsSs/f048fd04f28c638a5c3d8b4390976d25

**Comment by scyzoryck** [comment]
Coming back to this issue. 

@mpragliola Are you using `DefaultValuePropertyDriver`? The case that you are describing in the first post seems to be working fine for me. See `BaseSerializationTestCase::testConstructorPromotionWithDefaultValues` test case that is covering exactly what you described :)

**Comment by markuspoerschke** [comment]
We experienced the same problem when using the JSM Serializer Bundle with Symfony Framework.

Adding the following config solved the issue for us.

```php
jms_serializer:
    default_value_property_reader_support: true
```

**Comment by dmaicher** [comment]
> We experienced the same problem when using the JSM Serializer Bundle with Symfony Framework.
> 
> Adding the following config solved the issue for us.
> 
> ```
> jms_serializer:
>     default_value_property_reader_support: true
> ```

@markuspoerschke this indeed fixes our issue :blush: Thanks! @mpragliola let's close here
