### ISSUE TITLE
MaxDepth shows empty array property

### ISSUE THREAD

**Issue by jdeveloper** [schmittjoh/serializer#148]
When the MaxDepth is reached, the collection properties are showed as empty arrays, even they have data, but the property should not been showen at all.

This happens to me when using doctrine relations.

**Comment by andreaslarssen** [comment]
+1.

It's very confusing for end users of the API when a collection output is being displayed as an empty collection, when in fact it's supposed to be excluded by the maxDepth config parameter.

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/pull/743/commits/94c319db88883757a14ac267115272be030aef28
