### ISSUE TITLE
Update doctrine/instantiator to v2.x for PHP 8.1

### ISSUE THREAD

**Issue by JBlocks** [schmittjoh/serializer#1483]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no

## Steps required to reproduce the problem

1. Using PHP >=v8.1
2. Install jms serializer with composer `composer req jms/serializer`
3. Installation failed with `doctrine/instantiator[1.1.0, ..., 1.3.0] require php ^7.1 -> your php version (8.1.16) does not satisfy that requirement.`

## Expected Result

* Update the dependency of doctrine/instantiator to v2.x to be compatible with php 8.1

## Actual Result

* Installation failed with `doctrine/instantiator[1.1.0, ..., 1.3.0] require php ^7.1 -> your php version (8.1.16) does not satisfy that requirement.`

**Comment by mbabker** [comment]
The `doctrine/instantiator` package supports `^7.1 || ^8.0` as of its 1.3.1 release.  Try updating that package first.

**Comment by JBlocks** [comment]
Thanks for the feedback. Would it still be possible to bring the jms serializer to the new version 2 of doctrine/instantiator?

We currently have to resolve some dependencies, as e.g. the new TYPO3 CMS v12 uses the doctrine/instantiator:^2 package. The CMS and third-party providers will now increasingly update to the new versions. The `doctrine/orm` package also uses the v2 of `doctrine/instantiator`.

**Comment by scyzoryck** [comment]
Hi. Last time when I was checking it there were some troubles with its installation - conflicts with other library. However if you have some time feel free to take a look at it and submit MR. I will be glad to help you if you would need any help. I will add this to my personal todo list too, however it is hard to estimate when I will have some time to work on that.

**Comment by scyzoryck** [comment]
`doctrine/orm` has been released, however to run proper tests for the serialiser there is one more blocker - https://github.com/doctrine/phpcr-odm 
```
➜  serializer git:(master) composer why-not doctrine/instantiator 2
jms/serializer     3.x-dev requires doctrine/instantiator (^1.0.3) 
doctrine/phpcr-odm 1.7.1   requires doctrine/instantiator (^1.0.1) 
```
