### ISSUE TITLE
JMS serializer implements Symfony serializer

### ISSUE THREAD

**Issue by themark147** [schmittjoh/serializer#1484]
Hello,

In SF 6.3 we will have feature https://symfony.com/blog/new-in-symfony-6-3-mapping-request-data-to-typed-objects

but RequestPayloadValueResolver resolver requires Only interfaces from symfony serializer ... its any change JMS serializer will be implements symfony serializer interface? cause JMS is used by JMS bundle and FOS rest bundle

thanks

**Comment by scyzoryck** [comment]
No problem! Feel free to submit pull request. I will be glad to help with code review or the merge process. 

Best scyzoryck.

**Comment by scyzoryck** [comment]
Let's move discussion to: https://github.com/schmittjoh/JMSSerializerBundle/issues/928
