### ISSUE TITLE
"Can't use incorrect type integer for collection" on PHPDoc-typed integer, boolean or double

### ISSUE THREAD

**Issue by outtersg** [schmittjoh/serializer#1489]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Have the DocBlockTypeResolver activated (`infer_types_from_doc_block: true`)
2. Have a Doctrine entity with an member attribute that is:
   * typed with PHPDoc (`@var integer`) as an **integer** (not _int_)
   * computed, not persistent (no ORM mapping)
   * serializable (`@Serializer` annotations, for e.g. Groups or SerializedName; but no type, for which we rely on PHPDoc)
3. Try to generate metadata cache

## Expected Result

* attribute is detected as int

## Actual Result

* "Can't use incorrect type integer for collection" exception

## Cause

`isPrimitiveType()` does not know the alternative, long names that are [part of PHPDoc](https://docs.phpdoc.org/3.0/guide/references/phpdoc/types.html): `integer`, `boolean`, `double`.
As such it avoids all kind of typing in `DoctrineTypeDriver::setType()` and ends considering those members as a collection (= behaviour for anything not being detected as a primitive, scalar, type).

**Comment by scyzoryck** [comment]
Fixed 3.26.0 :)
