### ISSUE TITLE
Hierarchical object serialization does not appear to inherit metadata from ancestors for metadata defined in XML

### ISSUE THREAD

**Issue by swquinn** [schmittjoh/serializer#151]
When defining a class's serialization metadata in XML for a hierarchy of objects, e.g. `Employee` which extends `Person`, attempting to serialize the `Employee` does not take into consideration any of the inherited properties from `Person` and whether they should be serialized or not. Please see gist: https://gist.github.com/swquinn/88a97c3702efd11f1eb5.

Based on my understanding of the serializer the **ThirdParty.Employee.xml** metadata should expose only the employee's `role`, but also inherit the `name` and `age` of the employee based on the XML definition of **ThirdParty.Person.xml**. While I understand the role groups play, this example is explicitly done without them.

The `$result` of the serialization, as shown in the gist, is `{"name":"John Doe","gender":"male","age":42,"role":"Manager"}`, where I would expect the result to be: `{"name":"John Doe","age":42,"role":"Manager"}`.

**Comment by goetas** [comment]
Sorry for the terribly long feedback loop. This issue has been probably already solved, if the problem still occurs, feel free to comment it here, and I will re-open it again.
