### ISSUE TITLE
The dependency on doctrine/annotations should become an optional one

### ISSUE THREAD

**Issue by stof** [schmittjoh/serializer#1511]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | depends on the implementation
| RFC?             | no

The doctrine/annotations is expected to be marked as abandoned soon by the Doctrine team: https://github.com/doctrine/annotations/issues/485

It would be great to make the dependency on doctrine/annotations optional so that projects that have migrated to attributes don't need to install it anymore.

Side note: it would probably make sense to deprecate the support for annotations in favor of attributes (maybe it makes sense to first drop support for PHP 7.x though).

**Comment by scyzoryck** [comment]
HI! 
Thanks for letting us know! :) 
At the moment we are in the middle of the migration, as such change will be backward incompatible. 
I think at the moment the last PR that is needed is: https://github.com/schmittjoh/serializer/pull/1471 

Best, scyzoryck

**Comment by mbabker** [comment]
This can be closed, the latest release has made annotations and optional dependency.
