### ISSUE TITLE
Use another field than "id" to find Doctrine entity

### ISSUE THREAD

**Issue by ebuildy** [schmittjoh/serializer#1533]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

Given this JSON

``` 
[{"title":"toto"}]
```

Doctrine entity class:

```
class Hotel {
  private $title: string;
} 
```

When doing:

```
$this->serializer->deserialize("JSON", sprintf('array<%s>', Hotel::class), 'json');
```

## Expected Result

* Entity found by using the "title" field

## Actual Result

* Entity is not found, because there is no ID from JSON string, because https://github.com/schmittjoh/serializer/blob/master/src/Construction/DoctrineObjectConstructor.php#L109

This could call the entity repository as fallback to find the Entity ?

Something like

```
if (empty($identifierList)) {
            $object = $objectManager->getRepository($metadata->name)->findSpecial($data);
        } else {
            $object = $objectManager->find($metadata->name, $identifierList);
        }
```

**Comment by scyzoryck** [comment]
Hi! 
I do not fully understand a need for such feature. 
Looking at the [Doctrine documentation](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/basic-mapping.html#identifiers-primary-keys):
> Every entity class must have an identifier/primary key

On the other side - I can see many potential issues with implementing such possibility - how to configure which field/fields should be used, what if the field is not unique. 

So if other people do not see a need for such feature I guess implementing your own fallback constructor would do the job in your case and I guess would be the simplest solution. 

Best, Marcin.

**Comment by ebuildy** [comment]
what about an event `serializer.entity_reconciliation` ?

**Comment by scyzoryck** [comment]
Sounds a bit complicated and redundant. :) I do not see a lot of value in adding it right now - especially when it can be achieved with existing features.
