### ISSUE TITLE
Support `@phpstan-import-type`

### ISSUE THREAD

**Issue by simPod** [schmittjoh/serializer#1547]
| Q                | A
| ---------------- | -----
| Feature request? | yes

serializer seems to understand `@phpstan-type` annotations

https://github.com/schmittjoh/serializer/blob/d0a24b7a89b2764a58b530981d1ab016d6a9138d/src/Metadata/Driver/DocBlockDriver/DocBlockTypeResolver.php#L411

It should also understand `@phpstan-import-type` when the shape is imported from another class.

**Comment by simPod** [comment]
I've done some investigation and I think it is not trivial. It's very hard to determine FQN of the `from` class.

**Comment by simPod** [comment]
can you point me more specifically? I've opened the file which uses doctrine/commons where I checked test fixtures and did not find any example.

**Comment by goetas** [comment]
I think it is here https://github.com/schmittjoh/serializer/blob/master/src/Metadata/Driver/DocBlockDriver/DocBlockTypeResolver.php#L244

**Comment by simPod** [comment]
Lol ok so it was right next to where I was looking the whole time.
