### ISSUE TITLE
getter is not called when serializing Discriminator parent entity

### ISSUE THREAD

**Issue by nicolaslattuada** [schmittjoh/serializer#156]
Hello
It seems that at the moment when using Discriminator, the getter for exposed property does not get called.
I am adding a code example to explain my question.

```
/**
 * @Serializer\Discriminator(field = "type", map = {
 *    "car": "JMS\Serializer\Tests\Fixtures\Discriminator\Car",
 *    "moped": "JMS\Serializer\Tests\Fixtures\Discriminator\Moped",
 * })
 */
abstract class Vehicle
{
    /** @Serializer\Type("integer") */
    public $km;

    public function getKm()
    {
        return 25;
    }
}
```

Given this code snippet, would it be possible to have serialized property km to have the value of 25?
Thanks in advance!
Nicolas.

**Comment by Namoshek** [comment]
For future reference, there is a hint regarding this issue in the docs:

>  Note: If you need only to serialize your data, you can avoid providing a setter by setting the property as read-only using the `@ReadOnly` annotation.
