### ISSUE TITLE
serialize() throws error when object has member of type "float|int|null"

### ISSUE THREAD

**Issue by captain-igloo** [schmittjoh/serializer#1562]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

The following code throws an error under version 3.31.0 but not under 3.30.0:

```
class Foo
{
    public float|int|null $a = 99;
}

$serializer = SerializerBuilder::create()->build();
$serializer->serialize(new Foo(), 'json');
```
The error is:

```
In Parser.php line 30:                                                                                       
JMS\Serializer\Type\Parser::parse(): Return value must be of type array, null returned
```

**Comment by kargpfen** [comment]
I have the same problem 🙁

**Comment by scyzoryck** [comment]
Thanks! I will take a look in the evening on this issue.

**Comment by KevinMarques** [comment]
Same here. Thank you for taking a look ;)

**Comment by igordeveloper** [comment]
> Thanks! I will take a look in the evening on this issue.

Thank you @scyzoryck 

Do you believe it is a quick error to fix, or will it take a long time?

**Comment by scyzoryck** [comment]
[3.31.0](https://github.com/schmittjoh/serializer/releases/tag/3.31.0) released!

**Comment by igordeveloper** [comment]
> [3.31.0](https://github.com/schmittjoh/serializer/releases/tag/3.31.0) released!

thank you.

**Comment by kargpfen** [comment]
Thanks for release [3.31.1](https://github.com/schmittjoh/serializer/releases/tag/3.31.1)
