### ISSUE TITLE
Union types are serialized to null

### ISSUE THREAD

**Issue by dmaicher** [schmittjoh/serializer#1565]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

## Steps required to reproduce the problem

Since version 3.31.1 there is an issue with serializing union types. With 3.30.0 it worked fine previously.

Given this class

```php
class FooDTO
{
    public function __construct(
        public readonly int|float|null $value,
    ) {
    }
}
```
## Expected Result

Serializing `new FooDTO(5)` should result in `{"value":5}`

## Actual Result

Serializing `new FooDTO(5)` actually results in `{"value":null}` :open_mouth:

**Comment by dmaicher** [comment]
I cannot reproduce it with a serializer instance created via `SerializerBuilder::create()->build()`. So this must have something todo with the JMS Serializer Bundle and the way the serializer is configured :thinking:

**Comment by scyzoryck** [comment]
I guess bundle might miss handler configuration.  I might have some time the day after tomorrow to look at it.

**Comment by dmaicher** [comment]
Closing here as its an issue on the Bundle. See https://github.com/schmittjoh/JMSSerializerBundle/issues/953
