### ISSUE TITLE
Error serializing union types between class and boolean value types

### ISSUE THREAD

**Issue by gregtyler** [schmittjoh/serializer#1568]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

As of 3.31.0, if you try to serialize a method that is a union type between a class a boolean value type (e.g. `MyClass|false`), JMS Serializer raises an exception.

This is because the value type [is filtered out by `TypedPropertiesDriver->shouldTypeHint()`](https://github.com/schmittjoh/serializer/blob/6226197b0eadab798b2101d8259f03a8707892d3/src/Metadata/Driver/TypedPropertiesDriver.php#L164-L166) (because `true` and `false` aren't in the allowlist) so the only acceptable value becomes "MyClass".

## Steps required to reproduce the problem

```php
class SubClass {
}

class TestClass {
    public SubClass|false $falsableProp = false;
}

$serializer = JMS\Serializer\SerializerBuilder::create()->build();
$jsonContent = $serializer->serialize(new TestClass(), 'json');
echo $jsonContent;
```

## Expected Result

```php
{"falsable_prop":false}
```

## Actual Result

Exception thrown:

> JMS\Serializer\Exception\InvalidArgumentException: Value at TestClass is expected to be an object of class SubClass but is of type boolean

## Workarounds

Changing the typehint to `MyClass|bool` fixes this, though means you're opening your type wider than needed.

## Fix

I believe this can be fixed with two changes:
- Adding `'true'` and `'false'` to [the TypedPropertiesDriver whitelist](https://github.com/schmittjoh/serializer/blob/6226197b0eadab798b2101d8259f03a8707892d3/src/Metadata/Driver/TypedPropertiesDriver.php#L71-L83)
- Adding `'true'` and `'false'` as cases to [the graph navigator boolean acceptor](https://github.com/schmittjoh/serializer/blob/master/src/GraphNavigator/SerializationGraphNavigator.php#L157-L159) (without, the navigator treats value types as objects)

I'm happy to raise a PR for this, but I'm not very familiar with the nuances of the codebase so I'm not confident this won't cause other issues.

**Comment by scyzoryck** [comment]
Hi! It looks like it will work :) I can help with reviewing the PR.
