### ISSUE TITLE
Allow phpstan/phpdoc-parser 2.0

### ISSUE THREAD

**Issue by simoheinonen** [schmittjoh/serializer#1580]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

**Comment by scyzoryck** [comment]
Hi! 
The support will be release with the next released. It is already available in `dev-master` version. 
#1572

**Comment by simoheinonen** [comment]
Ahh, missed that!
