### ISSUE TITLE
@MaxDepth or Exclusion Strategies don't work with setSerializeNull(true)

### ISSUE THREAD

**Issue by lichnow** [schmittjoh/serializer#161]
when SerializationContext::create()->enableMaxDepthChecks()->setSerializeNull(true),this has a error says Warning: json_encode(): recursion detected in vendor/jms/serializer/src/JMS/Serializer/JsonSerializationVisitor.php line 29 ,but when don't use enableMaxDepthChecks(),it works fine,this is a bug?

**Comment by goetas** [comment]
fixed in 2.0
