### ISSUE TITLE
PreSerialization Event not handled if the value is not object

### ISSUE THREAD

**Issue by yoshi49535** [schmittjoh/serializer#162]
If the type of property is not object, "pre_serialization" event is not dispatched.
In other words, the method "SerializationContext::isVisiting" throw an exception before handle event listener, iff the value is not an object. 

This is too limited i think.

In my case, I created Hash Type, which can be either "String hash" or "Hashable instance".
I want to serialize without replacement of the object.

**Comment by goetas** [comment]
see https://github.com/schmittjoh/serializer/pull/610
