### ISSUE TITLE
Use expression for virtual properties

### ISSUE THREAD

**Issue by adrienbrault** [schmittjoh/serializer#171]
It would be nice to be able to specify an expression instead of a method for virtual properties in yaml/xml.
Not sure if it'd make sense to have this feature in annotations.

``` yaml
virtual_properties:
    property: { expression: "object.getA().getB()" }
```

**Comment by goetas** [comment]
this will become interesting when https://github.com/schmittjoh/serializer/pull/673 will be merged

**Comment by goetas** [comment]
done in https://github.com/schmittjoh/serializer/pull/708
