### ISSUE TITLE
Customize how Booleans are serialized

### ISSUE THREAD

**Issue by Richtermeister** [schmittjoh/serializer#180]
I have a use-case where I need to serialize booleans to "Y" or "N". 

It seems like I would need to extend the Visitor classes to do that, but since they use private properties internally, this is a no-go. I would be nice to be able to customize the boolean values, perhaps even on a per-entity/property level..

**Comment by AlexKovalevych** [comment]
+1

**Comment by hanovruslan** [comment]
+1

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/pull/610
