### ISSUE TITLE
Magic and inconsistencies in array serialization

### ISSUE THREAD

**Issue by Tobion** [schmittjoh/serializer#191]
This ticket tries to sum up some bad things in array serialization.
- There seems to be some inconsistency in JSON and YAML given empty arrays. See #183 and #124.
- Inconsistency in JSON and XML given empty arrays (depending on scalar types or objects as values ).

```
    /**
     * @var array[string]
     * @Serializer\Type("array<string>")
     * @Serializer\XmlList(entry="store_id")
     */
    public $storeIds = array();
```

In JSON: `store_ids: [ ]`
In XML: no element or anything

```
    /**
     * @var array[Attribute]
     * @Serializer\Type("array<Attribute>")
     * @Serializer\XmlList(entry="attribute")
     */
    public $attributes = array();
```

In JSON: `attributes : [ ]`
In XML: `<attributes/>`
- Inconsistency when beeing null:

```
@Serializer\Type("array<MyModel>")
public $attributes;
```

is serialized in JSON as empty array `attributes: []` even though it's `null`.
Whereas `@Serializer\Type("array")` would not serialize the property because it's null.
- I really dislike the magic of the array serializer that looks at the keys and checks whether they are integer and consecutively. If they are not then the keys are still used as a hashmap. This can happen quite fast and gives WTF moments.
  For example given the following annoation which basically means a LIST (ignoring keys) instead of a HASH.

```
@Serializer\Type("array<MyModel>")
public $attributes;
```

But if `$this->attributes = array(0 => new MyModel(), 2 => new MyModel())` which e.g. can happen when you use `unset()` then the serializer serializes it as HASH like

```
nutrients: {
   0: {
        quantity: 69
    }
    2: {
        quantity: 0.5
    }
}
```

which is really bad.
So IMHO this magic should only happen for the general `array` serialization type which makes it a good allround solution. But for `array<T>` (always LIST) and `array<K, V>` always HASH) this should not happen.
Also IMHO the naming of `array<T>` and `array<K, V>` is unfortunate and causes lots of confusion. Instead I would prefer to use `array<T>` -> `list<T>` and `array<K, V>` -> `hash<V>`. I don't see the point of specifying the key type for hashes. It can only be `integer` or `string` anyway and this distinction makes no sense in PHP. If you have a mixed array like `array(0 => 'value', 'foo' => 'bar')` what would you annotate as key? All that matters is, if the key is important or not. This is why `list` or `hash`. This would also be consistent with `@XmlList` and `@XmlHash` which only adds additional information specific to xml like `inline`.
- I think `@Serializer\XmlKeyValuePairs` should be the default for associative arrays. Otherwise the xml representation is toally useless.

**Comment by eexit** [comment]
I'm having the same issue, is it possible to consider a clean fix any soon?

Thanks!

**Comment by goetas** [comment]
solved in  https://github.com/schmittjoh/serializer/pull/728
