### ISSUE TITLE
Can't use handlers on strings (and other simple types)

### ISSUE THREAD

**Issue by Brammm** [schmittjoh/serializer#194]
The API I'm accessing returns XML that returns simple strings, but sometimes adds an attribute to the string element. In that case, I need to ignore the value and do something with the attribute. 

However, if I look in the GraphNavigator, I see that handlers aren't called for strings, integers, booleans, floats, doubles, arrays or resources.

**Comment by goetas** [comment]
solved with https://github.com/schmittjoh/serializer/issues/610
