### ISSUE TITLE
Automatic mapping of properties

### ISSUE THREAD

**Issue by mnapoli** [schmittjoh/serializer#200]
Hi there, first time user of this lib so maybe I'm not getting it correctly.

I'm using this lib to serialize/unserialize DTO objects to JSON (or whatever).

So instead of using `json_decode` and ending up with a `stdClass`, I'd like to use:

```php
$dto = $serializer->deserialize($json, MyDTO::class, 'json');
```

And `$dto` would be an instance of:

```php
class MyDTO
{
    public $id;
    public $label;
}
```

Doing this manually, i.e. mapping `stdClass` to `MyDTO` is pretty simple. But I'm looking for a more generic solution.

But I don't understand why I have to add annotations to my DTO to force types. I have validation on a separate level, here I just want a DTO, i.e. a `stdClass` but with a known schema (good for autocompletion for example).

So am I missing something, is this something possible with this library? Or is there a reason it's not?

**Comment by goetas** [comment]
answered
