### ISSUE TITLE
No way to serialize binary data with a custom type

### ISSUE THREAD

**Issue by Toflar** [schmittjoh/serializer#202]
Hey,

I do have a database where file paths are referenced via UUID and those are stored binary in the database.
I'm now trying to display both, the UUID and the path to the file in the serializer.

I worked my way through the code (pretty impressive!) and found that I could actually register my own `@Type()` to achieve this.
When I did that, I got the message

> Expected object but got resource. Do you have the wrong @Type mapping or could this be a Doctrine many-to-many relation?

So I tracked this down and found that this is because of the `GraphNavigator` not knowing this type and therefore calling `isVisiting()` (https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/GraphNavigator.php#L144) which then throws and Exception if it's not an object (this is the case for me, as I have a `resource`).

So I thought I could maybe register on the `preSerialize` event to turn the resource into a valid array but as you can see from the code, the event follows after the check. So this is no option.
As far as I could analyze this situation, I think I have to replace the whole default `SerializationContext` which I find a bit of an overkill.

Don't you think it would be helpful if we could decide about a type on our own before you throw any Exceptions? :-)

I'll be happy to help working on a solution but wanted to add an issue first. Maybe my approach was completely wrong - could well be :-D
Thanks for your feedback on this!

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/pull/610
