### ISSUE TITLE
Warning when deserializing removed entity

### ISSUE THREAD

**Issue by ddeboer** [schmittjoh/serializer#216]
When a Doctrine entity is serialized, removed from the database and then  deserialized, a warning is given:

```
Warning: ReflectionProperty::setValue() expects parameter 1 
to be object, null given in /vendor/jms/serializer/src/JMS/Serializer/GenericDeserializationVisitor.php on line 176
```

The entity is then deserialized as an integer (its original id) instead of an object. The relevant code is [DoctrineObjectConstructor.php](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Construction/DoctrineObjectConstructor.php#L86): if the entity is not found, `null` is returned. 

Simply adding the following helps, but means that you can end up with entities that are no longer in the database:

``` php
// Entity update, load it from database
$object = $objectManager->find($metadata->name, $identifierList);
if (!$object) {
    return $this->fallbackConstructor->construct($visitor, $metadata, $data, $type, $context);
}
```

What would be the intended behaviour in this case?

**Comment by magnetik** [comment]
Facing the same problem

**Comment by brettminnie** [comment]
@magnetik have a proposed fix sitting here #290 Hopefully it will help you until it's addressed

**Comment by brettminnie** [comment]
@magnetik have a look here #290 this is how we solved it

**Comment by ignace** [comment]
I used the serializer component for an API. The client sends an entity with an identifier, which makes the doctrineobjectconstructor confuse it with an existing entity. Doing the above solves this problem and the new entity is constructed as expected as are any associated entities (in my case a parent object "parent": {"id": 1}}).

**Comment by nuxwin** [comment]
See my answer here for alternative solution: https://github.com/schmittjoh/serializer/pull/290#issuecomment-159778071

**Comment by mmeloni** [comment]
Same problem
