### ISSUE TITLE
property path support

### ISSUE THREAD

**Issue by j** [schmittjoh/serializer#22]
I have a property "foo" which is a referenced doctrine document.  I basically want to serialize it as:

```
{
   "foo_id": 1
}
```

Internally, the serializer sees that the object is a doctrine proxy object then changes it's type to the document class.  Normally, I'd create my own handler here to just call, $foo->getId() and make that the value with configuration of:

``` xml
<property name="foo" type="DoctrineIdentifier" serialized-name="foo_id" />
```

However, because the doctrine proxy event converts the type to the class name first, it never hits the handler.

Any current ways around this before I start digging into the code?

Utilizing the PropertyPath component may be cool?

``` xml
<property name="foo.id" type="string" />
```

would output:

``` json
{ "foo_id": 1 }
```

Another example

``` xml
<property name="posts[0].id" type="string" />
<property name="friends[0].best_friend.name" type="string" serialized-name="my_first_friends_bff" />
```

would output:

``` json
{
    "posts_0_id": 1,
    "my_first_friends_bff": "Johannes"
}
```

Etc, etc.  I feel like I create a lot of handlers for doing stuff like this and it'd be cool to easily put something via property path in the root!

Anyway, two questions:

1) How can I achieve this now?
2) Does the PropertyPath component fit into the serializer?

**Comment by goetas** [comment]
can be achieved with https://github.com/schmittjoh/serializer/pull/708
