### ISSUE TITLE
Feature proposal: dynamic property serialized name

### ISSUE THREAD

**Issue by marcospassos** [schmittjoh/serializer#225]
Hello folks!

I've some projects where I've dynamic fields names based on the type. For example, I've implemented an API where I've to serialize the request before sending. This request looks like it:

``` xml
<request action="get">
     <objectName>
         <element/>
         <element/>
     </objectName>
</request>
```

The element `<objectName>` changes according with the object contained in the request. Currently, to achieve that I've to write a lot of boilerplate code:

``` php
public function onPostSerialize(ObjectEvent $event)
{
    $request = $event->getObject();

    if (!$request instanceof ModelRequest) {
        return;
    }

    $model = $request->getModel();
    $factory = $event->getContext()->getMetadataFactory();
    $requestMetadata = $factory->getMetadataForClass(get_class($request));
    $resourceMetadata = $factory->getMetadataForClass(get_class($model));
    $visitor = $event->getVisitor();
    /** @var PropertyNamingStrategyInterface $namingStrategy */
    $namingStrategy = $visitor->getNamingStrategy();
    $nodeName = $namingStrategy->translateName($requestMetadata->propertyMetadata['model']);
    /** @var \DOMDocument $document */
    $document = $visitor->getDocument();
    $modelNode = $document->getElementsByTagName($nodeName)->item(0);

    if (!$modelNode) {
        return;
    }

    // Simulates the DOMDocument::renameNode which is not implemented yet
    $renamedNode = $document->createElement($resourceMetadata->xmlRootName);
    $renamedNode->appendChild($modelNode->firstChild);
    $modelNode->parentNode->replaceChild($renamedNode, $modelNode);
}
```
# Proposal

I propose introducing a new `@NamingStrategy` annotation where we can specify the naming strategy for that property. 

``` php
class Object
{
    /** @NamingStrategy("XmlRootName") */
    private $property;
}
```

It brings up some interesting possibilities that can be delivered as bultin strategies, such:
- `DefaultNamingStrategy` - Default value, uses the default strategy to naming the property.
- `XmlRootNameNamingStrategy` - Uses, if available, the `@XmlRootName` of the type as the property name
- `ObjectNameNamingStrategy` - Uses, if applicable, the name of the class as the property name
- `DiscriminatorTypeNamingStrategy` - Uses, if applicable, the discriminator property value as the property name
# Changes required

At first glance, these seems to be the changes required to introduce this feature keeping BC compatibility:
- Add the `Context` as optional parameter in the `PropertyNamingStrategyInterface`

``` php
 public function translateName(PropertyMetadata $property, Context $context = null);
```
- Introduce a `Registry` to store all the naming strategies
- Change the serializer visitor to take in account possible property specific naming strategies

I'd appreciate some comments.

**Comment by goetas** [comment]
Implemented in  https://github.com/schmittjoh/serializer/pull/859 (note, due to performance reasons, this feature will not be available in the 2.0 release)
