### ISSUE TITLE
Allow @var instead of @Type when deserializing

### ISSUE THREAD

**Issue by ianfp** [schmittjoh/serializer#233]
This is a feature request; apologies if it's been made before. 

It would be convenient if the deserializer could fall back on the `@var` annotation if the `@Type` annotation is missing. I realize that `@Type` supports a more thorough syntax for deserializing complex data structures such as arrays and objects, but for simple types it would be nice to just use `@var`, which I'm usually using anyway.

Thanks!

**Comment by goetas** [comment]
`@var` and `@Type` have different proposes, not planning to implement this feature
