### ISSUE TITLE
Request Annotation for Array Data

### ISSUE THREAD

**Issue by jonmchan** [schmittjoh/serializer#234]
I am trying to build a Request class built by annotation to be used by FOSRest body converter.

The data to be deserialized looks like:
`[{"id":88,"name":"Poland","created_at":"2012-09-28T11:59:06+0000"},{"id":90,"name":"Great Britain","created_at":"2012-09-28T11:59:06+0000"}]`

Can I annotate a Request class for this? I tried:

```
/**
  * @Type("ArrayCollection<AcmeBundle\Entity\Country>")
  */
class CountryRequest {
}
```

And of course it wouldn't work. Is there a workaround for JMS Serializer to handle this type of data?

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/pull/728
