### ISSUE TITLE
Missing addData in XmlSerializerVisitor makes it impossible to add data in serializer.post_serialize event

### ISSUE THREAD

**Issue by benglass** [schmittjoh/serializer#235]
I might be missing something but since XmlSerializerVisitor doesnt extend GenericSerializerVisitor you cannot add data in the post_serialize event. When its JSON which extends GenericSerializer I can add data but not when its xml.

**Comment by goetas** [comment]
can be done in the  via 
```php
$visitor->getCurrentNode()->appendChild($yourNode);
```
