### ISSUE TITLE
Alphabetical accessor order doesn't respect SerializedName overrides

### ISSUE THREAD

**Issue by paulferrett** [schmittjoh/serializer#240]
When you override a property's name with a SerializedName config, the original name is still used when ordering the properties using the "alphabetical" accessor ordering. 

I'm happy to fix this issue if you'd like, and think it's an issue. If this is desired behaviour, or you think it could break existing code, I could implement it as a new ordering strategy?

**Comment by goetas** [comment]
implementing this feature will not be possible, especially for xml serialization.

please use custom access order
