### ISSUE TITLE
Serialization with groups return json object instead array

### ISSUE THREAD

**Issue by marc-j** [schmittjoh/serializer#267]
I have a problem with serialization groups :

$tasks is a array of task

```
$rep = $this->get('jms_serializer')->serialize($tasks, 'json');
-> $rep = '[{...},{...}]';
```

```
$rep = $this->get('jms_serializer')->serialize($tasks, 'json', 
SerializationContext::create()->setGroups(array('list')));
-> $rep = '{"0":{...},"1":{..}}'; ???? Bug ?
```

Thx

**Comment by robations** [comment]
Is this happening because of this?

http://haacked.com/archive/2009/06/25/json-hijacking.aspx/

Not that all json serialization is for creating web services.

**Comment by goetas** [comment]
solved in https://github.com/schmittjoh/serializer/pull/728
