### ISSUE TITLE
Bug Entity constructor not called

### ISSUE THREAD

**Issue by createproblem** [schmittjoh/serializer#270]
Hello, I've a very strange behavior with the serializer. I've an entity like this.

``` php
namespace Acme\DemoBundle\Entity;

class Foo
{
    private $id;

    private $created;

    private $name;

    public function __construct()
    {
        $this->created = new \DateTime();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getCreated()
    {
        return $this->created;
    }

    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    public function getName()
    {
        return $this->name;
    }
}
```

As you can see, I setup the create date by default in my `constructor`. The idea behind this is, I don't have to set the creation date by hand.

Here comes the test.

``` php
$json = '{"name":"test"}';
$foo = $serializer->deserialize($json, 'Acme\DemoBundle\Entity\Foo', 'json');

var_dump($foo->getCreated())
```

The output is `NULL` always. I added a `die()` in my `Foo::__construct()` but the `die()` will never be called. So in my opinion the serializer will ignore the constructor (how is this possible, looks very spooky), this is very painful because, on other Entities I've some `Doctrine\Common\Collections\Collection` initializations.  These initializations are also ignored. This behavior of the serializer will alway result in strange errors. Can someone explain **why** the Entity constructor is ignored and what can I do to execute the `constructor`

so long and thanks for the help.

**Comment by eschwartz** [comment]
For anyone wondering how to get around this:

```php
class Foo {
  protected $someInitializedProp;

  public function __construct() {
    $this->someInitializedProp = new SomeObj();
  }

  // ADD THIS
  public function __wakeup() {
    $this->__construct();
  }
}
```

Why does this work? `deserialize()` uses the built in `unserialize()` php method (as noted by @stof). The `__wakeup` magic method runs on `unserialize.` So there you go.

There's probably some way to extend the `\JMS\Serializer\Construction\ObjectConstructorInterface` to force calling the object constructor. This would be nice, as you could then keep this serialization-related logic out of your model. But that's more than I want to tackle right now.

**Comment by asgardia7** [comment]
Hello, I struggle with all method in Symfony now. It doesn't work. I deserialize with JMS Serializer of course and with `DoctrineObjectConstructor`. I initilize `ArrayCollection `in the constructor as stated in the doctrine best practices. But now I have problem on a `add `method inside the entity 'cause the `property `is null.

- `__wakeup `is not called ever
- `postLoad method `not called too

I temporarily force check if the `property `is null in `add `method and initialize it then.

Thanks
