### ISSUE TITLE
resources serialization

### ISSUE THREAD

**Issue by bazo** [schmittjoh/serializer#275]
By default, resource serialization is not supported.

so i want to write my own serialization handler for these resources, but i can't because the GraphNavigator has decided for me that it is not supported instead of asking the visitor if it support this kind of data.

is there any way how to override this? or do i have to get rid of all my blobs in doctrine?

because this behaviour is stupid...

**Comment by goetas** [comment]
This can be achieved with a virtual type and a custom handler.

```php
class Foo {
  /**
   * @var resource
   * @Type("MyImageResource")
   */
  provate $prop;
}
```

Defining a handler on `MyImageResource` type, you can serialize resources
