### ISSUE TITLE
Virtual property having type overriden by doctrine metadata

### ISSUE THREAD

**Issue by cblegare** [schmittjoh/serializer#276]
Say I have a doctrine entity

``` php
/**
 * @Entity
 * @Table(name="some_table")
 */
class SomeEntity {
    /** @Column(type="blob") */
    protected $someObject;

    /**
     * @return SomeType
     */
    public function getSomeObject()
    {
        // ... unserialize $this->someObject to $unserializedObject
        /** @var SomeType $unserializedObject */
        return $unserializedObject
    }
}
```

And the following Serializer configuration :

``` yaml
SomeEntity:
    access_type: public_method
    virtual_properties:
        getSomeObject:
            serialized_name: someObject
```

Note that no `type` is specified in the `virtual_properties` configuration for `getSomeObject`.  I expect the JMSSerializer to infer the type (`SomeType`) using the return value of `getSomeObject`.

But this is not happening.  Instead, even if it is a virtual property, it fetches the type from Doctrine metadata of the property having a related name (`$someObject`) and cast is as a `string` because `blob`is considered string by the DoctrineDriver.  See https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Metadata/Driver/DoctrineTypeDriver.php#L47.

The issue is : why should a doctrine type driver be used in case of a virtual property ?  I can work around this issue renaming the property to something funny :

``` php
class SomeEntity {
    /** 
     * This property has a funny name because JMSSerializer has a funny behavior
     *
     * @Column(type="blob")
     */
    protected $someObjectTotoFooBarFunnyNameHuh;

    /**
     * @return SomeType
     */
    public function getSomeObject()
    {
        // ... unserialize $this->someObjectTotoFooBarFunnyNameHuh to $unserializedObject
        /** @var SomeType $unserializedObject */
        return $unserializedObject
    }
}
```

Did I missed something or is it pure nonsense ?

**Comment by goetas** [comment]
solved with https://github.com/schmittjoh/serializer/commit/afe0e405a552bf2b2d419d787bcad9d84ad2f21b and will be released with v1.6
