### ISSUE TITLE
SimpleObjectProxy is not implement abstract methods of Proxy class

### ISSUE THREAD

**Issue by empire** [schmittjoh/serializer#287]
`Serializer` is dependent on  `doctrine/orm ~2.1`, `Doctrine\Common\Proxy` declare 6 abstract methods , but 2 of them is implemented in SimpleObjectProxy. 

Following error is occur when I test my application.

PHP Fatal error:  Class JMS\Serializer\Tests\Fixtures\SimpleObjectProxy contains 6 abstract methods and must therefore be declared abstract or implement the remaining methods (Doctrine\Common\Proxy\Proxy::__setInitialized, Doctrine\Common\Proxy\Proxy::__setInitializer, Doctrine\Common\Proxy\Proxy::__getInitializer, ...) in /.../vendor/jms/serializer/tests/JMS/Serializer/Tests/Fixtures/SimpleObjectProxy.php on line 41

**Comment by goetas** [comment]
solved with https://github.com/schmittjoh/serializer/commit/f9bb48b14e879ed188708308acc4a6f2ddffc494
