### ISSUE TITLE
Integer serialized as String using VirtualProperty

### ISSUE THREAD

**Issue by ClementGautier** [schmittjoh/serializer#289]
Hi,

``` php
    /**
     * @Serializer\VirtualProperty
     * @Serializer\SerializedName("mood")
     *
     * @return string
     */
    public function getSomeMethod()
    {
        return 42;
    }
```

is serialized as a string in my json output.

**Comment by bkosborne** [comment]
I have the same issue, trying to find a solution.

**Comment by goetas** [comment]
Closing, Sorry for the long feedback loop. This issue has been probably already solved, if the problem is still here, feel free to comment it and I will re-open the issue
