### ISSUE TITLE
serializer ignores properties added by traits

### ISSUE THREAD

**Issue by jrencz** [schmittjoh/serializer#313]
I'm using serialized with JMSSerializerBundle for symfony.
i'm configuring serializer using annotations.

I've been trying to use KNP DoctrineBehaviors on my models.
As it is suggested i used `use ORMBehaviors\Sluggable\SluggableMethods;`:

```
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

/**
 * Story
 *
 * @Serializer\ExclusionPolicy("none")
 */
class Story
{
    use ORMBehaviors\Sluggable\Sluggable;
}
```

it adds protected property `$slug`.
Despite using ExclusionPolicy('none') slug is not exposed.

There's a workaround:
trait Sluggable contains of 2 traits: SluggableMethods and SluggableProperties
One can use only SluggableMethods and define a property manually.

**Comment by goetas** [comment]
> Just installed new version of JMSSerializerBundle(dev-master 3a980e5) and it working fine with traits.
