### ISSUE TITLE
Serialization of empty object

### ISSUE THREAD

**Issue by lwojciechowski** [schmittjoh/serializer#323]
Could anyone explain why is this behavior expected?

```
public function testSerializeArrayWithEmptyObject()
{
    $this->assertEquals('{"0":{}}', $this->serialize(array(new \stdClass())));
}
```

Taken from [JsonSerializationTest.php line 202](https://github.com/schmittjoh/serializer/blob/master/tests/JMS/Serializer/Tests/Serializer/JsonSerializationTest.php#L202)

Thank you!

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/pull/730
