### ISSUE TITLE
HandlerCallback inconsistent behaviour

### ISSUE THREAD

**Issue by kustolovic** [schmittjoh/serializer#324]
When serializing an object, it is mandatory to set Root item for the handler to be effective, like in the docs, and the values returned are unused:

``` php
/** @HandlerCallback("json", direction = "serialization") */
public function serializeToJson(JsonSerializationVisitor $visitor)
{
    $visitor->setRoot(array($this->element => $this->value));
}
```

but when serializing an array of objects I have to return the value (because setting the root for each object is not a good idea):

``` php
/** @HandlerCallback("json", direction = "serialization") */
public function serializeToJson(JsonSerializationVisitor $visitor)
{
    return array($this->element => $this->value);
}
```

But I have a case where I need to do both: objects are sometimes alone or in an array:

``` php
/** @HandlerCallback("json", direction = "serialization") */
public function serializeToJson(JsonSerializationVisitor $visitor)
{
    if ($visitor->getRoot() === null){
        $visitor->setRoot(array($this->element => $this->value));
    }
    return array($this->element => $this->value);
}
```

I have to check getRoot because visitArray set it to array() before beginning
But that doesn't seem very secure and maybe it has drawbacks.

I think it will be safer and cleaner that the handler always take the return value. The setRoot should be set where the callback is called ?

**Comment by goetas** [comment]
Fixed in 2.0, now the visitors do not use an internal data representation, but the data are passed always back an forward to the graph navigator and serialized/deserialized with the new SerializationVisitorInterface::getResult($data) and DeserializationVisitorInterface::getResult($data) methods
