### ISSUE TITLE
Deserialize @XmlKeyValuePairs property?

### ISSUE THREAD

**Issue by jpetitcolas** [schmittjoh/serializer#325]
I got an issue when trying to unserialize the following simple entity:

``` php
class Bag
{
    /**
     * @Type("array<string,string>")
     * @XmlKeyValuePairs
     * @SerializedName("parameters")
     */
    private $parameters;

    public function getParameters()
    {
        return $this->parameters;
    }
}
```

If I serialize it, it works correctly and I get a XML like:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<result>
  <parameters>
    <hello><![CDATA[world]]></hello>
  </parameters>
</result>
```

Yet, if I try to unserialize the same XML, I got an empty array. Am I doing something wrong? Or is it not yet implemented? If so, is there any reason for that? :)

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/pull/868
