### ISSUE TITLE
Recursion groups, serializing properties in entities

### ISSUE THREAD

**Issue by YoruNoHikage** [schmittjoh/serializer#329]
As pointed out in this thread http://stackoverflow.com/questions/12746455/jmsserializerbundle-serialization-groups-in-entities-with-relations there's no way I know to make a difference between groups in the main entity and its relations.

The changes brought by the answer are perfect to do so, but the author didn't submit his code here.

How should I do, is there a better way to do what I want or to implement this changes ? Should we open a pull request ? (I forked this repo and applied the changes in it as a temporary solution).

**Comment by lopsided** [comment]
This would be a really useful addition to the bundle. Check out the proposed usage here by @andreasferber :
https://github.com/andreasferber/serializer/commit/60582e7d672a26db4b2a3cd9126f18d7d3ad9c8b

Unless there is a suitable workaround? How else can you serialize User->Friends(User) without pulling in all the same fields for all the friends as you have for the original user?

**Comment by lopsided** [comment]
The way I'm working around this at the moment is to create a new model class (not persisted) for `Friend` containing only the properties that I want to be serialized and then changing my `getFriends()` method to convert the returned `User` objects into an array of my new `Friend` objects. Feels a bit messy.

**Comment by adrienbrault** [comment]
Have you seen https://github.com/schmittjoh/serializer/pull/170 ?

**Comment by lopsided** [comment]
@adrienbrault No I hadn't! Thanks for the ref I'll keep an eye on that one too.

**Comment by YoruNoHikage** [comment]
@adrienbrault Wow, didn't see that. It seems to do the same thing. I think this can be closed.
