### ISSUE TITLE
Default conversion of camelCase to underscores is counterintuitive

### ISSUE THREAD

**Issue by mathiasverraes** [schmittjoh/serializer#33]
``` php

<?php

class Thing
{
    /**
     * @JMS\Type("integer")
     */
    private $fooBar;

    public function getFooBar()
    {
        return $this->fooBar;
    }
}

$json = '{"fooBar": 123}';
$deserializedThing = $serializer->deserialize($json, 'Thing', 'json');

assert(123, $deserializedThing->getFooBar()); 
// FAILS, we get null instead
// Adding @JMS\SerializedName("fooBar") resolves the issue
// Internally, the serializer converts fooBar to foo_bar unless instructed otherwise

```

This behavior is documented under @SerializedName http://jmsyst.com/libs/serializer/master/reference/annotations

However, this is so counterintuitive, that I think it is a bug. In the example above, there's absolutely no reason why the serializer should interfere with my naming, since both the json and the php code use camelcase.

**Comment by eddiejaoude** [comment]
Thanks @steffenbrem , that worked and is simple!

I am just wrapping your answer in a yaml code block for easier reading:

```yaml
jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
```

**Comment by Rawwood** [comment]
So to update:

```php
    return SerializerBuilder::create()
            ->setPropertyNamingStrategy(new SerializedNameAnnotationStrategy(new PassThroughNamingStrategy()))
            ->build();
```

Should now be:
```php
    return SerializerBuilder::create()
        ->setPropertyNamingStrategy(new SerializedNameAnnotationStrategy(new IdenticalPropertyNamingStrategy()))
    ->build();
```

**Comment by linuxninja39** [comment]
I strongly agree with the original issue. Regardless of the reason it came to be, it's awful. If the json field matches the object field then it should work.

While there is one line of documentation to hint at this, if you're unaware of the 'convention' then finding out why you're field isn't being populated is very difficult. At the very least there should be some kind of warning or verbose messages available. But really, the 'bug' should be corrected.

**Comment by Cethy** [comment]
@linuxninja39 where do you see anything in the documentation ? 
I was searching for this for 1 hour before losing hope, checking google and landing here.

> ... but perhaps a big fat warning in the docs would be nice :)

Is a **big fat** understatement.

**Comment by linuxninja39** [comment]
@Cethy The original post has a link to where it's documented. But I completely agree, this 'feature' is very poorly documented and should be considered a bug and fixed. Honestly it should be easy enough to make it search for the matching field AND a converted underscore so as not to break backward compatibility.

**Comment by Cethy** [comment]
@linuxninja39 Oh right, I read it too fast.
Your idea would not work if, for a reason or another, there is both matching field in the Object.  Additionally, it would add some unwanted complexity.

CamelCase to underscore or not is mainly a matter of experience (what languages you're used to), so I can understand it does not bother everyone, but it should be the first line in the doc, decorated by a `<marqee />` element, not buried in the reference/annotations page.

**Comment by luishdez** [comment]
same here I've spend 2 hours trying to see the problem :(

**Comment by vooj-tae** [comment]
camelCase can be set globally like this:

https://stackoverflow.com/questions/43529287/jms-serializer-how-to-use-camel-case-for-properties
