### ISSUE TITLE
VirtualProperty(s) are ignored with AccessorOrder

### ISSUE THREAD

**Issue by four43** [schmittjoh/serializer#349]
Specifying something like

@AccessorOrder("propA","virtualProp1","propB") 

at the top of a class will reproduce our of expected order data like:

{
"propA": "hello",
"propB":"world",
"virtualProp1":"nope"
}

Exclusion policy is set to all then properties are exposed via groups.

Just a small ordering issue we came across. Virtual properties are working great for us other than that. They are great for our use case.

Thanks,
-Seth

**Comment by patrickkempff** [comment]
I have the same problem. Are there any updates on this issue?

**Comment by goetas** [comment]
Sorry for the terribly long feedback loop. This issue has been already solved, if the problem still occurs, feel free to comment it here, and I will re-open it again.
