### ISSUE TITLE
Serializing object with empty array

### ISSUE THREAD

**Issue by pscheit** [schmittjoh/serializer#350]
Hi there,

``` php
$toSerialize = (object) array('expenses'=>array());

var_dump($toSerialize);

object(stdClass)#434 (1) {
  ["expenses"]=>
  array(0) {
  }
}
```

i expect the output:

``` json
{
 "expenses": []
}
```

i have the output:

``` json
{

}
```

how can I workaround this?

best regards
Philipp

**Comment by davidverholen** [comment]
same Problem here with xml.

When I serialize an empty array with XmlList and inline=false I would need an empty XmlElement, but I get no element at all.

Tried to setSerializeNull to true in the Context but that does not help

**Comment by davidverholen** [comment]
When I remove the last check https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/XmlSerializationVisitor.php#L310 isset($metadata->type['params'][1])
the XML Element is serialized as empty Element.

But, to be honest, I have no Idea what the check is exactly for. But maybe it would be possible to add a new Setting to the XmlList Annotation wether to serialize empty arrays or not?

**Comment by goetas** [comment]
solved in https://github.com/schmittjoh/serializer/pull/749
