### ISSUE TITLE
Object to array normalization

### ISSUE THREAD

**Issue by alsma** [schmittjoh/serializer#354]
Hello! 

Currently I'm working on unified API implementation for our project, and I'd like to use serializer for REST api serialization/deserialization.
But also we are looking to reuse metadata that required for JMSSerializer in our SOAP api implementation. I see that normalization/denormalization logic  are coupled together in visitors. Could you please assist how we can use serializer in order to do `array -> object` denormalization and vise versa ?

**Comment by davidwindell** [comment]
Duplicate of #20
