### ISSUE TITLE
GenericSerializationVisitor and shouldSerializeNull

### ISSUE THREAD

**Issue by FlashBlack** [schmittjoh/serializer#360]
Why he checks only string keys ? ( https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/GenericSerializationVisitor.php#L104)
```
if (null === $v && (!is_string($k) || !$context->shouldSerializeNull())) {
```
If I have array and **shouldSerializeNull == true**
```
array('test1' => null, 1 => null);
````
I got:
```
array('test1' => null);
````
In my opinion, it is not correct, or there are some but.. ?

**Comment by sgehrig** [comment]
Ping...

Same problem here: an array `[null, 1, null, 2]` will be serialized to something like `[1, 2]` which is not correct obviously.

**Comment by goetas** [comment]
will be fixed with https://github.com/schmittjoh/serializer/pull/626
