### ISSUE TITLE
Exclude annotation not preventing attempt to find public methods when using AccessType

### ISSUE THREAD

**Issue by andrewboerema** [schmittjoh/serializer#367]
I have discovered an issue where, if you set AccessType("public_method") on a class, Exclude annotations on that class's properties are ignored. Ex:
```
<?php
namespace Application\Fruits;

use JMS\Serializer\Annotation as JMS;

/**
 * Class Bananas
 *
 * @package Application\Fruits
 * @JMS\AccessType("public_method")
 */
class Bananas {
    /**
     * @var array
     * @JMS\Exclude
     */
    private static $acceptedStatuses = array(
        'Approved',
        'Pending',
    );
    ...
}
```

In this case, I get the error "There is neither a public getAcceptedStatuses method, nor a public isAcceptedStatuses method, nor a public hasAcceptedStatuses method in class Application\Model\RedOakPage. Please specify which public method should be used for retrieving the value of the property acceptedStatuses."

It would be my understanding that the more specific Exclude annotation on the property would override the class-level annotation of AccessType. If that isn't true, this isn't a defect, but it should be made clear on the docs for AccessType.

**Comment by Strate** [comment]
+1

**Comment by Nemo64** [comment]
still no fix?

**Comment by mattjanssen** [comment]
PR #397

**Comment by detook** [comment]
+1

**Comment by goetas** [comment]
PR has been merged
