### ISSUE TITLE
serialized_name for discriminator

### ISSUE THREAD

**Issue by gepo** [schmittjoh/serializer#372]
I was need change serialized name of discriminator, because it's too long.
I implement it for Yaml driver: 
https://github.com/gepo/serializer/commit/a5cc28e87f3ec10d47b008ff410bc74ab2b046a2

It's obvious and helpful feature, is it need for others? It should be implemented for other drivers before pull request.

**Comment by goetas** [comment]
`@Discriminator(field="foo")`
