### ISSUE TITLE
Add support for array format

### ISSUE THREAD

**Issue by sandermarechal** [schmittjoh/serializer#374]
Please add an additional 'array' format that serializes/deserializes PHP arrays. The implementation is trivial (it's basically just the generic visitor) but the format should be added to the default handlers.

**Comment by DanielBadura** [comment]
:+1:

**Comment by davidwindell** [comment]
See #20, no progress yet from what I can see unfortunately. The fork does work if you need it.

**Comment by renan** [comment]
:+1:

**Comment by goetas** [comment]
done in https://github.com/schmittjoh/serializer/issues/435
