### ISSUE TITLE
Serializer working with parent class

### ISSUE THREAD

**Issue by kessiler** [schmittjoh/serializer#376]
I have an application that uses doctrine 2 (ORM), and use an override in datetimes. (Doctrine\DBAL\Types\Type::overrideType)
In this situation the handlers not serialize the object type, even though the son of datetime.

See the example:

Class A -> ORM\DateTimeType extends \DateTime
Object A -> instance of DateTimeType

To serialize, the return should be a string of type date
Example:  serialize($A); -----> '2014-12-26 16:46:10'

But is an empty object..( {} )

**Comment by goetas** [comment]
this is a more general problem and sub-problem of https://github.com/schmittjoh/serializer/pull/698
