### ISSUE TITLE
PHP < 5.3.9 BC break

### ISSUE THREAD

**Issue by boekkooi** [schmittjoh/serializer#383]
It looks like the composer.json has a invalid php restriction since commit cd90daaa170bf4e1724b00ba31c0c1e3900af856.

This commit introduced the usage of the third `is_subclass_of` parameter (https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/GraphNavigator.php#L152) the problem is that this parameter was added in PHP version 5.3.9.

http://php.net/is_subclass_ofp version 5.3.9

**Comment by lukaszjurys** [comment]
+1

**Comment by boekkooi** [comment]
Closing because PHP has updated to require 5.4.0
