### ISSUE TITLE
Custom Type Handler for String Values

### ISSUE THREAD

**Issue by eschwartz** [schmittjoh/serializer#384]
I would like to create a custom type handler for serializing/deserializing string values.

```php
class Guy {
  /** JMS\Type("PhoneNumber") */
  public $phoneNumber;
}


$guy = $serializer->deserialize('{ "phoneNumber": "(123) 555-1234 ext789"}', 'Guy');
$guy->phoneNumber; // "1235551234x789"
$serializer->serialize($guy, 'json');  // { "phoneNumber": "(123) 555-1234 ext789"}
```

I've tried creating a `PhoneNumberHandler`, but it looks like you cannot create custom type handlers for string values:

```
LogicException: Expected object but got string. Do you have the wrong @Type mapping or could this be a Doctrine many-to-many relation?
```

The problem is in the `GraphNavigator::accept` method:

```php
default:
                if ($context instanceof SerializationContext) {
                    if (null !== $data) {
                        if ($context->isVisiting($data)) {
                            return null;
                        }
                        $context->startVisiting($data);
                    }
                }
```

Which calls `SerializationContext::isVisiting`, which enforces that the value is an object.

Could you help me understand what's going on here? Why does the SerializationContext have this requirement? What is the `GraphNavigator` doing when it makes the `isVisiting` check? Is there any other way to go about this? 

I know I could use accessors in my models, but I hate to have to duplicate the logic everywhere, and I'd like to keep view logic out of my model logic.

Similar issues #202, #180

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/pull/610
