### ISSUE TITLE
Access level propose for Handler/DateHandler.php

### ISSUE THREAD

**Issue by iamake** [schmittjoh/serializer#386]
== File: serializer/src/JMS/Serializer/Handler/DateHandler.php ==

Why the following variables and functions in the above file has 'private' access level ?

```
private $defaultFormat;
private $defaultTimezone;
private $xmlCData;

private function parseDateTime($data, array $type)
private function getFormat(array $type)
```

I see it's better to have 'protected' access level so others can overload those functions.

For my use case, I want the parsed DateTime to have TimeZone set to my application timezone. If those functions have 'protected' access, I can only overload the parseDateTime to get this done.

With 'private' access level, I have to rewrite a lot of redundancy code. :(

Thanks !

**Comment by goetas** [comment]
see https://github.com/schmittjoh/serializer/pull/126#issuecomment-291128451
