### ISSUE TITLE
API stable 1.0.0 release in sight?

### ISSUE THREAD

**Issue by patkar** [schmittjoh/serializer#395]
Looking at the packagist stastics and an overall of over 2.1 million downloads, is there a chance to get a API stable 1.0.0 release and all following releases according to semver.org?

**Comment by schmittjoh** [comment]
You can follow the 0.x releases just as if they were 1.x.

**Comment by patkar** [comment]
You mean I can require ~0.16 and there will be sure no BC breaks in minor releases?

**Comment by schmittjoh** [comment]
Yes, exactly. The API is super stable, (and used by a lot of people); we will not break any BC in these releases anymore. 

If we need to break stuff, then in the next major version, i.e. 1.0.

**Comment by patkar** [comment]
Ok. Thank you for the info. Glad to hear this. :+1:
