### ISSUE TITLE
Add class properties inheritance for extending classes (e.g. XmlRoot)

### ISSUE THREAD

**Issue by TiS** [schmittjoh/serializer#396]
Example:

``` php

use JMS\Serializer\Annotation\XmlRoot

/**
 * @XmlRoot("A")
 */
class A {
}

class B extends A {
}
```

Currently, the XmlRoot for class B will be the default one, not the root defined in base class. I think, that the logical behavior will be to inherit root from base class. Current behavior forces to define xml root and xml schema in each and every class.

This causes problems, especially when used along with JMSSerializerBundle, which parses all class annotations by default, even if annotations are not defined.

[Either this or, add option in bundle to exclude namespaces from annotation parsing (e.g when I want all of metadata definitions in XML). If this solution is preferred, then this issue can be moved to bundle repository. But this does not cover inheritance when I want to use annotations.]

**Comment by rrajkomar** [comment]
I agree with the fact that XmlRoot should be retrieved from parent classes if defined there when there's no XmlRoot definition on the child class.

**Comment by rrajkomar** [comment]
@schmittjoh your input on this feature request please ?

**Comment by goetas** [comment]
Currently all the metadata are always per-class and they are never inherited from the parent.

**Comment by goetas** [comment]
saw only not this, sorry if it took so long for the feedback

**Comment by rrajkomar** [comment]
I know that currently it works that way, that's precisely the issue.
Is there no way to add this feature : if a property has no serialization annotation defined but there's a parent class, look for the annotations on the parent class...?
