### ISSUE TITLE
Add symfony expression in exclusions/expositions

### ISSUE THREAD

**Issue by nicodmf** [schmittjoh/serializer#406]
I'm not sure this isn't implemented yet, but i see many use case, specially which control the parent group when depth is more than one.

By example :

```
@ExposeIf(group == 'list' and depth <= 2)
```

or

```
@ExposeIf(group in {'list'} and depth <= 2 and 'User' not in parents() )
```

**Comment by goetas** [comment]
implemented with https://github.com/schmittjoh/serializer/pull/673

**Comment by nicodmf** [comment]
Thanks :)
