### ISSUE TITLE
Serialize doctrine entities load linked entities even if the max depth should stop this behavior

### ISSUE THREAD

**Issue by nicodmf** [schmittjoh/serializer#407]
When serialize doctrine entity, if exclusion is made :
- by max_depth : the linked entities are loaded, the field appears but it is empty if array and doesn't appear if single
- by groups : the linked entities aren't loaded and the field doesn't appear

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/pull/743/commits/94c319db88883757a14ac267115272be030aef28  and https://github.com/schmittjoh/serializer/commit/136fb0d6da43bc255aa8658414a724acb889f3c1
