### ISSUE TITLE
Question: update context on serializer.pre_serialize

### ISSUE THREAD

**Issue by johndodev** [schmittjoh/serializer#414]
Hello,

we would like to define serialization groups depending on user roles in _security.context_ to all our serializations (or almost). The idea was to do it in the _serializer.pre_serialize_ event, but it say something like _context immutable, already inited_. 

So, we are about to surcharge _handleView_ in a controller, it is the right way to do it ? Or is it a way to do it in an event ?

Thanks

**Comment by goetas** [comment]
context is immutable. if you need changes to it before starting the serialization process
