### ISSUE TITLE
new stable release 

### ISSUE THREAD

**Issue by eventhorizonpl** [schmittjoh/serializer#416]
Hi,

Is it possible to get new stable release in the near future?

Best regards,
Michal

**Comment by brettminnie** [comment]
:+1: There are a lot of outstanding pull requests that add fixes and functionality as well.

**Comment by davidwindell** [comment]
@schmittjoh are you open to bringing on maintainers to help speed up releases?

**Comment by bassrock** [comment]
:+1:

**Comment by crazycodr** [comment]
Are these related?

https://github.com/schmittjoh/serializer/issues/427

**Comment by davidwindell** [comment]
@crazycodr I'm not sure how they relate?

**Comment by crazycodr** [comment]
I misunderstood the question, i thought he meant a release with passing tests, nvm

**Comment by xelan** [comment]
:+1:

**Comment by maennchen** [comment]
@schmittjoh: Are you still maintaining this project?
Would it be an idea to create a GitHub organization with selected members to maintain the project?

**Comment by fulldecent** [comment]
I can guarantee that PRs are accepted faster and releases come more often when build tests pass.

Here is a problem
https://travis-ci.org/schmittjoh/serializer/builds/88068042

**Comment by goetas** [comment]
done this summer
