### ISSUE TITLE
Use different accessor for each group

### ISSUE THREAD

**Issue by mangelsnc** [schmittjoh/serializer#420]
Taken for example this piece of code:
```
/**
 * @ORM\Column(type="string", length=255, nullable=true)
 * @Serializer\Accessor(getter="getAbsolutePath")
 * @Serializer\Groups({"minimal", "details", "search-result"})
 */
 protected $path;
```
I pretend to use an  accessor for _minimal_ and _details_ groups (for example getRelativePath) and a different one for _search-result_ (getAbsolutePath).
As far as I know, there's no way to do this, but I think it could be a very interesting feature.

Exists a simple way to do this? In case of no, what do you think about add this feature?

**Comment by sebastianhoitz** [comment]
:+1: we need exactly this feature in one of your projects, too.

**Comment by vcourtin** [comment]
Any new about this feature ?

**Comment by goetas** [comment]
actually this can be done using virtual properties on specific accessor methods
