### ISSUE TITLE
Possible mismatch of xml-attribute-map and $pMetadata->xmlAttribute in XmlDriver.php

### ISSUE THREAD

**Issue by sonyatvwebteam** [schmittjoh/serializer#422]
I was looking through the source of the library trying to understand something about how it works, and I happened to notice this on line 210 (vendor/jms/serializer/src/JMS/Serializer/Metadata/Driver/XmlDriver.php:210):

$pMetadata->xmlAttribute = 'true' === (string) $pElem->attributes()->{'xml-attribute-map'};

Shouldn't that read instead as:

$pMetadata->xmlAttributeMap = 'true' === (string) $pElem->attributes()->{'xml-attribute-map'};

If I've misunderstood the code, please forgive me, but comparing it to the YmlDriver.php, it seems like it might be unintentional.

Thanks.

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/pull/595
