### ISSUE TITLE
Empty Objects get serialized as "array()"

### ISSUE THREAD

**Issue by wjaspers** [schmittjoh/serializer#43]
For reference: https://github.com/schmittjoh/JMSSerializerBundle/issues/271

Again, I am not sure which repository is most appropriate to open this issue against.

**Comment by kg-itembase** [comment]
It seems this issue was fixed only for main (root) objects that are serialized. But it still appears for child objects in main object. Is it possible to fix?

**Comment by hanneskaeufler** [comment]
Yeah I still see the issue for child objects.

**Comment by clemp6r** [comment]
Please reopen issue

**Comment by fracz** [comment]
+1

**Comment by m1rm** [comment]
so, I encountered the issue today. Still not fixed?
