### ISSUE TITLE
Deprecated usage of ValidatorInterface

### ISSUE THREAD

**Issue by Soullivaneuh** [schmittjoh/serializer#438]
Concerned file: https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/EventDispatcher/Subscriber/SymfonyValidatorSubscriber.php#L30

Related notice:

``` php
 * @deprecated since version 2.5, to be removed in 3.0.
 *             Use {@link \Symfony\Component\Validator\ValidatorInterface} instead.
```

As this class is passed on the constructor, don't really know how to manage it.

Maybe create a legacy class? Where this class is used?

Regards

**Comment by schmittjoh** [comment]
Not sure this message makes sense, we are already using this interface?

**Comment by Soullivaneuh** [comment]
Seems yes. See your [SymfonyValidatorSubscriber](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/EventDispatcher/Subscriber/SymfonyValidatorSubscriber.php#L30) class. :+1:

**Comment by stof** [comment]
Well, given the API used in this subscriber, it is very easy to support both the old and the new validator interfaces: just accept both in the constructor. The API used in the code is common to both versions (the old API has more optional args in its ``validate()`` method, but the subscriber does not use them)

**Comment by Soullivaneuh** [comment]
@stof Yes, but it use groups arguments that is not the second parameter on the new interface. Have to check that.

**Comment by stof** [comment]
Ah indeed. I missed the fact that the second argument was used. It is the third argument in the new API.
This can easily be checked with an instanceof check to switch between API.

**Comment by Soullivaneuh** [comment]
@stof yes. I did it on #491.

**Comment by goetas** [comment]
solved in https://github.com/schmittjoh/serializer/pull/682
