### ISSUE TITLE
PHP Fatal error: Using $this when not in object context in JMS/Serializer/Serializer.php on line 99

### ISSUE THREAD

**Issue by simonhayre** [schmittjoh/serializer#441]
PHP Fatal error: Using $this when not in object context in JMS/Serializer/Serializer.php on line 99

**Comment by fsaez-ix** [comment]
+1

**Comment by dbojdo** [comment]
Same problem. It's because PHP < 5.4 doesn't support $this inside the closures. The solution is to bump the minimum PHP version in the composer.json up to 5.4. What do you think guys?

**Comment by schmittjoh** [comment]
Sounds good. We should have enough releases that work with 5.3

**Comment by takeit** [comment]
:+1:

**Comment by Kaz-** [comment]
@schmittjoh Hello, i'm forced to work with PHP 5.3.28 in my professional environment, which JMSSerializerBundle should I use to avoid this problem ?

**Comment by GaryRogers** [comment]
@schmittjoh Ditto What @Kaz- said, RHEL 6 offers PHP 5.3, and we won't be upgrading to anything newer for a while.

**Comment by goetas** [comment]
Solved in 1.0
