### ISSUE TITLE
Multiple types for property?

### ISSUE THREAD

**Issue by miraage** [schmittjoh/serializer#445]
My propery my be empty string or array. How do I annotate with `@Type`?

**Comment by natebrunette** [comment]
I'd also like to know how to handle a property that can be more than one type.  I realized that if you're not serializing nulls, you can set the same `@SerializedName` on  multiple properties, but it blows up on deserialization.

**Comment by natebrunette** [comment]
This can actually be handled by setting up a listener on pre serialize/deserialize.

**Comment by goetas** [comment]
> This can actually be handled by setting up a listener on pre serialize/deserialize.
