### ISSUE TITLE
Only serialize id of child object

### ISSUE THREAD

**Issue by hanneskaeufler** [schmittjoh/serializer#448]
Hi, I´m trying to solve the age old question of how we serialize nested objects.

Say 

``` php
class Parent {
    public $id = 1;
    public $child;

    public function __construct() { $this->child = new Child(); }
}

class Child {
    public $id = 4;
}
```

By "default" the representation would look like

``` json
{ "id": 1, "child": { "id": 4 } }
```

What I want to achieve for all of our serialized representations is to make the output look like:

``` json
{ "id": 1, "child": 4 }
```

I currently find no way of configuring the serializer in such a way, furthermore I´m having trouble (sanely) extending it.

While I can override the `JsonSerializationVisitor` class, I cannot change the underlying data in `visitProperty` as the `$data` property is private. I also cannot add my own annotation (in yml), as `PropertyMetadata` is hardcoded in `YamlDriver`. I can override `getRoot` to hack this behaviour in, but thats just really messy.

Did anybody achieve similar behaviour? (Adding `getChildId` methods on all parents is not really an option imho. Property path getters would be, but the issue seems dead.)

Thanks

**Comment by yellow1912** [comment]
I think you can do it this way: You can use the SerializerListener then put then modify the data as you wish. Another option is that you can expose "child" via virtual property instead, then use a custom method in your Parent model to return the id only.

**Comment by hanneskaeufler** [comment]
Thanks for your input. I´d rather not add hundreds of `getChildId` methods to the models to be able to use virtual properties. I would really like to use the models as they are.

I don´t think you can register a "catch all" Serializer Listener, can you? Adding a Listener for each one of the models seems cumbersome and error prone as well to me.

For now I have privately forked the serializer and added an `only_id` option. However, forking has its own drawbacks so a solution in the upstream library would be cool :)

**Comment by cdaguerre** [comment]
+1 for an implementation of this feature, @schmittjoh Any reason this has never made it into the code? (besides deserialization)

**Comment by fesor** [comment]
Same problem here, but i want to deserialize plain id into object:

```
{ "name": "test", "reference_id": 1}
```

instead of

```
{ "name": "test", "reference_id": {"id":1 }}
```

I can do this via listeners but this is tricky and i thing this is not so good from maintainability point of view.

**Comment by Arkemlar** [comment]
This stupid poblem is one of set of reasons why I decided to make DTO API and throw away this bundle in my own project. However in another project there is no way to do the same thing. Now I have to add another get*ID() method, what a shame!
Thinkging about this really stupid problem I wondering - why nobody made PR since they solved it? And generally speaking, I think JMS serialiser bundle needs to meet and get friendly with PropertyPath, that could solve a tonn of similar problems.

**Comment by Arkemlar** [comment]
Well, just noticed that 24 days ago we got in master this awesome thing https://github.com/schmittjoh/serializer/pull/708

**Comment by goetas** [comment]
Yes #708 solves it well

**Comment by JustBlackBird** [comment]
@goetas Could you please provide an example of how to serialize only ID of child entity(based on #708)?
