### ISSUE TITLE
[feature] Handler failback

### ISSUE THREAD

**Issue by ivan1986** [schmittjoh/serializer#450]
Add way to failback to default processing from handler
https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/GraphNavigator.php#L213

for example for

serializeJson(...)
{
    if ($context->[is custom view])
         return [....]
    else
         return [using default visitor]
}

i think easy way is exception

**Comment by ivan1986** [comment]
#446

**Comment by goetas** [comment]
duplicate of #446
