### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by csimplestring** [schmittjoh/serializer#455]
I want to use [Sourcegraph](https://sourcegraph.com) for serializer code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/schmittjoh/serializer. (It should only take 30 seconds.)

Thank you!

**Comment by goetas** [comment]
sorry for the long feedback. probably this is not a need anymore
