### ISSUE TITLE
Serialized name based on the format

### ISSUE THREAD

**Issue by CentaurWarchief** [schmittjoh/serializer#456]
How can I change the property serialized name based on the serialization format? I would like to have `property-name` for **XML** format, and `property_name` for **JSON**. Is it possible?

**Comment by goetas** [comment]
Closing, Sorry for the long feedback loop
You can use a custom naming strategy defined differently depending on the serialization format.

(if you are using the symfony bundle, this is not supported yet)

**Comment by goetas** [comment]
not possible for now. in 2.0 the property name is cached as metadata attribute. if you need so, you have to use two different serializer instances using different metadata files (no annotations)
