### ISSUE TITLE
DateHandler Timezone ignored on deserialization

### ISSUE THREAD

**Issue by jimmypoms** [schmittjoh/serializer#457]
Not really sure this is a bug, but think it is not intended behaviour:

Inside the DateHandler the date string gets parsed as follows:

``` php
        $datetime = \DateTime::createFromFormat($format, (string) $data, $timezone);
```

However, if the string is a UNIX timestamp or specifies a timezone, the $timezone parameter is ignored as stated in the documentation of [DateTime::createFromFormat](http://php.net/manual/en/datetime.createfromformat.php).

```
Note:
The timezone parameter and the current timezone are ignored when the time parameter either contains a UNIX timestamp (e.g. 946684800) or specifies a timezone (e.g. 2010-01-28T15:00:00+02:00).
```

Calling format on the deserialized date object will give you the passed date string instead of converting the time to the configured timezone.

Explicitly setting the timezone as shown after will fix this issue:

``` php
        $datetime = \DateTime::createFromFormat($format, (string) $data);
        $datetime->setTimeZone($timezone);
```

**Comment by goetas** [comment]
> However, if the string is a UNIX timestamp or specifies a timezone, the $timezone parameter is ignored as stated in the documentation of DateTime::createFromFormat.

there must be a reason if the timezone is ignored in the PHP's official `DateTime::createFromFormat` function

**Comment by goetas** [comment]
fixed by https://github.com/schmittjoh/serializer/pull/835
