### ISSUE TITLE
The sub-class "Proxy-Class" is not listed in the discriminator of the base class "DiscriminatorClass"

### ISSUE THREAD

**Issue by digitalkaoz** [schmittjoh/serializer#459]
I have a strange Problem here,

im getting this Error on serialization:

```
[LogicException]
The sub-class "Dl\DomainModel\Proxies\__CG__\Dl\Component\DomainModel\Product\Attribute\EntityAttribute" is not listed in the discriminator of the base class "Dl\Component\DomainModel\Product\Attribute\AbstractAttribute".
```

it happens during serialization:

```
 [file]: string (57) "/www/vendor/jms/metadata/src/Metadata/MetadataFactory.php"
 [line]: int 150
 [function]: string (5) "merge"
 [class]: string (37) "JMS\Serializer\Metadata\ClassMetadata"
 [type]: string (2) "->"
 [args]: array (1)
  · [0]: object(JMS\Serializer\Metadata\ClassMetadata)

 [1]: array (6)
 [file]: string (57) "/www/vendor/jms/metadata/src/Metadata/MetadataFactory.php"
 [line]: int 105
 [function]: string (16) "addClassMetadata"
 [class]: string (24) "Metadata\MetadataFactory"
 [type]: string (2) "->"
 [args]: array (2)
  · [0]: object(JMS\Serializer\Metadata\ClassMetadata)
  · [1]: object(JMS\Serializer\Metadata\ClassMetadata)

 [2]: array (6)
 [file]: string (64) "/www/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php"
 [line]: int 188
 [function]: string (19) "getMetadataForClass"
 [class]: string (24) "Metadata\MetadataFactory"
 [type]: string (2) "->"
 [args]: array (1)
  · [0]: string (88) "Dl\DomainModel\Proxies\__CG__\Dl\Component\DomainModel\Product\Attribute\EntityAttribute"

 [3]: array (6)
 [file]: string (77) "/www/vendor/jms/serializer/src/JMS/Serializer/GenericSerializationVisitor.php"
 [line]: int 140
 [function]: string (6) "accept"
 [class]: string (29) "JMS\Serializer\GraphNavigator"
 [type]: string (2) "->"
 [args]: array (3)
  · [0]: object(Dl\DomainModel\Proxies\__CG__\Dl\Component\DomainModel\Product\Attribute\EntityAttribute)
  · [1]: array (2)
  ·  · [name]: string (88) "Dl\DomainModel\Proxies\__CG__\Dl\Component\DomainModel\Product\Attribute\EntityAttribute"
  ·  · [params]: array (0)

  · [2]: object(JMS\Serializer\SerializationContext)

 [4]: array (6)
 [file]: string (64) "/www/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php"
 [line]: int 235
 [function]: string (13) "visitProperty"
 [class]: string (42) "JMS\Serializer\GenericSerializationVisitor"
 [type]: string (2) "->"
 [args]: array (3)
  · [0]: object(JMS\Serializer\Metadata\PropertyMetadata)
  · [1]: object(Dl\Component\DomainModel\Partner\UnmatchedValue)
  · [2]: object(JMS\Serializer\SerializationContext)

 [5]: array (6)
 [file]: string (77) "/www/vendor/jms/serializer/src/JMS/Serializer/GenericSerializationVisitor.php"
 [line]: int 102
 [function]: string (6) "accept"
 [class]: string (29) "JMS\Serializer\GraphNavigator"
 [type]: string (2) "->"
 [args]: array (3)
  · [0]: object(Dl\Component\DomainModel\Partner\UnmatchedValue)
  · [1]: array (2)
  ·  · [name]: string (47) "Dl\Component\DomainModel\Partner\UnmatchedValue"
  ·  · [params]: array (0)

  · [2]: object(JMS\Serializer\SerializationContext)

 [6]: array (6)
 [file]: string (74) "/www/vendor/jms/serializer/src/JMS/Serializer/JsonSerializationVisitor.php"
 [line]: int 55
 [function]: string (10) "visitArray"
 [class]: string (42) "JMS\Serializer\GenericSerializationVisitor"
 [type]: string (2) "->"
 [args]: array (3)
  · [0]: object(Dl\Component\Helpers\DataType\ArrayCollection)
  · [1]: array (2)
  ·  · [name]: string (5) "array"
  ·  · [params]: array (1)
  ·  ·  · [0]: array (2)
  ·  ·  ·  · [name]: string (47) "Dl\Component\DomainModel\Partner\UnmatchedValue"
  ·  ·  ·  · [params]: array (0)

  · [2]: object(JMS\Serializer\SerializationContext)

 [7]: array (6)
 [file]: string (64) "/www/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php"
 [line]: int 129
 [function]: string (10) "visitArray"
 [class]: string (39) "JMS\Serializer\JsonSerializationVisitor"
 [type]: string (2) "->"
 [args]: array (3)
  · [0]: object(Dl\Component\Helpers\DataType\ArrayCollection)
  · [1]: array (2)
  ·  · [name]: string (5) "array"
  ·  · [params]: array (1)
  ·  ·  · [0]: array (2)
  ·  ·  ·  · [name]: string (47) "Dl\Component\DomainModel\Partner\UnmatchedValue"
  ·  ·  ·  · [params]: array (0)

  · [2]: object(JMS\Serializer\SerializationContext)

 [8]: array (6)
 [file]: string (77) "/www/vendor/jms/serializer/src/JMS/Serializer/GenericSerializationVisitor.php"
 [line]: int 140
 [function]: string (6) "accept"
 [class]: string (29) "JMS\Serializer\GraphNavigator"
 [type]: string (2) "->"
 [args]: array (3)
  · [0]: object(Dl\Component\Helpers\DataType\ArrayCollection)
  · [1]: array (2)
  ·  · [name]: string (5) "array"
  ·  · [params]: array (1)
  ·  ·  · [0]: array (2)
  ·  ·  ·  · [name]: string (47) "Dl\Component\DomainModel\Partner\UnmatchedValue"
  ·  ·  ·  · [params]: array (0)

  · [2]: object(JMS\Serializer\SerializationContext)

 [9]: array (6)
 [file]: string (64) "/www/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php"
 [line]: int 235
 [function]: string (13) "visitProperty"
 [class]: string (42) "JMS\Serializer\GenericSerializationVisitor"
 [type]: string (2) "->"
 [args]: array (3)
  · [0]: object(JMS\Serializer\Metadata\PropertyMetadata)
  · [1]: object(Dl\Import\Task\PersistTask)
  · [2]: object(JMS\Serializer\SerializationContext)

 [10]: array (6)
 [file]: string (60) "/www/vendor/jms/serializer/src/JMS/Serializer/Serializer.php"
 [line]: int 176
 [function]: string (6) "accept"
 [class]: string (29) "JMS\Serializer\GraphNavigator"
 [type]: string (2) "->"
 [args]: array (3)
  · [0]: object(Dl\Import\Task\PersistTask)
  · [1]: array (2)
  ·  · [name]: string (26) "Dl\Import\Task\PersistTask"
  ·  · [params]: array (0)

  · [2]: object(JMS\Serializer\SerializationContext)

 [11]: array (6)
 [file]: string (60) "/www/vendor/jms/serializer/src/JMS/Serializer/Serializer.php"
 [line]: int 82
 [function]: string (5) "visit"
 [class]: string (25) "JMS\Serializer\Serializer"
 [type]: string (2) "->"
 [args]: array (4)
  · [0]: object(JMS\Serializer\JsonSerializationVisitor)
  · [1]: object(JMS\Serializer\SerializationContext)
  · [2]: object(Dl\Import\Task\PersistTask)
  · [3]: string (4) "json"

 [12]: array (2)
 [function]: string (44) "Closure$JMS\Serializer\Serializer::serialize"
 [args]: array (1)
  · [0]: object(JMS\Serializer\JsonSerializationVisitor)

 [13]: array (4)
 [file]: string (54) "/www/vendor/phpoption/phpoption/src/PhpOption/Some.php"
 [line]: int 89
 [function]: string (14) "call_user_func"
 [args]: array (2)
  · [0]: object(Closure$JMS\Serializer\Serializer::serialize;1748757503)
  · [1]: object(JMS\Serializer\JsonSerializationVisitor)

 [14]: array (6)
 [file]: string (60) "/www/vendor/jms/serializer/src/JMS/Serializer/Serializer.php"
 [line]: int 85
 [function]: string (3) "map"
 [class]: string (14) "PhpOption\Some"
 [type]: string (2) "->"
 [args]: array (1)
  · [0]: object(Closure$JMS\Serializer\Serializer::serialize;1748757503)

```

anyone have a clue why this occurs?

**Comment by digitalkaoz** [comment]
im using the type inference from doctrine `DoctrineTypeDriver`

**Comment by digitalkaoz** [comment]
mh somewhat fixed it with 

```php
class MetadataFactory extends \Metadata\MetadataFactory
{
    public function getMetadataForClass($className)
    {
        $className = substr($className, strpos($className, '__\\')+3);

        return parent::getMetadataForClass($className);
    }
}
```

and injecting this `MetadataFactory` into the Serializer. But that doesnt feel right...it seems the MetadataFactory needs to be aware of Doctrine-Proxies (and remove the Proxy Prefix so it fetches the Metadata for the Underlying Object instead of the Proxy)

@schmittjoh can you have a look at it?

**Comment by vdzpeter** [comment]
any progress on this issue ? how can i inject the MetadataFactory into the Serializer ?

**Comment by digitalkaoz** [comment]
with reflections ;)

**Comment by Nemo64** [comment]
I have the same problem. How can this even happen? Because i'm guessing that this is a doctrine error.

**Comment by vdzpeter** [comment]
did u solve the problem ?

**Comment by vdzpeter** [comment]
@schmittjoh do you have any advice maybe?

**Comment by Nemo64** [comment]
Not really. The project I was working on had an old version of the serializer.
```
"jms/metadata": "dev-bugfix-doctrine-proxy-class as 1.1",
"jms/serializer": "0.15.0",
"jms/serializer-bundle": "0.13.0",
```
There I had a problem with relations. The serializer did serialize the proxy class. I updated the serializer which resolved the issue with relations, but introduced the current issue we are having here.

My temporary solution was to downgrade the serializer again and explicitly tell which classes the relations would have using the `@Type` annotation. This obviously doesn't work if you have relations to a base class of an inheritance.

**Comment by arnauddeklerk** [comment]
I upgraded to 1.7, and unfortunately I still have this issue. My class hierarchy:

AbstractBaseClass -> Organisatie -> Verzekeraar

Serialization of proxies of the Verzekeraar still results in:

The sub-class "Proxies\__CG__\AppBundle\Entity\Verzekeraar" is not listed in the discriminator of the base class "AppBundle\Entity\Organisatie".

Anyone also still experiencing this?

**Comment by goetas** [comment]
will verify

**Comment by goetas** [comment]
can you share the code of your AbstractBaseClass.  Organisatie, Verzekeraar classes? is necessary to know exactly which classes are abstract and which classes are concrete, and on which class you have the discriminator map...

**Comment by arnauddeklerk** [comment]
OK, herewith my classes. AbstractEntityClass is abstract, Organisatie is concrete, there is the discriminator map, and Verzekeraar is concrete.


[Entities.zip](https://github.com/schmittjoh/serializer/files/995492/Entities.zip)

**Comment by goetas** [comment]
There is no JMS discriminator map in your files, only the doctrine discriminator map... you need both.

You need  [this](http://jmsyst.com/libs/serializer/master/reference/annotations#discriminator)

**Comment by arnauddeklerk** [comment]
I tried it, if I add a JMS discriminator map, it doesn't make a difference. Besides, according to the documentation, the JMS discriminator map is only for deserialization, which I'm not doing. 

The problem is in this code (lines 185-192 of JMS/Serializer/Metadata/ClassMetadata.phpClassMetaData.php):

if ($this->discriminatorMap && ! $this->reflection->isAbstract()) {
            if (false === $typeValue = array_search($this->name, $this->discriminatorMap, true)) {
                throw new \LogicException(sprintf(
                    'The sub-class "%s" is not listed in the discriminator of the base class "%s".',
                    $this->name,
                    $this->discriminatorBaseClass
                ));
            }

$this->discriminatorMap refers to the Doctrine map, and whenever a proxy class is serialized, derived from a class with a Doctrine discriminator map, the code reaches the LogicException.

So either proxy classes shouldn't be serialized at all, or this code should be taking into account the fact that proxy class names are not mentioned in discriminator maps. 

Or do I miss out on something trivial here???

**Comment by goetas** [comment]
> the JMS discriminator map is only for deserialization, which I'm not doing.

Can you point out the documentation that says that. discriminator map is used for both, serialization and deserialization

> $this->discriminatorMap refers to the Doctrine map,

not true, it refers to the jms discriminator map.

Are you using the serializer with the symfony bundle?

Have you tried to check-out the testcase https://github.com/goetas/serializer/commit/14fc654b76b32156bc84f2d2057fc9fd7ffcd89c ?
That code works as said [before](https://github.com/schmittjoh/serializer/issues/459#issuecomment-300828195) . Can you try to spot if there are differences between your code and mine?

**Comment by arnauddeklerk** [comment]
OK, I figured it out.

First of all: [here](http://jmsyst.com/libs/serializer/master/reference/annotations#discriminator) the documentation says the JMS discriminator is for deserialization, but maybe I should assume it works for serialization as well.

Second: I really don't think you need both JMS and Doctrine maps, it works with just a Doctrine map as well.

Third: the error in my code is caused by a third party bundle (https://github.com/steffenbrem/JsonApiBundle), calling the JMS serializer method getMetadataForClass for a proxy classname, in a postserialize event. I forked this bundle now, and modified it in such way that it doesn't call getMetadataForClass for proxy classnames anymore.

Sorry for the confusion, the JMS serializer bundle works fine (the test case also), although I now see it requires special attention when using it with proxy classes.

**Comment by goetas** [comment]
> First of all: here the documentation says the JMS discriminator is for deserialization, but maybe I should assume it works for serialization as well.

Documentation has been fixed with https://github.com/schmittjoh/serializer/commit/a1ae8be9c750a635d03dc791b1444f08493debb7

> Second: I really don't think you need both JMS and Doctrine maps, it works with just a Doctrine map as well.

You are right, i forgot that there is an extra triver that copies doctrine annotations to jms (see [DoctrineTypeDriver](https://github.com/schmittjoh/serializer/blob/master/src/Metadata/Driver/DoctrineTypeDriver.php#L3))

> Third: the error in my code is caused by a third party bundle (https://github.com/steffenbrem/JsonApiBundle), calling the JMS serializer method getMetadataForClass for a proxy classname, in a postserialize event. I forked this bundle now, and modified it in such way that it doesn't call getMetadataForClass for proxy classnames anymore.

> Sorry for the confusion, the JMS serializer bundle works fine (the test case also), although I now see it requires special attention when using it with proxy classes.

ok, no problem, happy to hear that the problem is solved

**Comment by goetas** [comment]
@arnauddeklerk have you considered https://github.com/willdurand/Hateoas ? works really well for json api...

**Comment by RuslanZavacky** [comment]
@goetas Unfortunately it does not support jsonapi.org specification :) I've landed here with the same error. Glad that I've found this thread as I had the same issue as @arnauddeklerk .

**Comment by arnauddeklerk** [comment]
@RuslanZavacky @goetas Good to know others also experienced this problem. I myself do not use HATEOS (don't see the advantage of using that for complex API's that clients need to have quite some knowledge about anyway), so the combination of the FOSRestBundle, the JMS Serializer bundle, and the JSONApiBundle will do for me. The latter caused me quite some problems, but I think I have it under control by now, though I needed to fork the bundle.
