### ISSUE TITLE
getClassName regex may incorrectly retrieve a false class name from comments above the class.

### ISSUE THREAD

**Issue by rhousworth** [schmittjoh/serializer#460]
A comment such as "Any class that extends this one should..." above the class definition will result in an attempt to find a class named "that" in the given namespace, resulting in a rather cryptic error message. The solution would be to strip comments from the contents of the file before attempting to match the class name. See getClassName in AnnotationConfigurationPass.php.

**Comment by goetas** [comment]
Closing, Sorry for the long feedback loop. If the problem is still here, feel free to comment (pointing out the code that presents the issue) it and I will re-open the issue.
