### ISSUE TITLE
Add new tag (upgrade packagist)

### ISSUE THREAD

**Issue by bertterheide** [schmittjoh/serializer#461]
The last stable release of the jms/serialize package on packagist is ~0.11 (which implies 0.16.0). The last commit on this version was the 18th of May 2014. The last commit on the master branch is the 1st of May 2015.

Maybe it's time for a new tag (e.g. 0.17.0)? This will probably require a new version of the jms/serialize-bundle.

**Comment by stof** [comment]
1.0.0 was released a few days after this issue was opened. It should be closed
