### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by ruudk** [schmittjoh/serializer#465]
The latest tag has 40 new commits and is from Mar 18, 2014

**Comment by stof** [comment]
#490 should be merged first to avoid releasing with a regression

**Comment by lsmith77** [comment]
would be good to have a 1.1 release with the twig fixes

**Comment by raistlin** [comment]
+1

**Comment by schmittjoh** [comment]
Sorry for the wait, I've tagged 1.1 now.
