### ISSUE TITLE
[Question] Handler/Converter for specific field

### ISSUE THREAD

**Issue by unusorin** [schmittjoh/serializer#476]
Hi,
I'm trying to use hashids for converting a specific field to a hashid (using doctrine2 entities).
My game plan is to use a interface called `HashidInterface` that certain entities will implement, and when an object hits the serializer a specific field should be serialized with a different value (ex: 5 => 21kj1)
The quick solution would be to use a virtual property, but then I don't want to inject the service that will handle this conversion into an entity. 

I've looked at handlers part and it doesn't quite match what I need, because it's doesn't support interfaces as type and I'll have to handle the serialization of the entire object, which is overkill for this simple task. 

Can someone point me to a solution at this problem ? I've crawled the docs but it lacks examples. 

Thanks,
Sorin!

**Comment by javitoxhz** [comment]
Same things here, waiting a solution !

Thanks for ask !

**Comment by goetas** [comment]
You can use `@Type("any_string_here")` and adding later a handler on `any_string_here`.

`any_string_here` does not need to be a class, is just used to match its handler
