### ISSUE TITLE
PHP 7 compatability issue

### ISSUE THREAD

**Issue by dvc** [schmittjoh/serializer#478]
$ php bin/php7cc.php ../some_symfony_project
...
File: ../some_symfony_project/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php
Line 214. Indirect variable, property or method access: $object->{$metadata->handlerCallbacks[$context->getDirection()][$context->getFormat()]}($visitor, $context instanceof SerializationContext ? null : $data, $context);

File: ../some_symfony_project/vendor/jms/serializer/tests/JMS/Serializer/Tests/Metadata/Driver/XmlDriverTest.php
Line 89. Function argument(s) returned by "func_get_arg" might have been modified: func_get_arg(0);

**Comment by goetas** [comment]
as of 1.2.0 we have php7 compat
