### ISSUE TITLE
Composer deps issue

### ISSUE THREAD

**Issue by kleijnweb** [schmittjoh/serializer#494]
When trying to figure out the lowest deps at which my tests would pass, I discovered that:

```json
{ "jms/serializer": "1.0" }
```
Results in `Fatal error: Call to undefined method PhpOption\Some::getOrThrow()` when installed with `composer update --prefer-lowest`.

Adding:
```json
{ "phpoption/phpoption": ">=1.1.0" }
```
Makes the problem go away.

**Comment by goetas** [comment]
solved with 1.2.0
