### ISSUE TITLE
Travis needs a renewed token to be able to set the status

### ISSUE THREAD

**Issue by stof** [schmittjoh/serializer#495]
in June, Travis required to authenticate again to be able to renew the tokens to have enough permission to set the commit status because of Github permission changes.
@schmittjoh please login again on Travis because it does not set the status anymore since months (meaning all PRs are green while the testsuite is actually failing since months: https://travis-ci.org/schmittjoh/serializer/builds)

**Comment by stof** [comment]
@schmittjoh it would be great to have the Travis status again

**Comment by Soullivaneuh** [comment]
:+1:

**Comment by schmittjoh** [comment]
Sorry for the wait, I've updated this now.
