### ISSUE TITLE
Permit (optional) inheritance of HandlerCallback functions

### ISSUE THREAD

**Issue by eggyal** [schmittjoh/serializer#499]
[Handler methods are not inherited by subclasses](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Metadata/ClassMetadata.php#L146-L147):

> ``` php
>         // Handler methods are taken from the outer class completely.
>         $this->handlerCallbacks = $object->handlerCallbacks;
> ```

This is completely reasonable, given that subclasses will often add further properties for serialisation about which a parent class's handler would not be aware.

However, I'm attempting to implement a pattern through which serialisation _is_ handled by a parent class (overridden, if necessary, in the child).

I propose adding an additional property to `HandlerCallback` to indicate whether it is inherited.  If flagged as such, it will be inherited by subclasses _unless_ they either define their own `HandlerCallback` for the same format/direction combination, or flag in a class annotation that parent handlers (for particular format/direction combinations) should _not_ be inherited.

Would you accept a PR for this?  Is there any community interest?

**Comment by richsage** [comment]
+1, I'd be interested in this - I've just come across it today where my callback in a parent class wasn't being fired, because I was serializing the child object.

**Comment by ktounet** [comment]
:+1:

**Comment by goetas** [comment]
handler callbacks have been removed in 2.0, see https://github.com/schmittjoh/serializer/issues/615. As alternative, please use custom handlers
