### ISSUE TITLE
MaxDepth exclusion strategy for OneToMany (ArrayCollection) type triggers too many doctrine queries.

### ISSUE THREAD

**Issue by vishalmelmatti** [schmittjoh/serializer#500]
Hi 

I have Node class which has self parent-child  relationship.

```
class Node {

    public $id
    public $title;

/**
 * @ORM\OneToMany(targetEntity="Node", mappedBy="parent")
 * @Expose
 * @MaxDepth(2)
  */
    public $children;
```

}

This should display Top level Node + its children. The problem is, while displaying children properties for each property which is exposed, getter of that property is called. 
So for each children, "getChildren" is also called which triggers separate doctrine query for each child. 

As we only want to display up to level 2  MaxDepth(2),  childrent of children won't be displayed which is fine but still queries for each child gets triggers as their getter is called which impact performance tremendously with more number of children.

So getChildren getter should not be called at MaxDepth(2) level. For that, DepthExclusionStrategy needs to handle it.

I tried doing below changes, it works for me. Please let me know if there is any better way to do it and it would be great to have it fixed in this serializer repository.

```
private function isTooDeep(Context $context, $property = null)
{

    $depth = $context->getDepth();
    $metadataStack = $context->getMetadataStack();

    $nthProperty = 0;
    // iterate from the first added items to the lasts
    for ($i = $metadataStack->count() - 1; $i > 0; $i--) {
        $metadata = $metadataStack[$i];
        if ($metadata instanceof PropertyMetadata) {
            $nthProperty++;
            $relativeDepth = $depth - $nthProperty;

            if ($property && $property->type['name'] == "ArrayCollection") {
             if (null !== $metadata->maxDepth && $relativeDepth >= $metadata->maxDepth) {
                return true;
             } 
            } else {
             if (null !== $metadata->maxDepth && $relativeDepth > $metadata->maxDepth) {
                return true;
             } 
           }
        }
    }

    return false;
}
```

**Comment by oshanz** [comment]
@vishalmelmatti i had same issue.
its not the best, because it can be any other type (T / array<T>). but temporary this solved my case thanks.

**Comment by akomm** [comment]
Just encountered the same Issue.

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/pull/760 and https://github.com/schmittjoh/serializer/commit/136fb0d6da43bc255aa8658414a724acb889f3c1
