### ISSUE TITLE
Object check on SerializationContext::isVisiting()

### ISSUE THREAD

**Issue by natebrunette** [schmittjoh/serializer#502]
In `SerializationContext::isVisiting()` this is a call to check to see if the variable is an object.

```
if ( ! is_object($object)) {
    throw new LogicException('Expected object but got '.gettype($object).'. Do you have the wrong @Type mapping or could this be a Doctrine many-to-many relation?');
}
```

Is there a reason this is done before the pre serialize event, which is the first place that allows a change of type?

**Comment by goetas** [comment]
this has been solved with https://github.com/schmittjoh/serializer/pull/610
