### ISSUE TITLE
Entity changed via preserialize and wrongly persisted

### ISSUE THREAD

**Issue by edrush** [schmittjoh/serializer#509]
Hi,

in my entity class I have a @Preserialize function, which modifies some properties before serialization. My serialization is done within an command. This command is scheduled and therefore stored in the database. After running the commands I update their "last run on" property. So at the end I call $em->flush.
Here comes the strange behaviour: my serialized entities get persisted with the modified properties. But I never called a persist() on them, they are not be updated at all, only serialized.

Did I misunderstand something?

Best regards,
Wolfram

**Comment by goetas** [comment]
Closing, Sorry for the long feedback loop. This issue is probably a problem of your application (calling somewhere `persist`, or  you have `cascade=persist|all` somewhere. 

Looks to be a doctrine issue anyway
