### ISSUE TITLE
Serialize to array

### ISSUE THREAD

**Issue by tarjei** [schmittjoh/serializer#518]
Hi, one thing I often miss is the option to serialize something to an array. 

Usecases are:
* Appending the serialized values to a bigger array so I can use different serializationcontexts to different parts of the object graph.
* Testing

Is this a feature you would consider?

**Comment by afurculita** [comment]
This feature has been already included in the library: 

https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Serializer.php#L116

**Comment by tarjei** [comment]
Yes, I saw that. I would like to suggest that ->serialize($obj, 'array') to that method, but apart from that I'll close this issue :)

T

**Comment by Aliance** [comment]
`->serialize($obj, 'array')` looks good. Needs just to extend `GenericSerializationVisitor`.
@schmittjoh @goetas is there any necessity in it? I can make a pr with my solution. Or using `Serializer::toArray` is enough?

**Comment by goetas** [comment]
@Aliance `$serializer->serialize($obj, 'array')` and `$serializer->toArray($obj)` have different  semantics.

-  `$serializer->serialize($obj, 'array')`  use the array visitor..  (that does not exists...)
-  `$serializer->toArray($obj)` is a "specific" feature of the serializer to return the array representation using the json visitor.

Will prefer to not introduce more "special" cases

**Comment by Aliance** [comment]
> use the array visitor.. (that does not exists...)

I understand & my proposal was to create it. By your comment, I was not able to clearly understand for you or not?

**Comment by goetas** [comment]
no, prefer to keep it as it is now. thanks :)
