### ISSUE TITLE
Introducing the NormalizerInterface

### ISSUE THREAD

**Issue by dbojdo** [schmittjoh/serializer#537]
As #20 introduced normalization / denormalization I'd be nice to have a possibility to type hint those methods on an interface level. It's common to use Serializer just for normalization process.

I think it's good idea to introduce the "NormalizerInterface" with fromArray / toArray methods and allow "Serializer" implements both "SerializerInterface" and "NormalizerInterface"

**Comment by alcalyn** [comment]
+1 for this PR: https://github.com/schmittjoh/serializer/pull/538

**Comment by goetas** [comment]
fixed with https://github.com/schmittjoh/serializer/pull/592

**Comment by alcalyn** [comment]
Yep, this is named `ArrayTransformerInterface` instead. Thanks.
