### ISSUE TITLE
Add DateTimeImmutable support to DateHandler

### ISSUE THREAD

**Issue by wI2L** [schmittjoh/serializer#543]
Hello
The actual `DateHandler` support `DateTime` and `DateInterval` types. Would you consider adding `DateTimeImmutable` support for this handler ? I can do a Pr if you like the idea.

Regards,

@mathroc

**Comment by brendo** [comment]
:+1: Got burnt by this today as well.

**Comment by wI2L** [comment]
Hy @brendo 
This is what i ended up doing, using `DateTimeInterface`

**Comment by martinezdelariva** [comment]
Sorry I don't get to run the solution from @brendo.
I've used a custom handler only for serialization while this issue is resolved.

```php
class DateTimeImmutableHandler implements \JMS\Serializer\Handler\SubscribingHandlerInterface
{
    /**
     * @var string
     */
    private $format;

    public static function getSubscribingMethods()
    {
        return [
            [
                'direction' => \JMS\Serializer\GraphNavigator::DIRECTION_SERIALIZATION,
                'format'    => 'json',
                'type'      => 'DateTimeImmutable',
                'method'    => 'serializeDateTimeImmutableToJson',
            ]
        ];
    }

    /**
     * @param string $format
     */
    public function __construct($format = DATE_ISO8601)
    {
        $this->format = $format;
    }

    public function serializeDateTimeImmutableToJson(
        \JMS\Serializer\JsonSerializationVisitor $visitor,
        \DateTimeImmutable $date,
        array $type,
        \JMS\Serializer\Context $context
    ) {
        return $visitor->visitString($date->format($this->format), $type, $context);
    }
}

// Usage
$serializer = \JMS\Serializer\SerializerBuilder::create()
    ->configureHandlers(function(JMS\Serializer\Handler\HandlerRegistry $registry) {
        $registry->registerSubscribingHandler(new DateTimeImmutableHandler());
    })
    ->build();
```

**Comment by adamquaile** [comment]
To get this working (in a symfony service) I had to tag the above `DateTimeImmutableHandler` with `jms_serializer.subscribing_handler` and explicitly add the `@Type` annotation to my property. 

http://jmsyst.com/libs/serializer/master/reference/annotations#type

**Comment by toby-griffiths** [comment]
I've submitted #604 but it's failing on the environment with the '--prefer-lowest --prefer-stable' composer flags.  Not sure why though, as I've not touched composer

**Comment by toby-griffiths** [comment]
I thought it would automatically update this ticket, as I followed Github's suggested branch name convention!?!

**Comment by grzegorztomasiak** [comment]
any news on implementing this? It's seems kinda weird to not have DateTimeImmutable type

**Comment by wolfwolker** [comment]
+1. I totally agree with  @brendo

**Comment by toby-griffiths** [comment]
It's (hopefully) just waiting for someone to review my PR.

**Comment by matiux** [comment]
+1 @brendo
For now I have changed type from `\DateTime` to `\DateTimeInterface.` in DateHandler::serializeDateTime() because in symfony I can't run my custom handler. I have installed with composer JmsSerializerBundle. Then I have create the Handler like @martinezdelariva has said above and finally I have registered the Handler

```
services:
    jms_serializer.datetimeimmutable_handler:
        class: Acme\Jms\DateTimeImmutableHandler
        tags:
            - { name: jms_serializer.subscribing_handler }
```

But symfony ignores my Handler and I still get this error:

> TypeError: Argument 2 passed to JMS\Serializer\Handler\DateHandler::serializeDateTime() must be an instance of DateTime, instance of DateTimeImmutable given

What am I doing wrong?

**Comment by grzegorztomasiak** [comment]
in your entities you have to specifically mark them as DateTimeImmutable, like the following example:

    use JMS\Serializer\Annotation\Type;

    /**
     * @Type("DateTimeImmutable<'Y-m-d'>")
     */
    private $bookingDate;

**Comment by matiux** [comment]
Uhm.. thanks @grzegorztomasiak but this solution does not really like.
I don't want to bind my domain model with infrastructural stuff.
I'm following a ddd approach. So for now I leave the edit proposed by @brendo 

Furthermore I have some property in array, for instance:

```
class Model {
	private $properties;
	public function __construct() {

		$this->properties = [

			'time' => new \DateTimeImmutable(),
		];
	}
}
```

So i can't mark $properties like \DateTimeImmutable.

@grzegorztomasiak might you have some experiences with JmsSerializerBundle and Symfony?
I have some problem to use custom yaml config.
1) I need to specify what fields is need to serialize
2) where my entity and metadata are
3) enable cache system

**Comment by toby-griffiths** [comment]
I've just submitted a new PR (https://github.com/schmittjoh/serializer/pull/635) submitted with this implemented.

**Comment by JustBlackBird** [comment]
Is there any progress on the issue?

**Comment by toby-griffiths** [comment]
@JustBlackBird my commit was merged into v1.5

**Comment by toby-griffiths** [comment]
Perhaps this can be closed now?

**Comment by FireLizard** [comment]
Hi,

I still getting this error:

> Type error: Argument 2 passed to JMS\Serializer\Handler\DateHandler::serializeDateTime() must be an instance of DateTime, instance of DateTimeImmutable given

I try to serialize the `\Hateoas\Representation\PaginatedRepresentation` ([PaginatedRepresentation.php](https://github.com/willdurand/Hateoas/blob/master/src/Hateoas/Representation/PaginatedRepresentation.php)) inside my Controller with help of [FOSRestBundle](http://symfony.com/doc/master/bundles/FOSRestBundle/index.html).

Can you please help me to figure out what I've missed?

My environment:
```
$ composer show symfony/*
[...]
symfony/symfony            v2.8.18 The Symfony PHP framework

$ composer show jms/*
jms/metadata          1.6.0 Class/method/property metadata management in PHP
jms/parser-lib        1.0.0 A library for easily creating recursive-descent parsers.
jms/serializer        1.6.0 Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
jms/serializer-bundle 1.3.1 Allows you to easily serialize, and deserialize data of any complexity

$ composer show willdurand/*
willdurand/hateoas                  2.10.0 A PHP library to support implementing representations for HATEOAS REST web services
willdurand/hateoas-bundle           1.2.0  Integration of Hateoas into Symfony2.
willdurand/jsonp-callback-validator v1.1.0 JSONP callback validator.
willdurand/negotiation              v2.2.1 Content Negotiation tools for PHP provided as a standalone library.

$ composer show friendsofsymfony/*
friendsofsymfony/rest-bundle 2.1.1  This Bundle provides various tools to rapidly develop RESTful API's with Symfony
```
app/config.yml
```yml
jms_serializer:
    metadata:
        directories:
            app:
                namespace_prefix: "AppBundle\\Entity"
                path: "@AppBundle/Resources/config/serializer"
```

**Comment by goetas** [comment]
It looks some of your entities is using a datetimeimmutable, but the type
metadats says that is a datetime.

Can you post your entity and the yaml metadata file?

**Comment by FireLizard** [comment]
Thank you for your quick response ;)

I figure it out:
To serialize the third party entity of `PaginatedRepresentation` I have to add ["Default"](http://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#creating-different-views-of-your-objects) to my serializable groups of properties. This step brings other third party entities into the game of serialization. So I also had to exclude two properties (which representing timestamps) coming from `\Gedmo\Timestampable\Traits\Timestampable`.

serializer/AbstractEntity.yml
```yml
AppBundle\Entity\AbstractEntity:
    properties:
        title:
            groups: ['myGroup']
        createdAt:
            exclude: true
        updatedAt:
            exclude: true
```
