### ISSUE TITLE
detect serialisation without groups set

### ISSUE THREAD

**Issue by tarjei** [schmittjoh/serializer#546]
Hi, is there a way I could create a listener that could detect that serialization is happening without any serialization groups set?

I got some large graphs that cause issues for us and it would be great to detect all spots during testing.

**Comment by lolmx** [comment]
Got here by accident, if you're still wondering how to:

For the listener refer to the [documentation](http://jmsyst.com/libs/serializer/master/event_system#register-an-event-listener-or-subscriber), then you can access to the groups in the closure (or in the onPreSerialize method for the subscriber) by writing:
`$event->getContext()->attributes->get('groups')` which returns the array of groups used.
