### ISSUE TITLE
SerializedName misleading usage and constructor issue

### ISSUE THREAD

**Issue by enachesilviu** [schmittjoh/serializer#548]
It's about these lines: https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Annotation/SerializedName.php#L33

https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Annotation/SerializedName.php#L37

As far as I know it's common practice that annotation classes used with implementations of Doctrine\Common\Annotations\Reader to have property names and (if any) accessor/mutators names equivalent to property names you specify on a DocBlock line. For instance, I expect this to work: @Serializer\SerializedName(name="releaseType"). But it Instead I have to use @Serializer\SerializedName(value="releaseType") for it to work which doesn't make much sense following common practice. I believe popular editors follow common practice so they give you autocomplete on "name" field.

So I specified the "name" property in the DockBlock line and I stumbled across this using FOSElasticaBundle fos:elastica:populate command. I got this exception:

[Symfony\Component\Debug\Exception\ContextErrorException]
  Notice: Undefined index: value

**Comment by Nezahual** [comment]
+1

**Comment by goetas** [comment]
partially solved with https://github.com/schmittjoh/serializer/commit/fb93c7272c0bd9f1eac541b7cb53158543b93f21 

regarding `name` vs `value`, I do not see differences
