### ISSUE TITLE
JsonDeserializationVisitor throw an error in PHP 7

### ISSUE THREAD

**Issue by tiagobrito** [schmittjoh/serializer#549]
The `decode` method in `src/JMS/Serializer/JsonDeserializationVisitor.php` throw a "Could not decode JSON, syntax error - malformed JSON." exception in PHP 7 with an empty string. This only happens with PHP 7 due to the BC on `json_last_error()` function.

Check this test: https://3v4l.org/eZ7Zv

**Comment by maennchen** [comment]
Why should an empty string not trigger an error? `''` is not a valid JSON.

**Comment by maennchen** [comment]
I'd rather say we should throw the same error in PHP `< 7`.

**Comment by goetas** [comment]
since now only php 7 is supported this can be considered as solved
