### ISSUE TITLE
Ability to getGroups on Context

### ISSUE THREAD

**Issue by phillipsnick** [schmittjoh/serializer#554]
We can set groups on the context as defined here: https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Context.php#L168

But theres no simple method for fetching them.

This usually results in me having to do the following code in every listener...

``` php
$attributes = $event->getContext()->attributes;

if (!$attributes->containsKey('groups')) {
    return [];
}

$groups = $attributes->get('groups')->get();
```

Is there a better way?

**Comment by goetas** [comment]
Groups inside the context are there only for the group exclusion strategy proposes.

If you need to access them, you can set them explicitly in the "serialization" attributes and use them as you prefer
