### ISSUE TITLE
Allow to define the default timezone to be used by DateHandler globally

### ISSUE THREAD

**Issue by rrajkomar** [schmittjoh/serializer#555]
It would be nice to have the following :

1) DateHandler using the date.timezone ini setting if available by default before using the current default UTC timezone 

2) The serializer builder providing a method to modify a default handler configuration/definition (i.e for the DateHandler it would be nice to be able to change the default format and timezone).

**Comment by goetas** [comment]
`DateHandler` accepts the timezone as second argument
