### ISSUE TITLE
Why do we need this check inside SerializedName constructor, if there is name?

### ISSUE THREAD

**Issue by idchlife** [schmittjoh/serializer#558]
I encountered this part when using PhpStorm with PHP Annotations plugin, when I wrote name="my_preferred_name" and got error "value" key undefined after opening my app.

https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Annotation/SerializedName.php#L33

So, if there is public property $name, why is there value? How about PR for this thing, whatcha guys think if I manage one?

**Comment by scaytrase** [comment]
This check is needed when writing things like `@SerializedName("the_property_name")`. But of course, this should check, whether the 'value' key exist in this case.

**Comment by goetas** [comment]
This is ment to make obligatory the first parameter of the anotation
