### ISSUE TITLE
Object handler callback returns array, but serialized object = null

### ISSUE THREAD

**Issue by tetele** [schmittjoh/serializer#594]
I have a class that needs to be serialized to an `array`. If I provide a serialization handler that returns an array, the returned serialized object is `null`

Example code:

```
use JMS\Serializer\Annotation\HandlerCallback;

class Container {
    private $things = array();

    public function addThing($thing) {
        $this->things[] = $thing;

        return $this;
    }

    public function getThings() {
        return $this->things;
    }

    /**
     * @HandlerCallback("json", direction = "serialization")
     */
    public function serializeToJson() {
        return $this->things;
    }
}
```

If I try to

```
$container = new Container();
$container->addThing('something'); // optional
print_r($serializer->serialize($container, 'json'));
```

I get a `null` result. It doesn't matter if the array is empty or not, if it is associative or not.

**Comment by Orasik** [comment]
I have exactly the same issue, did you manage to find any solution?

**Comment by goetas** [comment]
As described in the documentation (http://jmsyst.com/libs/serializer/master/reference/annotations#handlercallback), `@HandlerCallback` receives an instance of the visitor, so you have to do something as 

```php
    /**
     * @HandlerCallback("xml", direction = "serialization")
     */
    public function serializeToXml(XmlSerializationVisitor $visitor)
    {
        $visitor->visitArray($this->things);
    }
```
