### ISSUE TITLE
Trying to decorate a member to ArrayCollection but gets an error when deserilizing because composer didn't download the class from doctrine.

### ISSUE THREAD

**Issue by alexandrubeu** [schmittjoh/serializer#596]
This is the code
    /**
     * @var array|MovieCollectionItemViewModel
     * @Type("ArrayCollection<Server\BusinessLayer\ViewModels\MovieCollectionItemViewModel>")
     */
    public $collectionItems = array();

The error: 
PHP Fatal Error: Class 'Doctrine\Common\Collections\ArrayCollection' not found in ......./vendor/jms/serializer/src/JMS/Serializer/Handler/ArrayCollectionHandler.php on line 76

**Comment by goetas** [comment]
do you have installed doctrine collection at least? https://github.com/doctrine/collections

**Comment by goetas** [comment]
see explanation of https://github.com/schmittjoh/serializer/issues/517#issuecomment-237240517
