### ISSUE TITLE
Serializes FOS:User datas with ExclusionPolicy("all") 

### ISSUE THREAD

**Issue by fagyikaa** [schmittjoh/serializer#599]
I use Fos UserBundle for user managing. Created a custom User class extending the base fos user like this:

```

use JMS\Serializer\Annotation as JMS;
 /**
 * @ORM\Entity(repositoryClass="Core\UserBundle\Repository\UserRepository")
 * @ORM\Table(name="users")
 * 
 * @JMS\ExclusionPolicy("all")
 */
class User extends BaseUser {
...
}
```

In an other entity the user is related with a ManyToOne relation.
In this entity (which has the same exclusion policy) i exposes the user.

In my opinion the behavior should be that the related user field contains only fields which are directly exposed in the user entity however it serializes the fields which are in the base user entity. 
It is a dangerous behavior because datas such as salt, roles, etc. are exposed... 
As we extends the base user class, the child class's exclusion policy should be applied on the base class thus not exposing the fields.

**Comment by mvrhov** [comment]
This is known since the beginning, please read the documentation which contains the detail on how to configure the serialization policy for base/3rd party classes

**Comment by fagyikaa** [comment]
I missed this piece because i use only annotation and havent need to use meta yet. However i still think that this behavior is dangerous. Is it not possible to watch the policy of the child and use that in such cases or whats the reason behind this behavior?

**Comment by mvrhov** [comment]
Its been like this since the beginning, so this won't get changed as this would be a huge BC break.

**Comment by goetas** [comment]
related to https://github.com/schmittjoh/JMSSerializerBundle/issues/100

**Comment by goetas** [comment]
closing as per explanation provided with https://github.com/schmittjoh/JMSSerializerBundle/issues/100#issuecomment-298007275
