### ISSUE TITLE
XML serialisation performance vs. SimpleXML?

### ISSUE THREAD

**Issue by steffenschumacher** [schmittjoh/serializer#606]
Hi,
Just wondering if any tests have been conducted on the above?
This project is used by xsd2php, where XSD generated PHP classes can be serialised into XML using serializer, and I really need performance - both for un/marshalling.
So if any comparisons have been made, then I would be keen to know the ballpark outcome?

**Comment by goetas** [comment]
i tried to explore the idea... but without real tests...
simplexml will improve the memory usage, but im not really sure about cpu performance (but will make the serializer a bit more complex).
probably there are rooms for improvements anyway keeping the dom serializer.

**Comment by steffenschumacher** [comment]
Not sure I understand:
> but will make the serializer a bit more complex
What I was thinking (in no way to the end), was if the php-classes generated by xsd2php, could include autogenerated code to un/marshal objects from/to XML, using simpleXML?
This way, xsd2php would have no dependency towards serializer and the generated classes could be used without any dependencies at all.
Automatically building the methods for un/marshalling on each class would be quite complex of course..
I'll close the question - thanks!

**Comment by goetas** [comment]
> could include autogenerated code to un/marshal objects from/to XML, using simpleXML?

this will violate SRP and generally IMO is a bad idea.

> Automatically building the methods for un/marshalling on each class would be quite complex of course..

I will add also that the code obtained from it can not be re used in any context.

**Comment by steffenschumacher** [comment]
Right - I guess one approach could be to add more meta data onto the classes, so that a separate module could deal with in/marshaling- kinda like how JAXB works for Java..
