### ISSUE TITLE
[RFC] Serialization refacotring

### ISSUE THREAD

**Issue by goetas** [schmittjoh/serializer#609]
Hello everybody. 

I have started a more or less big adventure refactoring the serializer

Here you can find the work in progress PR https://github.com/goetas/serializer/pull/3

Currently I have not a specific goal, but probably will be a fork of the project if @schmittjoh is not happy with the changes

_Of course will not be BC with the current branch_

Feedback is welcome

**Comment by schmittjoh** [comment]
I would be curious about the goals behind it. Could you share a bit more?

**Comment by goetas** [comment]
Currently i have a lot of projects that uses the serializer, and I see that a lot of other open source projects rely on it.

I hear often that is slow, and must admit that compared to other libs is a bit slower (but of course it has way more features then the others).

The basic idea is that refactoring it a bit, will be easier to find some spots for improvements.

(Some ideas are to use other xml libraries to write xml, and try to see if there are rooms for optimizations in the case of the json and yaml serializer)

On the other hand, adding new features is not always easy... the code base is pretty old and  there are some features that makes it more unstable.
some ideas are: replacing some components with more standard libs (yaml writer, event dispatcher, lexer), making native types handled as ordinary types, reducing/simplfiying the number of visitor classes.

Other minor changes can be removing some features from the core and move them to a separate repo, fix some PSR standards

In general i think that this is a great library, but needs some fresh air.

Of course i have also some projects that need more features from the serializer and i need to roll out them somehow. And I started to consider a fork as alternative.

**Comment by goetas** [comment]
not working on it at the moment
