### ISSUE TITLE
Can't hint interface using @Type to trigger custom handler

### ISSUE THREAD

**Issue by thomask** [schmittjoh/serializer#631]
I would like to trigger a custom handler using an interface as the `type`. As per @schmittjoh 's [comment](https://github.com/schmittjoh/serializer/pull/177#issuecomment-27942813) I thought I could achieve this by using the `@Type` annotation to hint the interface. However, the type name [is 'overwritten' in the GraphNavigator](https://github.com/schmittjoh/serializer/blob/705d0b4633b9c44e6253aa18306b3972282cd3a3/src/JMS/Serializer/GraphNavigator.php#L153) meaning the custom type cannot be found .

Is it simply not possible to do what I want or am I missing something?

**Comment by goetas** [comment]
Currently is not possible to hint interfaces.... only classes or virtual types (not existing classes)

**Comment by goetas** [comment]
prefer to use explicit anotation, the `@var` is not created for it. use the `@Type` annotation
