### ISSUE TITLE
JMS Serializer cuts trailing zeros

### ISSUE THREAD

**Issue by crashev** [schmittjoh/serializer#636]
Hello,
jms serializer cuts trailing zeros when serializing an object although there is float or double type configured on certain field. So 100.00 becomes 100 and is treated for example by elastic search as long not as float/double. 

It should be fixed and allow jms serializer to output values like 100.00 in places where it is specified as such type.

**Comment by goetas** [comment]
You can easily create a custom handler for floats and decide the policy for
fliats

On 29 Aug 2016 14:37, "Pawel Furtak" <notifications@github.com> wrote:

Hello,
jms serializer cuts trailing zeros when serializing an object although
there is float or double type configured on certain field. So 100.00
becomes 100 and is treated for example by elastic search as long not as
float/double.

It should be fixed and allow jms serializer to output values like 100.00 in
places where it is specified as such type.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/schmittjoh/serializer/issues/636>, or mute the thread

**Comment by scaytrase** [comment]
I think there should be some built-in configuration for float formatting, like one we have for `\DateTime` formats

**Comment by goetas** [comment]
> I think there should be some built-in configuration for float formatting, like one we have for \DateTime formats

I agree. PR are welcome

**Comment by goetas** [comment]
setting `JSON_PRESERVE_ZERO_FRACTION` in the json visitor options will solve the problem.

If you are using the symfony bundle, see http://jmsyst.com/bundles/JMSSerializerBundle/master/configuration#extension-reference  (`visitors/json/optins` section)

**Comment by Sevavietl** [comment]
How can I preserve zeros in XML serialization? I am using [webservices/xsd2php](https://github.com/goetas-webservices/xsd2php). Tried to create a dedicated handler, but, though I register it, it doesn't work.

Handler looks like this:

```
class FloatHandler implements SubscribingHandlerInterface
{
    public static function getSubscribingMethods()
    {
        return [
            [
                'direction' => GraphNavigator::DIRECTION_SERIALIZATION,
                'format' => 'xml',
                'type' => 'float',
                'method' => 'serializeFloatPreserveZeros'
            ]
        ];
    }

    public function serializeFloatPreserveZeros(XmlSerializationVisitor $visitor, $data, array $type, Context $context)
    {
        var_dump($data);

        return $data;
    }
}
```

And I try to register it like this:

```
$serializerBuilder->configureHandlers(function (HandlerRegistryInterface $handler) use ($serializerBuilder) {
            $serializerBuilder->addDefaultHandlers();
            $handler->registerSubscribingHandler(new BaseTypesHandler());
            $handler->registerSubscribingHandler(new XmlSchemaDateHandler());
            $handler->registerSubscribingHandler(new AnyTypeHandler());
            $handler->registerSubscribingHandler(new FloatHandler());
        });
```
It doesn't var_dump any data, so I guess the method is not executed.

Please, advise me, maybe I am doing something wrong.

Thank you in advance.

**Comment by goetas** [comment]
This is not yet available for the XML driver. PR are welcome ([hint](https://github.com/schmittjoh/serializer/blob/f1e87ecdecf50b87225322c3ec7d0550436a1228/src/JMS/Serializer/XmlSerializationVisitor.php#L164) on where to start and add some option "preserve float zero fraction") . 

@Sevavietl regarding your specific use-case, you can do it via PR as said above or use a custom handler for float types as it is not possible to set handlers for native types
