### ISSUE TITLE
Add metadata informations

### ISSUE THREAD

**Issue by matiux** [schmittjoh/serializer#637]
Hi,
I'm using jms serializer (bundle) in a symfony project.
For now, I'm serializing an array of object and it's all ok.

```
[
{"prop": "value"},
{"prop": "value"},
{"prop": "value"}
]
```

But I need to add information about the pagination (I fetch data with doctrine) to end up to have a json like this:

```
[
"meta": {"page": 2, "total": 3, "per_page": 2},
"results": [
   {"prop": "value"},
   {"prop": "value"},
   {"prop": "value"}
   ]
]
```

As you can see, I need to add the informations about total items, current pagination page and the number of the elements in the page.

I have created a `PostSerializationSubscriber` that implements `JMS\Serializer\EventDispatcher\EventSubscriberInterface` and I have implemented the `getSubscribedEvents()` method like this:

```
    public static function getSubscribedEvents()
    {
        return [
            [
                'event' => 'serializer.post_serialize',
                'method' => 'onPostSerialize'
            ],
        ];
    }
```

how can I edit my serialized object in `onPostSerialize()` method?

```
    public function onPostSerialize(ObjectEvent $postSerializeEvent)
    {
        $postSerializeEvent->getContext()->getVisitor()->addData('someKey','someValue');
    }
```

The code below, add 'someKey','someValue' for each elements... but it is not what I want

Thanks

**Comment by goetas** [comment]
your data structure must be 
```
{
"meta": {"page": 2, "total": 3, "per_page": 2},
"results": [
   {"prop": "value"},
   {"prop": "value"},
   {"prop": "value"}
   ]
}
```
(**pay attention that I have used `{}` and not `[]`**)
and to do that you need an object as root object.
when you have a root object, you can easily add pagination information.

As example:

```php
class PaginatedResult
{
  protected $items;
// @exclude
  protected $current_page;
// @exclude
  protected $page_nr;
}
```

and 
```
public function onPostSerialize(ObjectEvent $postSerializeEvent)
    {
        $postSerializeEvent->getContext()->getVisitor()->addData('someKey','someValue');
    }
```
registered for `PaginatedResult`

**Comment by matiux** [comment]
Hi @goetas, thanks!
Ok for the json, I had wrong the example.

However I don't still understand the way in which I can add `PaginatedResult` to my just serialized object.

Can you provide me some additional details?

**Comment by goetas** [comment]
> And what is PaginatedResult? A plain object?

yes

you need to store somewhere the current page number and the number of pages

I suggest you to have a look to : 
- https://github.com/TheFootballSocialClub/FSCHateoasBundle/blob/master/Serializer/Handler/PagerfantaHandler.php 
-  https://github.com/KnpLabs/KnpPaginatorBundle 
- https://github.com/borisguery/PaginatedResource

**Comment by matiux** [comment]
But is there a way to achieve my goal without additional bundle?
I have seen in the first example that is called the method setRoot with an array so I have tried this:

`$postSerializeEvent->getContext()->getVisitor()->setRoot(['tot' => 2]);`

but doesn't work

**Comment by goetas** [comment]
can you share the code used to generate the pagination result? (not the event listener)

**Comment by matiux** [comment]
Thanks @goetas 
I'm using doctrine Paginator. I have a Repository that returns `Doctrine\ORM\Tools\Pagination\Paginator`, and this is my serializer method:

```
class JmsRequestEmailSerializer extends JmsEntitySerializer implements RequestEmailSerializer
{
    public function serialize(Paginator $collection)
    {
        $serializedEntity = $this->serializer->serialize(
            $collection->getIterator()->getArrayCopy(),
            static::JSON_FORMAT
        );

        return $serializedEntity;
    }
}
```

**Comment by goetas** [comment]
how your code is able to obtain the number of pages ? you are passing to the serializer only the array of the current page... right?

**Comment by matiux** [comment]
The number of page can be obtained by dividing total items with the number of elements in page

**Comment by goetas** [comment]
so `$collection->getIterator()->getArrayCopy()` has the whole set... is not paginated

**Comment by matiux** [comment]
no no
has only paginated items because this is my query:

```
        $queryBuilder = $this->createQueryBuilder('s');
        $queryBuilder->setFirstResult(0)
            ->setMaxResults(40)
            ->orderBy('s.tifaRequestHeader.dataRichiesta', 'ASC');

        $paginator = new Paginator($queryBuilder);

        return $paginator;
```

**Comment by goetas** [comment]
then you have to :

```
class JmsRequestEmailSerializer extends JmsEntitySerializer implements RequestEmailSerializer
{
    public function serialize(Paginator $collection)
    {
        $serializedEntity = $this->serializer->serialize(
            $collection,
            static::JSON_FORMAT
        );

        return $serializedEntity;
    }
}
```

and the handler now you can extract the page informations, because doing "->getIterator()->getArrayCopy()" you loose all the info about the collection size

**Comment by matiux** [comment]
Uhm ok..
so how can I use doctrine paginator to put meta information in the serialized json?

**Comment by matiux** [comment]
Need I to KnpPaginatorBundle?

**Comment by goetas** [comment]
no, a custom listener on `Paginator` is enough

**Comment by matiux** [comment]
on Doctrine\ORM\Tools\Pagination\Paginator?

Can you help me with an example?

**Comment by matiux** [comment]
If I try to serialize a Paginator object,

```
    public function serialize(Paginator $collection)
    {
        $serializedEntity = $this->serializer->serialize(
            $collection,
            static::JSON_FORMAT
        );
```


I get this error:

`Resources are not supported in serialized data. Path: Monolog\Handler\StreamHandler -> Symfony\Bridge\Monolog\Logger -> Symfony\Bridge\Doctrine\Logger\DbalLogger -> Doctrine\DBAL\Logging\LoggerChain -> Doctrine\DBAL\Configuration -> Doctrine\DBAL\Connection -> Doctrine\ORM\EntityManager -> Doctrine\ORM\Query -> Doctrine\ORM\Tools\Pagination\Paginator`

**Comment by goetas** [comment]
you need a custom handler for it
```php
class MyHandler implements SubscribingHandlerInterface
{
    public static function getSubscribingMethods()
    {
        return array(array(
                'direction' => GraphNavigator::DIRECTION_SERIALIZATION,
                'format' => 'json',
                'type' => 'Paginator',
                'method' => 'serialize'
            )
        );
    }

    public function serializeAnyType(JsonSerializartionVisigtor $visitor, Paginator $data, array $type, Context $context)
    {
        // serialize your object here
    }

}
```

**Comment by goetas** [comment]
of course you need the right paginator namespace and class name

**Comment by matiux** [comment]
Ok, I have removed the listener to post.serialized event since it no longer need.
I have created a custom handler and I registered it

```
    jms_serializer.doctrine_paginator_handler:
        class: AppBundle\DomainModel\Stat\Service\Serializer\Jms\DoctrinePaginatorHandler
        tags:
            - { name: jms_serializer.subscribing_handler }
```

But I have still doubts about the creation of metadata and results fields

```
    public function serializeDoctrinePaginator(JsonSerializationVisitor $visitor, Paginator $paginator, array $type, Context $context)
    {
        $breakpoint = true;
    }
```

**Comment by goetas** [comment]
`/src/JMS/Serializer/Handler/ArrayCollectionHandler.php` is a good place to start with to see what it should be inside

```php
    public function serializeCollection(JsonSerializationVisitor $visitor, Collection $collection, array $type, Context $context)
    {
        // We change the base type, and pass through possible parameters.
        $type['name'] = 'array';

        $p = new StaticPropertyMetadata(get_class($collection), 'page_nr', 5);
        $visitor->visitProperty($p, 5, $context);

        $p = new StaticPropertyMetadata(get_class($collection), 'total_pages', 99);
        $visitor->visitProperty($p, 5, $context);

        
        // serialize collection
        return $visitor->visitArray($collection->->getIterator()->toArray(), $type, $context);
    }
```
is just an example

**Comment by matiux** [comment]
There is something that doesn't work...

```
        $type['name'] = 'array';

        $totalPage = ceil($paginator->count() / 40);

        $p = new StaticPropertyMetadata(get_class($paginator), 'total_pages', $totalPage);
        $visitor->visitProperty($p, null, $context);

        $p = new StaticPropertyMetadata(get_class($paginator), 'total', $paginator->count());
        $visitor->visitProperty($p, null, $context);

        return $visitor->visitArray($paginator->getIterator()->getArrayCopy(), $type, $context);
```

return only the number 5, that is the total pages

**Comment by goetas** [comment]
Why `null`  in ` $visitor->visitProperty($p, null, $context);` ?

**Comment by goetas** [comment]
can you try to serialize `$paginator->getIterator()->getArrayCopy()` the result with `StaticPropertyMetadata`  too?

**Comment by matiux** [comment]
Whats is the second parameters of visitProperty() ?

visitProperty() method calls getValue() on StaticPropertyMetadata class  but this is the implementation:

```
    public function getValue($obj)
    {
        return $this->value;
    }
```

$obj seems to be unused

About your last message, how can I serialize $paginator->getIterator()->getArrayCopy() with StaticPropertyMetadata

thanks for your patience

**Comment by goetas** [comment]
```
        $totalPage = ceil($paginator->count() / 40);

        $p = new StaticPropertyMetadata(get_class($paginator), 'total_pages', $totalPage);
        $visitor->visitProperty($p,  $totalPage, $context);

        $p = new StaticPropertyMetadata(get_class($paginator), 'total', $paginator->count());
        $visitor->visitProperty($p,  $paginator->count(), $context);

        $p = new StaticPropertyMetadata(get_class($paginator), 'items', $paginator->getIterator()->getArrayCopy());
        $visitor->visitProperty($p,  $paginator->getIterator()->getArrayCopy() $context);

```

can this work?

**Comment by matiux** [comment]
Nothing to do, continues to return "5" instead a serialized json object

```
        $type['name'] = 'array';

        $totalPage = ceil($paginator->count() / 40);

        $p = new StaticPropertyMetadata(get_class($paginator), 'total_pages', $totalPage);
        $visitor->visitProperty($p,  $totalPage, $context);

        $p = new StaticPropertyMetadata(get_class($paginator), 'total', $paginator->count());
        $visitor->visitProperty($p,  $paginator->count(), $context);

        $p = new StaticPropertyMetadata(get_class($paginator), 'items', $paginator->getIterator()->getArrayCopy());
        $visitor->visitProperty($p,  $paginator->getIterator()->getArrayCopy(), $context);

        return $visitor->visitArray($paginator->getIterator()->getArrayCopy(), $type, $context);
```

**Comment by goetas** [comment]
in my example i have intentionally omitted `return $visitor->visitArray($paginator->getIterator()->getArrayCopy(), $type, $context)`

**Comment by matiux** [comment]
OK sorry, but the problem doesn't change.

I have remove the return line, but in this code

```
        $serializedEntity = $this->serializer->serialize(
            $collection,
            static::JSON_FORMAT
        );
```

`$serializedEntity` contains 5

**Comment by matiux** [comment]
Obviously, serializer is an object of JMS\Serializer\Serializer type

**Comment by goetas** [comment]
@matiux I guess, you are italian, please write me over skype, my id is the same as my github username

**Comment by goetas** [comment]
I gess https://github.com/TheFootballSocialClub/FSCHateoasBundle/blob/master/Serializer/Handler/PagerfantaHandler.php#L107 is exactly what you need

**Comment by matiux** [comment]
Thank @goetas finally work and this is the current implementation of the handler for Doctrine Paginator:

```
class DoctrinePaginatorHandler implements SubscribingHandlerInterface
{
    public static function getSubscribingMethods()
    {
        return [
            [
                'direction' => GraphNavigator::DIRECTION_SERIALIZATION,
                'format'    => 'json',
                'type'      => 'Doctrine\ORM\Tools\Pagination\Paginator',
                'method'    => 'serializeDoctrinePaginator',
            ]
        ];
    }

    public function serializeDoctrinePaginator(JsonSerializationVisitor $visitor, Paginator $paginator, array $type, Context $context)
    {
        $totalPage = ceil($paginator->count() / 40);

        $resultsType = array(
            'name' => 'array',
        );

        if (isset($type['params'])) {

            $resultsType['params'] = $type['params'];
        }

        $shouldSetRoot = null === $visitor->getRoot();

        $data = array(
            'page' => $paginator->getQuery()->getFirstResult() + 1,
            'total_page' => $totalPage,
            'total' => $paginator->count(),
            'results' => $visitor->getNavigator()->accept($paginator->getIterator()->getArrayCopy(), $resultsType, $context),
        );

        if ($shouldSetRoot) {
            $visitor->setRoot($data);
        }
    }
}

```
