### ISSUE TITLE
BC from 1.1.* to ^1.2

### ISSUE THREAD

**Issue by ruscon** [schmittjoh/serializer#643]
v 1.1.*
has translations.**en** key

```
"category": {
        "id": 6,
        "position": 4,
        "createdAt": "2016-04-28T14:12:00+0300",
        "updatedAt": "2016-07-27T00:48:15+0300",
        "translations": {
          "en": {
            "name": "xxx"
          },
          "ru": {
            "name": "yyy"
          }
        }
      }
```

v ^1.2

```
"category": {
        "id": 6,
        "position": 4,
        "createdAt": "2016-04-28T14:12:00+0300",
        "updatedAt": "2016-07-27T00:48:15+0300",
        "translations": [
          {
            "name": "xxx"
          },
          {
            "name": "yyy"
          }
        ]
      },
```

**Comment by goetas** [comment]
Looks because of https://github.com/schmittjoh/serializer/commit/b0a46c80cf3dbd97205f2e2ffeb9229080899c76

**Comment by smurfy** [comment]
Yea i'm having the same problem. Even ```array<string,MyObject>``` instead of ```array<MyObject>``` does not help.

It looks like associative arrays are no longer supported.

**Comment by goetas** [comment]
@schmittjoh can you help here?

**Comment by goetas** [comment]
@smurfy 
>  Even array<string,MyObject> instead of array<MyObject> does not help.

are you sure about this?

**Comment by smurfy** [comment]
@goetas yes, just tested again to be sure. even with declaring the key to be of type ```string``` it still transforms the array from a associative arrays to a normal array in the serialisation.

**Comment by goetas** [comment]
@ruscon can you provide a failed test case for this?

**Comment by smurfy** [comment]
@goetas, @ruscon I can create a unittest for this as-well, for example if @ruscon has no time for it.

**Comment by goetas** [comment]
@smurfy if you can, for me is fine

**Comment by smurfy** [comment]
@goetas Ok, while trying to reproduce the problem in a unit-test, i failed to do so. 
So i went back to my code and tried to reproduce it there and my test failed.
BUT after changing the annotation to ```array<string,MyObject>``` it worked. But only after i did a cache clear on my symfony2 application. 

So my guess is i missed the cache clear on my tests on september the ninth and i told you false informations. (currently running all my unittest just to be sure)

But in a way this is still a BC break and i would add this maybe to a upgrading or changlog :)

So @ruscon i would suggest trying to fix your annotations by adding the key type of the array.

**Comment by ruscon** [comment]
@smurfy, I will try, thx

**Comment by ruscon** [comment]
works
```
properties:
    translations:
        expose: true
        type: array
```

**Comment by goetas** [comment]
works :)
