### ISSUE TITLE
[RFC] Introduce normalizer\denormalizer interface

### ISSUE THREAD

**Issue by scaytrase** [schmittjoh/serializer#646]
Currently `Serializer` has method `Serializer::toArray` which is not covered by any interface. I suggest gracefully rename it to `normalize` and extract as `NormalizerInterface`. The same thing I suggest to do with `fromArray` method - `DenormalizerInterface`.

With graceful rename I mean having both methods now, marking old one as deprecated and to be remove in next major release

**Comment by goetas** [comment]
See https://github.com/schmittjoh/serializer/pull/592

**Comment by scaytrase** [comment]
Oh, I've even searched for this before submitting. But in issues :(
