### ISSUE TITLE
OneToOne entities are not deserialized if passing a nested one-to-one property

### ISSUE THREAD

**Issue by bertuz** [schmittjoh/serializer#652]
I have `User` and `UserInfo` 

```
class User
{

    ...

    /**
     * @ORM\OneToOne(targetEntity="UserInfo")
     * @ORM\JoinColumn(name="userinfo_id", referencedColumnName="id_user")
     * @Serializer\Groups({"o", "i-self-editUser"})
     */
    private $userInfo;

    ...

}

class UserInfo
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id_user", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\SequenceGenerator(sequenceName="users_id_user_seq", allocationSize=1, initialValue=1)
     */
    private $idUser;

    ...

}
```

And I'm trying to deserialize a User sent by means of JMSSerializer and its Doctrine Contructor. Everything works fine if `UserInfo` is not specified. User is loaded from the DB and the sent fields are updated:

By sending:

```
{
    "username": "test@test.us",
    "email": "test@test.us",
    "name": "test",
    "lang": "en-US"
}   
```

What I get deserialized is User's and UserInfo's well loaded.

But if I try to send something like this:

```
{
    "username": "test@test.us",
    "email": "test@test.us",
    "name": "test",
    "lang": "en-US"
    "user_info": {
        "short_date_format": "Y-m-dd"
    }
}   
```

`short_date_format` is update, but all the other fields will not be loaded from the DB, setting all of them to `null`. This is not the behavior I would like to get. Am I misusing JMSSerializer and the doctrine constructor?

**Comment by goetas** [comment]
this is because the serializer places a new object as "user_info", if you want to update it, you have to provide a way to load your object using one of https://github.com/schmittjoh/serializer/tree/master/src/JMS/Serializer/Construction strategies
