### ISSUE TITLE
Inconsistency between serializing arrays and objects key names

### ISSUE THREAD

**Issue by nospoon** [schmittjoh/serializer#655]
Currently when serializing objects their property names are converted to snake case by default, however when serializing arrays, keys are not converted the same way which in my opinion is inconsistent. 
So it seems that naming strategy only applies to objects?
Is this the expected behaviour?

**Comment by goetas** [comment]
It is a long standing bug. :(

anybody interested to implement a BC compatible fix?

**Comment by goetas** [comment]
array keys are not object properties. do not see why they should be converted. 

closing
