### ISSUE TITLE
Class name not reflecting in serialized json

### ISSUE THREAD

**Issue by archana27m** [schmittjoh/serializer#662]
I am trying to serialize object to json using following code but unable to get class name in json as root name.

$obj = new Test(array("Name"=>"ABC");

when I try to serialize it with jms serializer, 
it shows json output as { "Name" : "ABC" } , Expected output is as { "Test" : { "Name" : "ABC"} }

Please help me for this solution.

**Comment by goetas** [comment]
Can you add more details? As example annotations present on the test class?

**Comment by goetas** [comment]
Please have a look to http://jmsyst.com/libs/serializer

Your example requires a custom handler probably

**Comment by archana27m** [comment]
There are no annotations added for test class, I will add up one if It will give class name in seriazed json but I could not get it. I checked with custom handling but that does not specify class name representation in json.
