### ISSUE TITLE
Not compatible with Symfony 3's Controller::json()

### ISSUE THREAD

**Issue by ReSpawN** [schmittjoh/serializer#663]
The JMS bundle expects 3 arguments of which the 3rd being a Context instance, wheras Symfony submits the context as a 4th.

**Comment by goetas** [comment]
This is a symfony issue.
https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php#L118 is expecting to have a symfony serializer instance, not a JMS serializer.

I suggest you to open the issue on the symfony repo.

**Comment by goetas** [comment]
see https://github.com/symfony/symfony/pull/17642

**Comment by ReSpawN** [comment]
Perhaps I might misunderstand, but seeing this is an extension **for** Symfony, isn't that the job for the developers of the actual extension? It's expecting an interface, which is easily extended from the Symfony serializer class. 

Fortunately somebody beat me to it so I guess the issue will be fixed shortly. 

Thanks for the reply goetas.

**Comment by goetas** [comment]
This is not the official symfony serializer (even if probably  is the most popular).
Is a standalone serializer that can be integrated in almost any php project (some examples https://packagist.org/packages/jms/serializer/dependents)

**Comment by ReSpawN** [comment]
I know, I've been using it standalone in other projects. :) Simply pointing out that if you make an extension for another project as a purpose (in example, the bundle) it should be compatible. :)
