### ISSUE TITLE
Move `FormErrorHandler` to the bundle

### ISSUE THREAD

**Issue by hpatoio** [schmittjoh/serializer#664]
I think that [`FormErrorHandler`](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Handler/FormErrorHandler.php) should be moved from `jms/serializer` to `jms/serializer-bundle` because it handle Symfony forms and not a generic type.

I can submit PRs to both repo but I first would like to know if I'm right or I'm missing something.

**Comment by goetas** [comment]
the tricky part it that somebody can be using the symfony form component without the symfony framework itself. for that reason this class has to stay here (or in a separate package... but this only for 2.0)
