### ISSUE TITLE
Doctrine Proxies and serializer.pre_serialize

### ISSUE THREAD

**Issue by scasei** [schmittjoh/serializer#666]
Listener for 'serializer.pre_serialize' is not called, when class attribute is set and class is a Doctrine Entity.

This example will not trigger, because in EventDispatcher `$class` is 'Proxies__CG__\Prima\Catalog\MediaBundle\Entity\Media' instead of 'Prima\Catalog\MediaBundle\Entity\Media'.

``` php
<?php

namespace Prima\Catalog\MediaBundle\Listener;

use JMS\Serializer\EventDispatcher\EventSubscriberInterface;
use JMS\Serializer\EventDispatcher\ObjectEvent;
use JMS\Serializer\EventDispatcher\PreSerializeEvent;

/**
 * Add data after serialization.
 */
class SerializationListener implements EventSubscriberInterface
{
    /**
     * @var \Sonata\MediaBundle\Provider\FileProvider
     */
    protected $file_provider;


    /**
     * @param \Sonata\MediaBundle\Provider\FileProvider        $file_provider
     */
    public function __construct(
            \Sonata\MediaBundle\Provider\FileProvider $file_provider
    ) {
        $this->file_provider = $file_provider;
    }

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedEvents()
    {
        return array(
            array(
                'event' => 'serializer.pre_serialize', 
                'class' => 'Prima\Catalog\MediaBundle\Entity\Media', 
                'method' => 'onPreSerialize',
            ),
        );
    }

    /**
     * @param PreSerializeEvent $event
     */
    public function onPreSerialize(PreSerializeEvent $event)
    {
        /* @var $object \Prima\Catalog\MediaBundle\Entity\Media */
        $object = $event->getObject();

        $object->setBinaryTransport($this->file_provider->getReferenceFile($object)->getContent());
    }
}
```

**Comment by goetas** [comment]
I guess this can be solved adding your listener on the proxy class too.

**Comment by scasei** [comment]
You are right, this is my workaround. But this should be mentioned somewhere or there could be a solution like detecting this classes. 
Should I provide a PR?

**Comment by goetas** [comment]
Can be fixed probably detecting in some event listener the doctrine proxy class...

**Comment by goetas** [comment]
@scasei Can you check the priority of your listener? `DoctrineProxySubscriber` should do exactly what you need

**Comment by scasei** [comment]
There is no priority set, so its default, or '0'.

As I understand `DoctrineProxySubscriber` is just for loading data from database, as it invokes `load()` on the proxy class.

My use case is that Alice fills some data for json transport, here binary file data as base64. Because Bob has not this file at his filesystem and cant use the received data to call a sonata-provider as Alice would do.

**Comment by goetas** [comment]
probably something as this:
```php
        if ( ! $virtualType || IS_PROXY) {
            $event->setType(get_parent_class($object));
        }
```

should fix... can you isolate the failure and make a PR?

**Comment by scasei** [comment]
yes, will make test case and PR

**Comment by scasei** [comment]
Digged into it and found, listeners/subscribers are triggered here: https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/GraphNavigator.php#L163

````php
                if ($context instanceof SerializationContext) {
                    if (null !== $this->dispatcher && $this->dispatcher->hasListeners('serializer.pre_serialize', $type['name'], $context->getFormat())) {
                        $this->dispatcher->dispatch('serializer.pre_serialize', $type['name'], $context->getFormat(), $event = new PreSerializeEvent($context, $data, $type));
                        $type = $event->getType();
                    }
````

You can see the name of class which is taken to find callables `$type['name']` couldnt be changed through a subscriber/listener. So if we want that we have to rewrite the event dispatcher and these lines in the graph navigator.

The other possibility is to add the subscriber for the proxy class magically here or somewhere else or let the workaround be as is.

Or what about to dispatch again, as long as the type changes?

**Comment by goetas** [comment]
:( i was thinking will be possible to register a listener triggered on an interface  (`DoctrineProxy`)
https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/GraphNavigator.php#L152

(but im not sure it will work.. you can try it)

**Comment by scasei** [comment]
Seems that this line is injecting `Proxies__CG__\Prima\Catalog\MediaBundle\Entity\Media' for 'Prima\Catalog\MediaBundle\Entity\Media'  as `$type['name']`.

So if I comment that out, it works. Any suggestions?

**Comment by dragosprotung** [comment]
@scasei @goetas could #677 be a solution ?

**Comment by goetas** [comment]
An easy way to solve this issue is just adding the `@Type` annotation on the filed that needs to be serialized
