### ISSUE TITLE
Warning: Invalid argument supplied for foreach() on getCurrentPath method

### ISSUE THREAD

**Issue by kalypso63** [schmittjoh/serializer#668]
With 1.4.0 version, i've found an error with getCurrentPath() method on Context.php class when i try to load my Nelmio api doc with dev mode on symfony. Property $this->metadataStack is always null and can't be parsed on foreach (line 260)

**Comment by goetas** [comment]
The ` $this->metadataStack` is initialized in `initialize()` on the public `Context` class.

Are you trying to use the "context", maybe using the group strategies before starting the serialization process?

**Comment by goetas** [comment]
can you try https://github.com/schmittjoh/serializer/pull/669

**Comment by kalypso63** [comment]
Bug fixed

**Comment by goetas** [comment]
:+1:

**Comment by goetas** [comment]
Fixed in https://github.com/schmittjoh/serializer/releases/tag/1.4.1

**Comment by kalypso63** [comment]
:clap:
