### ISSUE TITLE
From old issue #290

### ISSUE THREAD

**Issue by mmeloni** [schmittjoh/serializer#670]
We have same problem described in #290 :

ReflectionProperty::setValue() expects parameter 1 to be object, null given in .../vendor/jms/metadata/src/Metadata/PropertyMetadata.php:60

Solution proposed by @nuxwin still working

**Comment by goetas** [comment]
if somebody can implement a proper test case, im open for merging it

**Comment by nuxwin** [comment]
@goetas 

A test which ensure that a **EntityNotFoundException** is throw when the entity IDENTIFIER is inconsistent? There is no test covering such a case already? If so, you could just extend it by add the fallback code part as shown in #290, right?

**Comment by goetas** [comment]
as said in https://github.com/schmittjoh/serializer/pull/290 you can create a new pr with a testcase for it

**Comment by nuxwin** [comment]
@goetas 

Did you read my question at least? The question is: Does a testcase already exists for ensuring that **EntityNotFoundException** is raised ? I would be happy to provide a PR, including a testcase but I would be also happy to known the purpose of that testcase. You known your code better than us.

BTW: We could also answer you: There is a bug regarding this. Please, fix it. You're the maintainer after all ;)

Thank you for your understanding.

**Comment by goetas** [comment]
@nuxwin please read the [License](https://github.com/schmittjoh/serializer/blob/master/LICENSE) provided with this software and its terms and conditions  (especially sections 7,8,9)

**Comment by nuxwin** [comment]
@goetas 

Funny answer (ironic)....

To be more serious, If all open-source community acted like you, nobody would use an open-source software... Your answer here is really an asshole' answer. If you have not more interest for that library, just go ahead but don't provide such answer which only discredits the the project.

@schmittjoh  

I don't even know how such a guy can be a collaborator on this project.
