### ISSUE TITLE
Warning: JMS\Serializer\XmlDeserializationVisitor::visitArray(): Node no longer exists

### ISSUE THREAD

**Issue by ama-gi** [schmittjoh/serializer#674]
I got this error when deserializing after I updated the bundle from 1.3.1 to 1.4.1.

**Comment by goetas** [comment]
thanks for the ticket, already working on it, this is a temporary patch https://github.com/schmittjoh/serializer/pull/672

**Comment by goetas** [comment]
introduced with https://github.com/schmittjoh/serializer/pull/658

**Comment by goetas** [comment]
re-fixed in https://github.com/schmittjoh/serializer/pull/697
