### ISSUE TITLE
Doctrine cache dependency when using setCacheDir

### ISSUE THREAD

**Issue by hyperized** [schmittjoh/serializer#676]
When using the serializer as a stand-alone library, the following error is given with the default dependencies from composer:

`PHP Fatal error:  Uncaught Error: Class 'Doctrine\Common\Cache\FilesystemCache' not found in myproject\vendor\jms\serializer\src\JMS\Serializer\SerializerBuilder.php:391`

The following relevant section from composer.json:

```json
  "require": {
    "php": ">=7.0",
    "jms/serializer": "^1.4"
  },
  "require-dev": {
    "phpunit/phpunit": "~5.5",
    "phpspec/phpspec": "~2.1",
    "symfony/console": "^3.1"
  },
```

Relevant code section:

```php
$serializer = SerializerBuilder::create()
    ->setCacheDir('/cache')
    ->setDebug(true)
    ->addMetadataDir('src/Metadata')
    ->build();
```

The following addition to composer fixed the issue for me:

`composer require doctrine/cache`

composer.json after:

```json
  "require": {
    "php": ">=7.0",
    "jms/serializer": "^1.4",
    "doctrine/cache": "^1.6"
  },
  "require-dev": {
    "phpunit/phpunit": "~5.5",
    "phpspec/phpspec": "~2.1",
    "symfony/console": "^3.1"
  },
```

Could you please fix the dependency?

**Comment by goetas** [comment]
`doctrine/cache` is an optional dependency and is not included in the main `require` section.
