### ISSUE TITLE
Remove PHP metadata driver

### ISSUE THREAD

**Issue by goetas** [schmittjoh/serializer#686]

**Comment by Aliance** [comment]
You mean [Metadata/Driver/PhpDriver](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Metadata/Driver/PhpDriver.php)?

**Comment by goetas** [comment]
Yes

**Comment by goetas** [comment]
(and all the test suite related to it... that is really a pain)

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/pull/743/commits/117d0f5e2269af380b9598952bb0c83a1e3f9ded
