### ISSUE TITLE
Problem with FOSUserBundle ROLE serialization

### ISSUE THREAD

**Issue by qweluke** [schmittjoh/serializer#690]
Hi,

This is my code:

```
    /**
     *
     * @Rest\Get( "/{user}", requirements={"user" = "\d+"})
     * @Rest\View(serializerGroups={"ROLE_USER", "ROLE_ADMIN"})
     * @param User $user
     * @return View
     * @throws \NotFoundHttpException
     *
     * @ApiDoc(
     *  headers={
     *      {
     *          "name"="Authorization",
     *          "required"="true",
     *          "description"="Bearer TOKEN"
     *      }
     *  },
     *  resource="/api/user/",
     *  description="Returns user information",
     *
     *  output={
     *   "class"="CoreBundle\Entity\User",
     *   "parsers"={"Nelmio\ApiDocBundle\Parser\JmsMetadataParser"},
     *   "groups"={"ROLE_USER", "ROLE_ADMIN"}
     *  }
     * )
     */
    public function showAction(User $user)
    {

        print_r( $user->getRoles() );
        
        $view = View::create()
            ->setSerializationContext(SerializationContext::create()
                ->setGroups($this->getUser()->getRoles())
            )
            ->setData($user);

        return $this->handleView($view);

    }
```
and [here](http://i.imgur.com/cuO2UBA.png) is an output.

The problem/question is: Why it is not returning any roles?
See that `print_r`, it returns `ROLE_USER` but using `FOSRestBundle` with this seialization option returns an empty array...

**Comment by goetas** [comment]
Can you share your user class definition?

**Comment by qweluke** [comment]
@goetas [here](https://github.com/qweluke/SimpleRestServer/blob/master/src/CoreBundle/Entity/User.php) you go

**Comment by qweluke** [comment]
It seems that this is not a problem with jmsserializer. Moved to [FOS](https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1634)

**Comment by adadgio** [comment]
Strange way to "solve" issues... This seems like a workaround, but this issue must be re-opened AND fixed in the bundle.

The behavior is **extremely misleading** for developers.

**Comment by goetas** [comment]
From the described issue was not clear if actually something needs to be fixed... Maybe Was just a misconfiguration. 
If you have a similar case, will be happy to go deeper into it. 

At the moment I see here: fosuserbundle, fosrest bundle and jms serializer... The "bug" can be anywhere

**Comment by adadgio** [comment]
True, i had this issue on a quite big project and can only bet that its coming from here from what i have read and because the fix actually works. I'll look into a clearer example.

**Comment by terox** [comment]
@goetas Ok, now I understand.

Thank you so much for clarification ;)
