### ISSUE TITLE
Groups logic

### ISSUE THREAD

**Issue by Aliance** [schmittjoh/serializer#693]
Currently, the specified groups are combined as OR (`|`) condition. If property have specify `group: [groupA, groupB]` – serializing with one of these groups (`[groupA]`, `[groupB]` or both `[groupA, groupB]`) will expose the property.

Sometimes, we need to expose the property only when all of specified groups are present. @goetas  should we think about this possibility?

**Comment by goetas** [comment]
this can be easily solved at application level adding a third group, and using it.

`group: [groupA, groupB, groupAB ]` at application level set the group `groupAB` if `groupA, groupB` are set too.

can be done via simple group concatenation

**Comment by Aliance** [comment]
That's right, but sometimes it's a little bit complicated.

Okay, let's close this issue, but maybe someone will +1 it – when we will see the demand.

**Comment by Aliance** [comment]
PS: may be you can comment my other [question](http://stackoverflow.com/questions/41548030/complex-serialization)? If so, I will delete this post later =)

**Comment by goetas** [comment]
> PS: may be you can comment my other question? If so, you can delete this post =)

@Aliance done

**Comment by goetas** [comment]
@Aliance 

Regarding: 
> PS: may be you can comment my other question? If so, you can delete this post =)

https://github.com/schmittjoh/serializer/pull/708 is probably the best solution for what you need
