### ISSUE TITLE
Array serialized as JSON object

### ISSUE THREAD

**Issue by apapsch** [schmittjoh/serializer#706]
Attached script PHP-unserializes the array with two Doctrine entities, then tries to JMS-serialize the array. Expected output is two JSON arrays:

```
[{},{}]
[1,2,3]
```

Actual output:

```
{"0":{},"1":{}]
[1,2,3]
```

I kept the script minimal for reproducibility. The original issue occurs in a REST API GET endpoint, where two Doctrine entities are fetched, and the array passed to the serializer:

```
    // controller method
    public function findValueByParent(Application $app, $parent_id) {
        $valueRepo = $app["entitymanager"]->getRepository(self::NS_VALUE);
        $parent = $valueRepo->find($parent_id);
        if (!($parent instanceof Value)) {
            return ErrorFactory::createResponse(ErrorFactory::NOT_FOUND);
        }
        $childValues = $valueRepo->findBy(["parent" => $parent]);
        return $this->serializeDetail($app, $childValues);
    }

    // helper method
    public function serializeDetail(Application $app, $it) {
        $serializeCtx = SerializationContext::create()
                ->enableMaxDepthChecks()
                ->setGroups(["details"]);
        $resp = new Response($app["serializer"]->serialize($it, "json", $serializeCtx));
        $resp->headers->set("Content-Type", "application/json");
        return $resp;
    }

    // serializer service
    $app["serializer"] = function () {
        return SerializerBuilder::create()->build();
    };
```

**Comment by apapsch** [comment]
Of course, the script: [serializer-bug.zip](https://github.com/schmittjoh/serializer/files/726904/serializer-bug.zip)

**Comment by apapsch** [comment]
I tested the issue with PHP 5.4.45, 5.5.38, 5.6.30 and 7.0.15.

**Comment by goetas** [comment]
Related to https://github.com/schmittjoh/serializer/pull/698 probably

**Comment by goetas** [comment]
Related to https://github.com/schmittjoh/JMSSerializerBundle/issues/373 probably

**Comment by apapsch** [comment]
In serializer-bug I applied #698 as patch in vendor/jms/serializer. With or without `"array"` as fourth parameter to `serialize`, I now get the following output:

```
{"0":{},"1":{}}
[1,2,3]
```

(There are empty inner objects because the referenced classes in the serialized object cannot be found in the minimal example.) Even with the "array" type hint, the array is still serialized as object. Do I need to apply other patches?

**Comment by apapsch** [comment]
I tried the complete branch `typehinded-serialization` of your fork in composer.json. Even with that, no luck. I need to find a quick, brute force solution… Can you give me a hint where I can find the "first step serialization" in the code?

**Comment by Baachi** [comment]
This is a known behaviour from the `json_encode` function and doesn't belong to this repo, so i close this issue.

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/pull/728
