### ISSUE TITLE
Array gets serialized as object, not as array, depending on order.

### ISSUE THREAD

**Issue by korsarNek** [schmittjoh/serializer#709]
jms/serializer version 1.4.2

I attached an example showing that if the first object inside of an array has a property that doesn't serialize any data, the json root gets serialized as an object. If the first object always serializes something and one of the following doesn't, the result is an array, as expected.
[jms-serializer.zip](https://github.com/schmittjoh/serializer/files/736816/jms-serializer.zip)

working:
`[{"working_entity":{"property":33}},{"failing_entity":{}}]`

failing:
`{"0":{"failing_entity":{}},"1":{"working_entity":{"property":33}}}`

The problem code for me is this:

```
    public function endVisitingObject(ClassMetadata $metadata, $data, array $type, Context $context)
    {
        $rs = parent::endVisitingObject($metadata, $data, $type, $context);

        // Force JSON output to "{}" instead of "[]" if it contains either no properties or all properties are null.
        if (empty($rs)) {
            $rs = new \ArrayObject();

            if (array() === $this->getRoot()) {
                $this->setRoot(clone $rs);
            }
        }

        return $rs;
    }
```

**Comment by korsarNek** [comment]
Changing the function to this gives me the expected result:
```
    public function endVisitingObject(ClassMetadata $metadata, $data, array $type, Context $context)
    {
        $rs = parent::endVisitingObject($metadata, $data, $type, $context);

        // Force JSON output to "{}" instead of "[]" if it contains either no properties or all properties are null.
        if (empty($rs)) {
            $rs = new \ArrayObject();

            if (array() === $this->getRoot() && $context->getDepth() == 0) {
                $this->setRoot(clone $rs);
            }
        }

        return $rs;
    }
```

`[{"b":{}},{"b":{"property":33}}]`

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/pull/728
