### ISSUE TITLE
serialization of dateinterval fails when some time parts are negative

### ISSUE THREAD

**Issue by gggeek** [schmittjoh/serializer#711]
To the best of my knowledge, it is possible to create a valid time interval with negative parts, such as eg. -1 year plus 4 days.
That interval will not be correctly serialized by the DateHandler.
Alas it seems that the ISO-8601 does not support negative parts in its short notation for intervals - or at least it does not mention it. Which means that, in order to support this, the serializer should switch to a different format...

**Comment by goetas** [comment]
Sorry for the late feedback... but i do not understand the issue... the format can be customized for each field, and for complex (weird) date format, I use "custom" handlers with custom date types... 

can you elaborate more your problem?

**Comment by gggeek** [comment]
Well, I would expect the default serializer to be able to transfer the interval '-1year +4days' - since this is a value which php does handle - without having to resort writing custom code (I assume here that php producer and php consumer is the most common case).

**Comment by goetas** [comment]
'-1year +4days'  are not in the supported formats by http://php.net/manual/de/datetime.createfromformat.php , so the serializer does not support them out of the box.

to add on top of it, they are relative date formats, that depend on a "base" date (http://php.net/manual/de/function.strtotime.php the `$now` parameter). relative date formats are uncommon in API design... 

Not planning to add it to the core serializer.

curious about your usecase :)

**Comment by goetas** [comment]
If you need to transfer "intervals" as "3 days" or "6 years 3 days and 9 minutes" i suggest you to have a look to `DateInterval` type (that is a ISO 8601 format http://php.net/manual/en/class.dateinterval.php)

**Comment by gggeek** [comment]
there might be some miscommunication here. This bus report *is* about DateInterval

**Comment by goetas** [comment]
aaaa... anyway, the "ISO 8601" dateinterval  is something as "P10DT3S".

what you have in mind are formats supported by PHP's `strtotome` (and the underlying C function ), that has nothing to do with DateInterval and ISO 8601

Am I must understanding again?
