### ISSUE TITLE
Serialized DateTime instances are not valid ISO-8601

### ISSUE THREAD

**Issue by xelan** [schmittjoh/serializer#713]
The [default format of JMS\Serializer\Handler\DateHandler is \DateTime::ISO8601](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Handler/DateHandler.php#L64), which is however [not fully compatible with ISO 8601](http://php.net/manual/en/class.datetime.php). Specificially, the time zone delimiter is missing.

Example:
`2016-04-06T14:39:32+0200`
should be:
`2016-04-06T14:39:32+02:00`

As a result, the serialized string can't be validated via XML schema (xs:dateTime) and the interoperability with other software is also limited.
The PHP documentation suggests to use `DateTime::ATOM` instead of `DateTime::ISO8601` for ISO 8601 compatibility.

In my opinion, the fix would technically be a breaking change, as the serialized XML/JSON would be different from that of previous versions. The deserialization would need to support both variants for backwards compatibility, newly serialized documents should use the standard-compliant DateTime format as default.

What do you think?

**Comment by xelan** [comment]
Deserialization already seems to work with both `DateTime::ISO8601` and `DateTime::ATOM` (Tested with jms/serializer 1.4.2) using JSON and XML.

**Comment by mvrhov** [comment]
This can also fixed when DateHandler instance is created. And the bundle already supports this as you can set the format in your configuration.

**Comment by xelan** [comment]
Thanks for your fast response, @mvrhov. What is the recommended way to set the DateHandler for the serializer? I don't use the bundle.

To fix the issue and provide a standards-compliant default, I created a patch which sets the default to DateTime::ATOM and adapted the test suite accordingly.

**Comment by goetas** [comment]
If you are not using the bundle, then probably you are using the serialization builder.

```php
$builder->configureHandlers(function($h) {
        $h->registerSubscribingHandler(new DateHandler(YOUR_DEFAULT));
        $h->registerSubscribingHandler(new PhpCollectionHandler()); // omit if not using 
        $h->registerSubscribingHandler(new ArrayCollectionHandler()); 
        $h->registerSubscribingHandler(new PropelCollectionHandler()); // omit if not using propel
});
$serializer = $builder->build();

**Comment by xelan** [comment]
Yes, I'm using the SerializerBuilder, so your suggested solution should work. Thank you very much, @goetas!
Is there still interest in changing the default to conform with ISO-8601 later on (e.g. with serializer 2.0)? If so, I could submit my PR.

**Comment by goetas** [comment]
yes, i'm interested, so a PR (with tests :smile:) is welcome.

The only thing is that a release date for 2.0 is really not yet defined, so if can take many months before it gets released.
For now i'm just adding ideas and requirements for the 2.0, but haven't started yet to write code..

**Comment by goetas** [comment]
closing the issue since it looks resolved
