### ISSUE TITLE
Regression with 1.5.0 => Undefined offset 15

### ISSUE THREAD

**Issue by Toilal** [schmittjoh/serializer#715]
I just upgraded to 1.5.0, but it seems there's a regression causing an Exception in [ClassMetadata.php](https://github.com/schmittjoh/serializer/blob/1.5.0/src/JMS/Serializer/Metadata/ClassMetadata.php#L269-L288).

`$unserialized` is an array of 15 elements, but the code tries to unpack 16 elements and it cause an Exception => `Undefined offset 15`.

I'm running PHP 7.1 and the Symfony Bundle.

**Comment by mvrhov** [comment]
You probably need to clear the cache.

**Comment by goetas** [comment]
@Toilal ?

**Comment by Toilal** [comment]
No sorry, the composer install launch the `cache:clear` command, and to be sure I have also cleared the symfony cache manually.

Where does this serialized array comes from initially ?

**Comment by goetas** [comment]
can you share more info about it? what was your previous version?

**Comment by Toilal** [comment]
I was running 1.4.2 previously. Fixing this version in composer.json file is my current workaround.

**Comment by goetas** [comment]
can you post the stacktrace of your error?

**Comment by Toilal** [comment]
I'll post it tomorrow. The error is catch by the phpunit bridge because it occurs in a unit tests.

**Comment by goetas** [comment]
@Toilal news on this?

**Comment by goetas** [comment]
closing, no feedback.

if the problem persists, feel free to comment here, will re-open the issue

**Comment by Ranmus** [comment]
Hi,

This problem still persits. Today i've upgraded JmsSerializer to 1.7.1 and JmsSerializerBundle to 1.5.0  in my application (that is rest api provider). After that all my api works, but phpunit tests aren't passing now. Every api route during testing throws the same exception like @Toilal described in first post.

- Example stack trace:  https://pastebin.com/19KhdMWC
- PHP 7.1
- Symfony 3.2.1
- PHPUnit 5.6
- PHPUnit-bridge 3.2
- cache cleared, Doctrine is not caching any metadata etc.
