### ISSUE TITLE
SerializedName based on a property value

### ISSUE THREAD

**Issue by Narcotic** [schmittjoh/serializer#716]
Is-it possible to have a serialized_name based on a property value?

**Comment by goetas** [comment]
generally no, of course you can set a custom naming strategy and implement it.

as advise, is not recommended to have dynamic naming strategy (means that your model can not be used as specification..)

**Comment by Narcotic** [comment]
I totally agree...But I have to do it that way. What do you advise me to use to achieve that?

Thanks for your fast reply.

**Comment by goetas** [comment]
if you have to do it only for few fields, you can use something as http://stackoverflow.com/questions/41548030/complex-serialization/41552643#41552643

if you have to do it for all the fields in a class, then use a similar approach but using a custom serialization handler.

(with the naming strategy you do not have access to the current object..)

**Comment by goetas** [comment]
related to https://github.com/schmittjoh/serializer/issues/717

**Comment by Narcotic** [comment]
Thank you, I will try your way or use the handler_callbacks..
