### ISSUE TITLE
Is it possible to achieve something like - shouldSerializeEmpty 

### ISSUE THREAD

**Issue by blueeyez** [schmittjoh/serializer#725]
I'm having a hard time to serialize some complex data because some relations are 0/1 -> n or vice-versa and the field itself was set in the database as a blank space or empty, and in some cases NULL.

For these being said, I can't make the best use of setSerializeNull.

Is there any work around to achieve something like that in the GenericSerializationVisitor for the visitArray method to add extra check?

Thank you!

**Comment by goetas** [comment]
What about using virtual properties, and using them to normalise data?

**Comment by blueeyez** [comment]
So, I guess there's no other option beside that?
The point why i was asking this is that the system is quite complex, like i mentioned before,  and to go thru all the Entities will take "forever".
But if you think there's no other way then ...

Thanks!

**Comment by goetas** [comment]
you can use a custom exclusion strategy. https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Exclusion/ExclusionStrategyInterface.php this should work well if you want to do it globally
