### ISSUE TITLE
How to handle Doctrine not found entity ?

### ISSUE THREAD

**Issue by VincentClair** [schmittjoh/serializer#731]
Actually, I want to deserialize an object like this:
```
{id: 2, challenge: {id: 3}, user: {id: "22317C6C-34C0-4A81-9351-55640BCF6AD8"}}
```
It works like a charm if all objects exists.
But if one of the entity is not found, i get a Exception like this one:
'Warning: ReflectionProperty::setValue() expects parameter 1 to be object, null given'
The null is the response of Doctrine for the object not found. After that, JMS tries to setValue of a property on non-object.

If I look at the context given by Exception, I have just an Array with 'obj' (set to null) and 'value' property. Ideally, I would like to found here the type of object required (here the class of my main object or a sub-object like Challenge or User).

I think there could be 2 strategies if Doctrine return null:
- Set a full new object (property must set probably to cascade persist), but it could be surprising to set an ID on it (depends on use cases perhaps)
- Throw an exception like 'ResourceNotFoundException', or better, throw an exception containing all resources not found.

How could I achieve the second strategy and where could i start ?
Thanks in advance for your help.

**Comment by goetas** [comment]
to achieve the second strategy, you can implement a custom object constructor (see https://github.com/schmittjoh/serializer/pull/385 for a hint), and if the returned entity is null, you can throw the exception you prefer.

**Comment by VincentClair** [comment]
Thanks, it works. I had to duplicate DoctrineObjectConstructor to get the results I want. Actually throw an Exception at first entity not found.

I will look at managing all entities not found eventually.

Thank you again for your really quick replay.
