### ISSUE TITLE
Outdated docs site

### ISSUE THREAD

**Issue by JustBlackBird** [schmittjoh/serializer#733]
As I can see [docs in the repository](https://github.com/schmittjoh/serializer/blob/master/doc/reference/annotations.rst#type) say that `DateTimeInterface` is a supported serialization type. At the same time, [these docs](http://jmsyst.com/libs/serializer/master/reference/annotations#type) say nothing about this type.

May be it's time to rebuild docs site?

**Comment by goetas** [comment]
Done
