### ISSUE TITLE
Add support for replacing serialization object inside events

### ISSUE THREAD

**Issue by alex88** [schmittjoh/serializer#74]
It could be useful to replace the element to be serialized in the post-serialization event as the docs says: "You can for example use this to add additional data to an object that you normally do not save inside objects such as links"

Trying to change the object fields in the post_serialization event doesn't makes any change in the resultant serialized object.

Edit: I've seen that in the pre-serialization event the object is changed, so it should be useful to improve the docs about that

**Comment by enrike1983** [comment]
up @bezhermoso question!

**Comment by ahsanity** [comment]
+1 @bezhermoso question!

**Comment by alex88** [comment]
Guys you really expect support? Look at the response rate of other issues :smiley:

**Comment by ahsanity** [comment]
created a PR related to this #409

**Comment by alex88** [comment]
I think you need to add tests too for those methods

**Comment by helmuthva** [comment]
@schmittjoh: would be really helpful to have removeData and updateData in the GenericSerializationVisitor.

**Comment by quant61** [comment]
function replaceData is already in master and appeared more than 2 years ago [commit](https://github.com/schmittjoh/serializer/commit/0d1b30ee5a08f96098918087e91e53dfeee1505a)
But it is still no in release.
Why?

**Comment by goetas** [comment]
@quant61 the PR was merged last week (what you see on github it just the commit timestamp)
