### ISSUE TITLE
Is it possible to use @XmlNamespace & @XmlRoot in a class at same time ?

### ISSUE THREAD

**Issue by hiromik** [schmittjoh/serializer#759]
I'm trying to declare a namespace in my root element and change the "result" with XmlRoot at same time but it doesn't work, am I doing something wrong ?

    /**
     * @Serializer\XmlNamespace(uri="http://www.w3.org/2005/Atom", prefix="atom")
     * @Serializer\XmlRoot("MyClass", namespace="http://www.w3.org/2005/Atom")
     */
    class MyClass

Thanks for your help.

**Comment by goetas** [comment]
What is the expected output?

**Comment by hiromik** [comment]
Thanks for the ultra fast answer, 

```````
<atom:MyClass xmlns="http://www.w3.org/2005/Atom">

</atom:MyClass>
````````

**Comment by goetas** [comment]
```php
    /**
     * @Serializer\XmlRoot("atom:MyClass", namespace="http://www.w3.org/2005/Atom")
     */
    class MyClass
```

should work 



(related to https://github.com/schmittjoh/serializer/issues/506 )
