### ISSUE TITLE
Add data using setData produces hashes instead of arrays

### ISSUE THREAD

**Issue by amorimjuliana** [schmittjoh/serializer#761]
Setting data using `setData` produces hashes instead of arrays:

```php
//onSerializer
$visitor->setData('foo', ['bar']); // Results in stdClass
```

**Comment by goetas** [comment]
When you decide to use `setData`, means that you are dealing with the internal datastructures of the json visitor. This means that is your responibility provide the right datastructures to obtain the desired output.

If you need to have an array, i suggest you to:

```php
$meta = new StaticPropertyMetadata('foo', 'foo', $data);
$meta->setType("array<string>");
$visitor->visitProperty($meta, $data, $context);

**Comment by amorimjuliana** [comment]
Thank you, @goetas!

**Comment by amorimjuliana** [comment]
@goetas I got the same output. Is it a bug?

**Comment by goetas** [comment]
beware that you have to use the 1.7-release candidate  that solved many if the issues related to this topic (see https://github.com/schmittjoh/serializer/milestone/7?closed=1)

planned stable release for tomorrow
