### ISSUE TITLE
Error deserializing a map of (nullable) objects

### ISSUE THREAD

**Issue by marcospassos** [schmittjoh/serializer#762]
Hi folks!

We have a use case here where we need to deserialize an `array<string,User>` where a user can be null. Furthermore, `User` has a couple of subclasses. Whenever we try to deserialize such map, we got the following error:

```
The discriminator field name "type" for base-class "Acme\User" was not found in input data.
```

Is this the expected behavior?

**Comment by goetas** [comment]
actually yes. if your type is `array<string,User>` then all the instances inside the array have to be `User` (this means having a valid `type` field). `array<string,User|null>` is not a supported feature.

**Comment by marcospassos** [comment]
Is there any workaround?

**Comment by goetas** [comment]
you can specify the array as:`array<string,NullableVirutalUser>` and add a custom type handler:

```
class StdClassHandler implements SubscribingHandlerInterface
{
    public static function getSubscribingMethods()
    {
        $methods = array();
            $methods[] = array(
                'direction' => GraphNavigator::DIRECTION_DESERIALIZATION,
                'type' => 'NullableVirutalUser',
                'format' => 'json',
                'method' => 'deserializeNullableUser',
            );

        return $methods;
    }

    public function deserializeNullableUser(VisitorInterface $visitor, $data, array $type, Context $context)
    {
        if (!$data) { // null
            return  null;
        } else {
          return  $context->accpet($data, ['name'=> 'User', 'params' => []], $context);
        }
    }
}
```

maybe the syntax is no 100% correct, but hope you get the idea

**Comment by scaytrase** [comment]
@goetas hello, will this be supported at some point?
