### ISSUE TITLE
Missing bool type in graphNavigator.php in method accept()

### ISSUE THREAD

**Issue by Webonaute** [schmittjoh/serializer#764]
In class GraphNavigator.php in method accept() near line 139.

it missing 
case 'bool':

**Comment by goetas** [comment]
no, as you can see here, `bool` is not in the list of the default base types http://jmsyst.com/libs/serializer/master/reference/annotations#type

**Comment by goetas** [comment]
you  have to write `boolean`

**Comment by Webonaute** [comment]
oh ok. I found it.
thank
