### ISSUE TITLE
serialize_null configuration

### ISSUE THREAD

**Issue by AAtticus** [schmittjoh/serializer#77]
To be able to work with Knockout.js I require the keys of empty values to be preserved.
I thought this was added to a previous version of JMSSerializerBundle / Serializer but in the current version I can't find anything to make sure it also serializes null values.

Any suggestions?

(note: not sure if this should be posted in JMSSerializeBundle or here)

**Comment by davidspiess** [comment]
Here is an example

```php
use JMS\Serializer\SerializationContext;

$serializationContext = SerializationContext::create()->setSerializeNull(true);
$serializer->serialize($object, $format, $serializationContext);
```
