### ISSUE TITLE
Allow access to PropertyMetadata in Dynamic Exclusion strategies

### ISSUE THREAD

**Issue by bblue** [schmittjoh/serializer#772]
Is this possible to access the propertyMetada in via `$navigatorContext`, or can it be added as a variable in `ExpressionLanguageExclusionStrategy`. 

The `metadata` can be added as a variable in the same was as the `context `is.
https://github.com/schmittjoh/serializer/blob/master/src/Exclusion/ExpressionLanguageExclusionStrategy.php#L56

**Comment by goetas** [comment]
the navigator is already available via `context.getNavigator()`, regarding the metadata, PR are welcome
