### ISSUE TITLE
Why custom EventDispatcher?

### ISSUE THREAD

**Issue by enumag** [schmittjoh/serializer#773]
Why does this package use a custom EventDispatcher instead of symfony/event-dispatcher? If there is no benefit (I don't see any), can you refactor it?

I'm asking this because whenever I need to use a class from synfony/event-dispatcher, PHPStorm suggests classes from this package first. Accidently using a class from this package leads to nasty bugs. Unfortunately PHPStorm doesn't seem to have a way to exclude a class from suggestions.

**Comment by goetas** [comment]
see https://github.com/schmittjoh/serializer/pull/750#issuecomment-297453441
