### ISSUE TITLE
doctrine/annotations now requires php 7.1

### ISSUE THREAD

**Issue by sdevore** [schmittjoh/serializer#795]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

Your composer requirement for "doctrine/annotations": "^1.0", now wants to load 
doctrine/annotations[1.5.x-dev] which now requires 7.1  version 1.4.x for annotations doesn't at this time.  Your requirements allow php 5.6.x+ so this seems to be in a bit of a conflict

**Comment by goetas** [comment]
`^1.0` means any of 1.0, 1.1, 1.2, 1.3, 1.4 and so on... so depending on your environment, composer will choose the best (latest) version possible
