### ISSUE TITLE
Add support for overriding default annotation driver configuration

### ISSUE THREAD

**Issue by noemi-salaun** [schmittjoh/serializer#804]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

I think it would be handy to set up the default behavior of the `AnnotationDriver`.
Currently, if we want all our classes to be readOnly, we must specify it with the annotation in each class, one by one. Same for the `exclusionPolicy` and the `accessType`.

When creating a serializer with the `DefaultDriverFactory`, we don't have any way to set this defaults behavior, so the factory can create an `AnnotationDriver` with this same defaults.

In all cases, the factory can still use the same default values if no configuration is specified, so there is no breaking change.

To go further, it would be cool to be able to access these options from the yml configuration in the Symfony bundle.

See mirror issue https://github.com/schmittjoh/JMSSerializerBundle/issues/586

## Contributing

Actually, I already did the implementation in my project, by extending the `DefaultDriverFactory` and the `AnnotationDriver`. I can submit a PR for this feature. Just tell me :wink:

**Comment by goetas** [comment]
Closing for the same reasons as https://github.com/schmittjoh/JMSSerializerBundle/pull/427
