### ISSUE TITLE
The sub-class "Proxies\__CG__\AppBundle\Entity\SomeClass" is not listed in the discriminator of the base class "AppBundle\Entity\SomeBaseClass"

### ISSUE THREAD

**Issue by jhonatanTeixeira** [schmittjoh/serializer#805]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

jms serializer-bundle ^2.0
jms serializer ^1.7

I'm having this issue with the serializer now in a case wich i serialize a doctrine proxy class and when i try to deserialize i get this error:
The sub-class "Proxies\__CG__\AppBundle\Entity\SomeClass" is not listed in the discriminator of the base class "AppBundle\Entity\SomeBaseClass"

this is my base class
```php
/** 
 * @ORM\DiscriminatorMap({
 *      "concrete1" = "Concret1", 
 *      "concrete2" = "Concret2", 
 *      "concrete3" = "Concret3"
 * })
 * @JMS\Discriminator(field = "type", groups={"read", "write"}, map = {
 *    "concrete1": "AppBundle\Entity\Concret1",
 *    "concrete1": "AppBundle\Entity\Concret2",
 *    "concrete1": "AppBundle\Entity\Concret3"
 * })
 */
abstract class SomeBaseClass
{
    //...... code
}

class Concrete3 extends SomeBaseClass
{
    //.....code
}
```

at some point on my code more specificaly on a doctrine subscriber method i serialize the Concrete3 class and send over Amqp to another service. And when that service tries to deserialize i get this error.

Any tips someone? isit an issue?

looking at the line thats reporting the exception i got this code

```php
        if ($this->discriminatorMap && !$this->reflection->isAbstract()) {
            if (false === $typeValue = array_search($this->name, $this->discriminatorMap, true)) {
                throw new \LogicException(sprintf(
                    'The sub-class "%s" is not listed in the discriminator of the base class "%s".',
                    $this->name,
                    $this->discriminatorBaseClass
                ));
            }
            //,,,,,
```
it seens it isnt meant to handle doctrine proxies, is there any workaround?

Thanks

**Comment by goetas** [comment]
can you share the full stack trace? this error should be when serializing...

**Comment by goetas** [comment]
No, feedback. closing

**Comment by goetas** [comment]
Thank you for the feedback. 
If you are able to provide more info to reproduce this, I'm definitively ready to re-open this ticket.

If I can not reproduce the issue or I do not have enough info about the problem itself, I ask some commitment to the developer signaling the issue, this means at least replying to the ticket.
