### ISSUE TITLE
Add "bool" Annotation/Type

### ISSUE THREAD

**Issue by VincentChataignier** [schmittjoh/serializer#807]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Can we add the type "bool"  to Annotation/Type with "boolean" type ?
Like "integer" and "int" type.

Example : 
```php
/**
* @Assert\Type(type="bool")
*/
```

Thank you for your feedback :smiley:

**Comment by goetas** [comment]
why not :) PR are welcome!

**Comment by VincentChataignier** [comment]
Ok :smiley:  I will try to analyse the code and adding with PR.

**Comment by goetas** [comment]
tests and documentation in this case are nice to have :)

**Comment by Majkl578** [comment]
#818
