### ISSUE TITLE
XML Discriminator tags don't work in YAML metadata

### ISSUE THREAD

**Issue by jonty-comp** [schmittjoh/serializer#811]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I don't know if i'm missing something obvious, but when I try to set the `xml_*` attributes in my YAML metadata file, they have no effect.  The example below highlights the `xml_attribute` tag, but `xml_cdata` and `xml_namespace` don't seem to work either.

I tracked what I believe to be the problem down to [`JMS/Serializer/Metadata/ClassMetadata.php#L142`](https://github.com/schmittjoh/serializer/blob/1fcacaa/src/JMS/Serializer/Metadata/ClassMetadata.php#L142), where the discriminator properties are set on the merged metadata object, and successfully "fixed" the issue by adding the following:
```
            $this->xmlDiscriminatorAttribute = $object->xmlDiscriminatorAttribute;
            $this->xmlDiscriminatorCData = $object->xmlDiscriminatorCData;
            $this->xmlDiscriminatorNamespace = $object->xmlDiscriminatorNamespace;
```
in between discriminator merge check statements, but as I said, I feel like I might be missing something obvious!

If this is indeed what must be changed, then I can submit a quick PR with the above changes in.  Otherwise, i'd appreciate being shown where my error is!

## Steps required to reproduce the problem

My metadata file contains:

```
  discriminator:
    field_name: type
    map:
      aperture: MyCompany\Visualisation\Element\MountElement\Aperture
      mount_line: MyCompany\Visualisation\Element\MountElement\MountLine
    xml_attribute: true
```

## Expected Result
```
      <mount_elements>
        <element type="aperture">
          <x_mm>28.5</x_mm>
          <y_mm>28.5</y_mm>
          <width_mm>248</width_mm>
          <height_mm>197</height_mm>
          <colour>srgb(255,255,255)</colour>
        </element>
      </mount_elements>
```

## Actual Result

```
      <mount_elements>
        <element>
          <x_mm>28.5</x_mm>
          <y_mm>28.5</y_mm>
          <width_mm>248</width_mm>
          <height_mm>197</height_mm>
          <colour>srgb(255,255,255)</colour>
          <type><![CDATA[aperture]]></type>
        </element>
      </mount_elements>
```

**Comment by goetas** [comment]
which serializer version are you using?

**Comment by goetas** [comment]
It is weird because `testDiscriminatorAsXmlAttribute` is exactly there to ensure it works https://github.com/schmittjoh/serializer/blob/fe455eed56b5bc6468615d585217984cc979fb38/tests/Serializer/XmlSerializationTest.php#L445

**Comment by jonty-comp** [comment]
I'm on version 1.8.1 of serializer and 1.6.0 of metadata.  Could it be unique to YAML metadata? 

I can do some more testing later today.

**Comment by jonty-comp** [comment]
So I've tried to mock the structure of my scripts in a new repository, and it seems to be working fine there...([`jonty-comp/yaml-serializer-test`](https://github.com/jonty-comp/yaml-serializer-test))

In particular, the YAML metadata file at [`metadata/ObjectWithXmlAttributeDiscriminatorParent.yml`](https://github.com/jonty-comp/yaml-serializer-test/blob/5711e60cce29eb4fd721f8f5c589d1e73b302d83/metadata/ObjectWithXmlAttributeDiscriminatorParent.yml) exactly mirrors (other than variable/class names) the one in my project which is seemingly ignoring the `xml_attribute` tag.  It is also at the same nesting level below the top-level object I'm serializing/deserializing to/from.

I will continue trying to make the mock project more and more like my failing project and see whether there is indeed something I have written that is causing the wrong behaviour.

**Comment by goetas** [comment]
@jonty-comp closing for now then.
