### ISSUE TITLE
Doctrine LazyCriteriaCollection not supported

### ISSUE THREAD

**Issue by sandermarechal** [schmittjoh/serializer#814]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

It seems that the `ArrayCollectionHandler` does not support Doctrine's new `Doctrine\ORM\LazyCriteriaCollection`. When serializing it, the serializing attempts to serialize the collection object itself, not the contents.

**Comment by goetas** [comment]
just put `@Type("ArrayCollection")` and it will work
