### ISSUE TITLE
Serializer fails if there is no AnnotationDriver in the DriverChain instance

### ISSUE THREAD

**Issue by korotovsky** [schmittjoh/serializer#815]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Setup MetadataFactory with YamlLoader only
2. Pass object that has no mapping for serialization
3. In the line `$metadata = $this->metadataFactory->getMetadataForClass($type['name'])` (https://github.com/schmittjoh/serializer/blob/1.8.1/src/JMS/Serializer/GraphNavigator.php#L211) we have got `null` because metadata was not found for this class.

In common Symfony installations everyone has `ChainLoader` that has `YamlLoader`, `XmlLoader`, `PhpLoader` and `AnnotationLoader` <--. The `AnnotationLoader` creates `ClassMetadata` each time, even if there is no mapping for the particular class, but `YamlLoader` does not create. Moreover it filters `NullMetadata` and returns `null` — so as a result the whole Serializer failed due to internal errors.

As for now, I had to enable `AnnotationReader` to have metadata even for classes without mapping files, but I think that's a bug of the serializer library, because it makes no sense to force end-user include `AnnotationDriver` eve if I don't need it.

## Expected Result

* No Fatal Error

## Actual Result

* `Argument 1 passed to JMS\Serializer\Exclusion\VersionExclusionStrategy::shouldSkipClass() must be an instance of JMS\Serializer\Metadata\ClassMetadata, null given, called in /app/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php on line 221`

I purpose to add default fallback driver without any dependencies:

```php
class NullDriver implements DriverInterface
{
    public function loadMetadataForClass(\ReflectionClass $class)
    {
        $classMetadata = new ClassMetadata($name = $class->name);
        $classMetadata->fileResources[] = $class->getFilename();

        return $classMetadata;
    }
}
```

or to take care of `null` metadata in the `GraphNavigator`

**Comment by goetas** [comment]
see https://github.com/schmittjoh/serializer/pull/822
