### ISSUE TITLE
 Node no longer exists - Deserialize Error

### ISSUE THREAD

**Issue by mikaelplouhinecvetup** [schmittjoh/serializer#817]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1.  Initiate the deserializer
2. Deserialize the data

## Expected Result

No Warning 

## Actual Result

<table border="1">
	<tr><td>str : </td><td>JMS\Serializer\XmlDeserializationVisitor::isNull(): Node no longer exists</td></tr>
	<tr><td>line : </td><td>402</td></tr>
	<tr><td>file : </td><td>/var/www/myApp/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php</td></tr>
	<tr><td>Warning on : </td><td>localhost</td></tr>
	<tr><td>no : </td><td>2</td></tr>
	<tr><td>callStack : </td><td><br>ln: 402 on /var/www/myApp/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php, function errorHandler<br>ln: 130 on /var/www/myApp/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php, function isNull<br>ln: 266 on /var/www/myApp/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php, function accept<br>ln: 267 on /var/www/myApp/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php, function visitProperty<br>ln: 193 on /var/www/myApp/vendor/jms/serializer/src/JMS/Serializer/Serializer.php, function accept<br>ln: 128 on /var/www/myApp/vendor/jms/serializer/src/JMS/Serializer/Serializer.php, function visit<br>ln: ? on ?, function JMS\Serializer\{closure}<br>ln: 89 on /var/www/myApp/vendor/phpoption/phpoption/src/PhpOption/Some.php, function call_user_func<br>ln: 131 on /var/www/myApp/vendor/jms/serializer/src/JMS/Serializer/Serializer.php, function map<br>ln: 355 on /var/www/myApp/modules/abaxis/abaxisControllerAjax.php, function deserialize<br></td></tr>
	<tr><td>userAgent : </td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36</td></tr>
</table>

<table>
	<tr><td >errContext :<br>>array(2) {
  ["value"]=>
  object(SimpleXMLElement)#102 (0) {
  }
  ["xsiAttributes"]=>
  object(SimpleXMLElement)#100 (0) {
  }
}
</td></tr>
</table>

[attachments.zip](https://github.com/schmittjoh/serializer/files/1277080/attachments.zip)

**Comment by goetas** [comment]
from the stack trace it looks you are using a custom error handler... the error reported by you is silenced...  is the implementation of your handler correct?

**Comment by mikaelplouhinecvetup** [comment]
Yes.
My object is deserialize correctly but I have this exception.

**Comment by goetas** [comment]
can you share your errorhandler code?

**Comment by goetas** [comment]
forwarding to https://bugs.php.net/bug.php?id=75168

**Comment by goetas** [comment]
@mikaelplouhinecvetup can you try https://github.com/schmittjoh/serializer/pull/825 ?
