### ISSUE TITLE
Mapping request payload works for JSON but not for XML

### ISSUE THREAD

**Issue by BentCoder** [schmittjoh/serializer#820]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I have a model which is used to map JSON and XML payloads. JSON mapping works fine but XML doesn't. I asked similar question [here](https://github.com/schmittjoh/JMSSerializerBundle/issues/470) but it was ignored with a passion!

Property `random` contains random/unknown/dynamic properties so I can not hardcode them. How do you map such properties?

Thanks

**MODEL**
```
/**
 * @Serializer\XmlRoot("data")
 */
class Data
{
    /**
     * @Serializer\Type("array<string>")
     * @Serializer\XmlValue
     */
    public $random;
}
```
**JSON**
```
{
  "random": {
    "hello": "world",
    "colour": "blue",
    "age": "19"
  }
}
```

**RESULT**
```
Data Object
(
      [random] => Array
          (
              [hello] => world
              [colour] => blue
              [age] => 19
          )
)
```

**XML**
```
<?xml version="1.0" encoding="UTF-8"?>
<data>
    <random>
        <hello>world</hello>
        <colour>blue</colour>
        <age>19</age>
    </random>
</data>
```

**RESULT**
```
Data Object
(
      [random] => Array
          (
          )
)
```

This won't map either:
```
@Serializer\Type("array<string, string>")
@Serializer\XmlKeyValuePairs
```

**Comment by goetas** [comment]
Random has to be a type. you should create a class that contains the fields hello, color, age. can't be just a plain array.

An alternative solutioni is custom type handler.

```php
/**
 * @Serializer\XmlRoot("data")
 */
class Data
{
    /**
     * @Serializer\Type("MyType")
     */
    public $random;
}
```

```php

class MyHandler implements SubscribingHandlerInterface
{
    public static function getSubscribingMethods()
    {
        return array(
            array(
                'direction' => GraphNavigator::DIRECTION_DESERIALIZATION,
                'format' => 'xml',
                'type' => 'MyType',
                'method' => 'deserializeMyType'
            ),
            array(
                'direction' => GraphNavigator::DIRECTION_SERIALIZATION,
                'format' => 'xml',
                'type' => 'MyType',
                'method' => 'serializeMyType'
            )
        );
    }

    public function serializeAnyType(XmlSerializationVisitor $visitor, $data, array $type, Context $context)
    {
        // serialize your object here
    }

    public function deserializeAnyType(XmlDeserializationVisitor $visitor, $data, array $type)
    {
        // deserialize your object here
    }
}
```

**Comment by goetas** [comment]
Not sure which is the format for `XmlKeyValuePairs`, will re-open for now

**Comment by BentCoder** [comment]
For unknown class properties: all we need is to achieve result below after sending an appropriate JSON and XML request payload.

```
Data Object
(
      [random] => Array
          (
              [hello] => world
              [colour] => blue
              [age] => 19
          )
)
```

If the model below works (it does!) for JSON then it should also work for XML by default.

```
/**
 * @Serializer\XmlRoot("data")
 */
class Data
{
    /**
     * @Serializer\Type("array<string>")
     * @Serializer\XmlValue
     */
    public $random;
}
```

I am happy to change the model as long as I can make XML mapping happy so I would be greateful if you could show me an example.

Thanks

**Comment by goetas** [comment]
checked right now, `xmlKeyValuePairs` is not implemented when de-serializing... will be happy to accept a pull request!
