### ISSUE TITLE
Dynamic exclusion strategy, Variable "object" is not valid

### ISSUE THREAD

**Issue by InfopactMLoos** [schmittjoh/serializer#826]
| Q                | A
| ---------------- | -----
| Bug report?      | not sure?
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Enable Expression Language exclusion strategy as per: [https://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#dynamic-exclusion-strategy](https://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#dynamic-exclusion-strategy)
2. Use the object variable in a expression within the Expose annotation on a class property, like so:
```
@Serializer\Expose(if="object.isRedacted() === false")
```
3. Call deserialize on a string using this class, like so:
```
$serializer->deserialize($requestBody, 'MyClass', 'json');
```
4. Receive exception:
```
Variable \"object\" is not valid around position 3 for expression `!(object.isRedacted() === false)`.
```

## Expected Result

* I expect a successful deserialization.

## Actual Result

* Serialization failed with above exception message. As I looked closer at the code it seems that the object variable is only set when there is a SerializationContext. Meaning ofcourse that this variable is not available during deserialization. You can find this in class JMS\Serializer\Exclusion\ExpressionLanguageExclusionStrategy line 60. 
Although this might be quite logical since the object is still being created (and I actually don't need this expression to be evaluated during deserialization), however how do I only enable it on serialization? Or actually what would be the best way to do this? I can ofcourse extend the expression but since I have this expression on like 106 properties I would like to keep these expressions as simple and clean as possible. Or maybe I should write a custom exclusion strategy...

**Comment by goetas** [comment]
You are right. This is an unexpected behavior of the current implementation.

A possible workaround for this can be 

`@Serializer\Expose(if="context.getDirection() === 1 && object.isRedacted() === false")`.

Actually this solution will require anyway to update the `ExpressionLanguageExclusionStrategy.php`  with

```php
L59
if ($navigatorContext instanceof SerializationContext) {
        $variables['object'] = $navigatorContext->getObject();
} else {
        $variables['object'] = null;
}
```


This solution might work but I guess there are better solutions... ideas?

**Comment by InfopactMLoos** [comment]
Yes I indeed already tried the workaround (forgot to mention) but the variable is always evaluated. Your commit seems promising though I will have a look at it. 
I was also thinking if it might be possible to catch the exception and just return false if the variable does not exist. But that might give other problems as the exception returned seems to be a generic, Symfony\Component\ExpressionLanguage\SyntaxError.

**Comment by goetas** [comment]
solved by https://github.com/schmittjoh/serializer/pull/827
