### ISSUE TITLE
Deserialization not working with camelCase

### ISSUE THREAD

**Issue by enumag** [schmittjoh/serializer#831]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

```php
class Foo
{
	/**
	 * @var string
	 * @Serializer\Type("string")
	 */
	public $name;

	/**
	 * @var string
	 * @Serializer\Type("string")
	 */
	public $firstName;
}

$data = <<<EOF
{
	"name": "FOO",
	"firstName": "whatever"
}
EOF;

$foo = $serializer->deserialize($data, 'Foo', 'json');

var_export($foo);
```

## Expected Result

```
Foo::__set_state(array(
   'name' => 'FOO',
   'firstName' => 'whatever',
))
```

## Actual Result

```
Foo::__set_state(array(
   'name' => 'FOO',
   'firstName' => NULL,
))
```

**Comment by goetas** [comment]
not a bug. depending on the default naming strategy results might be different.

the default strategy is "snake_case". 

check it [here](http://jmsyst.com/bundles/JMSSerializerBundle/master/configuration) (`property_naming`) or [here](https://github.com/schmittjoh/serializer/tree/master/src/JMS/Serializer/Naming)

**Comment by enumag** [comment]
There is no mention of naming strategy [here](http://jmsyst.com/bundles/JMSSerializerBundle/master/configuration). How exactly do I change it?

You should consider changing the default strategy in the next major release. This is wtf.

**Comment by goetas** [comment]
```yml
    property_naming:
        id: ~
        separator:  _
        lower_case: true
        enable_cache: true
```

**Comment by enumag** [comment]
Well that's the default one, right? It is still unclear how to change it from CamelCaseNamingStrategy to something different. In my case I'm guessing IdenticalPropertyNamingStrategy?

**Comment by goetas** [comment]
> Well that's the default one, right? It is still unclear how to change it from CamelCaseNamingStrategy to something different. 

not fully true. as said, the default is https://en.wikipedia.org/wiki/Snake_case 

(CamelCaseNamingStrategy is not a good name for a class, but it supports multiple naming strategies in one class...)

**Comment by enumag** [comment]
Maybe this? (I can't try it at the moment.)

```
property_naming:
    id: 'jms_serializer.identical_property_naming_strategy'
```

**Comment by enumag** [comment]
Yeah, this works as I need. But you really should consider making this default. I can send a PR if you want.

**Comment by goetas** [comment]
Since is documented, do not see anything wrong with it. Changing will be a
BC break

**Comment by enumag** [comment]
It is not documented. At least not properly. It should be mentioned in some common issues section that camelCase does not work with default configuration and how to fix it using the configuration I posted above.

**Comment by Martin-P** [comment]
@enumag Thanks for this issue, it saved me a lot of time.

For documentation (and also for internet search engines):

This used to work:
```yaml
parameters:
    jms_serializer.serialized_name_annotation_strategy.class:
        JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
```
However, not anymore, because when I tried to clear the cache in Symfony 3.3.14 using the command line (`php bin/console cache:clear`) I encountered an exception:

> [Symfony\Component\DependencyInjection\Exception\RuntimeException]                                                              
>   Cannot dump definition because of invalid class name ('JMS\\Serializer\\Naming\\IdenticalPropertyNamingStrategy'."\n".'# doctrine.dbal.default_connection')

The solution from @enumag fixed it:
```yaml
jms_serializer:
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
```

@goetas
Could you provide the link to the page where I can find the text `jms_serializer.identical_property_naming_strategy`? I did a text search on the [configuration page](http://jmsyst.com/bundles/JMSSerializerBundle/master/configuration), but get no results. Am I looking on the wrong page? Thanks!
