### ISSUE TITLE
Disable all the Doctrine metadata stuff

### ISSUE THREAD

**Issue by miguelrs** [schmittjoh/serializer#834]
Question

I use JMS Serializer and I really like explicitness in code, so I have all my YAML files where I configure the (de)serialization for each of my entities 👌  

However, I noticed that there's a lot of stuff going on in this library in order to get metadata information about the objects being (de)serialized from Doctrine mapping files and so on...  
I understand that all that stuff may useful in some scenarios, but it's a bit confusing and slow...

Basically I'd like a behaviour as similar as possible to:  
> Given an object to be (de)serialized, if there's a YAML file for it in a particular directory, proceed according to that file; and if not, do nothing, or better yet, throw an exception...

I want as little magic as possible going on - is there any configs I can set for that purpose?

The only config I have is (using the Bundle):
```
jms_serializer:
    metadata:
        auto_detection: false
        directories:
            my_dir:
                namespace_prefix: "My\\Entity\\Directory"
                path: "@MyBundle/Resources/config/serialization"
```

**Comment by goetas** [comment]
- if you are worried about speed, consider that all the metadata are cached in plain php files, so when a class is met for the  first time, all the data are cached. So no speed penalties from metadata collection.
- some doctrine proxies handling is necessary if you are using doctrine and is highly recommended.


Which kind of "extra-stuff" would you like to remove/skip in particulare?

**Comment by miguelrs** [comment]
@goetas Thanks a lot for your quick response - actually my problem is I have a pretty big project and I've noticed _lots_ of disk access from JMS, which seem to correspond to cache reads, and that's causing performance decrease...  

I'm not sure why that's happening because I've not explored the code very deeply, but I did see there's a lot of metadata collecting going on from Doctrine mapping files, which is something I'm not using at all, so I'd like a way to disable it... (Note: apart from the performance, I've had issues because my YAML files were wrongly placed and I was getting weird results, because it was silently using Doctrine metadata, when I was expecting it to throw and tell me my YAML file wasn't found).

Maybe that doesn't solve my problem, and actually I'm considering writing my own caching service not using file cache, but this seems a bit more complex, and I've not found any info or examples about this, so I was just trying to find out if I can "simplify" the config somehow so performance increases, before going for this option...

**Comment by goetas** [comment]
if you see in your disc access "doctrine", is because the cache library used here is doctrine/cache (but has nothing to do with Doctrine ORM)

the file strategy is only one of the supported backends, as you can see [here](https://github.com/doctrine/cache/tree/master/lib/Doctrine/Common/Cache) the list of supported backends is pretty big.

I personally on most of projects i'm using a files, a local redis or apcu. never had any problem (one of the biggest project i worked had approximately 5000-7000 different class types to serialize/deserialize)

**Comment by goetas** [comment]
Closing as is not really an issue

**Comment by goetas** [comment]
An issue you might face if you have a lot of entities is that the cache folder can be pretty big (in the sense that has a lot of files), and depending you your file system, file access can be slower.

ext3 has a limit of 32k files, and suggested to not go upper than 10k.

You might try `PhpFileCache` that should take advantage of php's OP cache

**Comment by miguelrs** [comment]
👌 thanks a lot for your help - I don't think that's my issue as I don't have so many entities...  
I think I will try to explore the possibility to write my own cache adapter to avoid the file access...  

Anyway, the ability to disable all the usage of doctrine metadata, not just for performance, but simply for explicitness is something that would be nice... This library is great, but imho sometimes it tries to be too smart, which sometimes is good, but sometimes is a bit confusing...

**Comment by goetas** [comment]
are you using it as standalone or with symfony?

**Comment by goetas** [comment]
if symfony, you can disable the doctrine introspection with: 

```yaml
jms_serializer:
    metadata:
        infer_types_from_doctrine_metadata: false
```

**Comment by miguelrs** [comment]
I'm using it with Symfony. Great, I think that's exactly what I was looking for! Couldn't see that in any docs...
Thanks a lot again 👍

**Comment by miguelrs** [comment]
Still I don't think that will solve my issue and I'll need to write a custom cache adapter, but that's very useful

**Comment by goetas** [comment]
just out of curiosity, which kind of cache adapter do you have in mind? why one of the doctrine provided adapters is not good?

**Comment by miguelrs** [comment]
actually, looking at it, yeah you're right - I think all I need is add a service definition for one of those adapters and set its alias to the jms serializer config 🤔   
sorry I haven't got much experience with PHP caching in general 😅

**Comment by goetas** [comment]
jms_serializer:
    metadata:
        cache: 'your_service_id_here'

**Comment by miguelrs** [comment]
yeah exactly 👍  nice support mate, thanks!
