### ISSUE TITLE
DateTime format documentation

### ISSUE THREAD

**Issue by enumag** [schmittjoh/serializer#836]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The [documentation](https://jmsyst.com/libs/serializer/master/reference/annotations#type) of the `@Type` annotation is unclear what the default format for DateTime / DateTimeImmutable actually is.

Also is there a way to use predefined format like `\DateTime::ATOM`? I mean without actually writing the format with `@Type("DateTimeImmutable<'Y-m-d\TH:i:sP'>")`.

**Comment by goetas** [comment]
> The documentation of the @Type annotation is unclear what the default format for DateTime / DateTimeImmutable actually is.

the default format is decided [here](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Handler/DateHandler.php#L64) or [here](https://jmsyst.com/bundles/JMSSerializerBundle/master/configuration#configuration-block-2-0) if you are using symfony

> Also is there a way to use predefined format like \DateTime::ATOM? 

currently no, there is no way to specify constants

PR on the documentation are welcome, the sources are[here](https://github.com/schmittjoh/serializer/tree/master/doc)

**Comment by enumag** [comment]
Hmm this seems a bit odd. The configuration page you linked claims it has the default values - and there is `\DateTime::ATOM` there. Yet the source code you also linked has `\DateTime::ISO8601` as default.

I realize that the constructor's default value is probably not actually used and I also found out in the meantime that the default configuration actually was `\DateTime::ISO8601` in previous versions. So the default value in `DateHandler` is a leftover and maybe it should be changed to ATOM as well? Should I send a PR?

**Comment by enumag** [comment]
For the documentation I thought I would change the "default format" string to a link to `https://jmsyst.com/bundles/JMSSerializerBundle/master/configuration#extension-reference`. However I'm not sure how to write this kind of link since it would go from Serializer docs to JMSSerializerBundle docs.

**Comment by goetas** [comment]
> I realize that the constructor's default value is probably not actually used and I also found out in the meantime that the default configuration actually was \DateTime::ISO8601 in previous versions. So the default value in DateHandler is a leftover and maybe it should be changed to ATOM as well? 

Not fully true, it depends if you are using the standalone library or the symfony bundle. Thats why I sent you the two separate links.

> Should I send a PR?
For documenting it OK, if you want ti change defaults, NO as it will result in a BC break.

**Comment by goetas** [comment]
> For the documentation I thought I would change the "default format" string to a link to https://jmsyst.com/bundles/JMSSerializerBundle/master/configuration#extension-reference. However I'm not sure how to write this kind of link since it would go from Serializer docs to JMSSerializerBundle docs.

it depends which part you want to change.
