### ISSUE TITLE
Problem deserialize xml with namespace: xmlns="http://www.w3.org/2000/09/xmldsig#" in tag root

### ISSUE THREAD

**Issue by martinepic** [schmittjoh/serializer#837]
Hello, I have an xml with namespace: xmlns = "http://www.w3.org/2000/09/xmldsig#" and Unfortunately the jms does not work when trying to deserialize, can someone help me?

Example:

`<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
     <TestValue>Hello Jms</TestValue>
</Signature>`

**Comment by martinepic** [comment]
@goetas can you inform me?

**Comment by martinepic** [comment]
Any position?

**Comment by martinepic** [comment]
@goetas I have a class that makes a call Signature, 
But not in this example, only class Signature.
Can this help you?

example:
<?php

namespace Presentation\DataTransferObject\Signature;

use JMS\Serializer\Annotation as A;

/**
 * @A\XmlNamespace(uri="http://www.w3.org/2001/XMLSchema")
 * @A\XmlNamespace(uri="http://www.w3.org/2000/09/xmldsig#")
 */
class Signature
{
    /**
     * @var SignedInfo
     * @A\Type("Presentation\DataTransferObject\Signature\SignedInfo")
     */
    private $SignedInfo;

    /**
     * @var string
     * @A\Type("string")
     */
    private $SignatureValue;

    /**
     * @var KeyInfo
     * @A\Type("Presentation\DataTransferObject\Signature\KeyInfo")
     */
    private $KeyInfo;
}

**Comment by martinepic** [comment]
`<?php

namespace Presentation\DataTransferObject\Signature;

use JMS\Serializer\Annotation as A;

/**
 * @A\XmlNamespace(uri="http://www.w3.org/2001/XMLSchema")
 * @A\XmlNamespace(uri="http://www.w3.org/2000/09/xmldsig#")
 */
class Signature
{
    /**
     * @var SignedInfo
     * @A\Type("Presentation\DataTransferObject\Signature\SignedInfo")
     */
    private $SignedInfo;

    /**
     * @var string
     * @A\Type("string")
     */
    private $SignatureValue;

    /**
     * @var KeyInfo
     * @A\Type("Presentation\DataTransferObject\Signature\KeyInfo")
     */
    private $KeyInfo;
}
`

**Comment by martinepic** [comment]
@goetas 

`<?php

namespace Presentation\DataTransferObject\Signature;

use JMS\Serializer\Annotation as A;

/**
 * @A\XmlNamespace(uri="http://www.w3.org/2001/XMLSchema")
 * @A\XmlNamespace(uri="http://www.w3.org/2000/09/xmldsig#")
 */
class Signature
{
    /**
     * @var SignedInfo
     * @A\Type("Presentation\DataTransferObject\Signature\SignedInfo")
     */
    private $SignedInfo;

    /**
     * @var string
     * @A\Type("string")
     */
    private $SignatureValue;

    /**
     * @var KeyInfo
     * @A\Type("Presentation\DataTransferObject\Signature\KeyInfo")
     */
    private $KeyInfo;
}
`

**Comment by martinepic** [comment]
My xml example

`<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
            <SignedInfo>
                <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
                <Reference URI="Rps150">
                    <Transforms>
                        <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
						<Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                    </Transforms>
                    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                    <DigestValue>Teste</DigestValue>
                </Reference>
            </SignedInfo>
            <SignatureValue>Teste
            </SignatureValue>
`

**Comment by martinepic** [comment]
My xml example

`<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
            <SignedInfo>
                <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
                <Reference URI="Rps150">
                    <Transforms>
                        <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
						<Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                    </Transforms>
                    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                    <DigestValue>Teste</DigestValue>
                </Reference>
            </SignedInfo>
            <SignatureValue>Teste</SignatureValue>
</Signature>
`

**Comment by martinepic** [comment]
@goetas possible bug?

**Comment by goetas** [comment]
XmlElement annotation with the property "namespace" needs to be defined on
each property

**Comment by goetas** [comment]
http://jmsyst.com/libs/serializer/master/reference/annotations#xmlelement

**Comment by martinepic** [comment]
@goetas thank you.
