### ISSUE TITLE
Allow serialization groups to be accessible within event subscriber callbacks.

### ISSUE THREAD

**Issue by craigmarvelley** [schmittjoh/serializer#84]
I'm using event subscribers to add additional data post-serialize. I'd like to only add certain properties if a particular exclusion strategy group is active, but can't see a way to access that information from within the callback. Assuming I haven't missed something, would it be possible to add this functionality, perhaps by making it available from the event? I'd make a PR if so.

**Comment by goetas** [comment]
see https://github.com/schmittjoh/serializer/issues/554
