### ISSUE TITLE
ExclusionStrategy backward compatibility break

### ISSUE THREAD

**Issue by michal-hary** [schmittjoh/serializer#843]
| Q                | A
| ---------------- | -----
| Bug report?      | yes?
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

## Steps required to reproduce the problem

In v.1.9.0 ExclusionStrategy::shouldSkipProperty skips only main properties , in 1.9.1 it skips properties of embed object too. It's a bug or backward compatibility break (shouldn't be due to Semantic Versioning)

## Example config

	// Product Entity
		/**
		 * @var int
		 * @JMS\Groups({"prod"})
		 */
		protected $id;
		
		/**
		 * @var Category
		 * @JMS\Groups({"prod"})
		 */
		protected $cat;
		
		/**
		 * @var string
		 * @JMS\Groups({"prod"})
		 */
		protected $shortName;

		
	// Category Entity

		/**
		 * @var int
		 * @JMS\Groups({"prod"})
		 */
		protected $id;
		
		/**
		 * @var string
		 * @JMS\Groups({"prod"})
		 */
		protected $shortName;

## Expected Result (version v1.9.0)

* If I exclude shortName, Shop::shortName is not excluded

## Actual Result (version v1.9.1 and 1.9.2)

* If I exclude shortName, Shop::shortName is excluded

**Comment by goetas** [comment]
are you serializing to json or xml?

**Comment by michal-hary** [comment]
To JSON

**Comment by michal-hary** [comment]
It's nice feature (if it's not a bug), but due to backward compatibility break it can cause problems

I solve problem by adding this code to shouldSkipProperty

        if ($navigatorContext->getDepth() > 1) {
            return false;
        }

**Comment by goetas** [comment]
I'm not sure is a bug/bc break what you are reporting. as you can see https://github.com/schmittjoh/serializer/compare/1.9.1...1.9.2 have almost no changes (especially if you are dealing with json

**Comment by michal-hary** [comment]
Sorry, I just checked, the last version I had used have been 1.9.0, not 1.9.1.

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/compare/1.9.0...1.9.2 is not much different anyway

**Comment by michal-hary** [comment]
Ok. It's related to some other library. It is a coincidence, but last package update caused problem i thought it is related to Serializer. I'm sorry for the trouble

**Comment by goetas** [comment]
:+1:
