### ISSUE TITLE
Serializing a self-referencing object returns null

### ISSUE THREAD

**Issue by turbo-tony** [schmittjoh/serializer#845]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Create a self-referencing object:

```php
class A
{
    /**
     * @var string
     * 
     * @JMS\Expose
     * @JMS\Groups({"label"})
     */
    public $label = 'text';

    /**
     * @var A[]
     * 
     * @JMS\Expose
     * @JMS\Groups({"associations"})
     */
    public $associations = [];
}
```

Then:

```php
$a = new A();
$a->associations[] = $a;
```

2. Serialize the object with default serializer and graph navigator. Use a [complex serialization group](https://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#overriding-groups-of-deeper-branches-of-the-graph) to avoid infinite recursions:

```php
$groups = [
    "label",
    "associations",
    "associations" => ["label"],
];
$context = new SerializationContext();
$context->setGroups($groups);

return $serializer->serialize($a, 'json', $context);
```

## Expected Result

```json
{
    "label": "text",
    "associations": [
        {
            "label": "text"
        }
    ]
}
```

## Actual Result

```json
{
    "label": "text",
    "associations": [
        null
    ]
}
```

# Remarks

* The cause of the problem seems to originate from `GraphNavigator::accept`. This bit seems off:

```php
            default:
                // TODO: The rest of this method needs some refactoring.
                if ($context instanceof SerializationContext) {
                    if (null !== $data) {
                        if ($context->isVisiting($data)) {
                            return null;
                        }
                        $context->startVisiting($data);
                    }
```

Removing `return null` works for me.

* Although the bug was only confirmed for JSON it looks like all possible formats would be affected as well, as long as the default `GraphNavigator` is used. 

* It is possible to circumvent the problem using cloning. The following would work as expected:

```php
$a = new A();
$a->associations[] = clone $a;
```

* This is extremely old, so much that even though it can be regarded as a bug, introduction of BC breaks should be a concern here. It looks like this was written to avoid infinite recursions, at a time when complex serialization groups were not yet available.

**Comment by goetas** [comment]
Can you try with 

```php
$groups = [
    "label"
];
$context = new SerializationContext();
$context->setGroups($groups);

return $serializer->serialize($a, 'json', $context);
```

please?

**Comment by turbo-tony** [comment]
```php
{
    "label": "text"
}
```

But I really want to have `associations` in the resulting JSON though. And the object really needs to contain the very same instance of itself.

The problem was originally spotted in a Symfony/Doctrine/JMS stack.

**Comment by goetas** [comment]
consider that **circular references should be serialized only once**. 
putting them inside the association makes the problem even more tricky.

do not know it this can be considered a bug.

**Comment by turbo-tony** [comment]
Don't know either, and I understand the danger of infinite loops coming with circular references.

But there should be a clean way to bypass this if needed.

**Comment by Maxooo** [comment]
Hi @goetas 

First of all, thank you for the time given to the JMS Serializer and the attention paid to the issues and feedbacks.

I understand your point of view and the main idea that object with circular reference should be serialized only once.

However I would add a precision to this postulate which is incorrect to me : An object with circular reference should be serialized only once __in a specific context__.

Let me explain : 

In the following sample, we are in the first level (main) context.

```
{
    "label": "text", // <-- Here
    "associations": [
        ...
    ]
}
```

In this second one, we are in a children context.

```
{
    ...
    "associations": [
        {
            "label": "text" // <-- Here
        }
    ]
}
```

And in this third one, in a children context too.

```
{
    ...
    "associations": [
        {
            ...
            "associations": [
                {
                    "label": "text" // <-- Here
                }
        ]
    ]
}
```

What I want to say is : how to know that an object has a circular reference, if you don't display it at least one time in a different context (here, children context) ?

**Comment by goetas** [comment]
> An object with circular reference should be serialized only once in a specific context.

agree with this. How can this be implemented (in a safe and backward compatible way)?
I'm open to hear proposals here

> The null value is not a good indicator to show circular reference (in any case for the first children context)

This is also true. checking for null values inside the array is not a good idea... but without solving the *"An object with circular reference should be serialized only once in a specific context."* (as you said) i guess this can not be solved anyway

**Comment by Maxooo** [comment]
Thank you for your fast answer, your analysis and your approach with which I agree.

I think we need to give us some time to cogitate and implement a safe sustainable solution (backward compatible as you said).

Thanks again, we will come back with a serious implementation.

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/pull/743/commits/94c319db88883757a14ac267115272be030aef28
