### ISSUE TITLE
Exception when clearing cache in Symfony2

### ISSUE THREAD

**Issue by tomazahlin** [schmittjoh/serializer#848]
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in vendor/jms/serializer/src/JMS/Serializer/EventDispatcher/LazyEventDispatcher.php on line 31

**Comment by goetas** [comment]
which php version are you using?

**Comment by goetas** [comment]
No, feedback. closing
