### ISSUE TITLE
setSerialiseNull(true) + exclusion strategies still include data

### ISSUE THREAD

**Issue by carnage** [schmittjoh/serializer#852]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | maybe (It worked as expected on a very old version, possibly prior to 1.0.0)
| RFC?             | no

## Steps required to reproduce the problem

1. Use an exclusion strategy to exclude an item from an array/hash
2. Set serialise null => true
3. Get extra null values in the array (eg item wasn't fully excluded)

## Expected Result

*  Only the items the exclusion strategy allows through are in the serialised result

## Actual Result

*  Extra nulls are included in the array/hash
* (untested) I suspect the same will happen for excluded properties. eg their value will be set null instead of the key being excluded entirely.

## Details
The issue occurs here:
https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/GenericSerializationVisitor.php#L111

When the navigator determines an item should be excluded, it returns null for that value. This works as expected if setSerialiseNull is false, however when it's true, the item gets included with a null value.

## Solution

The solution here is to have the navigator throw an UnacceptableException (https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/GraphNavigator.php#L225) when it encounters a field which should not be included in the result. That can then be caught in the code linked above and handled eg excluded from the result. 

## BC preservation
As this will now change behaviour, it may be desirable to include a configuration parameter (eg setIncludeExcludedAsNull()) to enable this new behaviour, defaulting to on. However I consider this behaviour to be a bug and is inconsistent with the behaviour when setSerialiseNull is set to false so I don't think this is required

**Comment by fsevestre** [comment]
I'm having the exact same issue after upgrading from `1.1.0` to the latest version. Do you know any workaround ?

**Comment by fsevestre** [comment]
The issue was introduces by #660 :|

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/pull/895
