### ISSUE TITLE
Annotation does not exist, or could not be auto-loaded.

### ISSUE THREAD

**Issue by rafa-acioly** [schmittjoh/serializer#855]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I'm trying to use the `Type` class but always get the error:
> The annotation "@JMS\Serializer\Annotation\Type" in property App\Product::$sellersku does not exist, or could not be auto-loaded.'

I've declare que `use` statement and used the example from `http://jmsyst.com/libs/serializer/master/reference/annotations`

this is my `xml`:

```xml
<?xml version=\"1.0\" encoding=\"UTF-8\" ?>
<Request>
  <Product>
    <SellerSku>SKU-AAAA</SellerSku>
    <Price>10.0</Price>
    <SaleStartDate>2015-07-01T11:11:11+0000</SaleStartDate>
    <SaleEndDate>2015-07-01T11:11:11+0000</SaleEndDate>
    <SalePrice>8.0</SalePrice>
  </Product>
</Request>
```

the deserialize method:

```php
$serializer = JMS\Serializer\SerializerBuilder::create()->build();
$object = $serializer->deserialize($xml, 'App\Product', 'xml');
var_dump($object);
```

the `product` class:

```php
use JMS\Serializer\Annotation\Type;
class Product
{
   /**
    * @Type("string")
    */
   public $SellerSku;

   /**
    * @Type("float")
    */
   public $Price;

   /**
    * @Type("string")
    */
   public $SaleStartDate;

   /**
    * @Type("string")
    */
   public $SaleEndDate;

   /**
    * @Type("string")
    */
   public $SalePrice;
}
```

**Comment by goetas** [comment]
make sure that the annotation autolaoder is registered as explained  on http://docs.doctrine-project.org/projects/doctrine-common/en/latest/reference/annotations.html#registering-annotations

```php
$autoloader = require "vendors/autoload.php";
AnnotationRegistry::registerLoader(array($loader, "loadClass"));
```

**Comment by rafa-acioly** [comment]
@goetas thank you, but everything is null on the object! :rofl:

**Comment by goetas** [comment]
you need an object `Request` that contains a property `Product`

**Comment by rafa-acioly** [comment]
even if i remove the `request` knot the result from `serialize` is:

`string(49) "<?xml version=\"1.0\" encoding="UTF-8"?><result/>"`

```php
$xml = "
<Product>
   <SellerSku>SKU-AAAA</SellerSku>
   <Price>10.0</Price>
   <SaleStartDate>2015-07-01T11:11:11+0000</SaleStartDate>
   <SaleEndDate>2015-07-01T11:11:11+0000</SaleEndDate>
   <SalePrice>8.0</SalePrice>
</Product>";

$p = new App\Product();
$serializer = JMS\Serializer\SerializerBuilder::create()->build();
$object = $serializer->serialize($p, 'xml');
var_dump($object);
```

**Comment by goetas** [comment]
pay attention that by default the serializer uses `snake_case` . you have to specify `@SerializedName` for for each prop (or to enable "identical name naming strategy")

**Comment by BenoitDuffez** [comment]
Updated link, valid as of today: https://www.doctrine-project.org/projects/doctrine-annotations/en/1.10/annotations.html#registering-annotations
