### ISSUE TITLE
DeserializedName

### ISSUE THREAD

**Issue by LeaklessGfy** [schmittjoh/serializer#857]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

This is a simple request in order to have an annotation like SerializedName but for deserialization process.

## Why ?
Let's guess we have a REST Api that deliver JSON objects with snake_case convention.
You call this API and deserialise the result but then you want to serialise your object in camelCase for your front.

**Comment by goetas** [comment]
ah, so you are using the same objects to consume "two" possibly different APIs (as they have different naming conventions, they may start also having different implementations...)

**Comment by goetas** [comment]
WHY not use YAML and load different metadata depending on the caller?

**Comment by LeaklessGfy** [comment]
@goetas Same object because it is indeed the same implementations. We act as a bridge, get data from a different API and retransmit it but with a different naming convention.
{API}snake_case -> [US]{API}camelCase -> front

YAML ? I'm afraid I can't see how to do that but I'm curious to see a little example if you it's possible ?

**Comment by goetas** [comment]
you can use two different set of metadata, one  will contain the info when serializing, and another when deserializing (could be a bit complicated to configure if you are using symfony... but easy if you are using it as standalone component)

**Comment by LeaklessGfy** [comment]
We are using symfony and I really can't see how to use different sets of metadata (I don't have much experience with jms YAML configuration)

**Comment by goetas** [comment]
serialize: 
```yaml
App\Entity\User:
   properties:
      userName:
         serialized_name: "user_name"
```
de-serialize: 
```yaml
App\Entity\User:
   properties:
      userName:
         serialized_name: "UserName"
```

and load selectively them (using two serializer instances)

**Comment by LeaklessGfy** [comment]
I don't think I can make two jms serializer instance with two different configuration file in symfony.
Also, it seems that it's a bit bad ... A new annotation (and configuration option in yaml) would be nicer.
Or keep SerializedName but pass it options such as : SerializedName(serialisation="snake_case", deserialisation="whatever")

**Comment by goetas** [comment]
In this case I suggest you to implement i custom naming strategy (have a look here https://github.com/schmittjoh/serializer/tree/master/src/JMS/Serializer/Naming)

**Comment by LeaklessGfy** [comment]
The naming strategy doesn't get the serialization way .. (if it's serial or deserial) so I don't think it cover our use case.

**Comment by LeaklessGfy** [comment]
If I try to make a PR of this issue would you be interested ?

**Comment by goetas** [comment]
What about adding `AdvancedPropertyNamingStrategy` and pass to it the Context?

**Comment by LeaklessGfy** [comment]
It force us to have two type of namingStrategy.
I can do that but it implies a lot of code.
Use case : what to do if PropertyNamingStrategy and Advanced* are set ? which one do the job ?

Maybe just adding Context in PropertyNamingStrategyInterface and not create a new Interface ?
