### ISSUE TITLE
Exception thrown for non-existant accessor to an excluded property

### ISSUE THREAD

**Issue by 0mars** [schmittjoh/serializer#862]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Declare a class definition with access type = public_method and an excluded property with no accessor 
2. serialize

## Expected Result

* successful serialization

## Actual Result

* Runtime Exception:
```
JMS\Serializer\Exception\RuntimeException: There is neither a public getIShallNotBeAccessed method, nor a public isIShallNotBeAccessed method, nor a public hasIShallNotBeAccessed method in class JMS\Serializer\Tests\Fixtures\ExcludePublicAccessor. Please specify which public method should be used for retrieving the value of the property iShallNotBeAccessed.
```

**Comment by goetas** [comment]
Fixed in https://github.com/schmittjoh/serializer/pull/863
