### ISSUE TITLE
Context Group not working

### ISSUE THREAD

**Issue by pesseyjulien** [schmittjoh/serializer#865]
Hi,

I'm using Groups to choose what to serialize depending on my request, and so far I had no issue until now.

If I set up my groups, as follow :

```
       $view = $this->view(array('pages' => array_values($pages)));
        $context = new Context();
        $context->addGroups(array('page'));
        $view->setContext($context);
        return $this->handleView($view);
```

I'm not seeing my reference, declared as follow : 

```
 /**
     * @MongoDB\ReferenceOne(targetDocument="Categorie", storeAs="id")
     * Groups({"page"})
     */
    protected $category;

```

I need to comment setContext in order to be able to see my field 'category' on the output.
The document 'Categorie' also have fields with the Groups "page".

I'm using this kind of configuration with similar field on other Documents, and it's working fine.
Therefore, why it's not working here ? 

I have tried clearing my cache, obviously, and many other things but the only way to make it work is by removing the context group so far. Which is not really what I'm looking for..

Any help would be welcome !

Thanks,
Julien

**Comment by goetas** [comment]
This looks more a FOS Rest issue. have you tried this https://stackoverflow.com/questions/35437023/symfony2-fosrestbundle-how-to-use-group-with-jmsserializerbundle ?

**Comment by pesseyjulien** [comment]
I did, no difference !

The thing is, the serialization based on my Group is working, just not for this particular field..

**Comment by goetas** [comment]
is the field maybe null?

**Comment by pesseyjulien** [comment]
Nop, I see everything just fine If i dont set the Context, and I have checked directly on the Database.

**Comment by goetas** [comment]
no idea currently... i can just ask you if you can reproduce  the case and send a failing test case pull request...

**Comment by pesseyjulien** [comment]
Nevermind, fixed it ! I was missing the '@' before 'Groups'.. Such a silly mistake ! 
Sorry I have wasted your time, and thanks for willing to help !
