### ISSUE TITLE
The discriminator map cannot be empty

### ISSUE THREAD

**Issue by Nehadigi** [schmittjoh/serializer#866]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no

 I am using symfony  2.8 with sonata e-commerce. Now every thing working but when I click on "Process payment button " error occurred. 
The discriminator map cannot be empty
But when I pass sub classes to Entity.Bowl.xml then error changed into 
The discriminator of class "Application\Sonata\ProductBundle\Entity\Bowl" would overwrite the discriminator of the parent class "Application\Sonata\ProductBundle\Entity\Product". Please define all possible sub-classes in the discriminator of Application\Sonata\ProductBundle\Entity\Product.

**Comment by goetas** [comment]
Did you check it it is a sonata related issue? (in general, yes, discriminator can not be empty)

**Comment by Nehadigi** [comment]
Error is resolved by adding discriminator-disabled="true" in the serializer file.
