### ISSUE TITLE
Annotation SerializedName gets ignored

### ISSUE THREAD

**Issue by AlexandreKilian** [schmittjoh/serializer#873]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Since switching to Symfony 3.4 (not sure if that is related), I'm having issues with the SerializedName annotation being ignored. Rather than using it, the serializer uses the property name or accessor methods name.

```js
"symfony/symfony": "3.4.*",
"jms/serializer-bundle": "^2.3",
"friendsofsymfony/rest-bundle": "^2.3",
``` 

in this example, I would expect the properties to be named "value" and "label":

```php
/**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * 
     * @JMS\SerializedName("value")
     * @JMS\Groups({"messages"})
     */
    public $id;
    
    /**
     * @var string
     *
     * @ORM\Column(name="message", type="text")
     * 
     * @JMS\SerializedName("label")
     * @JMS\Groups({"messages"})
     */
    public $message;
```

but the resulting json looks like this:

```json

[
{
"id": 1,
"message": "Lorem Ipsum"
},
{
"id": 2,
"message": "Dolor sit"
},
{
"id": 3,
"message": "Amet Consetetur"
}
]

```

## Steps required to reproduce the problem

1. Create a Virtual Property via Annotation @VirtualProperty
2. Set Name via Annotation @SerializedName
3. Serialize entity to Array

## Expected Result

* Field uses name specified in annotation

## Actual Result

* Field uses name of property or accessor method

**Comment by goetas** [comment]
can you reproduce the problem in a demo-project or similar?

**Comment by goetas** [comment]
@AlexandreKilian did you check https://github.com/schmittjoh/serializer/pull/874 ?

**Comment by goetas** [comment]
Few things, you are talking here about virtual properties, but I do not see virtual properties in the code posted by you. The serializedname annotation goes on the virtual property.
