### ISSUE TITLE
Problem with serializing the discriminator in class that extends model

### ISSUE THREAD

**Issue by PanzerLlama** [schmittjoh/serializer#878]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Symfony 3.4
When serializing entity that uses Discriminator and extends some base model class the annotation for groups in Discriminator is ignored.

## Steps required to reproduce the problem

1. Create class (model).

```
class Address {
    /**
     * @var string
     */
    protected $name;
}
```

2. Extend the class by creating an entity with Discriminator, use groups annotation in discriminator.

```
/**
 * @ORM\Entity
 * @ORM\Table(name="address")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string", length=16)
 * @ORM\DiscriminatorMap({
 *      "physical"  = "CustomerAddress",
 *      "billing"   = "CustomerBillingAddress"
 * })
 * @JMS\Discriminator(
 *      field = "type",
 *      map = {
 *          "home":     "CustomerAddress",
 *          "billing":      "CustomerBillingAddress"
 *      },
 *      groups = {"DefaultSerializer"}
 * )
class CustomerAddress extends Address {
    /**
     * @var string
     * @ORM\Column(type="string", length=128, nullable=true)
     * @JMS\Groups("DefaultSerializer")
     */
    protected $name;
}
```

3. Serialize entity with the DefaultSerializer context.

## Expected Result

```
{
	"name": "blah",
	"type": "home"
}
```

## Actual Result

```
{
	"name": "blah",
}
```
When I don't extend Addres but CustomerAddress is created as the base class, the serialization works properly.

Please advise.

**Comment by goetas** [comment]
Hi, sorry if it took that long (more than a year...), but somehow I've missed this...
If you are still having the issue, can you share the code used to invoke the serialization?

**Comment by FrKevin** [comment]
hello, I have same issue, when serializing entity that uses Discriminator and extends some base model class the annotation for groups in Discriminator is ignored.

**Comment by goetas** [comment]
@ebuildy the error `Symfony\Component\Serializer` says that you are using the symfony serializer, not the jms serializer

**Comment by goetas** [comment]
If some of you is able to create a failing test case and send it as PR, that would help

**Comment by goetas** [comment]
Fixed in https://github.com/schmittjoh/serializer/pull/1175
