### ISSUE TITLE
Notice when trying to de-serizlize incorrect value type

### ISSUE THREAD

**Issue by smilesrg** [schmittjoh/serializer#880]
```
Notice: Array to string conversion in /var/www/html/protected/vendor/jms/serializer/src/JMS/Serializer/GenericDeserializationVisitor.php on line 61
```

It happens when trying to de-serialize a model, one of the property type is defined as a string in configuration, but actual value is an array. Maybe in this case any exceptions have to be catched and throwed some JMS\Serializer\Exception\Exception?

**Comment by goetas** [comment]
Not sure about it... your underlying data looks to be an array, but you declared it as a string.... so a php error is what to expect.

**Comment by smilesrg** [comment]
@goetas I think it shoul be catched and converted to exception to let developer know of incorrect configuration or incorrect value.

**Comment by gitnik** [comment]
In our project we convert notices to exceptions because they often hide code smells in PHP and we thus want execution to stop. With this behaviour, we have no way to gracefully handle invalid POST data in our API. Would you be willing to accept a pull request here?

**Comment by goetas** [comment]
>Would you be willing to accept a pull request here?

Generally speaking, yes!
What would be the proposed solution? typecheck each property being visited?

**Comment by smilesrg** [comment]
>What would be the proposed solution? typecheck each property being visited?
I think yes, it's what needed!
