### ISSUE TITLE
Catchable Fatal Error after composer install - symfony 2.8

### ISSUE THREAD

**Issue by cami-typo** [schmittjoh/serializer#882]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

Running composer install on symfony 2.8 Projects with JMS\SerializerBundle as dependency ends
in error after install and cache:clear command.

Error:
  [Symfony\Component\Debug\Exception\ContextErrorException]
  Catchable Fatal Error: Argument 2 passed to JMS\Serializer\AbstractVisitor::__construct() must implement interface JMS\Serializer\Accessor\AccessorStrategyInterface, instance
  of JMS\Serializer\Construction\UnserializeObjectConstructor given, called in C:\Users\Carlos\Development\symfony\opentrans\feature-lotnumber\app\cache\de_\appDevDebugProjectCo
  ntainer.php on line 2490

**Comment by goetas** [comment]
Can you tell me the serializer bundle and versions you are using?

**Comment by statista** [comment]
we encountered the same error. The error is occuring through installation of
jms/serializer-bundle 1.10

This leads to installation of jms/serializer 1.11.0 instead of 1.5.0 (which was the last working version)

**Comment by goetas** [comment]
Can you please update the bundle to the latest 1.x version?

However I Suggest you to install the bundle 2.x that is actively developed.

It is fully backward compatible except for very few things explained on
https://github.com/schmittjoh/JMSSerializerBundle/blob/master/UPGRADING.md

Most of the canges are just optimized defaults.
