### ISSUE TITLE
Overwrite XmlVisitors for boolean properties

### ISSUE THREAD

**Issue by giero** [schmittjoh/serializer#885]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hi,

Is there any way to have custom output for boolean values while serializing/deserializing to/from xml?
In Visitors for xml: [here](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/XmlSerializationVisitor.php#L157) and [here](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/XmlDeserializationVisitor.php#L116) there are only available english values true/false, but in my xml output I would like to have those values in my own language.

I could preg_replace generated xml to replace those values, but I don't think it would be a great idea (for example there can be string fields with text 'true' which should not be changed - this should be done only for bool properties).

**Comment by goetas** [comment]
Does not sound a good idea... booleans are booleans.

If you really want to do it, you can implement a virtual type and manually map booleans to your custom type.

**Comment by giero** [comment]
You're right - booleans are booleans, but I only wanted different representation after serialization.

Few minutes ago I have found [this solution](https://stackoverflow.com/questions/20544792/automatic-translation-before-serialization-in-symfony2-with-jmsserializerbundle) and then I managed to get what I wanted :)

Case closed, thx ;)

**Comment by goetas** [comment]
The solution there is even worse.

Just use virtual types, much more elegant and no need to override a core
visitor
