### ISSUE TITLE
Avoid launching non utf8 exceptions in JsonSerializationVisitor

### ISSUE THREAD

**Issue by jcornide** [schmittjoh/serializer#894]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes

## Steps required to reproduce the problem

1.  Try to serialize some content with no utf8 characters
2. JsonSerializationVisitor will raise an exception

## Expected Result

* Encode the content to utf-8 instead

## Actual Result

* Excepton is raised

Suggestion change: JsonSerializationVisitor around line 240

```
public function getResult()
    {
        $result = @json_encode($this->getRoot(), $this->options);
        switch (json_last_error()) {
            case JSON_ERROR_NONE:
                return $result;
            case JSON_ERROR_UTF8:
                $clean = $this->utf8ize($this->getRoot());
                 return json_encode($clean, $this->options);
            default:
                throw new \RuntimeException(sprintf('An error occurred while encoding your data (error code %d).', json_last_error()));
        }
    }

private function utf8ize($mixed) 
{
                if (is_array($mixed)) {
                                foreach ($mixed as $key => $value) {
                                                    $mixed[$key] = $this->utf8ize($value);
                                                            }
                                    } else if (is_string ($mixed)) {
                                                    return utf8_encode($mixed);
                                                        }
                    return $mixed;
    }
```

**Comment by Majkl578** [comment]
This is -1 from me. Your application should only be using UTF-8 or there may be dragons. :dragon: 
If you deliberately need to work with non-UTF-8, you should do that in some bounded context and only expose valid UTF-8.

**Comment by goetas** [comment]
Agree with @Majkl578, trying to deal with utf-8 error inside this library will be something more than dangerous. Suggest to use virtual properties and ensure inside them that your data are properly encoded.
