### ISSUE TITLE
Virtual property is excluded when the name equals to an excluded property

### ISSUE THREAD

**Issue by wouterj** [schmittjoh/serializer#896]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When using a virtual property on a getter that results in the same name as an excluded property, the virtual property will be excluded as well. At least, that's what I've come across with the group exclusion policy.

```
$ composer info | grep jms
jms/metadata                         1.6.0   Class/method/property metadata management in PHP
jms/parser-lib                       1.0.0   A library for easily creating recursive-descent parsers.
jms/serializer                       1.11.0  Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
jms/serializer-bundle                2.3.1   Allows you to easily serialize, and deserialize data of any complexity
```

## Steps required to reproduce the problem

1. Create a class like:

   ```php
   use JMS\Serializer\Annotation as JMS;

   class User
   {
       private $name;

       public function __construct($name ) { $this->name = $name; }

       /**
        * @JMS\VirtualProperty
        * @JMS\Groups({"api"})
        */
       public function getName()
       {
           return ucfirst($this->name);
       }
   }
   ```

2. Serialize this into, for instance JSON:

   ```php
   $user = new User('wouterj');
   $serializationContext = SerializationContext::create()->setSerializeNull(true)->setGroups(['api']);
   print $serializer->serialize($user, 'json', $serializationContext);
   ```

## Expected Result

```json
{ "name": "Wouterj" }
```

## Actual Result

```json
{}
```

**Comment by goetas** [comment]
Hi, actually is not possible to have two properties with the same name
("getName" gets converted to "name") internally. For the 1.x this can not
be fixed as it will result in a BC break. Will be fixed in the 2.x.

**Comment by wouterj** [comment]
Thanks for your quick response! To make sure I understand things correctly: JMS first creates all properties and then excludes the ones that need exclusion?

In this case, because of the group exclusion policy, the property would not be covered by JMS at all, only the `getName()` method will be.

**Comment by goetas** [comment]
Exactly, properties are cached and stored during the first cache warmup
(during this phase the name property gets overwritten by getName because
props are stored in an associative array)  . Later at runtime exclusion
strategies are used on those properties.

**Comment by Legenyes** [comment]
Is there a solution ?
I am in version 3.12, the bug is always present.

**Comment by goetas** [comment]
@LeaklessGfy  see https://github.com/schmittjoh/serializer/commit/bd83bb54533cdef9076c2f6130f215ed1c614817#diff-243f054db7419c75f68b7af12869ca0fa56c9b75a0c3db8c5ebbe9e7007493bfR261
