### ISSUE TITLE
I want to change the default group used when overriding groups of deeper branches

### ISSUE THREAD

**Issue by FireLizard** [schmittjoh/serializer#898]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

By [Overriding Groups of Deeper Branches of the Graph](http://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#overriding-groups-of-deeper-branches-of-the-graph) how can I avoid the group 'Default' as fallback of childs not defining own group and using the last group found at the parent path instead? See [GroupsExclusionStrategy.php:81](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Exclusion/GroupsExclusionStrategy.php#L81).

Can I possibly override this exclusion strategy with my own implementation?
```php
// \JMS\Serializer\Exclusion\GroupsExclusionStrategy

private function getGroupsFor(Context $navigatorContext)
{
    $paths = $navigatorContext->getCurrentPath();

    $groups = $this->groups;
    foreach ($paths as $index => $path) {
        if (!array_key_exists($path, $groups)) {
              // Use parent group if a group was not defined
//            if ($index > 0) {
//               $groups = array(self::DEFAULT_GROUP);
//            }

              break;
        }

        $groups = $groups[$path];
    }

    return $groups;
}
```

## Environment
```
$ composer show --latest 'jms/*'
jms/metadata          1.6.0  1.6.0  Class/method/property metadata management in PHP
jms/parser-lib        1.0.0  1.0.0  A library for easily creating recursive-descent parsers.
jms/serializer        1.11.0 1.11.0 Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
jms/serializer-bundle 2.3.1  2.3.1  Allows you to easily serialize, and deserialize data of any complexity
```

## Expected Result

* Use of group of the parent path.

## Actual Result

* Group 'Default' is using.

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/pull/946
