### ISSUE TITLE
Replace in-house EventDispatcher by an existing one

### ISSUE THREAD

**Issue by Majkl578** [schmittjoh/serializer#912]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| RFC?             | yes

It would be nice to use external event dispatcher component, i.e. from Doctrine or Symfony, instead of maintaining yet another one in this library directly.

**Comment by goetas** [comment]
Was already thinking about this... 

but the symfony event dispatcher lacks some features (some kind of event categorization.....), in alternative events  should have some kind of naming scheme as:

```
$dispatcher->dispatch("jms_serializer.serialize.pre.json.App\Entity\User", new PreSerializeEvent(...))
```
And looks pretty ugly to me.


Doctrine event dispatcher? really? Where is it?

**Comment by goetas** [comment]
Closing for now as one of the biggest performance improvements for the release 2.0 was by tweaking the current event dispatcher to support JMS-specific logic (see https://github.com/schmittjoh/serializer/pull/924)
