### ISSUE TITLE
Adopt some coding standard

### ISSUE THREAD

**Issue by Majkl578** [schmittjoh/serializer#914]
| Q                | A
| ---------------- | -----
| RFC?             | yes

Would be nice to have some deterministic CS used in this library. My humble suggestion is [Doctrine CS](doctrine/coding-standard), but if you have any other specific in mind, let me know.
If you agree, I'll provide a PR (or ask someone to do so). :blush:

**Comment by goetas** [comment]
hmm sounds a good thing! (would be possible to add also some kind of build step to make it fail if the code is not well formatted?)

I guess something based on https://github.com/FriendsOfPHP/PHP-CS-Fixer or you had a different idea?

Will have a look to DoctrineCS... I'm using for private work something closer to SymfonyCS to evaluate which one should require less changes

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/pull/971 is merged
