### ISSUE TITLE
Update jms/metadata

### ISSUE THREAD

**Issue by goetas** [schmittjoh/serializer#936]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Update ` jms/metadata` to an hypothetical 2.0 version that does not use reflection anymore

**Comment by Majkl578** [comment]
Would rather get rid of it completely. :innocent:

**Comment by goetas** [comment]
And what should we use instead? We need to load/handle metadata anyway

**Comment by goetas** [comment]
WIP here https://github.com/schmittjoh/metadata/pull/67

**Comment by goetas** [comment]
done in https://github.com/schmittjoh/metadata/pull/67
