### ISSUE TITLE
Make inline property work with deserialization too

### ISSUE THREAD

**Issue by Majkl578** [schmittjoh/serializer#937]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| RFC?             | yes

This would give some love to to use first class collections which already work with serialization.

Use case:
```json
[
    {"a": 1, "b": false},
    {"a": 2, "b": false},
    {"a": 3, "b": true}
]
```

This should produce a first class collection object that holds a collection of Foos.
Should work like this (just like serialization):
```php
class FirstClassCollection implements ArrayAccess, IteratorAggregate
{
    /**
     * @Serializer\Inline
     * @var Foo[]
     */
    private $items;

    public function getIterator() : iterable
    {
         yield from $ŧhis->items;
    }

    // array access implementation
}

class Foo
{
    /** @var int */
    public $a;
    /** @var bool */
    public $b;
}
```

**Comment by goetas** [comment]
Do not understand, Should the deserialization deserialize in a class like `FirstClassCollection` or like `Foo` ?

**Comment by Majkl578** [comment]
The input JSON is an array (`[..]`), so it should return instance of FirstClassCollection.
