### ISSUE TITLE
Revert fix for #43 (JSON representation of empty objects)

### ISSUE THREAD

**Issue by Majkl578** [schmittjoh/serializer#942]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| RFC?             | yes

https://github.com/schmittjoh/serializer/blob/e75cdaf4a89ca7cd9f473c25ba0bf54c60889b5f/src/JsonSerializationVisitor.php#L112-L115

This piece of code is wrong. It breaks output for valid collections (especially first class collections with `@Inline` attribute).
It should be reverted or fixed properly, i.e. when not serializing inline collection.
This has caused troubles in past to me and consumers of my API since it violates API interface (which _returns collection of objects_ - `{}` is not an empty collection).

This was done in 66b26e97e9267ceb4cd8b47cbb8ce248d8b77b64 in order to fix #43. Unfortunately it has broken valid collections. According to the comments, it didn't even fix the root cause, only symptom for root objects.

**Comment by goetas** [comment]
Did you check https://github.com/schmittjoh/serializer/blob/master/doc/cookbook/arrays.rst?

**Comment by goetas** [comment]
Currently this is necessary to avoid empty objects being serialized as arrays. 
Can you send a failing test case?

**Comment by Majkl578** [comment]
Here you go: #943 

This is the 2nd case from you example called _typed as strict array_.

**Comment by goetas** [comment]
Closing as it is not a BC break or a but but a feature request as commented on https://github.com/schmittjoh/serializer/pull/943

**Comment by Majkl578** [comment]
Whatever you say, this behavior is broken and violates JSON specification.

**Comment by goetas** [comment]
The code you are suggesting to remove is used mainly to support https://github.com/schmittjoh/serializer/blob/e75cdaf4a89ca7cd9f473c25ba0bf54c60889b5f/tests/Serializer/JsonSerializationTest.php#L247 this test case. 
Do you know a better solution? 
I was thinking about having the `data` variable always instance of arrayobject. It could work but requires some extra fixes when merging inline properties
