### ISSUE TITLE
Add ability to apply groups separately to referenced child objects

### ISSUE THREAD

**Issue by epoplive** [schmittjoh/serializer#947]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

I would like to request the ability to specify the serialization groups on child objects that are different from the main object being serialized.  For instance:

Object A:
 - id
 - name
 - children (list of Object B's, would only like to show 'basic' group)

Object B:
 - id (serialization groups: full, basic)
 - name (serialization groups: full, basic)
 - description (serialization groups: full, basic)
 - date_created (serialization groups: full)
 - child_objects (serialization groups: full)

I'd like to be able to specify via annotation that when serializing the 'children' field in Object A, that it only uses the 'basic' group

**Comment by goetas** [comment]
please refer to the deep branch group exclusion  http://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#overriding-groups-of-deeper-branches-of-the-graph
