### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by goetas** [schmittjoh/serializer#950]
In order to change the license on this project, we have to get the approval of every past contributor. At the time of writing this we have had 128 contributors.

If you are reading this and you are a contributor on the below list, please reply to this GitHub issue with the following text:

```
I, @username, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.
```

- [ ] @steveYeah  [commits](https://github.com/schmittjoh/serializer/commits?author=steveYeah) code changes, already overwritten in 1.x
- [x] @emgiezet  [commits](https://github.com/schmittjoh/serializer/commits?author=emgiezet) changes part of the serializer-bundle already approved in the bundle MIT migration
- [x] @wheelsandcogs [commits](https://github.com/schmittjoh/serializer/commits?author=wheelsandcogs) yaml driver improvements, [become part](https://github.com/schmittjoh/JMSSerializerBundle/commits?author=wheelsandcogs) of the bundle repo and already approved in the bundle MIT migration
- [x] @dustin10  [commits](https://github.com/schmittjoh/serializer/commits?author=dustin10) doc changes, already overwritten in 1.x
- [x] @armetiz
- [x] @JustBlackBird
- [x] @dbu
- [x] @aviortm
- [x] @ftassi
- [x] @helmer
- [x] @lyrixx
- [x] @minayaserrano  [commits](https://github.com/schmittjoh/serializer/commits?author=minayaserrano) form handling improvements
- [x] @mrosiu
- [x] @Majkl578  [commits](https://github.com/schmittjoh/serializer/commits?author=Majkl578)
- [x] @olvlvl
- [x] @passkey1510
- [x] @ruimarinho
- [x] @l3l0
- [x] @igorw
- [x] @michelsalib
- [x] @toby-griffiths
- [x] @gimler
- [x] @Soullivaneuh
- [x] @0mars
- [x] @dsyph3r
- [x] @ajgarlag
- [x] @emilien-puget
- [x] @scasei
- [x] @TristanMogwai
- [x] @Strate
- [x] @spolischook
- [x] @ribeiropaulor
- [x] @richardfullmer
- [x] @jaymecd
- [x] @cystbear
- [x] @tarjei
- [x] @rande
- [x] @colinfrei
- [x] @Potherca
- [x] @mente
- [x] @DavidMikeSimon
- [x] @Lumbendil
- [x] @wouterj
- [x] @burki
- [x] @rothfahl
- [x] @xanido
- [x] @holtkamp
- [x] @gnat42
- [x] @Nyholm
- [x] @tvlooy
- [x] @rpg600
- [x] @phiamo
- [x] @mikemix
- [x] @hyperized
- [x] @patashnik
- [x] @romantomchak
- [x] @gordalina
- [x] @chasen
- [x] @dunglas
- [x] @greg0ire
- [x] @adrienbrault
- [x] @stof
- [x] @tystr
- [x] @scaytrase
- [x] @xoob
- [x] @jhkchan
- [x] @vicb
- [x] @xabbuh
- [x] @bblue
- [x] @mpajunen
- [x] @hacfi
- [x] @lsmith77
- [x] @yethee
- [x] @anyx
- [x] @jonotron
- [x] @ruudk
- [x] @Aliance
- [x] @robocoder
- [x] @andy-morgan
- [x] @tmilos
- [x] @leonnleite
- [x] @urakozz
- [x] @develth
- [x] @AlexKovalevych
- [x] @smurfy
- [x] @zerkms
- [x] @tyler-sommer
- [x] @bobvandevijver
- [x] @veloxy
- [x] @prosalov
- [x] @goetas
- [x] @schmittjoh
- [x] @chregu
- [x] @alcalyn
- [x] @fdyckhoff
- [x] @megazoll
- [x] @bburnichon
- [x] @akoebbe
- [x] @dragosprotung
- [x] @rosstuck
- [x] @josser
- [x] @Seldaek
- [x] @jockri
- [x] @BraisGabin
- [x] @Bukashk0zzz
- [x] @arghav
- [x] @scrutinizer-auto-fixer (@schmittjoh  bot)
- [x] @bertterheide
- [x] @chrisjohnson00
- [x] @jeserkin
- [x] @c0ntax
- [x] @aledeg
- [x] @guilhermeblanco
- [x] @willdurand
- [x] @HarmenM
- [x] @carusogabriel
- [x] @iambrosi
- [x] @zebraf1
- [x] @jgendera
- [x] @enumag
- [x] @kriswallsmith
- [x] @LeaklessGfy
- [x] @marcospassos
- [x] @MDrollette
- [x] @inanimatt
- [x] @JMSBot  (@schmittjoh  bot)
- [x] @mvanmeerbeck
- [x] @colinmorelli

**Comment by chregu** [comment]
I, @chregu, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by mpajunen** [comment]
I, @mpajunen, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by urakozz** [comment]
I, @urakozz, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by adrienbrault** [comment]
I, @adrienbrault, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by gordalina** [comment]
I, @gordalina, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by leonnleite** [comment]
I, @leonnleite, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by hacfi** [comment]
I, @hacfi, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by jonotron** [comment]
I, @jonotron, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by fdyckhoff** [comment]
I, @fdyckhoff, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by akoebbe** [comment]
I, @akoebbe, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by stof** [comment]
@goetas FYI, it is much easier to apply the license change to all maintained versions rather than only to 2.0. I avoids you getting Apache-2 contributions for 1.x bugfixes and MIT ones for 2.x PRs (and then having to restart this process for any of the 1.x contributions when merging 1.x onto 2.x)

**Comment by bburnichon** [comment]
I, @bburnichon, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by veloxy** [comment]
I, @veloxy, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by ruudk** [comment]
I, @ruudk, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by Aliance** [comment]
I, @Aliance, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by xoob** [comment]
I, @xoob, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by scaytrase** [comment]
I, @scaytrase, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by megazoll** [comment]
I, @megazoll, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by anyx** [comment]
I, @anyx, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by jhkchan** [comment]
I, @jhkchan, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by yethee** [comment]
I, @yethee, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by tystr** [comment]
I, @tystr, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by Lumbendil** [comment]
I, @Lumbendil, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by bblue** [comment]
I, @bblue, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by patashnik** [comment]
I, @patashnik, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by vicb** [comment]
I, @vicb, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by lsmith77** [comment]
I, @lsmith77, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by smurfy** [comment]
I, @smurfy, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by zerkms** [comment]
I, @zerkms, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by andy-morgan** [comment]
I, @andy-morgan, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by emgiezet** [comment]
I, @emgiezet, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by AlexKovalevych** [comment]
I, @AlexKovalevych, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by robocoder** [comment]
I, @robocoder, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by prosalov** [comment]
I, @prosalov, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by schmittjoh** [comment]
I, @schmittjoh, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by dunglas** [comment]
I, @dunglas, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

(Great move!)

**Comment by jeserkin** [comment]
I, @jeserkin, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by bertterheide** [comment]
I, @bertterheide, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by enumag** [comment]
I, @enumag, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by willdurand** [comment]
I, @willdurand, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by josser** [comment]
I, @josser, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by kriswallsmith** [comment]
I, @kriswallsmith, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by dragosprotung** [comment]
I, @dragosprotung, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by aledeg** [comment]
I, @aledeg, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by arghav** [comment]
I, @arghav, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by Bukashk0zzz** [comment]
I, @Bukashk0zzz, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by jockri** [comment]
I, @jockri, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by HarmenM** [comment]
I, @HarmenM, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by LeaklessGfy** [comment]
I, @LeaklessGfy, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by jgendera** [comment]
I, @jgendera, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by BraisGabin** [comment]
I, @BraisGabin, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by Seldaek** [comment]
I, @Seldaek, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by rosstuck** [comment]
I, @rosstuck, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by Potherca** [comment]
I, @potherca, agree to license my contributions to the `schmittjoh/serializer` project from the Apache-2.0 to the MIT license effective immediately.

**Comment by carusogabriel** [comment]
I, @carusogabriel, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by iambrosi** [comment]
I, @iambrosi, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by c0ntax** [comment]
I, @c0ntax, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by chrisjohnson00** [comment]
I, @chrisjohnson00, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by inanimatt** [comment]
I, @inanimatt, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by phiamo** [comment]
I, @phiamo, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by rpg600** [comment]
I, @rpg600, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by hyperized** [comment]
I, @hyperized, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by mvanmeerbeck** [comment]
I, @mvanmeerbeck, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by romantomchak** [comment]
I, @romantomchak, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by mikemix** [comment]
I, @mikemix, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by burki** [comment]
I, @burki, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by rande** [comment]
I, @rande, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by richardfullmer** [comment]
I, @richardfullmer, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by gnat42** [comment]
I @gnat42, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by Nyholm** [comment]
I, @nyholm, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by rothfahl** [comment]
I, @rothfahl, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by mente** [comment]
I, @mente, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by DavidMikeSimon** [comment]
I, @DavidMikeSimon, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by xanido** [comment]
I, @xanido, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by tarjei** [comment]
I, @tarjei, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by wouterj** [comment]
I, @wouterj, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by jaymecd** [comment]
I, @jaymecd, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by ribeiropaulor** [comment]
I, @ribeiropaulor, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by TristanMogwai** [comment]
I, @TristanMogwai, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by toby-griffiths** [comment]
I, @toby-griffiths, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by colinfrei** [comment]
I, @colinfrei, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by spolischook** [comment]
I, @spolischook, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by Strate** [comment]
I, @strate, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by emilien-puget** [comment]
I, @emilien-puget, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by 0mars** [comment]
I, @0mars, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by goetas** [comment]
@dsyph3r, @l3l0, @scasei, @Majkl578, @ajgarlag, @michelsalib, @emgiezet, @dbu, @minayaserrano, @helmer, @passkey1510, @aviortm, @Soullivaneuh, @dustin10, @ftassi, @mrosiu, @ruimarinho, @steveYeah, @gimler, @lyrixx, @igorw, @olvlvl, @armetiz, @wheelsandcogs 
Can you please approve this changes?

**Comment by armetiz** [comment]
I, @armetiz, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by gimler** [comment]
I, @gimler, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by scasei** [comment]
I, @scasei, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by lyrixx** [comment]
I, @lyrixx, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by ajgarlag** [comment]
, @ajgarlag, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by dsyph3r** [comment]
I, @dsyph3r, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by ftassi** [comment]
I, @ftassi, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by mrosiu** [comment]
I, @mrosiu, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by Soullivaneuh** [comment]
I, @Soullivaneuh, agree to license my contributions to the schmittjoh/JMSSerializerBundle project from the Apache-2.0 to the MIT license effective immediately.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
I, @igorw, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by michelsalib** [comment]
I, @michelsalib, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by l3l0** [comment]
I, @l3l0, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately

**Comment by ruimarinho** [comment]
I, @ruimarinho, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by dbu** [comment]
I, @dbu, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by helmer** [comment]
I, @helmer, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by aviortm** [comment]
I, @aviortm, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by goetas** [comment]
@minayaserrano Can you please approve this changes?

**Comment by minayaserrano** [comment]
I, @minaya, agree to license my contributions to the schmittjoh/serializer project from the Apache-2.0 to the MIT license effective immediately.

**Comment by Soullivaneuh** [comment]
> Your approval is not valid, you specified wrong project name. :)

:wine_glass: :wine_glass: :wine_glass: 

I promise, I try to stop. :wink:

**Comment by goetas** [comment]
This is complete, thanks to everyone!
