### ISSUE TITLE
Accessing static property as non static

### ISSUE THREAD

**Issue by Hunternnm** [schmittjoh/serializer#960]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hi! After update to 1.12.0 I started to get an error `Accessing static property Ramsey\Uuid\Uuid::$factory as non static`. 

An error occurs when trying to get a static method https://github.com/ramsey/uuid/blob/master/src/Uuid.php#L127 on a line https://github.com/schmittjoh/serializer/blob/1.12.0/src/JMS/Serializer/Metadata/PropertyMetadata.php#L187 
in version 1.11.0 of this code was not

**Comment by Hunternnm** [comment]
@goetas this is your commit. Can you tell me how you can solve the problem?

**Comment by Hunternnm** [comment]
@goetas Can we wait for the new version?

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/releases/tag/1.12.1

**Comment by Hunternnm** [comment]
@goetas Many thanks for such a quick fix! You're cool!

**Comment by goetas** [comment]
![ttr](https://user-images.githubusercontent.com/776743/40840152-c96f771e-65a5-11e8-8ba0-359e1a37c352.png)

time to resolution 40 min :smiley:  !

**Comment by Hunternnm** [comment]
This is the fastest fix in my memory! ))))

**Comment by danielchodusov** [comment]
Hi!

This issue happens to be with 3.2.0 - when using the serializer to send async email with symfony/mailer:

```
[ErrorException]
Notice: Accessing static property Egulias\EmailValidator\EmailLexer::$nullToken as non static


Exception trace:
  at /Users/daniel/dev/portaldrazeb.cz/vendor/jms/serializer/src/Accessor/DefaultAccessorStrategy.php:87
 Egulias\EmailValidator\EmailLexer::JMS\Serializer\Accessor\{closure}() at /Users/daniel/dev/portaldrazeb.cz/vendor/jms/serializer/src/Accessor/DefaultAccessorStrategy.php:92
 JMS\Serializer\Accessor\DefaultAccessorStrategy->getValue() at /Users/daniel/dev/portaldrazeb.cz/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php:234
```

**Comment by goetas** [comment]
I could not find that property in https://github.com/egulias/EmailValidator/blob/92dd169c32f6f55ba570c309d83f5209cefb5e23/EmailValidator/EmailLexer.php ...  can you share more details about it?

**Comment by danielchodusov** [comment]
Hi @goetas sorry I messed an issue a little bid (created a new issue 1122 meanwhile), so I closed it there.

The original issue I wrote here:

```
In DefaultAccessorStrategy.php line 86:

  [ErrorException]
  Notice: Accessing static property Egulias\EmailValidator\EmailLexer::$nullToken as non static
```

When I dump in `vendor/jms/serializer/src/Accessor/DefaultAccessorStrategy.php`:

dump($metadata->name); --> "nullToken"
dump($object);


```
Egulias\EmailValidator\EmailLexer^ {#1914
  #charValue: array:26 [
    "(" => 49
    ")" => 261
    "<" => 272
    ">" => 273
    "[" => 262
    "]" => 263
    ":" => 265
    ";" => 275
    "@" => 64
    "\" => 92
    "/" => 278
    "," => 274
    "." => 46
    """ => 34
    "-" => 264
    "::" => 266
    " " => 267
    "\t" => 268
    "\r" => 269
    "\n" => 270
    "\r\n" => 301
    "IPv6" => 271
    "{" => 276
    "}" => 277
    "" => null
    "\0" => 0
  ]
  #hasInvalidTokens: false
  #previous: array:3 [
    "value" => "com"
    "type" => 300
    "position" => 25
  ]
  -input: "legal-entity@test.arodax.com"
  -tokens: array:9 [
    0 => array:3 [
      "value" => "legal"
      "type" => 300
      "position" => 0
    ]
    1 => array:3 [
      "value" => "-"
      "type" => 264
      "position" => 5
    ]
    2 => array:3 [
      "value" => "entity"
      "type" => 300
      "position" => 6
    ]
    3 => array:3 [
      "value" => "@"
      "type" => 64
      "position" => 12
    ]
    4 => array:3 [
      "value" => "test"
      "type" => 300
      "position" => 13
    ]
    5 => array:3 [
      "value" => "."
      "type" => 46
      "position" => 17
    ]
    6 => array:3 [
      "value" => "arodax"
      "type" => 300
      "position" => 18
    ]
    7 => array:3 [
      "value" => "."
      "type" => 46
      "position" => 24
    ]
    8 => array:3 [
      "value" => "com"
      "type" => 300
      "position" => 25
    ]
  ]
  -position: 9
  -peek: 0
  +lookahead: null
  +token: array:3 [
    "value" => ""
    "type" => null
    "position" => 0
  ]
  -regex: "/([a-zA-Z_]+[46]?)|([^\x00-\x7F])|([0-9]+)|(\r\n)|(::)|(\s+?)|(.)|[\xA0-\xff]+/iu"
}
```

Did it help?

**Comment by goetas** [comment]
Hmm... this (https://github.com/schmittjoh/serializer/blob/41d806cc67a96ad25f9f06f1f7107cee0f2f146b/src/Metadata/PropertyMetadata.php#L144) check should have detected it... can you check if this line is ever executed for the `Egulias\EmailValidator\EmailLexer` class ? (clear the cache first...)
