### ISSUE TITLE
Exclude do not work when extends class

### ISSUE THREAD

**Issue by lukaszwit** [schmittjoh/serializer#972]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When serializing object of class that inherits properties from other class all Excludes are ignored and there is no way to exclude any field of class from serialization

## Steps required to reproduce the problem

Example (assume correct imports and jms/serializer in class B, usage as serializer and class A to not use any jms annotation)

```php
class A {
    protected $email = 'some email';
    protected $pass = 'some pass';
} 

class B extends A {
     /**
      * @Exclude
       */
     protected $pass;
}

$b = new $b;

$serializer->serialize($b);

```
## Expected Result
In above I expect that field email will be serialized. 

## Actual Result
Unfortunately $pass is serialized too.

**Comment by goetas** [comment]
`@Exclude` has to be applied directly on the class `A`. As said many times, metadata are per class, so `A::$pass` and `B::$pass` are seen as two separate props.

**Comment by lukaszwit** [comment]
Thanks, I'll try that. Sadly this issue appears after update jms serialize bundle (symfony) so it looks like it changed at same point.
