### ISSUE TITLE
Add documentation to deserialize on existing objects.

### ISSUE THREAD

**Issue by luishdez** [schmittjoh/serializer#978]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

I've review all issues and I've seen a lot of people struggling with this. This is a very common feature used to build APIs… 

I've found and example in the issues using a custom `InitializedObjectConstructor` and then:

```
    jms_serializer.object_constructor:
        alias: jms_serializer.initialized_object_constructor
        public: false

    jms_serializer.initialized_object_constructor:
         class:        App\Serializer\InitializedObjectConstructor
         arguments:    ["@jms_serializer.unserialize_object_constructor"]
```
Then:

```
        $context = new DeserializationContext();
        $context->attributes->set('target', $document);
```

And I guess that probably this is not the best way to do it and it's not very intuitive. I bet a lot of people will thank a proper documentation and/or an easy way to do this.

**Comment by goetas** [comment]
Fixed by https://github.com/schmittjoh/serializer/pull/1308

**Comment by yosvield** [comment]
How is the best way to deserialize on existing objects, i do not find in the documentation
