### ISSUE TITLE
Allow empty XML elements for DateTime

### ISSUE THREAD

**Issue by TomOne** [schmittjoh/serializer#981]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Given the following XML structure:
``` XML
<?xml version="1.0" encoding="utf-8"?>
<root>
  <date/>
</root>
```
2. Set `@Type("DateTime<'Y-m-d'>")` as annotation for the `date` property.
3. Deserialize it

## Expected Result

The XML DateTime deserializer should treat empty XML elements in the same way as the JSON DateTime deserializer with a `null` value.

## Actual Result

The following error is thrown:

`PHP Fatal error:  Uncaught JMS\Serializer\Exception\RuntimeException: Invalid datetime "", expected format Y-m-d. in jms/serializer/src/JMS/Serializer/Handler/DateHandler.php:188`

**Comment by goetas** [comment]
Thats the expected behavior. and empty node is interpreted as an empty string.

More info on NULLs in XML: https://stackoverflow.com/questions/774192/what-is-the-correct-way-to-represent-null-xml-elements

**Comment by goetas** [comment]
Your document should have been:



``` XML
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <date xsi:nil="true"/>
</root>
```

**Comment by TomOne** [comment]
Thanks.

Unfortunately I have no control over the XML structure. I ended up using `@Type("string")` and getters and setters for `date` in my XML that parse/format the value.

**Comment by goetas** [comment]
@TomOne you could implement your date time handler as https://github.com/schmittjoh/serializer/blob/1.x/src/JMS/Serializer/Handler/DateHandler.php and do the parsing there, keeping your model clean

**Comment by TomOne** [comment]
Thanks for the suggestion. I’ll do that.

**Comment by davidspiess** [comment]
@goetas any reason the Handler methods are private instead of protected? It makes it impossible to extend specific DateHandler methods.

```php
<?php

use JMS\Serializer\Handler\DateHandler;
use JMS\Serializer\XmlDeserializationVisitor;

class NullableDateHandler extends DateHandler
{
    public function deserializeDateTimeFromXml(XmlDeserializationVisitor $visitor, $data, array $type)
    {
        if ($this->isEmptyDate($data)) {
            return null;
        }
        
        // This is not possible
        return $this->parseDateTime($data, $type);
    }
    ...
}
```

**Comment by goetas** [comment]
I do not suggest extending this class. In the serializer v2.0 most of the classes are marked as "final", if you need to customize a date format parsing i suggest to implement your own handler

**Comment by davidspiess** [comment]
Okay thanks for the advice!
