### ISSUE TITLE
jms serializer 1.13 error with Symfony cache clear

### ISSUE THREAD

**Issue by zaidsa3sa3** [schmittjoh/serializer#990]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Symfony
./bin/console cache:clear --no-warmup
gives an error after updating from version 1.11 to 1.13

## Steps required to reproduce the problem

1. open a symfony project 
2. composer require jms/serializer:^1.13
3. ./bin/console cache:clear --no-warmup

## Expected Result

* No errors show after cache:clear

## Actual Result

*   [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:

   // Clearing the cache for the dev environment with debug
   // true

   [OK] Cache for the "dev" environment (debug=true) was successfully cleared.

  Xdebug could not open the remote debug file '/var/log/xdebug.log'.

    [InvalidArgumentException]
    The directory "/app/var/cache/dev/jms_serializer" does not exist.

  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-a
  nsi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by goetas** [comment]
looks related to the `--no-warmup` option...
can you please post the full exception trace?

**Comment by zaidsa3sa3** [comment]
After deep check it is not related to JMS
