### ISSUE TITLE
Need better extensibility

### ISSUE THREAD

**Issue by hxss** [schmittjoh/serializer#999]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes/no
| RFC?             | yes/no

Why you use so many `private`? I can't even register my custom `XmlSerializationVisitor` if I need to [exclude xml declaration](https://stackoverflow.com/a/17362351)(because of `propertyNamingStrategy` is private). Or if I want to [disable CDATA](https://github.com/schmittjoh/serializer/issues/752) - I cant do that because everything is private.

Can you please give more freedom?

**Comment by goetas** [comment]
Using inheritance to achieve some functionalities is often a bad idea. See 
https://github.com/schmittjoh/serializer/pull/126#issuecomment-291128451 where the same issue was raised.

In general, try to use composition over inheritance as much as possible. A good post about it is https://ocramius.github.io/blog/when-to-declare-classes-final/

**Comment by goetas** [comment]
closing for the same reasons as https://github.com/schmittjoh/serializer/issues/999#issuecomment-427835621
